### ISSUE TITLE
Can't re-insert Tab using `.`

### ISSUE THREAD

**Issue by pushkin-** [VSCodeVim/Vim#1811] opened 2017-06-06 22:05 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Environment**:
- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: Windows 10

**What happened**:
I inserted a tab, pressed `Esc` and repeated the command with `.`. I expected a tab to be inserted. Instead, the cursor moved back a character and no tab was inserted.

I can re-insert spaces, however.

**How to reproduce it**:
`<Esc>i<Tab><Esc>.`

**Comment by Chillee** [comment] 2017-06-06 23:03
This is a duplicate of https://github.com/VSCodeVim/Vim/issues/612

I thought I'd fixed this issue in the past, but this issue is actually a massive pain.

A "tab" in VSCode is not actually just a "tab". It can be an autocomplete, emmetcompletion, etc.

**Closed by Chillee** 2017-06-06 23:03 UTC
