### ISSUE TITLE
Failed to handle key=k. getLineLength() called with out-of-bounds line 1716

### ISSUE THREAD

**Issue by NicolasGutierrezC-11** [VSCodeVim/Vim#5804] opened 2020-12-02 03:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. getLineLength() called with out-of-bounds line 1716
	at Function.getLineLength (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:22225)
	at l.getUpWithDesiredColumn (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:11622)
	at $.execAction (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:191010)
	at $.createMovementResult (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:158252)
	at $.execActionWithCount (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:157909)
	at F.executeMovement (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:479443)
	at F.runAction (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:475347)
	at F.handleKeyAsAnAction (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:474805)
	at F.handleKeyEvent (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\nico2\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
