### ISSUE TITLE
Disable vim *only* for jupyter notebook editors 

### ISSUE THREAD

**Issue by rosspleban** [VSCodeVim/Vim#6950] opened 2021-08-03 16:18 UTC
Key bindings for vim and juptyer notebooks overlap, which can frustrate users.  For example the period (`.`) keystroke doesnt work.  Also j & k can move the active cell selection.

I prefer vim to be disabled in jupyter notebooks and remained enabled in other editors.  This preserves the notebook bindings.  Also, notebooks tend to be simpler code/text than traditional source code.

vscode-jupyter said they could not facilitate this: https://github.com/microsoft/vscode-jupyter/issues/6837

**Comment by northernocean** [comment] 2021-08-03 19:09
A toggleVim shortcut to quickly disable/enable Vim extension would be a quick way to turn off Vim when you are in a notebook and turn it back on when you aren't in a notebook.

https://stackoverflow.com/questions/47502318/how-to-toggle-between-vim-emulation-and-no-vim-emulation-when-the-vscodevim-exte

**Comment by rosspleban** [comment] 2021-08-03 23:28
Yes, I have a key binding for toggle vim entirely. Often I'm working with multiple file types simultaneously so that solution isn't ideal.

**Comment by PiotrCzapla** [comment] 2021-08-10 09:04
The VIM behaviour is really erratic in jupyter notebooks, there were too many bugs to describe them here. So it would be really good to let us disable the plugin in jupyter until the issues are sorted out.


Re. bugs it looks like internal state of plugin gets messed up when one I navigate the jupyter notebook with mouse. It manifest it self with cursor jumping to previous locations on edit, copy to clipboard not working , selection not working correctly etc.

**Comment by jswetzen** [comment] 2021-11-12 20:25
I just tried the notebook interface as well, and vim mode makes it completely unusable. Would love it to work of course, but until that's possible, disabling is a must.

**Comment by J-Fields** [comment] 2021-12-10 07:31
Marking this as a duplicate of #6960/#6104. Behavior will be much better in the upcoming release, so hopefully no need to disable 🙂

**Closed by J-Fields** 2021-12-10 07:31 UTC
Labels: status/duplicate

**Comment by ltalirz** [comment] 2022-06-16 09:55
In the meanwhile, another issue popped up about this very topic https://github.com/VSCodeVim/Vim/issues/6151

It seems to me there is a real demand for being able to disable the vim plugin for certain file types.
Given that both vim and Jupyter notebooks have their own extensive set of keybindings, it is also not clear to me whether it is even possible to marry vim and Jupyter notebooks in a way that does not lead to unexpected results (as is currently the case).

Is there a good reason for not implementing this feature to disable vim for certain file types?

**Comment by v3ss0n** [comment] 2023-01-11 09:00
anyone get this solve? how can i disable vscode vim for notebooks?

**Comment by fnl** [comment] 2023-12-16 22:16
I realized the same issues, and was hoping there already exists an automated way to disable `vscodevim` in Notebooks.
Using Vim editing semantics just don't seem to work well inside a Notebook - for me, in any case.
Is there any better solution other than disabling this extension entirely?

**Comment by corneliusroemer** [comment] 2023-12-17 13:01
It's been almost two months and 5 people have liked my comment asking for reopening so I'll open a new issue.

**Comment by jswetzen** [comment] 2023-12-17 13:14
What is not working for you? I've been using Vim mode in notebooks for months without issues. I can see if there are any special settings I made.

**Comment by corneliusroemer** [comment] 2023-12-17 13:26
>What is not working for you? I've been using Vim mode in notebooks for months without issues. I can see if there are any special settings I made.

`Esc` deletes my input rather than going from _insert_ mode to _normal_ mode, at least sometimes.
![2023-12-17 14 18 36](https://github.com/VSCodeVim/Vim/assets/25161793/69be8bc0-826a-4569-86b9-308160caa88c)

**Comment by jswetzen** [comment] 2023-12-18 10:21
Interesting, that never happens for me. I didn't have any workaround keybindings only had these:
1. jk to ESC
2. ctrl-p override for quickOpen
3. ctrl-shift-r to restart the Jupyter kernel, can be useful.
```
  "vim.insertModeKeyBindings": [

    {
      "before": [
        "j",
        "k"
      ],
      "after": [
        "<Esc>"
      ]
    },
  ],
  "vim.normalModeKeyBindings": [
    {
      "before": [
        "<C-p>",
      ],
      "commands": [
        "workbench.action.quickOpen",
      ],
    },
    {
      "before": [
        "<C-shift-r>",
      ],
      "commands": [
        "jupyter.restartkernel",
      ],
    },
  ],
```
