### ISSUE TITLE
`dit` and `cit` do not work for multi-line

### ISSUE THREAD

**Issue by kidproquo** [VSCodeVim/Vim#1078] opened 2016-11-22 16:07 UTC
### What did you do?

```
<test>

        aaa|aaa

</test>
```
Pressed `dit` or `cit` in Normal 
### What did you expect to happen?
```
<test>
</test>
```
### What happened instead?
Nothing
### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.3
* OS: Windows 7

**Comment by xconverge** [comment] 2016-11-23 04:57
Thanks, good catch! Looks like the tag match function only works for single lines currently

**Comment by johnfn** [comment] 2016-12-04 07:16
I believe this is a duplicate of #971. You can thumbs that one up. :)

**Closed by johnfn** 2016-12-04 07:16 UTC
