### ISSUE TITLE
Failed to handle key=<C-a>. 

### ISSUE THREAD

**Issue by Pauljanson002** [VSCodeVim/Vim#5388] opened 2020-10-12 11:49 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
RangeError: Failed to handle key=<C-a>. 
	at Function.readLineAt (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:21957)
	at Function.getLineLength (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22297)
	at l.isLineEnd (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:14231)
	at Function.immediateMatchingBracket (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:93851)
	at c (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:481980)
	at c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:482794
	at t.ExtHostTextEditor.edit (c:\Users\Paul Janson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
	at F.executeCommand (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:482786)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475467)
	at async F.handleKeyAsAnAction (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\Paul Janson\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 00:56
Duplicate of #5180

**Closed by J-Fields** 2020-10-14 00:56 UTC
