### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by 1dai-financ** [VSCodeVim/Vim#6245] opened 2021-03-08 06:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
	at g._lineAt (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:1166)
	at Object.lineAt (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:95)
	at x.delete (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:519744)
	at x.run (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:520516)
	at F.executeOperator (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.runAction (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
	at async F.handleKeyAsAnAction (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/zhengpenghou/.vscode-insiders/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:31
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:31 UTC
