### ISSUE TITLE
Auto indent / format when paste not working

### ISSUE THREAD

**Issue by Tsimopak** [VSCodeVim/Vim#5184] opened 2020-09-14 08:16 UTC
I encounter weird bug, assuming that this is my HTML code:

```html
<div>
    <p>Hi</p>
    <span>
        <b>Hi</b>
    </span>
</div>
```

If I copy (`yy`) the the 2nd line ( p tag ), and paste it beneath the span tag, it doesn't re-indent it properly, and keep it with the same indent as before.

Now, I checked without the vim extension, and if I *paste*, it does re-format the pasted code.

How can I solve that situation?

**Comment by J-Fields** [comment] 2020-09-21 18:42
Duplicate of #1269

**Closed by J-Fields** 2020-09-21 18:42 UTC
