### ISSUE TITLE
Failed to handle key=:. No cursor index - this should never ever happen!

### ISSUE THREAD

**Issue by awvalenti** [VSCodeVim/Vim#6853] opened 2021-07-07 20:30 UTC
**To Reproduce**

1.  Create text file with two lines
2.  Delete first one with `:d`
3.  Try repeating the action with `@:` (repeat last command, like in Vim)
4.  See error

**VSCodeVim version**: 1.21.4

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=:. No cursor index - this should never ever happen!
    at doTextEditorEdit (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\transformations\execute.ts:90:13)
    at c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\transformations\execute.ts:127:13
    at Object.edit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:50199)
    at executeTransformations (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\transformations\execute.ts:125:31)
    at Object.e [as executeTransformations] (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\transformations\execute.ts:228:15)
    at process.transformer (internal/process/task_queues.js:93:5)
    at j.actionToRecord [as runAction] (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\mode\modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\src\mode\modeHandler.ts:471:11)
    at c:\Users\andre\.vscode\extensions\vscodevim.vim-1.21.4\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[0, 3] | [0, 0]]"
]
actionsRunPressedKeys: [
  "<Esc>"
]
actionsRun: []
textTransformations: [
  {
    "type": "deleteRange",
    "range": [
      {
        "line": 0,
        "character": 0
      },
      {
        "line": 1,
        "character": 0
      }
    ],
    "manuallySetCursorPositions": true,
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 22:59
Duplicate of #6887

**Closed by J-Fields** 2021-07-23 22:59 UTC
