### ISSUE TITLE
Typing cc won't indent the line automatically

### ISSUE THREAD

**Issue by lumio** [VSCodeVim/Vim#1802] opened 2017-06-02 16:35 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**: Mac OS, Node JS
- EditorConfig: 0.9.3
- ESLint: 1.2.11
- Vim: 0.8.4

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: Mac OS 10.12.5

**What happened**: Typing cc will clear the line as it should be, but won't auto indent the line.

**What did you expect to happen**: Clearing and auto indent current line

**How to reproduce it**: Just type cc

**Comment by Chillee** [comment] 2017-06-02 16:58
Closing as duplicate of #1017 .

**Closed by Chillee** 2017-06-02 16:58 UTC
