### ISSUE TITLE
Disabling <D-d> with handleKeys still interfer with default behavior

### ISSUE THREAD

**Issue by rgehan** [VSCodeVim/Vim#2407] opened 2018-03-01 13:18 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
I'm trying to use VSCodeVim while still being able to use `Cmd+D` to select many instance of the same string.

I set the correct option in my user settings:
```
"handleKeys": {
	"<D-d>": false
}
```

It seems like it is no longer VSCodeVim that handles the `Cmd+D` shortcut, but then, I can only select two instances of the string.

It seems like after the first `Cmd+D`, it enters Visual Mode, and that is why it doesn't work

**What did you expect to happen**:
I'd like to be able to select as many instances of the selected string as neeeded

**How to reproduce it (as minimally and precisely as possible)**:
- Open a file with many instances of a given string
- Select the string
- Press `Cmd+D` once
- Two instances are selected
- Press `Cmd+D` a second time

Relevant settings:
```json
    "vim.leader": ",",
    "vim.cmdLineInitialColon": true,
    "vim.startInInsertMode": true,

    // Improve the look of the easymotion indicators
    "vim.easymotion": true,
    "vim.easymotionMarkerFontFamily": "Fira Code",
    "vim.easymotionMarkerHeight": 18,
    "vim.easymotionMarkerBackgroundColor": "#1f4b91",
    
    // Allow to click/select while in insert mode without going
    // to visual mode
    "vim.mouseSelectionGoesIntoVisualMode": false,

	"handleKeys": {
		"<D-d>": false
	}
```

**Environment**:
- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Mac OS Sierra 10.12.6

**Comment by jpoon** [comment] 2018-03-04 07:30
Possibly a dupe of https://github.com/VSCodeVim/Vim/issues/2325

**Comment by rgehan** [comment] 2018-03-04 21:29
I've added more details about this issue in #2325, it seems like it is a duplicate you're right

**Closed** 2018-03-05 01:37 UTC
