### ISSUE TITLE
getLineLength() called with out-of-bounds line 250

### ISSUE THREAD

**Issue by littlepotato123** [VSCodeVim/Vim#5327] opened 2020-10-04 11:30 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 250
	at Function.getLineLength (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.getRight (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10500)
	at F.updateView (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:491507)
	at _ (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:234397)
	at async Object.runTasks (c:\Users\sopan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:46
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:46 UTC
Labels: kind/bug, status/duplicate
