### ISSUE TITLE
ctrl-e / ctrl-y scrolling is lagging substantially

### ISSUE THREAD

**Issue by FableRBX** [VSCodeVim/Vim#4485] opened 2020-01-10 21:19 UTC
**Describe the bug**

Scrolling the view down/up with ctrl-e / ctrl-y is extremely laggy to the point where it's not really usable.

**To Reproduce**

1.  Scroll the view down or up with ctrl-e or ctrl-y
2.  Notice substantial document scroll latency

**Expected behavior**
Smooth seamless scrolling

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Windows 10

**Comment by vsobotka** [comment] 2020-01-11 13:15
I have the same issue. Has been fixed i nthe past as well #1943

**Comment by PymZoR** [comment] 2020-01-14 09:09
Stumbled upon this issue while looking for a way to speed up scrolling with ctrl-e / ctrl-y.

**Comment by sqlkoala** [comment] 2020-01-15 16:24
According to devs, this is fixed. See here
https://github.com/VSCodeVim/Vim/issues/4309

**Comment by FableRBX** [comment] 2020-01-30 16:49
@sqlkoala This may have been fixed previously, but is a regression in the latest release.

**Comment by TomServo3k** [comment] 2020-02-12 18:58
Issue #4309 says it was fixed in VsCodeVim version 1.11.3. However, I am using version 1.12.4 and the problem is very evident.

**Comment by sashaweiss** [comment] 2020-02-16 04:27
Seeing this behavior still on `v1.12.4` as well. Any ideas on what caused this?

**Comment by umutbozdag** [comment] 2020-02-20 12:29
Same for me with `v1.12.4`

**Comment by sqlkoala** [comment] 2020-02-20 14:05
There merge to master by j-fields was on 29 Dec, two days after the last release 1.12.4.
https://github.com/VSCodeVim/Vim/pull/4433

So I think we have not seen it live yet and we just need to wait a few days.

**Comment by J-Fields** [comment] 2020-02-20 21:47
Thanks @sqlkoala. Yeah, I'd meant to release a version over a month ago but life got in the way. There are a few things I want to polish up before the next release, but it's coming soon.

**Comment by J-Fields** [comment] 2020-03-08 17:57
This should be fixed, holler if it isn't

**Closed by J-Fields** 2020-03-08 17:57 UTC
