### ISSUE TITLE
The undo stack of the system and VIm does not syncronize

### ISSUE THREAD

**Issue by valleybay** [VSCodeVim/Vim#2416] opened 2018-03-03 19:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**What happened**:
The undo stack of the system (cmd + z) and Vim (`u`) does not syncronize. When I have something on my VIm clipboard and delete something with `d`, and then undo that with U it will paste older contents from my VIm clipboard.

**What did you expect to happen**:
Cmd + z should undo the same things as u would and vice-versa

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: OS X 10.13.1

**Comment by jpoon** [comment] 2018-03-04 05:04
Dupe of https://github.com/VSCodeVim/Vim/issues/1490

**Closed by jpoon** 2018-03-04 05:04 UTC
