### ISSUE TITLE
Illegal value for `line`

### ISSUE THREAD

**Issue by shoryasingh** [VSCodeVim/Vim#5305] opened 2020-09-30 11:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Illegal value for `line`
    at d._lineAt (/snap/code/45/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:535:222)
    at Object.lineAt (/snap/code/45/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:181)
    at Function.getLineAt (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22388)
    at Function.getCharAt (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22427)
    at F.updateView (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:492683)
    at _ (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/home/shorya/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:03
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:03 UTC
Labels: kind/bug
