### ISSUE TITLE
Normal mode key binding for '0' make 0 not usable in command count 

### ISSUE THREAD

**Issue by Xdminsy** [VSCodeVim/Vim#4339] opened 2019-12-09 02:07 UTC
**Describe the bug**

I `nnoremap 0 ^` in vim and it works perfectly. Because a command count won't start with a 0.
But in vscode, if I made such key binding, though if I only press 0 it works as expected, it makes preceding command count erroneous.
I mean, it makes 20G to be 2, cursorHome, and G, and guide me to line 2, this is not expected.
If i use `"after": ["^"]` instead of command of cursorHome, the 20G will be "2 times ^" and "G", well, even worse?
Let the number 0 in normal mode after a number still be 0, not mapped command.

**To Reproduce**
1. Add
```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["0"],
            "commands": ["cursorHome"]
        },
    ]
```
to settings.json.

2. Press 10G

**Expected behavior**
Like in vim,
Pressing 0 moves to line start,
Pressing 10G moves to line 10, not line 1

**Environment:**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.2
- OS: Windwos Version 1903 (OS Build 18362.356)

**Comment by J-Fields** [comment] 2019-12-09 04:24
Duplicate of https://github.com/VSCodeVim/Vim/issues/4184

**Closed by J-Fields** 2019-12-09 04:24 UTC
Labels: kind/bug
