### ISSUE TITLE
Search word under cursor using * (Shift-8) incorrectly includes leading tabs

### ISSUE THREAD

**Issue by konradsa** [VSCodeVim/Vim#5035] opened 2020-07-16 19:14 UTC
Noticed this with the latest release 1.15.0 on Windows (remotely installed on Linux), pretty sure it worked differently before.

When invoking the search word under cursor command using * (Shift-8), and there are some leading tabs (like at the beginning of the line), the search includes the tabs as well. Leading spaces cause no such behavior, they are ignored.

Expected behavior is that leading tabs just like spaces should not be part of the search.

**Comment by J-Fields** [comment] 2020-07-16 19:28
Duplicate of #5026, fixed in next release

**Closed by J-Fields** 2020-07-16 19:28 UTC

**Comment by konradsa** [comment] 2020-07-16 19:40
Thanks, I searched for it but didn't see it.
