### ISSUE TITLE
Failed to handle key=<down>. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by nicocossiom** [VSCodeVim/Vim#5938] opened 2020-12-29 12:59 UTC
**To Reproduce**

1. The extension for some reason forgets it's on and when in normal mode it types the characters in a white font with black background, but after finishing it does what it is supposed to. But the text is so annoying it's unusable
2. I'm using ElementaryOS which is based on Ubuntu 18.04.4 LTS, but I have had this error happen on windows as well as MacOS

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<down>. Cannot read property 'canBeRepeatedWithDot' of undefined
	at F.runAction (/home/nicolas_cossio/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172434)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/nicolas_cossio/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/home/nicolas_cossio/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/home/nicolas_cossio/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/home/nicolas_cossio/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:09
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:09 UTC
Labels: status/duplicate
