### ISSUE TITLE
Cannot insert emoji with VsCodeVim extension 🤐

### ISSUE THREAD

**Issue by fadhilsaheer** [VSCodeVim/Vim#6902] opened 2021-07-22 03:19 UTC
**Describe the bug**
Cannot insert emoji in Vscode with VsCodeVim extension enabled.
It displays `�` instead of emoji that I wanted.

**To Reproduce**

1.  Enable VsCodeVim extension
2.  Try inserting a emoji with `win + ;`
> I'm on windows

And it displays `�` instead of `🍕` I wanted.

**Expected behavior**
Emoji instead of `�`.
> It shows right emoji when you copy from other place & paste to editor
> I usually open command palette 
> - Insert my emoji there
> - cut it
> - paste it to the editor

**Screenshots**
- Without VsCodeVim enabled
![vim_bug_pic_1](https://user-images.githubusercontent.com/67850930/126585034-829ca95a-0426-42e8-b155-9cc3d2afc685.PNG)
- With VsCodeVim enabled
![vim_bug_pic_2](https://user-images.githubusercontent.com/67850930/126585077-ec3977fc-07fc-4f44-985e-89f3378878ad.PNG)

**Environment**

- Extension (VsCodeVim) version: Latest
- VSCode version: Lates
- OS: Windows

**Comment by J-Fields** [comment] 2021-07-22 17:34
Duplicate of #6046

**Closed by J-Fields** 2021-07-22 17:34 UTC
