### ISSUE TITLE
Failed to handle key=d. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by miguelhrocha** [VSCodeVim/Vim#5870] opened 2020-12-11 14:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=d. Cannot read property 'canBeRepeatedWithDot' of undefined
	at F.runAction (/Users/miguelhernandez/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172434)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/miguelhernandez/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/miguelhernandez/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/miguelhernandez/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/miguelhernandez/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:09
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:09 UTC
Labels: status/duplicate
