### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by githubmissyang** [VSCodeVim/Vim#5930] opened 2020-12-25 10:09 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:666)
	at t.ExtHostTextEditor.edit (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:201)
	at v.execute (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:66108)
	at F.runAction (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171693)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
	at async F.handleKeyEvent (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
	at async Object.promise (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
	at async Object.runTasks (d:\Users\yangsy49\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-01-24 18:31
Duplicate of #5224. Are you able to reproduce?

**Closed by J-Fields** 2021-01-24 18:31 UTC
