### ISSUE TITLE
Copying does not work when selecting backwards with arrow keys

### ISSUE THREAD

**Issue by nicolas-dular** [VSCodeVim/Vim#2053] opened 2017-10-05 22:45 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.170
- **VsCodeVim Version**:  0.10.1
- **OS**: macOS Sierra 10.12.5

**What happened**:
When selecting words backwards via arrow keys, copy/pasting does not work (only last selected character gets copy/pasted).
This happens in insert and command mode, but does not happen when selecting text backwards via the mouse. This bug is there for minimum ~2 months and is not related to the newest version.

**What did you expect to happen**: 
The whole word "Foo" gets copy/pasted

**How to reproduce it**: 
For example, we select the word "Foo" backwards (starting at the second o) via  SHIFT+LEFT-ARROW-KEY until we reach "F". Then CMD+C/CMD+V and it only pastes in the letter "F". This behaviour does not happen when selecting from "F" to "o".

**Comment by DanEEStar** [comment] 2017-10-11 19:47
This seems to be a duplicate of #1951 and should be fixed with #2062.
At least for insert mode.

**Comment by Chillee** [comment] 2017-10-12 23:10
I believe this is indeed fixed @DanEEStar .

**Closed** 2017-10-20 09:17 UTC
