### ISSUE TITLE
<C-o> and <C-i> do not work after EasyMotion movement

### ISSUE THREAD

**Issue by rndware** [VSCodeVim/Vim#5730] opened 2020-11-22 11:23 UTC
**Describe the bug**
`Ctrl + o` and `Ctrl + i` do not work correctly after vim easy motion movement

**To Reproduce**

1.  Open a document.
2.  Navigate to another place in the document using a vim easy motion command e.g. `<leader> <leader> 2 s`
3.  do `<C-o>` to go back to previous position
4.  Notice that it doesn't go back to correctly

**Expected behavior**
Should go back to previous position within the document

- Extension (VsCodeVim) version: 1.17.1

**Comment by J-Fields** [comment] 2020-11-23 16:51
Duplicate of #5111

**Closed by J-Fields** 2020-11-23 16:51 UTC
Labels: status/duplicate
