### ISSUE TITLE
Error on startup "Cannot read property 'document' of undefined", and startup time 744ms

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#2229] opened 2017-12-15 08:48 UTC
- Extension Name: vim
- Extension Version: 0.10.6
- OS Version: Windows_NT x64 6.1.7601 (Win7)
- VSCode version: 1.19.0

Just tried new VSCode feature `Running Extensions` and got following result:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 744,
		"activateCallTime": 10,
		"activateResolvedTime": 26,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```
Here is a screenshot of the dev-tools:
![image](https://user-images.githubusercontent.com/3358663/34034038-17f6f48c-e17d-11e7-9470-d27ba725bd54.png)

**Comment by jpoon** [comment] 2017-12-15 11:05
dupe of https://github.com/VSCodeVim/Vim/issues/2184

**Closed by jpoon** 2017-12-15 11:05 UTC
