### ISSUE TITLE
Failed to handle key=<C-[>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by korya** [VSCodeVim/Vim#6934] opened 2021-07-30 10:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-[>. Overlapping ranges are not allowed!
    at n._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/Users/korya/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/Users/korya/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/korya/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/Users/korya/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at r (/Users/korya/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:501:15)
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[141, 17] | [141, 16]]"
]
actionsRunPressedKeys: [
  "a",
  "<C-[>"
]
actionsRun: [
  "Qe",
  "C",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 141,
      "character": 17
    },
    "text": "Bu",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 141,
        "character": 11
      },
      {
        "line": 141,
        "character": 19
      }
    ],
    "text": "UrlsetBufs",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:06
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:06 UTC
