### ISSUE TITLE
Cursor not centering on jupyter ipynb

### ISSUE THREAD

**Issue by Enzodtz** [VSCodeVim/Vim#7377] opened 2022-01-05 19:45 UTC
**Describe the bug**
When you press `zz` the cursor will not be centered if you're on a jupyter ipynb file, from vscode's jupyter extension. I know that its a bug inside another extension, so I don't know if it's actually a bug from vim, maybe it could fit as a feature request, or it could just be a bug from them.

**To Reproduce**

1.  Install `ms-toolsai.jupyter` extension'
2.  Open any notebook
3.  Decentralize your cursor (you can add more cells and scroll)
4.  Press `zz`
5. See that the cursor position doesn't change

**Expected behavior**
It should work as in normal files. I think that the cell structure might be breaking some calculation to centralize it or something like that.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.10
- VSCode version: 1.63.2
- OS: Linux Mint 20.1 x86_64

**Comment by J-Fields** [comment] 2022-02-03 18:32
Duplicate of #6649

**Closed by J-Fields** 2022-02-03 18:32 UTC
