### ISSUE TITLE
Failed to handle key=<C-a>. 

### ISSUE THREAD

**Issue by xmascoffee** [VSCodeVim/Vim#5552] opened 2020-11-01 13:13 UTC
"Overlapping ranges are not allowed!"

**To Reproduce**

1.  Go to 'foobar.md'
2.  Enter  `<C-a>`
3.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
RangeError: Failed to handle key=<C-a>. 
	at Function.readLineAt (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:21957)
	at Function.getLineLength (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22297)
	at l.isLineEnd (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14231)
	at Function.immediateMatchingBracket (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:93851)
	at c (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:481980)
	at /home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482794
	at t.ExtHostTextEditor.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:647:588)
	at F.executeCommand (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482786)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475467)
	at async F.handleKeyAsAnAction (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/xmascoffee/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:04
Duplicate of #5224, please post steps on that issue if you can reproduce.

**Closed by J-Fields** 2020-11-12 23:04 UTC
Labels: status/duplicate
