### ISSUE TITLE
Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()

### ISSUE THREAD

**Issue by alinekoeerad** [VSCodeVim/Vim#5953] opened 2021-01-01 12:22 UTC
**To Reproduce** Steps to reproduce the behavior: 1.  Go to '...' 2.  Click on '....' 3.  Scroll down to '....' 4.  See error **VSCodeVim version**: 1.18.5 <details><summary>Stack trace</summary> ``` Error: Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions() at cr.getSearchRanges (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:132702) at cr.exec (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:130826) at cr.execCount (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24652) at x.exec (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:195125) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:94:5) at x.execCount (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641) at F.runAction (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581) at F.handleKeyAsAnAction (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974) at F.handleKeyEvent (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812) at Object.promise (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972) at Object.runTasks (/home/ali/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644) ``` </details>

**Comment by J-Fields** [comment] 2021-02-19 00:24
Duplicate of #5397

**Closed by J-Fields** 2021-02-19 00:24 UTC
Labels: status/duplicate
