### ISSUE TITLE
Failed to handle key=<C-d>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by wkekou** [VSCodeVim/Vim#5873] opened 2020-12-11 21:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.4

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-d>. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:424)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
    at t.with (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:514:1007)
    at B.exec (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:9:213617)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at B.execCount (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:1:24055)
    at D.runAction (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:130018)
    at D.handleKeyAsAnAction (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:129411)
    at D.handleKeyEvent (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:126220)
    at Object.promise (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:9:224042)
    at Object.runTasks (/home/users/etudiant/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:285853)
```

</details>

**Comment by lvdll** [comment] 2020-12-30 10:40
When I got the same error, I replaced
```sh
"vim.insertModeKeyBinds"
```
to
```sh
"vim.insertModeKeyBindings"
```
and it resolved.

**Comment by J-Fields** [comment] 2021-03-24 17:04
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:04 UTC
Labels: status/duplicate
