### ISSUE TITLE
VSCodeVim overriding keystrokes when focussing on breadcrumbs

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#6122] opened 2021-02-11 05:36 UTC
**Describe the bug**
Searching in breadcrumbs (focussed) by typing no longer works when VSCode Vim is enabled

**To Reproduce**

1.  Focus the breadcrumb using `command-shift-.`
2.  Breadcrumb is now focussed with dropdown open
3.  Start typing to search for symbols/files
4.  Keystrokes are registered as characters under normal mode, so nothing is searched and the breadcrumb may get unfocused when pressing `hjkl`

**Expected behavior**
Characters should be registered as those under insert mode, so the search in breadcrumb still works. It's even better if vim shortcut like next/previous item, expand/collapse menu still works

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.9
- VSCode version: 1.54.0-insider
- OS: macOS Catalina 10.15.7

**Comment by J-Fields** [comment] 2021-02-19 00:27
I think this is a duplicate of #3997 - you can hit `/` to filter breadcrumbs

**Closed by J-Fields** 2021-02-19 00:27 UTC
