### ISSUE TITLE
Unable to bind "0" to "^"

### ISSUE THREAD

**Issue by devinalvaro** [VSCodeVim/Vim#1492] opened 2017-04-11 00:52 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Trying to bind `0` to `^` in normal mode with this:

`
"vim.otherModesKeyBindingsNonRecursive": [
    {
        "before": ["0"],
        "after": ["^"]
    }
]
`

### What did you expect to happen?

When I press `0`, I go to the first non-whitespace character in the line

### What happened instead?

Pressing `0` make the cursor go to the first character in the line, whether whitespace or non-whitespace

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Windows 10

**Comment by xconverge** [comment] 2017-04-21 04:21
https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L775

The problem is here due to it being seen as ONLY a count

**Comment by jpoon** [comment] 2018-08-09 04:44
This was fixed with https://github.com/VSCodeVim/Vim/pull/2793

**Closed by jpoon** 2018-08-09 04:44 UTC
Labels: area/remap, kind/bug
