### ISSUE TITLE
Failed to handle key=0. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by vieiro** [VSCodeVim/Vim#5225] opened 2020-09-23 18:51 UTC
A file with many " that should be replaced with '

Did a %s/"/'/g

Then did many "u" commands, and this happened. It would be great if "%s" changes chould be grouped in a single undo operation.

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=0. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:508876)
	at h._isDocumentTextNeeded (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:511875)
	at h.addChange (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:512068)
	at F.handleKeyAsAnAction (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:473195)
	at F.handleKeyEvent (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471527)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
	at async Object.runTasks (c:\Users\antvie\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:59
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:59 UTC
Labels: status/duplicate
