### ISSUE TITLE
Failed to handle key=<tab>. Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by spatel2693** [VSCodeVim/Vim#6390] opened 2021-03-31 17:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<tab>. Cannot read property 'start' of undefined
    at y.exec (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/plugins/easymotion/easymotion.cmd.ts:370:70)
    at y.execCount (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/base.ts:249:20)
    at I.runAction (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:719:20)
    at I.handleKeyAsAnAction (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:650:16)
    at I.handleKeyEvent (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:40)
    at runMicrotasks (<anonymous>)
    at process.async (internal/process/task_queues.js:97:5)
    at Object.promise (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:632:27)
    at Object.runTasks (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 01:43
Duplicate of https://github.com/VSCodeVim/Vim/issues/7461

**Closed by J-Fields** 2022-03-09 01:43 UTC
