### ISSUE TITLE
Undo replaces file content

### ISSUE THREAD

**Issue by Diadlo** [VSCodeVim/Vim#2545] opened 2018-04-18 09:48 UTC
**This a BUG REPORT**

**How to reproduce it**:
1. Open document A
2. Open document B
4. Type `:wq` (or just close and save file)
5. Open B again
6. You can do some changes or do not (most annoying if you do)
7. Press `u`

**What happened**:
Content of document B will be replaced on content of A

**What did you expect to happen**:
Nothing

**Environment**:
- Extension (VsCodeVim) version: 0.11.4
- VSCode version: 1.22.2
- OS version: Arch Linux

**Comment by doudou** [comment] 2018-04-18 12:56
This is a longstanding bug (see https://github.com/VSCodeVim/Vim/issues/2007). Thank you SO MUCH for figuring out a way to reproduce it. As you can see, a lot of people tried without success.

For the record, I needed to *really open* the documents, i.e. either Ctrl+S or double-click the header. Temporarily opening A did not trigger the bug, a.k.a

1. Open document A
1. CTRL+S
1. Open document B
1. modify B
1. `:wq`
1. Open B again
1. Press `u`

**Comment by Diadlo** [comment] 2018-04-18 13:14
@doudou You are right. Thanks for thr record :+1:

**Comment by Chillee** [comment] 2018-04-18 14:37
Awesome! Thanks for the repro. I did some digging a week ago, and I'm pretty sure the commit that caused this issue was https://github.com/VSCodeVim/Vim/issues/1503.

Having a repro so I can make sure both cases still work is great! Hopefully I'll be able to nail down this issue once and for all soon.

**Comment by dagadbm** [comment] 2018-04-19 22:52
oh nice! I ended up just using visual studio undo and redo commands overriding vscode undos because of this random problem. also vscodevim would also "lowerify" all my text so that was awesome -_-

**Comment by Chillee** [comment] 2018-04-23 06:16
This particular issue is fixed in https://github.com/VSCodeVim/Vim/pull/2547

**Closed by Chillee** 2018-04-23 06:16 UTC
