### ISSUE TITLE
Failed to handle key=s. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by ldhlloyd** [VSCodeVim/Vim#5344] opened 2020-10-07 07:07 UTC
**To Reproduce**

1.  Create an empty file.
2.  Switch to visual mode. 
3.  Press "shift + a" or "shift + i"
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=s. Cannot read property 'stop' of undefined
	at p.get cursorStopPosition [as cursorStopPosition] (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
	at F.runAction (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475433)
	at F.handleKeyAsAnAction (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/home/lloyd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 03:03
Duplicate of #4678

**Closed by J-Fields** 2020-10-14 03:03 UTC
Labels: status/duplicate
