### ISSUE TITLE
Failed to handle key `q`: Cannot read property 'registerName' of undefined

### ISSUE THREAD

**Issue by sudoberlin** [VSCodeVim/Vim#7528] opened 2022-02-22 23:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `q`: Cannot read property 'registerName' of undefined
    at U.exec (/home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/src/actions/commands/actions.ts:343:53)
    at U.execCount (/home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/src/actions/base.ts:230:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at j.actionToRecord [as runAction] (/home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/src/mode/modeHandler.ts:714:47)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/src/mode/modeHandler.ts:663:43)
    at j.text [as handleKeyEvent] (/home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/src/mode/modeHandler.ts:478:11)
    at /home/sudoberlin/.vscode/extensions/vscodevim.vim-1.22.2/extensionBase.ts:359:73
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 01:53
Duplicate of #7142

**Closed by J-Fields** 2022-03-09 01:53 UTC
Labels: status/duplicate
