### ISSUE TITLE
Using the repeat command (.) removes next character

### ISSUE THREAD

**Issue by joshcummingsdesign** [VSCodeVim/Vim#4833] opened 2020-05-11 19:43 UTC
**Describe the bug**
When using the repeat command (.) inside a word, the character after the cursor is unexpectedly removed.

**To Reproduce**
1. Given the text `{ property: value, property: value }`, place cursor inside the first instance of the word "property" and do `ciw key`. Then go to the second instance of the word "property" and do `.`.
2. You would expect the result `{ key: value, key: value }`, but instead you get `{key: value, key value }` (the colon is removed).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.1
- VSCode version: 1.45.0
- OS: macOS Mojave 10.14.6

**Comment by J-Fields** [comment] 2020-05-11 19:44
I assume you have something like `jk` mapped to `<Esc>`?

**Comment by joshcummingsdesign** [comment] 2020-05-11 19:45
@J-Fields Yes, `fd` actually

**Comment by J-Fields** [comment] 2020-05-11 19:46
Duplicate of #4814. Should be fixed on master later today (there's a pending PR I haven't had a chance to review yet), and there'll be a patch release in the next day or two.

**Closed by J-Fields** 2020-05-11 19:46 UTC
Labels: kind/bug, status/needs-more-info
