### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ssataanass** [VSCodeVim/Vim#6376] opened 2021-03-29 16:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (c:\Users\iván\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:51884)
    at Object.edit (c:\Users\iván\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:49576)
    at Object.executeTransformations (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\src\transformations\execute.ts:122:29)
    at I.runAction (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:469:11)
    at Object.promise (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\extensionBase.ts:632:27)
    at Object.runTasks (c:\Users\iván\.vscode\extensions\vscodevim.vim-1.19.3\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-03-29 17:02
What were you doing when this happened? Can you reproduce?

**Comment by ssataanass** [comment] 2021-03-30 10:04
It doesn't matter, it was a typo, but thank you

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
