### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by philimon-reset** [VSCodeVim/Vim#6947] opened 2021-08-02 18:17 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\Phili\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\Phili\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at j.rerunRecordedState (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:207:12)
    at j.actionToRecord [as runAction] (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at r (c:\Users\Phili\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:501:15)
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[54, 25] | [54, 25]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "<C-v>",
  "<C-a>"
]
actionsRun: [
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 54,
      "character": 25
    },
    "text": "my",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 54,
        "character": 0
      },
      {
        "line": 54,
        "character": 27
      }
    ],
    "text": "myObject.incr = function (myObject",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:06
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:06 UTC
