### ISSUE TITLE
Visual Line Selection does not follow the cursor when Ctrl+U and Ctrl+D are used

### ISSUE THREAD

**Issue by maxponte** [VSCodeVim/Vim#1178] opened 2016-12-20 06:40 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Enter visual line mode with Shift+V, use Ctrl+U or Ctrl+D to page up or page down

### What did you expect to happen?

In Vim, paging up and down with Ctrl+U and Ctrl+D while in visual line mode cause the selection to follow the cursor, so that paging down will select a page in visual line, etc.

### What happened instead?

In VSCode Vim, the selection stays at the cursor row before paging up or down, and moving with hjkl will bring you back to your cursor's position

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.9
* OS: MacOS 10.11.6

**Comment by xconverge** [comment] 2016-12-20 08:03
This is a dupe of #907 I think

**Comment by johnfn** [comment] 2016-12-31 03:03
Correct, it is.

**Closed by johnfn** 2016-12-31 03:03 UTC
