### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by Mzaien** [VSCodeVim/Vim#6010] opened 2021-01-18 14:15 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
    at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
    at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
    at x.delete (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:43026)
    at x.run (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:43798)
    at F.executeOperator (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:177340)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172320)
    at F.handleKeyAsAnAction (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:31
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:31 UTC
