### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by zymos** [VSCodeVim/Vim#6379] opened 2021-03-30 05:47 UTC
**To Reproduce**
uncertain

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
    at I.updateView (/home/zymos/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:1181:50)
    at I.handleKeyAsAnAction (/home/zymos/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:657:16)
    at process.handledAsAction (internal/process/task_queues.js:97:5)
    at I.async [as handleKeyEvent] (/home/zymos/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/zymos/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:632:27)
    at Object.runTasks (/home/zymos/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:34
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:34 UTC
