### ISSUE TITLE
Support :normal @q command from visual mode

### ISSUE THREAD

**Issue by bschlenk** [VSCodeVim/Vim#2912] opened 2018-07-30 02:02 UTC
**Is your feature request related to a problem? Please describe.**
In vim, I can record a macro and then select some lines in visual mode and execute that macro on each line. The command is `:normal @q` or `:norm @q` ([documentation](http://vim.wikia.com/wiki/Macros#Running_a_macro))

Running this in VSCode I get the error `E492: Not an editor command. '<,'> norm @q`.

**Describe the solution you'd like**
I would like to be able to do the above in VSCode.

**Describe alternatives you've considered**
I can manually execute the macro on each line by navigating between lines with `j` and `k` and running `@q`. I sometimes use [Open in Vim](https://marketplace.visualstudio.com/items?itemName=jonsmithers.open-in-vim) for these types of situations, run the macro directly from vim, and then jump back into VSCode.

**Comment by bschlenk** [comment] 2018-07-30 02:04
Looks like this is a duplicate of https://github.com/VSCodeVim/Vim/issues/2548

**Comment by J-Fields** [comment] 2021-04-01 15:08
Closing as duplicate of #1733

**Closed by J-Fields** 2021-04-01 15:08 UTC
Labels: status/duplicate
