### ISSUE TITLE
Cannot read property 'selection' of undefined

### ISSUE THREAD

**Issue by ppasieka** [VSCodeVim/Vim#2099] opened 2017-10-27 14:37 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**:  0.10.2
- **OS**: Windows 10

**What happened**:

Error occur:
![image](https://user-images.githubusercontent.com/2170707/32108761-f9682e48-bb32-11e7-8caa-7cdfb91c1336.png)

```
Cannot read property 'selection' of undefined: TypeError: Cannot read property 'selection' of undefined
    at t.navigate (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2501577)
    at t.last (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2501036)
    at t.run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2894265)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2615209
    at n.Class.derive._oncancel.then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at p (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2615166)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2614886
    at t.invokeFunction (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1089386)
    at t._tryExecuteCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1080627)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1080327
```

**How to reproduce it**:

1. Open long file ...  to reach EOF you have to scroll it .
2.  Go to INSERT MODE ( I use <kbd>i</kbd> key) somewhere on the beginning of the file
3. Leave INSERT MODE (<kbd>ESC</kbd> key)
4. Hold 'j' key to scroll file down. Line where you went to INSERT mode shouldn't be visible anymore
5. Press 2x single quote key <kbd>'</kbd><kbd>'</kbd> or 2x  backtick key <kbd>\`</kbd><kbd>\`</kbd>

This is scenario where I can reproduce it every time. There is also way to have same error with <kbd>g</kbd><kbd>i</kbd> combination (this is how I encounter this bug first time) but now I cannot figure out right steps.

I think that this bug was introduced in last release, but I'm not 100% sure. 

EDIT:
You don't have to go to INSERT mode... it is enough to scroll in that way that line you were starting on scrolling is not visible on screen anymore ... then <kbd>'</kbd><kbd>'</kbd>

**Comment by westim** [comment] 2017-10-27 15:35
Duplicate of #2031.

**Comment by jpoon** [comment] 2017-11-06 04:46
Let's use #2031 to track.

**Closed by jpoon** 2017-11-06 04:46 UTC
Labels: status/duplicate
