### ISSUE TITLE
Implement vim-highlightedyank

### ISSUE THREAD

**Issue by epeli** [VSCodeVim/Vim#2916] opened 2018-07-30 09:37 UTC
This is the extension I miss the most from Vim. If you accidentally copy the wrong text you'll only know it after you have put it to somewhere.

The idea is to temporarily change to background color of the selection which was yanked to make clear which text actually was yanked.

Here's the original plugin https://github.com/machakann/vim-highlightedyank

Also the SimpleVim vscode plugin implements it https://github.com/jpotterm/vscode-simple-vim#settings

**Comment by nomad-software** [comment] 2018-11-02 11:57
Please make this optional. I would prefer to not see any unnecessary highlighting a la Vim. This plugin is to provide Vim features not those from other editors.

**Comment by jpoon** [comment] 2018-11-02 17:21
This request sounds like a dupe of https://github.com/VSCodeVim/Vim/issues/2333

**Closed** 2019-01-25 04:35 UTC
Labels: status/duplicate
