### ISSUE TITLE
Failed to handle key=~. getLineLength() called with out-of-bounds line 2956

### ISSUE THREAD

**Issue by adderrrallll** [VSCodeVim/Vim#5382] opened 2020-10-11 13:53 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=~. getLineLength() called with out-of-bounds line 2956
    at Function.getLineLength (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.getRight (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10500)
    at ir.exec (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:133443)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at ir.execCount (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37459)
    at F.runAction (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:121922)
    at F.handleKeyAsAnAction (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:121315)
    at F.handleKeyEvent (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:118124)
    at Object.promise (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:9:234345)
    at Object.runTasks (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:282242)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 00:56
Duplicate of #5180

**Closed by J-Fields** 2020-10-14 00:56 UTC
