### ISSUE TITLE
Failed to handle key=u. TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed

### ISSUE THREAD

**Issue by coderguy57** [VSCodeVim/Vim#7014] opened 2021-08-20 13:38 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.6

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed
    at h (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)
    at ua.$tryApplyEdits (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2410:20393)
    at r._doInvokeHandler (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:11989)
    at r._invokeHandler (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:11673)
    at r._receiveRequest (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:10335)
    at r._receiveOneMessage (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:9122)
    at vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:7218
    at l.fire (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at n.fire (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)
    at u._receiveMessage (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)
    at vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621
    at l.fire (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)
    at vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186
    at Socket.T (vscode-file://vscode-app/snap/code/72/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2897:159022)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by J-Fields** [comment] 2022-02-03 02:49
Duplicate of #6872

**Closed by J-Fields** 2022-02-03 02:49 UTC
