### ISSUE TITLE
Files shouldn't be treated as modified when all changes are undone.

### ISSUE THREAD

**Issue by changil** [VSCodeVim/Vim#4550] opened 2020-02-10 05:44 UTC
**Is your feature request related to a problem? Please describe.**
When I undo all changes I made after opening a file, I would like the file's dirty flag removed (i.e., the small filled circle next to the filename to disappear), like in vim. In this way, you know you haven't made any changes from the original file and quit without making any accidental changes.

With VSCodeVim, you open a file, make a change (e.g., delete a char by pressing `x`), undo that change (by pressing `u`), and that file still appears as modified. There's a filled circle next to the filename in the tab bar and you cannot close the file unless you save it, although there's no change that's made by now.

(Not quite sure this would be a feature, but I didn't think it was a bug so I'm filing a feature request. Let me know if you think I should file a bug report.)

**Describe the solution you'd like**
When all changes are undone and thereby there's no difference between the open file and the saved file, the file should be marked such that it's not modified (i.e., no filled circle) and could be closed without saving.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by J-Fields** [comment] 2020-02-12 22:24
Duplicate of https://github.com/VSCodeVim/Vim/issues/3201

**Closed by J-Fields** 2020-02-12 22:24 UTC
