### ISSUE TITLE
Page scrolls half down when cursor hits top / bottom of page

### ISSUE THREAD

**Issue by CrispinLin** [VSCodeVim/Vim#3000] opened 2018-08-28 20:18 UTC
**Describe the bug**
When cursor hits bottom of page and go further, the page jumps half down. Not sure if this is a bug or new feature.

**To Reproduce**
Place cursor at bottom of page and press "j" or "down".

**Expected behavior**
The page scrolls by line with the cursor as when vim is disabled:
![arrow](https://user-images.githubusercontent.com/7615806/44748211-7b856900-ab0f-11e8-96e0-0cb2d20ce8e0.gif)

**Obtained behavior**
It scrolls down half page and put cursor at middle of screen:
![vim](https://user-images.githubusercontent.com/7615806/44748249-95bf4700-ab0f-11e8-867d-346ef28eaaa0.gif)

**Environment**
Extension Name: vim
Extension Version: 0.16.1
OS Version: OSX 10.13.4
VSCode version: 1.26.1

**Comment by bluetech** [comment] 2018-08-29 07:47
Duplicate of #2998, though the gifs are nice.

**Closed** 2018-08-29 07:56 UTC
