### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 16

### ISSUE THREAD

**Issue by Shubham25-cmd** [VSCodeVim/Vim#5476] opened 2020-10-23 02:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 16
    at Function.getLineLength (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at F.executeMovement (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480271)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475336)
    at F.handleKeyAsAnAction (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:59
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:59 UTC
