### ISSUE TITLE
Failed to handle key=<up>. getLineLength() called with out-of-bounds line 496

### ISSUE THREAD

**Issue by manudatta** [VSCodeVim/Vim#5644] opened 2020-11-13 04:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<up>. getLineLength() called with out-of-bounds line 496
	at Function.getLineLength (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at V.execAction (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:191010)
	at V.createMovementResult (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at V.execActionWithCount (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/manu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-17 21:35
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-11-17 21:35 UTC
Labels: status/duplicate
