### ISSUE TITLE
cursor drifts while switch between split panels

### ISSUE THREAD

**Issue by Bittenbydog** [VSCodeVim/Vim#2826] opened 2018-07-10 10:36 UTC
**Describe the bug**
The cursor drifts while switch between split panels.

**To Reproduce**
1. split one file into two panels (left panel and right panel)
2. locate the cursor at line 3 in left panel
3. move the mouse to right panel and active this panel with locating the cursor at line 10
4. do some move actions like `j`, the cursor will jump to line 4 rather than goes to line 11

**Expected behavior**
It seems that the cursor locations in different panels are synchronized.
What expected is that the cursors in different panels are independent with each other even the file opened in panels are the same one.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.14.2
 - VSCode version: 1.25.0
 - OS: macOS High Sierra 10.13.5

**And thank you for your excellent jobs! :blush:**

**Comment by xconverge** [comment] 2018-07-10 14:45
Duplicate of #2688

**Closed by xconverge** 2018-07-10 14:45 UTC
