### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by virtusplmkrs** [VSCodeVim/Vim#3621] opened 2019-03-24 11:01 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.2.0`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/ay/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-03-28 18:54
Dupe of https://github.com/VSCodeVim/Vim/issues/3362

**Closed by jpoon** 2019-03-28 18:54 UTC
