### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by flyingoctopus** [VSCodeVim/Vim#5724] opened 2020-11-20 23:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:508963)
	at h.setLastHistoryEndPosition (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:516515)
	at F.runAction (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:478718)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\vince\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-23 17:33
Duplicate of #5209. If you can repro, please post steps there.

**Closed by J-Fields** 2020-11-23 17:33 UTC
Labels: status/duplicate
