### ISSUE TITLE
Simple undo command behaviour from vi/vim not implemented

### ISSUE THREAD

**Issue by mchong-teal** [VSCodeVim/Vim#3649] opened 2019-04-03 13:44 UTC
**Describe the bug**
The command ":u" is not implemented.  This is how I normally perform undo actions in vi/vim and makes this add-on unusable for me.

**To Reproduce**
- Open a file with vscode/vim
- perform an action
- press escape to go to normal (command mode)
- enter the command ":u"
- press enter
- see: 'Not an editor command u'
- repeat
- uninstall

**Expected behavior**
- The previous action is undone

**Environment (please complete the following information):**
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

**Comment by coreysharris** [comment] 2019-04-11 08:28
Any reason you use ":u" instead of the normal-mode command "u"?  

[https://vimhelp.org/undo.txt.html#undo-commands](https://vimhelp.org/undo.txt.html#undo-commands)

**Comment by mchong-teal** [comment] 2019-04-12 13:32
Muscle memory?

**Comment by J-Fields** [comment] 2019-08-06 00:19
Closing as a duplicate of #3197

**Closed by J-Fields** 2019-08-06 00:19 UTC
Labels: area/commandline, good first issue, kind/enhancement
