### ISSUE TITLE
Selection get cleared when next movement failed

### ISSUE THREAD

**Issue by Xadoy** [VSCodeVim/Vim#5094] opened 2020-07-31 14:30 UTC
**Describe the bug**
Selected text gets deselected if a user tries to perform a failed movement. 

**To Reproduce**

1.  Enter visual mode by hitting `'v'`
2.  select some text, in this example: `cout << "Hello Word!" << endl;`
3.  perform some text movement that will lead to a failure, like `'fa'`
4.  the command 'fa' will fail because it cannot find character `'a'` after the cursor. Selected text gets deselected, while in vim, it would not deselect the text.

**Expected behavior**
`cout << "Hello Word!" << endl;` remains in selection.

**Screenshots**
VSCodeVim:
![vscode](https://user-images.githubusercontent.com/9660951/89044227-adb12e00-d317-11ea-81f9-eef5166b9a72.gif)
Expected behavior from Vim:
![vim](https://user-images.githubusercontent.com/9660951/89044807-7b540080-d318-11ea-90c4-81ccbc9a72ba.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
V1.16.0
- VSCode version:
V1.47.2
- OS:
macOS Catalina V10.15.5

**Comment by J-Fields** [comment] 2020-07-31 15:54
Duplicate of #4512

**Closed** 2020-07-31 15:55 UTC
Labels: area/selection, kind/bug, status/duplicate

**Comment by Xadoy** [comment] 2020-08-01 00:47
That work around doesn't fix the following scenario:
selecting blocks of curly braces, and when it failed to find the next level of curly braces.
The first few command is to illustrate that `vim.sneakReplacesF` was enabled
![sneakFReplaceEnabled](https://user-images.githubusercontent.com/9660951/89090144-f34d1580-d36e-11ea-8da2-fb4533745592.gif)

**Comment by Xadoy** [comment] 2020-08-01 00:50
> That work around doesn't fix the following scenario:
> selecting blocks of curly braces, and when it failed to find the next level of curly braces.
> The first few command is to illustrate that `vim.sneakReplacesF` was enabled
> ![sneakFReplaceEnabled](https://user-images.githubusercontent.com/9660951/89090144-f34d1580-d36e-11ea-8da2-fb4533745592.gif)

nvm, I thought the original issue was closed.
Since it's an open issue, I can help to investigate it.
