### ISSUE TITLE
Ctrl-P and Ctrl-N can‘t work in the latest version

### ISSUE THREAD

**Issue by s97712** [VSCodeVim/Vim#4017] opened 2019-08-29 12:28 UTC
**Describe the bug**
Ctrl-P and Ctrl-N can‘t work in the latest version

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: Vim 1.10.0
- VSCode version: 1.36.1
- OS:

**Additional context**

**Comment by qingtao** [comment] 2019-08-29 13:34
the key Ctrl+n and Ctrl+p in path: C:\Users\tom\.vscode\extensions\vscodevim.vim-1.10.0

```json
{
    "key": "ctrl+n",
    "command": "extension.vim_ctrl+n",
    "when": "(editorTextFocus || vim.mode == 'SearchInProgressMode' || vim.mode == 'CommandlineInProgress') && vim.active && vim.use<C-n> && !inDebugRepl"
}````

```json
{
    "key": "ctrl+p",
    "command": "extension.vim_ctrl+p",
    "when": "(suggestWidgetVisible || vim.mode == 'SearchInProgressMode' || vim.mode == 'CommandlineInProgress') && vim.active && vim.use<C-p> && !inDebugRepl"
}
```

then look them in "Keyboard Shorcuts":
```json
{
  "key": "ctrl+n",
  "command": "extension.vim_ctrl+n",
  "when": "(editorTextFocus || vim.mode == 'SearchInProgressMode' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == ''CommandlineInProgress')'"
}
```
```json
{
  "key": "ctrl+p",
  "command": "extension.vim_ctrl+p",
  "when": "(suggestWidgetVisible || vim.mode == 'SearchInProgressMode' || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == ''CommandlineInProgress')'"
}
```

**Comment by J-Fields** [comment] 2019-08-29 14:59
Duplicate of #4011

**Closed by J-Fields** 2019-08-29 14:59 UTC

**Comment by nelsyeung** [comment] 2020-10-26 19:56
I just want to say that while Ctrl-N works from #4011, Ctrl-P still doesn't work, so this issue is valid.

**Comment by ITenthusiasm** [comment] 2023-09-11 13:15
@J-Fields This unfortunately still seems to be an issue. The linked issue, #4011, didn't deal with `<C-p>`, which is still broken in VS Code. This makes it pretty difficult to look up file names efficiently. Can we reopen?

**Comment by tamird** [comment] 2023-09-11 14:22
This is newly broken in https://github.com/VSCodeVim/Vim/releases/tag/v1.26.0.

**Comment by davetapley** [comment] 2023-09-11 20:49
Workaround for recent bug, add to `settings.json`:
```json
    "vim.handleKeys": {
        "<C-p>": false
    }
```

**Comment by gurry** [comment] 2023-09-26 01:46
> Workaround for recent bug, add to `settings.json`:
> 
> ```json
>     "vim.handleKeys": {
>         "<C-p>": false
>     }
> ```

This didn't work for me. Ctrl+p still moves one line up instead of opening the Go to File dropdown :(. Am I missing something?

**Comment by praharshbhatt** [comment] 2023-09-26 22:29
> > > Workaround for recent bug, add to `settings.json`:
> > > ```json
> > >     "vim.handleKeys": {
> > >         "<C-p>": false
> > >     }
> > > ```
> > 
> > 
> > This didn't work for me. Ctrl+p still moves one line up instead of opening the Go to File dropdown :(. Am I missing something?
> 
> Worked for me. do ctrl + shift + p. type "settings.json" open settings.json and add it there. Make sure to add the "," at the end if theres more stuff under it.

Thanks, this works. Here's how mine looks

```
    // Ignore these key bindings when vim is enabled
    // for ctrl+p and ctrl+w to to work
    "vim.handleKeys": {
        "<C-p>": false,
        "<C-w>": false
    }
```

**Comment by Kellen-Stuart** [comment] 2023-09-30 17:11
`CTRL +p` is a valid VIM command.
> Ctrl + p autocomplete word based on matching words in the backward direction.

This is not a bug, but a configuration issue. Echoing the people above me, you can override by putting the following in your appsettings.json
```
    "vim.handleKeys": {
        "<C-p>": false
     }
```
