### ISSUE TITLE
Cursur does not move when open big files

### ISSUE THREAD

**Issue by Compa0** [VSCodeVim/Vim#1954] opened 2017-08-06 08:55 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

 When open a big txt file, if the file is larger than 5MB, the cursor does not move when press h, j, k , l.
Also, all arrow keys will not work, and you can't type a word in the editor.
When the extension is disabled, cursor movement and typing turns to be fine.

**Comment by Chillee** [comment] 2017-08-08 02:34
@Compa0 I agree that this is an issue I want to fix (especially now that vscode is adding support for much larger files). However, this is a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/1461 Thanks!

**Comment by xconverge** [comment] 2017-09-28 01:25
closing in favor of #1461 thanks

**Closed by xconverge** 2017-09-28 01:25 UTC
