### ISSUE TITLE
Actions after visual line indent are relative to where cursor started

### ISSUE THREAD

**Issue by Metamist** [VSCodeVim/Vim#1143] opened 2016-12-09 13:08 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Selecting multiple lines and indenting them, then doing any actions (such as movement or v) will do the action relative to where the cursor started the selection.

Example keystrokes should be something like `<shift-v>kk>j`

### What did you expect to happen?
Actions done after the multi-line indent should be relative to where the cursor is after going back to normal, not where it started before visual line mode.

### What happened instead?
https://share.metamist.xyz/HyQv97uQl.mp4

### Technical details:

* VSCode Version: 0.4.9
* VsCodeVim Version: Insiders, not sure if that could be the issue?
* OS: Windows 8.1

**Comment by Metamist** [comment] 2016-12-09 13:15
Discovered the same issue with pasting, and it's going haywire when undoing and then pasting again, take a look:
https://share.metamist.xyz/By-_TXOXe.mp4

**Comment by xconverge** [comment] 2016-12-19 04:17
Does this still exist? I can't reproduce it

**Comment by xconverge** [comment] 2016-12-20 04:49
Is this a dupe of #1135

I can't repro either

**Comment by Metamist** [comment] 2016-12-20 06:36
It still happens for me, and has been happening on both my laptop and desktop on both insiders and stable. I’ll check if there are some extensions conflicting.

**Comment by jpoon** [comment] 2017-05-19 06:46
I believe this is fixed by https://github.com/VSCodeVim/Vim/pull/1402. Please re-open if that's not the case.

**Closed** 2017-05-20 09:30 UTC
Labels: status/needs-more-info
