### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by lianduy** [VSCodeVim/Vim#5213] opened 2020-09-23 03:06 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
    at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
    at new l (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:9260)
    at h.updateAndReturnMarks (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:510380)
    at h.finishCurrentStep (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:513901)
    at F.runAction (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:477803)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
    at F.handleKeyEvent (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
    at Object.promise (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235653)
    at Object.runTasks (/Users/zukunft/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-23 18:05
What were you trying to do when this happened?

**Comment by J-Fields** [comment] 2020-09-29 05:32
Dupe of #5277

**Closed by J-Fields** 2020-09-29 05:32 UTC
Labels: kind/bug
