### ISSUE TITLE
Don't scroll right when visually selecting and moving to long lines

### ISSUE THREAD

**Issue by bschlenk** [VSCodeVim/Vim#1609] opened 2017-04-29 21:48 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Type out a few lines of varying length, some of them longer than the available screen space. Make sure text wrapping is off.
Enter visual block selection (V) mode at the beginning of the block of lines and move the cursor down with j. The window scrolls to the text at the end of the line and there is no way to scroll back without grabbing the mouse.

### What did you expect to happen?

Either the window doesn't scroll at all or the cursor is allowed to move left/right within the selection.

### What happened instead?

The window scrolls to the end of the lines.

### Technical details:

It's possible that this is a limitation of vscode. In vim I can move the cursor horizontally within a block selection, so my window isn't forced to jump around because the cursor stays where it was. I'm not sure if vscode forces the cursor to always be at the end of a selection.

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.20
* OS: macOS 10.12.4

**Comment by Chillee** [comment] 2017-04-29 23:31
I think this is a limitation of how we currently store selections internally. We only store a selection's stop and start, and set the cursor at one of them.

For 99% of our use cases, it works fine, but in this case (and some others), we're somewhat limited.

**Comment by Chillee** [comment] 2017-04-30 18:09
This is also a duplicate of #1048 .

**Closed** 2017-05-02 21:58 UTC
Labels: status/duplicate
