### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by gamal-ezzat** [VSCodeVim/Vim#6002] opened 2021-01-16 09:22 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
    at d._lineAt (c:\Users\ALKODS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
    at Object.lineAt (c:\Users\ALKODS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
    at _.exec (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:196742)
    at _.execCount (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24590)
    at x.exec (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:195125)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.execCount (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24579)
    at F.runAction (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171581)
    at F.handleKeyAsAnAction (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
    at F.handleKeyEvent (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
    at Object.promise (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
    at Object.runTasks (c:\Users\ALKODS\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
