### ISSUE TITLE
Failed to handle key=a. Illegal value for `line`

### ISSUE THREAD

**Issue by LAMINE35** [VSCodeVim/Vim#5915] opened 2020-12-21 12:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. Illegal value for `line`
    at d._lineAt (c:\Users\LIL BOU\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
    at Object.lineAt (c:\Users\LIL BOU\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
    at Function.getCharAt (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:13177)
    at L.execAction (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:192209)
    at L.createMovementResult (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:153324)
    at L.execActionWithCount (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:152981)
    at F.executeMovement (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:175649)
    at F.runAction (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171527)
    at F.handleKeyAsAnAction (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170985)
    at F.handleKeyEvent (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167823)
    at Object.promise (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216277)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (c:\Users\LIL BOU\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:02
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:02 UTC
