### ISSUE TITLE
Failed to handle key=<Esc>. TextEditor(vs.editor.ICodeEditor:1,$model6) has been disposed

### ISSUE THREAD

**Issue by brianmhsu** [VSCodeVim/Vim#7115] opened 2021-09-28 06:56 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.7

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model6) has been disposed
    at h (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)
    at Sa.$tryApplyEdits (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:20393)
    at u._doInvokeHandler (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1502:12737)
    at u._invokeHandler (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1502:12421)
    at u._receiveRequest (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1502:11083)
    at u._receiveOneMessage (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1502:9761)
    at vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1502:7857
    at l.fire (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at r.fire (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:16477)
    at f._receiveMessage (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:21747)
    at vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:18625
    at l.fire (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at b.acceptChunk (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:13838)
    at vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:13186
    at Socket.k (vscode-file://vscode-app/c:/Users/aoron/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:164165)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by J-Fields** [comment] 2022-02-03 02:50
Duplicate of #6872

**Closed by J-Fields** 2022-02-03 02:50 UTC
