### ISSUE TITLE
TaskQueue: Error running task. Cannot read property 'options' of undefined.

### ISSUE THREAD

**Issue by jingzhou123** [VSCodeVim/Vim#3596] opened 2019-03-18 07:33 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11784213/54513641-f8d0d800-4992-11e9-83a4-607199716ad8.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.2.0
- VSCode version:1.32.3
- OS: mac 10.14.3

**Additional context**

**Comment by mvllow** [comment] 2019-03-19 16:10
On top of other scenarios, I notice this often when closing multiple tabs.

**Comment by wldcordeiro** [comment] 2019-04-15 20:16
This plugin has this problem a lot and halts often. It's like the one type of plugin that shouldn't halt and become unresponsive since it's the primary functionality of it, but so frequently it does. I see this particular issue a lot where it'll halt for some time, I'll get annoyed and close the file then 10s later when it finally decides to respond it tries to act on a closed document (if I didn't close it then I get the fun chaos of all the keys I attempted pressing, getting pressed at once.

**Comment by japboy** [comment] 2019-05-06 12:44
same here. and i don't know what the problem is... 🤔 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/84360/57225686-11cb4080-7048-11e9-8b32-2f7cc260d7aa.png">

**Comment by nicksergeant** [comment] 2019-05-07 21:24
Similar issue happening for me:

![https://i.nick.sg/8645545dbe2d4d429fa857172850427d.png](https://i.nick.sg/8645545dbe2d4d429fa857172850427d.png)

Though this is reproducible every time by selecting this option:

![https://i.nick.sg/fa2bda70bbc24f2c97c1a0d3ee8f308d.png](https://i.nick.sg/fa2bda70bbc24f2c97c1a0d3ee8f308d.png)

**Comment by brandoncc** [comment] 2019-05-09 16:39
I have the same problem as originally posted on this issue. It happens hundreds of times a day. Any recommendations on how to debug?

![image](https://user-images.githubusercontent.com/543973/57470721-5d473f80-723e-11e9-94c3-1b1f9bc03388.png)

**Comment by lefthandkick** [comment] 2019-05-11 02:16
Dito.. add me to the list.  I suspect it's a simple fix.  Please advise.

**Comment by llwt** [comment] 2019-05-21 19:47
Any update on this? I've had to disable the plugin due it constant hangups and not having VIM is killing me :'(

**Comment by damienstanton** [comment] 2019-06-03 12:59
For anyone looking for a stable alternative: https://marketplace.visualstudio.com/items?itemName=auiworks.amvim

**Comment by knightstick** [comment] 2019-06-20 01:18
This happens to me when I have multiple panes open, and close them all with "Close all Editors"

**Comment by brandoncc** [comment] 2019-06-20 04:59
I finally gave up and switched to atom. I miss VS Code but not enough to use it without this extension in a usable state :-/ I hope it gets resolved eventually!

**Comment by lefthandkick** [comment] 2019-06-20 18:34
Ditto... I'm back using neovim. For complex re-factor, etc., using Pycharms.

Have high hopes for Oni2 (I am also supporting), https://github.com/onivim/oni2





-----Original Message-----

**Comment by brandoncc** [comment] 2019-06-24 20:46
I decided to try removing any extensions I don't use in case there was one causing the issues....so far I haven't had the error come back up. This might be useful for others as well.

**Comment by adam-lee** [comment] 2019-07-09 21:00
So is this error unrelated to my `.vimrc`?

**Comment by brian-human-interest** [comment] 2019-07-14 22:31
I've been seeing this as well. No idea how to debug, would love to hear the community's thoughts.

**Comment by osdf** [comment] 2019-07-30 21:30
This happens to me when switching from a python file to the interactive jupyter pane using "ctrl-w l" (the pane is on the left of the open python file). After pressing the shortcut, it is no longer possible to edit the original python file, because numerous of these error messages constantly pop up: 'Not editing' here means that clicking into the tab/pane with the python file is 'rejected'(?), i.e. some light flickering happens, but no editable cursor appears. Instead, focus then quickly jumps back to the interactive jupyter pane.

**Comment by gerryster** [comment] 2019-07-30 21:55
FWIW: this only happens on my machine when I have another extension enabled. I recently disabled all but a few of my extensions and I have not seen this error. I currently only have the following extensions enabled besides this one: Atom Keymap, jshint, and Open in GitHub, Bitbucket, Gitlab, VisualStudio.com. I will be slowly enabling other extensions. If I find the culprit, I will update this thread. Unfortunately, the errors I see in the developer panel have not made the culprit obvious.

**Comment by osdf** [comment] 2019-07-30 23:02
I have uninstalled all plugins except for the python one and the vscodevim one. The error persists as described.

**Comment by eirikpre** [comment] 2019-08-06 11:03
After stripping my extension fully and enabling line by line, this is the line that is causing problems:
![image](https://user-images.githubusercontent.com/10548539/62534851-48347980-b84a-11e9-9c21-0c39b02c717d.png)
No idea how something might leak to your extension, but it seems it does. That explains why some extensions have this problem, and some does not.

**Comment by Abd-Elrazek** [comment] 2019-08-07 08:42
I have the Same Issue like others ..this happened when I Press on `ctrl + a `to select all document containers
![image](https://user-images.githubusercontent.com/33897416/62608354-fea66600-b8ff-11e9-935f-ad13ca7d4f22.png)

**Comment by johnfn** [comment] 2019-08-08 05:37
Reproduction steps would be very helpful.

**Comment by eirikpre** [comment] 2019-08-08 06:43
@johnfn I thought that was what I did in the post above.
I assume you can add collections to either an empty package and load it with yours while debugging, or you can probably even add it to your own.
1. Add collections to dependencies in `package.json`
2. npm install
3. Make sure collections are loaded. (it was collections/list, in my case)
FYI, removing it fixed it: https://github.com/eirikpre/VSCode-SystemVerilog/commit/98175c9c03a33e25cf1e41b93e3b9e7931a4ff62

**Comment by osdf** [comment] 2019-08-08 21:53
@johnfn Here are the steps to reproduce this error in a setting when using vscodevim when programming in python.

Extension: VsCodeVim, version:1.9.0; Python, ms-python.python 2019.8.29288
VSCode version:1.37.0
OS: OSX 10.14.6

Open a file, say `test.py`. 
* Type `#%%` followed by return.
* Type `print('hello')` and Shift-return. This starts an interactive jupyter session in a new pane (to the right of the python pane).
* Try to switch over to this pane using a vim shortcut (which works e.g. in split windows in vscode): `CTRL-w, l`.

The following error appears: `TaskQueue: Error running task. Failed to handle key=l. Cannot read property 'selections' of undefined.`

**Comment by evgenijrenke** [comment] 2019-11-19 09:59
same here 
VScode:
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-23-generic
```

**Comment by saurabh-hirani** [comment] 2019-12-12 11:43
I also keep on getting this issue often. Don't exactly know why it occurs

```
TaskQueue: Error running task. Failed to handle key=u. Cannot read property 'getTime' of undefined.
```

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by J-Fields** [comment] 2019-12-12 23:53
@saurabh-hirani This is a different issue that has been fixed in master. It'll be in a new patch release soon.

**Comment by ZuBB** [comment] 2019-12-13 12:21
I am not sure if this is still relevant or not but I think I have pretty reliable STR for issue described by @saurabh-hirani 

* open some js/ts file (there should some functions in it)
* select some function (visual selection in terms of vim)
* do 'refactor > move to new file' action;

after vscode done its stuff usually some empty lines remains in editor. and cursor seems to be active/present in edit area; so I press `dd` to drop line. and I get that error (except key `d` is pressed instead of `u`)

**Comment by oouxx** [comment] 2019-12-17 01:47
![Screenshot_20191217_094305](https://user-images.githubusercontent.com/31833929/70957757-1feb4000-20b2-11ea-9d20-df9355e45317.png)
please fix it as early as possible

**Comment by jennykortina** [comment] 2019-12-17 21:27
@J-Fields do you know when the patch comes out for @saurabh-hirani's issue? it happens all day to me

**Comment by marano** [comment] 2019-12-18 14:51
Can't dismiss it, it won't go away ...
![Screenshot 2019-12-18 at 15 50 42](https://user-images.githubusercontent.com/52855/71096255-45f60a80-21ae-11ea-900f-6c12dcda5685.png)

**Comment by Chuckatron** [comment] 2020-02-18 13:57
@J-Fields Hey :) Any details of the commit in master that fixes this, so we can have some idea of when it's in a release. Thanks!

**Comment by ashish5679** [comment] 2020-03-01 23:08
I also faced same issue while trying to record macro in vim extension. Als the recording could not stop when I try to press q. I am following below commands:

Reusable Editing with Macros
q{register} Start recording a new macro in {register}
q Stop recording macro
@{register} Replay macro in {register}
@@ Replay the last macro that you executed

**Comment by J-Fields** [comment] 2020-05-13 18:33
Anyone still seeing this?

**Comment by osdf** [comment] 2020-05-13 20:42
Gone for me. Switching from the python tab to the jupyter tab (where vim bindings no longer work).

**Comment by J-Fields** [comment] 2020-05-13 20:48
Closing this issue. If you see it again, please open a new issue with steps to reproduce.

**Closed by J-Fields** 2020-05-13 20:48 UTC
Labels: help wanted, kind/bug
