### ISSUE TITLE
hope [:e + TAB] Automatic completion of file names

### ISSUE THREAD

**Issue by januwA** [VSCodeVim/Vim#2661] opened 2018-05-16 01:37 UTC

**Comment by alanjds** [comment] 2018-07-04 17:59
May be duplicate of:
- tab completion on vim command line should work #745

May be related with:
- Visual mode replace with tab adds <tab> text #2499

**Comment by jpoon** [comment] 2018-07-04 20:19
Indeed. It is a duplicate of #745

**Closed by jpoon** 2018-07-04 20:19 UTC
