### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by danielcieslinski** [VSCodeVim/Vim#5801] opened 2020-12-01 21:35 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
    at Object.promise (/home/daniel/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235434)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/home/daniel/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:282242)
```

</details>

**Comment by J-Fields** [comment] 2020-12-07 01:11
Duplicate of #5306. What were you trying to do when this happened?

**Closed by J-Fields** 2020-12-07 01:11 UTC

**Comment by berknam** [comment] 2020-12-07 16:07
@danielcieslinski Where you trying to run the "Vim: Remap..." command from command palette when this happened?

**Comment by danielcieslinski** [comment] 2020-12-07 23:46
Yes
