### ISSUE TITLE
Failed to handle key=<Esc>. getLineLength() called with out-of-bounds line 33

### ISSUE THREAD

**Issue by desmith** [VSCodeVim/Vim#5255] opened 2020-09-26 05:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. getLineLength() called with out-of-bounds line 33
    at Function.getLineLength (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.getUpWithDesiredColumn (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11560)
    at l.getLeftThroughLineBreaks (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10810)
    at /Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475270
    at Array.map (<anonymous>)
    at F.runAction (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475217)
    at F.handleKeyAsAnAction (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 17:33
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 17:33 UTC
Labels: kind/bug, status/duplicate
