### ISSUE TITLE
Change surrounding tag keeping attributes

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#3101] opened 2018-10-05 11:31 UTC
**Is your feature request related to a problem? Please describe.**
When I input `cst<div>` the tag element gets overwritten but also all attributes get cleared out.
When hitting `csttdiv` and I don't finish the tag with `>` I cannot execute the surround.

**Describe the solution you'd like**
When hitting `csttdiv` without a closing `>` all attributes should be kept and only the tag should be overwritten.

**Describe alternatives you've considered**
At least prompt that the unclosed tag does not work with surround.

**Additional context**
https://stackoverflow.com/questions/16340037/change-html-tag-in-vim-but-keeping-the-attributes-surround

**Comment by xconverge** [comment] 2018-10-05 15:54
duplicate of #1938

**Closed by xconverge** 2018-10-05 15:54 UTC
