### ISSUE TITLE
Failed to handle key=o. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by joanacodes** [VSCodeVim/Vim#5282] opened 2020-09-28 16:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=o. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
	at new l (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at ft.execCount (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:112316)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/joanamehou-loko/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-29 05:32
Duplicate of #5277 - please let me know on that ticket if you can reproduce (and if so, how?)

**Closed** 2020-09-29 05:32 UTC
Labels: kind/bug, status/duplicate
