### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by altanbayar9** [VSCodeVim/Vim#5309] opened 2020-09-30 17:33 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (c:\Users\Altanbayar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:717)
	at t.ExtHostTextEditor.edit (c:\Users\Altanbayar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:252)
	at F.executeCommand (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:482834)
	at F.runAction (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475478)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\Altanbayar\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-11 03:08
Duplicate of #5224; if you can repro, please post steps there

**Closed by J-Fields** 2020-10-11 03:08 UTC
Labels: status/duplicate
