### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by androsfat** [VSCodeVim/Vim#5767] opened 2020-11-26 22:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:424)
	at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
	at new l (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at a (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77602)
	at O.exec (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77647)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475598)
	at async F.rerunRecordedState (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:487117)
	at async F.executeCommand (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:483915)
	at async F.runAction (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475467)
	at async F.handleKeyAsAnAction (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/home/andros/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 00:20
Duplicate of #5226

**Closed by J-Fields** 2020-12-05 00:20 UTC
