### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by arunkhattri** [VSCodeVim/Vim#3633] opened 2019-03-28 12:32 UTC
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3017900/vscodevim.vim-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.2.0`
- OS Version: `Linux x64 4.19.30-1-MANJARO`
- VSCode version: `1.32.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/arunkhattri/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-03-28 18:53
Dupe of https://github.com/VSCodeVim/Vim/issues/3362

**Closed by jpoon** 2019-03-28 18:53 UTC
