### ISSUE TITLE
visualModeKeyBindingsNonRecursive not work for first key after v pressed

### ISSUE THREAD

**Issue by tiansh** [VSCodeVim/Vim#2746] opened 2018-06-19 03:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT 

**What happened**:

```json
{
  "vim.visualModeKeyBindingsNonRecursive": [
    { "before": ["t"], "after": ["j"] },
    { "before": ["T"], "after": ["J"] },
    { "after": ["t"], "before": ["j"] },
    { "after": ["T"], "before": ["J"] },
    { "before": ["n"], "after": ["k"] },
    { "before": ["N"], "after": ["K"] },
    { "after": ["n"], "before": ["k"] },
    { "after": ["N"], "before": ["K"] },
    { "before": ["s"], "after": ["l"] },
    { "before": ["S"], "after": ["L"] },
    { "after": ["s"], "before": ["l"] },
    { "after": ["S"], "before": ["L"] }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    { "before": ["t"], "after": ["j"] },
    { "before": ["T"], "after": ["J"] },
    { "after": ["t"], "before": ["j"] },
    { "after": ["T"], "before": ["J"] },
    { "before": ["n"], "after": ["k"] },
    { "before": ["N"], "after": ["K"] },
    { "after": ["n"], "before": ["k"] },
    { "after": ["N"], "before": ["K"] },
    { "before": ["s"], "after": ["l"] },
    { "before": ["S"], "after": ["L"] },
    { "after": ["s"], "before": ["l"] },
    { "after": ["S"], "before": ["L"] }
  ]
}
```

1. Create an empty file
2. Prses following keys one by one <kbd>i</kbd><kbd>h</kbd><kbd>e</kbd><kbd>l</kbd><kbd>l</kbd><kbd>o</kbd><kbd>Esc</kbd><kbd>^</kbd><kbd>v</kbd><kbd>s</kbd>
3.
    - Actual: letter `h` was removed and vim enter insert mode
    - Expect: cursor moved to `e`, still in visual mode, `h` is selected

**Environment**:

- Extension (VsCodeVim) version: 0.13.0
- VSCode version: 1.24.1
- OS version: Microsoft Windows [Version10.0.17134.112]

**Comment by ohjames** [comment] 2018-06-19 12:44
This issue is already raised, duplicate.

**Comment by ohjames** [comment] 2018-06-19 12:45
Duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/2233

**Comment by ohjames** [comment] 2018-06-19 16:03
@tiansh Could you close this issue since it is a duplicate?

**Closed** 2018-06-19 17:57 UTC
