### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by gekkoandcompany** [VSCodeVim/Vim#6069] opened 2021-01-30 13:34 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
	at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:424)
	at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
	at a (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74323)
	at F.exec (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74368)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171810)
	at async F.rerunRecordedState (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:178233)
	at async v.execute (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:67137)
	at async F.runAction (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171647)
	at async F.handleKeyAsAnAction (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/ale/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
