### ISSUE TITLE
Cannot remap <C-e> in insert mode

### ISSUE THREAD

**Issue by sobjornstad** [VSCodeVim/Vim#3221] opened 2018-11-26 13:53 UTC
**Describe the bug**
The following setting has no effect:

    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-e>"],
            "after": ["<esc>"]
        }
    ],

(I don't actually want it to remap to just `<esc>`, but I'm starting simple.)

**To Reproduce**
Add the above text to `settings.json` and save. Enter insert mode and try pressing `C-e`. The character on the line below the current one is copied in -- rather than performing the mapped action of `<esc>`.

**Expected behavior**
VSCodeVim acts as if Escape was pressed.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.12
- VSCode version: 1.29.1
- OS: Windows 10.0.15063

**Additional context**
This does not appear to be a duplicate of [Unable to remap `<C-s`> in insert mode](https://github.com/VSCodeVim/Vim/issues/2411). In that issue, the keys that people were trying to remap were not handled by VSCodeVim. In this case, `<C-e>` is [listed in packages.json](https://github.com/VSCodeVim/Vim/blob/1a5f358a1a57c62d5079093ad0dd12c2bf018bba/package.json#L164), and VSCodeVim is doing something with the key (copying the character below the cursor).

**Comment by janhesters** [comment] 2018-12-24 10:13
Same behavior. I tried to remap:

```json
"vim.insertModeKeyBindingsNonRecursive": [{ "before": ["<C-o>", "$"], "after": ["<C-e>"] }]
```

Apparently there is [trouble with remapping `ctrl` commands](https://stackoverflow.com/a/53897785/8331756) in general.

**Comment by sobjornstad** [comment] 2018-12-31 14:00
The workaround is good, but it doesn't help in my case, as I use Ctrl-E to scroll in normal mode without moving the cursor, and not having that is much more annoying than not being able to bind it in insert mode. The `keybindings.json` is not aware of VSCodeVim's modes, so I can't override only in insert mode.

I am not sure that the parent issue @janhesters listed applies to the behavior for `C-e` in particular.. Maybe I'm misunderstanding, but the `package.json` file appears to be binding to Ctrl-E, and VSCodeVim is able to do things specific to the extension when I press Ctrl-E, so this seems like it may be a different issue.

**Comment by jpoon** [comment] 2019-01-30 23:54
Dupe of https://github.com/VSCodeVim/Vim/issues/3221

**Comment by sobjornstad** [comment] 2019-01-31 02:38
@jpoon: You marked this as a duplicate of itself -- did you make a typo? I'd like to follow the duplicate issue.

**Comment by jpoon** [comment] 2019-01-31 02:39
Oh crap. I'm on mobile. There's a PR that I submitted and merged that fixed this issue. You can find the duplicate issue from there.

**Comment by sobjornstad** [comment] 2019-01-31 14:05
Updated to 1.0.5 this morning and this is still not working for me. Or rather, it's working very inconsistently -- *sometimes* it works. I've only gotten it to work directly in the User Settings window and not in any other editor, even after reloading the window, and sometimes it just does nothing or copies the character on the line below (as it did before the change).

Also, if I literally type `<C-e>` in insert mode as the five characters, the mapping activates. >__<

I tried adding C-e explicitly to `vim.handleKeys`; doesn't matter whether I have it in there or not.

Here's my whole `settings.json` in case there's something additional in there that's interacting:

```
{
    "window.zoomLevel": 1,
    "editor.acceptSuggestionOnEnter": "off",
    "breadcrumbs.enabled": true,
    "files.trimTrailingWhitespace": true,
    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe",
    "team.showWelcomeMessage": false,

    "vim.hlsearch": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [" "],
            "commands": [
                ":nohlsearch"
            ]
        },
        {
            "before": ["\\"],
            "after": [";"]
        },
        {
            "before": ["|"],
            "after": [","]
        },
        {
            "before": [";"],
            "after": [":"]
        },
    ],
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-e>"],
            "after": ["<ESC>"]
        }
    ],

    "vim.handleKeys": {
        "<C-t>": false,
        "<C-j>": false,
        "<C-k>": false,
        "<C-s>": false,
        "<C-e>": true
    },

    "editor.rulers": [80],

    "[powershell]": {
        "editor.rulers": [
            120
        ]
    },

    "[markdown]": {
        "files.trimTrailingWhitespace": false
    },
    "workbench.activityBar.visible": true,
    "gitlens.currentLine.enabled": false,
    "gitlens.hovers.currentLine.over": "line",
    "editor.minimap.enabled": false,
    "workbench.sideBar.location": "right",
    "terminal.integrated.rendererType": "dom",
    "editor.renderControlCharacters": false,
    "editor.renderWhitespace": "all",
    "editor.fontLigatures": true,
    "editor.fontFamily": "'Fira Code Regular', Consolas, 'Courier New', monospace"
}
```

**Comment by jpoon** [comment] 2019-01-31 17:15
Can you share your console logs?

**Comment by jpoon** [comment] 2019-01-31 18:14
This works consistently for me.

```
    "vim.insertModeKeyBindings": [
      {
        "before": [
          "<C-e>",
        ],
        "after": [
          "<esc>"
        ]
      }
    ],
```

**Comment by jpoon** [comment] 2019-02-01 01:07
We even have a test case testing this exact scenario :/

https://github.com/VSCodeVim/Vim/blob/master/test/configuration/remapper.test.ts#L304

**Comment by sobjornstad** [comment] 2019-02-01 03:53
I mapped it non-recursively, unlike your snippet or test case -- possible that has anything to do with it?

I'll take a closer look on Monday if that isn't it.

**Comment by sobjornstad** [comment] 2019-02-04 14:03
This morning I updated to 1.0.7, removed all VSCodeVim settings from my `settings.json`, pasted in your snippet, and disabled all other extensions, and it still isn't working consistently for me. I got it to work a couple times, but the rest of the time it followed its unremapped behavior (copies the character on the line below the cursor, or does nothing when there's no character below the cursor). It seems that when it works, it's right after I reload the window, but it doesn't work once *every* time I reload the window.

I'm not sure where to get the console logs you're talking about.

**Comment by jpoon** [comment] 2019-02-04 17:31
1. is your `useCtrlKeys` = true? https://github.com/VSCodeVim/Vim#vscodevim-settings
2. See `debug` configs under https://github.com/VSCodeVim/Vim#vscodevim-settings

**Comment by sobjornstad** [comment] 2019-02-05 13:55
`useCtrlKeys` was not explicitly set; I changed it to `true` and didn't see any change.

The debug logs appear to reveal that there's a timing issue. In both of these cases I'm pressing `i` and then `<c-e>`. Here's when it works:

```
[Extension Host] ModeHandler: debug: handling key=i.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
console.ts:134 [Extension Host] Remapper: verbose: key=i. keySlice=i.
console.ts:134 [Extension Host] ModeHandler: debug: handling key=<C-e>.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=<C-e>. mode=Insert. keybindings=insertModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: verbose: key=<C-e>. keySlice=<C-e>.
console.ts:134 [Extension Host] Remapper: debug: insertModeKeyBindingsMap. match found. before=<C-e>. after=<Esc>. command=undefined.
console.ts:134 [Extension Host] ModeHandler: debug: handling key=<Esc>.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=<Esc>. mode=Insert. keybindings=insertModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: verbose: key=<Esc>. keySlice=<Esc>.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=<Esc>. mode=Insert. keybindings=insertModeKeyBindingsNonRecursiveMap.
```

And here's where it doesn't:

```
[Extension Host] ModeHandler: debug: handling key=i.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
console.ts:134 [Extension Host] Remapper: verbose: key=i. keySlice=i.
console.ts:134 [Extension Host] ModeHandler: debug: handling key=<C-e>.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i,<C-e>. mode=Insert. keybindings=insertModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: verbose: key=i,<C-e>. keySlice=i<C-e>.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=i,<C-e>. mode=Insert. keybindings=insertModeKeyBindingsNonRecursiveMap.
```

Now that I've looked at those, I can confirm that if I wait a second or so after my last keystroke in insert mode, `<C-e>` works correctly every time. Otherwise, VSCodeVim appears to be trying to match multiple characters and not checking to see if smaller numbers of characters form valid mappings.

**Comment by sobjornstad** [comment] 2019-02-13 14:09
Any news on this? Just want to make sure you haven't forgotten about it since the status is still "closed".

**Comment by ohjames** [comment] 2019-03-01 14:22
I'm hitting this issue also.

**Comment by peitalin** [comment] 2019-04-15 05:27
I'm seeing this issue as well:
> 
> Also, if I literally type `<C-e>` in insert mode as the five characters, the mapping activates. >__<
> 
> I tried adding C-e explicitly to `vim.handleKeys`; doesn't matter whether I have it in there or not.

With these settings, `<C-e>` doesn't trigger `cursorEnd`, but it does trigger when I type "<C-e>" in insert mode. The `<C-e>` does however work in normal mode fine.

```
    "vim.useCtrlKeys": true,
    "vim.handleKeys": {
        "<C-a>": true,
        "<C-e>": true,
    },
    "vim.insertModeKeyBindings": [
        {
            "before": ["k", "j"],
            "after": ["<esc>"]
        },
        {
            "before": ["<C-e>"],
            "commands": [
                {
                    "command": "cursorEnd",
                }
            ]
        },
        {
            "before": ["<C-a>"],
            "after": ["^"]
        },
    ],
```

**Comment by jpoon** [comment] 2019-04-15 05:53
Good place to debug the code is here if anybody wants to take a stab at it. https://github.com/VSCodeVim/Vim/blob/2e37f9d80960dabe31f1131d29a12b9c1c18269a/src/configuration/remapper.ts#L71

**Closed** 2019-10-27 04:31 UTC
Labels: status/duplicate, status/needs-more-info

**Comment by sobjornstad** [comment] 2019-12-05 18:33
I am still getting the same behavior I reported originally. VSCodeVim 1.11.3 and VSCode 1.40.2 now. I tried using both `NonRecursive` and normal mappings.
