### ISSUE TITLE
Make Vim * and # Quick Search Work Like REAL VIM

### ISSUE THREAD

**Issue by FremdSprach** [VSCodeVim/Vim#5001] opened 2020-07-08 10:38 UTC
Issue Type: <b>Feature Request</b>

For some **special characters** such as the **curly and square brackets** **`{} []`**, the Vim extension does not support * and # quick (search from where the cursor is located), while the REAL VIM can handle it naturally.

Extension version: 1.14.5
VS Code version: Code - Insiders 1.47.0-insider (49b121daccefff23c0f325ba6914fb3d0b6d7160, 2020-07-08T08:58:58.859Z)
OS version: Windows_NT x64 10.0.19041

**Comment by J-Fields** [comment] 2020-07-08 14:45
Duplicate of #4808

**Closed by J-Fields** 2020-07-08 14:45 UTC
Labels: area/search, kind/bug
