### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by realfranser** [VSCodeVim/Vim#6621] opened 2021-05-14 17:16 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
    at j.updateView (/home/franser/.vscode/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:1179:50)
    at j.handleKeyAsAnAction (/home/franser/.vscode/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:662:16)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at j.async [as handleKeyEvent] (/home/franser/.vscode/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:471:11)
    at Object.promise (/home/franser/.vscode/extensions/vscodevim.vim-1.20.2/extensionBase.ts:628:27)
    at Object.runTasks (/home/franser/.vscode/extensions/vscodevim.vim-1.20.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:34
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:34 UTC
