### ISSUE TITLE
getLineLength() called with out-of-bounds line 273

### ISSUE THREAD

**Issue by RileyMShea** [VSCodeVim/Vim#5498] opened 2020-10-27 08:16 UTC
**To Reproduce**

I don't know, I saw this pop up in my vscode out of the corner of my eye

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 273
	at Function.getLineLength (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/home/riley/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-29 16:18
Duplicate of #5180

**Closed by J-Fields** 2020-10-29 16:18 UTC
