### ISSUE TITLE
Pressing on navigation keys (ex. j) for a long time causes weird UI behavior

### ISSUE THREAD

**Issue by WonSong** [VSCodeVim/Vim#326] opened 2016-06-20 19:46 UTC
OS: Windows 10

This goes away only when I open a different file.
Upon returning to the file, this problem stops and is no longer reproducible, but still reproducible in other files. 

I couldn't upload a gif file, so here is the link: http://wonsong.me/random/vscodevim-bug.gif

**Comment by johnfn** [comment] 2016-06-21 04:09
Are you up to date with the latest version of VSCodeVim? I was aware of this bug, but I thought I fixed it a version or two ago.

**Comment by johnfn** [comment] 2016-06-21 06:31
Bahhh. I know why this is. VSCode currently doesn't allow us to register click events, so I attempted to hack around it and unfortunately my hacks have some bad side effects in some cases. 😞 

The worst thing is that I actually can't reproduce this problem any more, which makes it hard to know if I've fixed it. 

I'm going to think about it for a day to see if any clever hack to my hack will occur to me.

**Comment by johnfn** [comment] 2016-06-21 06:46
Oops, I didn't realize that mentioning this PR would close it, haha. 

But if you don't mind, could you check out the latest version on master and see if it fixes the problem at all? I'm mildly optimistic.

**Comment by WonSong** [comment] 2016-06-21 15:32
It's certainly better than before, but still has some issues. I can live with it though if you would like to close the bug hehe

**Comment by johnfn** [comment] 2016-06-22 08:19
Ah, that's... sorta good.

I pushed another change that might affect things. Is it better now?

**Comment by johnfn** [comment] 2016-07-06 06:13
I suspect that v0.1 will perma-fix this issue - I think I finally fixed what the root cause was.

**Closed by johnfn** 2016-07-06 06:13 UTC
Labels: pending vscode api addition
