### ISSUE TITLE
Repeating (using `.`) inserting a `<tab>` does not work

### ISSUE THREAD

**Issue by wmaurer** [VSCodeVim/Vim#1899] opened 2017-07-04 07:23 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: v0.9.0
- **OS**: Windows 10

**What happened**:
`i`
`<tab>`
`ESC`
`.`
Pressing `i` then `<tab>` inserts a tab as expected.
After pressing `.`, the cursor moves left one space.

**What did you expect to happen**: 
After pressing `.` I expected the operation to be repeated, i.e. another tab to be inserted.

**How to reproduce it**:
`i`
`<tab>`
`ESC`
`.`

*NOTE*: This bug is when trying to insert `<tab>`. When try to insert `<space>` or something else, e.g. `foo`, VSCodeVim works as expected.

**Comment by Chillee** [comment] 2017-07-04 09:22
This is a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/612

I'm going to close in favor of that issue.

Thanks!

**Closed by Chillee** 2017-07-04 09:22 UTC

**Comment by wmaurer** [comment] 2017-07-04 12:03
Oh I see, thanks. It looks rather complex then ...
