### ISSUE TITLE
Cursor position not remembered when navigating windows with <Ctrl-W>[h,l]

### ISSUE THREAD

**Issue by ashimoon** [VSCodeVim/Vim#753] opened 2016-09-10 23:31 UTC
### What did you do?
Navigate between two panes using Ctrl-w h and Ctrl-w l

### What did you expect to happen?

Navigate between two panes back and forth, maintaining (remembering) cursor position in both panes

### What happened instead?
When I navigate back to previous pane, it chooses some random cursor position near the top of the file

### Technical details:

* VSCode Version: 1.5.1
* VsCodeVim Version: latest
* OS: OSX

**Comment by rebornix** [comment] 2016-09-12 04:55
I remember I fixed this issue last time this bug occurred. Need to check why there is a regression.

**Comment by johnfn** [comment] 2016-09-13 02:28
git bisect to the rescue!

**Comment by xconverge** [comment] 2016-09-17 15:27
@rebornix this is still funky, this is now not a random cursor position but the position from the previous pane..

Aren't we retaining the modehandler for each pane with the current position?

When switching between panes, you should be able to have the cursor on 2 different lines

**Comment by xconverge** [comment] 2016-09-17 18:30
this is also a dupe of #581

**Comment by rebornix** [comment] 2016-09-19 17:02
@xconverge ops, I fixed it for two panes working on the same buffer but unluckily panes for different buffers are not covered.

**Closed** 2016-09-19 18:01 UTC
Labels: bug

**Comment by felixSchl** [comment] 2016-10-13 19:26
I am using VS code on Linux and it happens consistently for me (ver 0.3.7)

**Comment by xconverge** [comment] 2016-11-23 00:50
@rebornix I still see this issue
