### ISSUE TITLE
Cannot undo recent changes 

### ISSUE THREAD

**Issue by tweiss777** [VSCodeVim/Vim#8259] opened 2023-02-22 06:09 UTC
When i edit a file and want to undo, The vim plugin only remembers the last couple of changes and it won't let me undo every change that I make. As a result I'm forced to default to using undo normally,

Here is my version of vscode 

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

**Comment by nagy-nabil** [comment] 2023-02-22 16:25
same problem with the same version, and when i tried to disable it and enable it again worked as expected but each time i close vscode it do the same again

**Comment by Komar0ff** [comment] 2023-02-22 19:55
Hi! This is a known problem. https://github.com/VSCodeVim/Vim/issues/8157

**Comment by J-Fields** [comment] 2023-03-02 03:44
Duplicate of #8157, which should be fixed in `v1.25.1`

**Closed by J-Fields** 2023-03-02 03:44 UTC
