### ISSUE TITLE
Ability to clear search

### ISSUE THREAD

**Issue by OliverJAsh** [VSCodeVim/Vim#1053] opened 2016-11-11 12:30 UTC
I have an active search which I would like to clear using a keyboard shortcut, ideally escape. Is this possible? In Vim:

```
nnoremap <silent> <esc><esc> :noh<cr>
```

**Comment by FSMaxB** [comment] 2016-11-11 12:34
First there has to be `noh` before anything can be mapped to it. #1047 

And in Vim `nohl` doesn't clear the search btw. it only disables the highlighting. If you press `n` after `:nohl`, the next search result get's displayed and all the highlights are back again.

**Comment by OliverJAsh** [comment] 2016-11-11 12:35
Thanks for the fast response (and the great extension).

That makes sense. I guess I was asking for the ability to clear highlighting, not the search.

**Comment by FSMaxB** [comment] 2016-11-11 12:40
@OliverJAsh I'm not a developer of this extension.

**Comment by chrahunt** [comment] 2016-11-28 03:51
This looks like a duplicate of #1047?

**Comment by xconverge** [comment] 2016-12-09 02:04
@johnfn @rebornix this looks like it can be closed

**Closed** 2016-12-09 02:57 UTC
Labels: enhancement

**Comment by Awpteamoose** [comment] 2016-12-23 00:22
:noh has been implemented, but I'm still not sure if it's possible to bind ex commands to hotkeys.

**Comment by johnfn** [comment] 2016-12-23 01:15
Remapping is being tracked here: #1166
