### ISSUE TITLE
Failed to handle key=I. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by RongLi-aftership** [VSCodeVim/Vim#5753] opened 2020-11-25 11:25 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=I. Cannot read property 'stop' of undefined
	at p.get cursorStopPosition [as cursorStopPosition] (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
	at F.createUndoPointForBrackets (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:494726)
	at F.runAction (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476613)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/lr.zheng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:34
Do you have the `Template String Converter` extension installed? (#5736)

**Comment by J-Fields** [comment] 2020-12-05 18:38
Duplicate of #5399

**Closed by J-Fields** 2020-12-05 18:38 UTC
