### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by mostafaafara** [VSCodeVim/Vim#6150] opened 2021-02-16 18:17 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at t.ExtHostTextEditor._applyEdit (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:666)
    at t.ExtHostTextEditor.edit (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:201)
    at y.execute (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:782440)
    at F.runAction (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707900)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/home/mostafa/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-02-18 23:22
Duplicate of #5224. What were you trying to do when this happened? (What mode were you in? Did you have multiple cursors?)

**Closed by J-Fields** 2021-02-18 23:22 UTC

**Comment by mostafaafara** [comment] 2021-02-20 13:17
i was selecting text in inset mode in a python script with one curses

**Comment by mostafaafara** [comment] 2021-02-20 13:19
and now i can not use CTR C to copy while CTR V is working

thanks for responding :)

**Comment by J-Fields** [comment] 2021-02-22 17:14
Can you reproduce, or did it just happen once?
