### ISSUE TITLE
Anyway to preserve column when using `gj`/`gk`?

### ISSUE THREAD

**Issue by babramczyk** [VSCodeVim/Vim#6240] opened 2021-03-06 16:11 UTC
I typically remap `j` and `k` to be `gj` and `gk`.

However, when doing this, in VS Code the column is no longer preserves the line column when navigating with the remapped `j` and `k`.

Is this possible to be implemented/integrated with the `Startofline` setting? Ideally I’d be able to both have `j` and `k` respect wrapped lines while moving **and** preserve column when navigating between lines (i.e. when there’s blank lines in between — right now it just keeps the column of the cursor at 0 after hitting one of those lines)

Important to note that this works in native Vim as I describe.

### The remapping, for context

```
nnoremap j gj
nnoremap k gk
```

**Comment by J-Fields** [comment] 2021-03-08 18:17
Duplicate of #1323

**Closed by J-Fields** 2021-03-08 18:17 UTC
