### ISSUE TITLE
Failed to handle key `u`: TextEditor(vs.editor.ICodeEditor:8,$model235) has been disposed

### ISSUE THREAD

**Issue by Mr-qiao** [VSCodeVim/Vim#7658] opened 2022-04-28 11:23 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.2

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:8,$model235) has been disposed
    at i (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1596)
    at Ga.$tryApplyEdits (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2678:18070)
    at v._doInvokeHandler (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:13167)
    at v._invokeHandler (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:12851)
    at v._receiveRequest (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:11513)
    at v._receiveOneMessage (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:10191)
    at vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:8300
    at m.invoke (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at u.fire (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24188)
    at vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at m.invoke (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at o.acceptChunk (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at Socket.O (vscode-file://vscode-app/d:/Users/admin/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3160:9259)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

</details>

**Comment by J-Fields** [comment] 2022-06-09 01:57
Duplicate of #6872

**Closed by J-Fields** 2022-06-09 01:57 UTC
Labels: status/duplicate
