### ISSUE TITLE
getLineLength() called with out-of-bounds line 43

### ISSUE THREAD

**Issue by robyte-ctrl** [VSCodeVim/Vim#5638] opened 2020-11-12 16:11 UTC
**To Reproduce**

Not sure since I wasn't paying attention but this is what I did at the time the extension notified me of an error and asked if I want to report it

1.  Have 2 tabs open horizontally
2.  Create new file
2.  Drag the created file to the tab on the right

**VSCodeVim version**: 1.17.1

<details>
<summary>Stack trace</summary>
```
Error: getLineLength() called with out-of-bounds line 43
  at Function.getLineLength (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
  at l.getRight (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
  at F.updateView (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:138028)
  at _ (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:9:228771)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async Object.promise (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:9:233002)
  at async Object.runTasks (/home/roman/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:282242)
```
</details>

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
