### ISSUE TITLE
`CTRL-U` should delete the line in insert mode if this line does not have any character.

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6196] opened 2021-02-24 13:27 UTC
`CTRL-U` has different behaviour in insert mode. When the line has no characters, it will delete the line in Vim. But it does nothing in VSCodeVim.

**Comment by J-Fields** [comment] 2021-02-24 20:58
Yep, good catch. Note that the behavior here depends on the `backspace` setting.

**Comment by YangChenyuan** [comment] 2021-02-25 06:16
> Yep, good catch. Note that the behavior here depends on the `backspace` setting.

Could you check the issue #6190 ? I think `CTRL-T` in insert mode has some problem, it should not select any text.

**Comment by J-Fields** [comment] 2021-04-07 03:27
Found it 🙂

Duplicate of #6429

**Closed by J-Fields** 2021-04-07 03:27 UTC
Labels: kind/bug, status/duplicate

**Comment by YangChenyuan** [comment] 2021-04-07 03:32
> Found it 🙂
> 
> Duplicate of #6429

I forgot I have post it before.🤣
