### ISSUE TITLE
Failed to handle key=. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Myah4598** [VSCodeVim/Vim#6796] opened 2021-06-25 16:00 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. Overlapping ranges are not allowed!
    at s._applyEdit (c:\Users\samue\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52514)
    at Object.edit (c:\Users\samue\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:50206)
    at Object.executeTransformations (c:\Users\samue\.vscode\extensions\vscodevim.vim-1.21.3\src\transformations\execute.ts:124:29)
    at I.runAction (c:\Users\samue\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\samue\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (c:\Users\samue\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:471:11)
    at c:\Users\samue\.vscode\extensions\vscodevim.vim-1.21.3\extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:46
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:46 UTC
