### ISSUE TITLE
mouseSelectionGoesIntoVisualMode does not work when starting in insert mode

### ISSUE THREAD

**Issue by jkassis** [VSCodeVim/Vim#4666] opened 2020-03-22 18:38 UTC
**Describe the bug**
Start in insert mode. Click and drag the mouse with mouseSelectionGoesIntoVisualMode: true. Mode does not change.

**Expected behavior**
Mode changes to visual mode.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.13.0`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.43.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 255,
		"activateCallTime": 2,
		"activateResolvedTime": 791,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscodevim.vim",
				"_lower": "vscodevim.vim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by J-Fields** [comment] 2020-03-25 20:55
Closing as duplicate of #3389

**Closed by J-Fields** 2020-03-25 20:55 UTC
