### ISSUE TITLE
Marks for previously changed/yanked/pasted text are not set

### ISSUE THREAD

**Issue by ma53** [VSCodeVim/Vim#3693] opened 2019-04-19 14:46 UTC
**Describe the bug**
Changing, yanking, and pasting text does not set the `[` and `]` marks to the beginning and ending characters of the changed/yanked/pasted text.  Attempting to move to these marks yields `E20: Mark not set`.

**To Reproduce**

1.  Open a new file.
2.  Insert some text.
3.  In normal mode, do `` `[ `` or `` `] ``.
4.  Visually select some portion of that text and yank it.
6.  In normal mode, do `` `[ `` or `` `] ``.
7.  Paste the yanked text somewhere.
8.  In normal mode, do `` `[ `` or `` `] ``.

**Expected behavior**
Changing, yanking, and pasting text should set the special `[` and `]` marks to the first and last character of the changed/yanked/pasted text, respectively.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

**Additional context**
This was included as a feature request in #2349, but in my experience it is not the case that special marks are not supported at all.  The `<` and `>` marks for previous visual selection function as expected.  Similarly, the `` ` ``, `.`, and `'` marks all seem to work fine, so...this strikes me as a bug.

**Comment by Gsbansal10** [comment] 2019-07-24 03:01
Same issue here. Thanks for reporting. 

Windows 10
VSCode: latest version.
VSCodevim: latest version.

**Comment by vegerot** [comment] 2020-06-17 13:33
Bumping a year later with the same issue.  Even ideavim has this, and VSCodeVim is so much better!

**Comment by robclancy** [comment] 2020-08-11 20:49
Very common thing I do is visual select and indent then want to go to the end of the previous visual selection. But it doesn't work because of this issue.

**Comment by J-Fields** [comment] 2021-07-26 15:35
Marking as a duplicate of #4734, as I think that's the remaining gap

**Closed by J-Fields** 2021-07-26 15:35 UTC
Labels: kind/feature
