### ISSUE TITLE
Moving the cursor up/down doesn't behave correctly when file contains tabs

### ISSUE THREAD

**Issue by Chiel92** [VSCodeVim/Vim#6063] opened 2021-01-29 12:14 UTC
**Observed behavior**: the below screencaptures demonstrate that VSCodeVim behaves differently than both Vim and VSCode.
**Expected behavior**: VSCodeVim should behave like Vim

## Native VSCode:
https://user-images.githubusercontent.com/1030961/106273053-50e4f080-6232-11eb-8190-63879a5b780c.mp4

## Native Vim (and no, I have not remapped j/k to gj/gk)
https://user-images.githubusercontent.com/1030961/106273066-55110e00-6232-11eb-8a06-3217142d4430.mp4

## VSCodeVim
https://user-images.githubusercontent.com/1030961/106273058-52aeb400-6232-11eb-8a18-415e3c23d63e.mp4

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.53.0-insider
- OS: Win 10

This bug makes VSCodeVim effectively unusable when editing big TSV files, but it is also really annoying when editing code files that contain tabs as indentation. Remapping j/k to gj/gk is not a sufficient workaround, since that also changes the way the cursor behaves with respect to line wrapping.

**Comment by J-Fields** [comment] 2021-02-02 04:01
Duplicate of #2458

**Closed by J-Fields** 2021-02-02 04:01 UTC

**Comment by Chiel92** [comment] 2021-02-02 09:36
Ok the fact that the title of the duplicate mentions j/k and not up/down made that I couldn't find that issue.
