### ISSUE TITLE
Failed to handle key=<C-d>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by Dilshan-Janith** [VSCodeVim/Vim#5690] opened 2020-11-18 10:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-d>. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (c:\Users\Dark_Knight\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
    at new _ (c:\Users\Dark_Knight\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:513:424)
    at new _ (c:\Users\Dark_Knight\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:511:436)
    at l.with (c:\Users\Dark_Knight\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:514:1007)
    at L.exec (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:221021)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at L.execCount (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37395)
    at F.runAction (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
    at F.handleKeyAsAnAction (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\Dark_Knight\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-06 21:11
Duplicate of #5556

**Closed by J-Fields** 2020-12-06 21:11 UTC
