### ISSUE TITLE
Cannot read property 'visibleRanges' of undefined

### ISSUE THREAD

**Issue by FXSuperLee** [VSCodeVim/Vim#5312] opened 2020-10-01 08:16 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'visibleRanges' of undefined
	at F.updateView (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:489831)
	at _ (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:236493)
	at async Object.runTasks (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 22:00
Duplicate of #5256; if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 22:00 UTC
