### ISSUE TITLE
Pattern matching breaks on closing paren

### ISSUE THREAD

**Issue by leontepe** [VSCodeVim/Vim#6976] opened 2021-08-10 08:41 UTC
**Describe the bug**
Vim pattern matching (find with `/` or replace with `:s//`) breaks on closing parenthesis

**To Reproduce**

1.  Make a file
2.  Write something like `console.log('test')'
3.  Try to match the whole pattern using find or substitute
4.  See how it breaks on the closing parenthesis

**Expected behavior**
It should match the pattern. Vim also doesn't break on closing paren.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.21.5
- VSCode version: 1.59.0 (Universal)
- OS: macOS Big Sur 11.4

**Comment by J-Fields** [comment] 2021-08-14 01:25
Duplicate of #3996

**Closed by J-Fields** 2021-08-14 01:25 UTC
