### ISSUE TITLE
getLineLength() called with out-of-bounds line 969

### ISSUE THREAD

**Issue by TylerSustare** [VSCodeVim/Vim#5333] opened 2020-10-05 16:35 UTC
I'm just here after clicking on the "report bug" toast message. I saved a 1000 line terraform file and apparently got an error. I didn't even notice what the error might be.

**To Reproduce**

1.  `cmd + s`
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 969
	at Function.getLineLength (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/tyler/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-13 19:30
Duplicate of #5180, if you can repro, please post steps there.

**Closed by J-Fields** 2020-10-13 19:30 UTC
