### ISSUE TITLE
Non greedy search doesn't find anything

### ISSUE THREAD

**Issue by daelmaak** [VSCodeVim/Vim#5124] opened 2020-08-14 07:24 UTC
**Describe the bug**
Non greedy search (using `.\{-}`) doesn't find anything.

**To Reproduce**

1.  Go to any file
2.  Search with / for a string, using the non greedy matcher `.\{-}` (similar to greedy .*)

**Expected behavior**
I expect this pattern to find any character on the line. This works in a native vim.

**Screenshots**
![Screenshot from 2020-08-14 09-21-01](https://user-images.githubusercontent.com/34311965/90224259-aefe5280-de0f-11ea-9af6-4e690191938f.png)
![Screenshot from 2020-08-14 09-21-15](https://user-images.githubusercontent.com/34311965/90224267-b160ac80-de0f-11ea-9453-324a6a0df111.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.16.0
- VSCode version: 1.48.0
- OS: Ubuntu 18.04.5 LTS

**Comment by sql-koala** [comment] 2020-08-14 15:23
Hi,
vscodevim does not support vim regex syntax (or to a minimum amout). But you can enter javascript regex.
Your example would be: `.*?`
The "?" makes "*" non greedy.

**Comment by J-Fields** [comment] 2020-08-14 15:38
Closing as duplicate of #3996

**Closed by J-Fields** 2020-08-14 15:38 UTC
