### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by spatel2693** [VSCodeVim/Vim#6970] opened 2021-08-09 20:23 UTC
**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'name' of undefined
    at c.updateDecorations (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.21.5/src/actions/plugins/easymotion/easymotion.ts:394:40)
    at j.updateView (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:1583:32)
    at E (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:58:22)
    at runMicrotasks (<anonymous>)
    at process.mh (internal/process/task_queues.js:93:5)
    at /Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:364:13
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 03:26
Duplicate of #6729

**Closed by J-Fields** 2022-03-09 03:26 UTC
