### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by plouvi** [VSCodeVim/Vim#6337] opened 2021-03-23 08:56 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (c:\Users\plouvi\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:51884)
    at Object.edit (c:\Users\plouvi\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:49576)
    at Object.executeTransformations (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\src\transformations\execute.ts:122:29)
    at I.runAction (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\src\mode\modeHandler.ts:712:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\src\mode\modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\src\mode\modeHandler.ts:469:11)
    at Object.promise (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\extensionBase.ts:632:27)
    at Object.runTasks (c:\Users\plouvi\.vscode\extensions\vscodevim.vim-1.19.1\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-03-23 17:04
Can you reproduce?

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
