### ISSUE TITLE
:%s/    /\t/g replaces four spaces with a literal "\t" instead of a tab character

### ISSUE THREAD

**Issue by fadedbee** [VSCodeVim/Vim#4660] opened 2020-03-19 11:53 UTC
Issue Type: <b>Bug</b>

Edit some code indented with four spaces instead of tabs.

Press escape, then type "%s/    /\t/g".

There will now be lots of "\t"s in the code, rather than tab characters. 

Extension version: 1.13.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 2765)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (6.32GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by J-Fields** [comment] 2020-12-09 21:01
Duplicate of #2501, fixed in upcoming release

**Closed by J-Fields** 2020-12-09 21:01 UTC
Labels: status/duplicate
