### ISSUE TITLE
Mapping openEditorAtIndex1 breaks text entry

### ISSUE THREAD

**Issue by k0nserv** [VSCodeVim/Vim#1816] opened 2017-06-09 10:51 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 10.11.6
- **VsCodeVim Version**:  1.13.0
- **OS**: 0.8.4

**What happened**:

1. Added the following rule

```json
        {
            "before": ["<leader>", "1"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.openEditorAtIndex1",
                    "args": []
                }
            ]
        }
```

2. Performed \<leader\>+1
3. Editor changes to editor with index 1
4. Code freeezes and I can no longer edit text. Restarting Code is the only solution

**What did you expect to happen**: 

Change to editor 1 and have a functional editor

**How to reproduce it**:

Use the above rule and try changing active editor index with \<leader\>+1

**Comment by Chillee** [comment] 2017-06-09 17:17
Closing as a duplicate of https://github.com/VSCodeVim/Vim/issues/1648.

**Closed by Chillee** 2017-06-09 17:17 UTC
