### ISSUE TITLE
HJKL and arrow key navigation with same file in two panes occurs relative to last cursor position in either pane

### ISSUE THREAD

**Issue by tedthemusician** [VSCodeVim/Vim#2711] opened 2018-06-06 17:52 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: When the same file is open in two panes, HJKL and arrow key navigation occurs relative to the cursor's last position in either pane.

**What did you expect to happen**: HJKL and arrow key navigation should occur relative to the cursor's last position in the current pane only.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open the same file in two panes (opening a file and pressing `Ctrl+/` is sufficient).
1. Place the cursor at an arbitrary position in one pane.
1. With the mouse, place the cursor at a different position in the other pane.
1. Click the first pane's title tab.
1. Press H, J, K, L, or any arrow key.
Rather than moving one character relative to its previous position, the cursor will move one character relative to the position of the other pane's cursor.

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: 1.23.1, commit d0182c3417d225529c6d5ad24b7572815d0de9ac
- OS version: Windows 10 Pro, version 1803, build 17134.48

**Comment by jpoon** [comment] 2018-06-08 07:27
Dupe of https://github.com/VSCodeVim/Vim/issues/2688

**Closed by jpoon** 2018-06-08 07:27 UTC
