### ISSUE TITLE
Cannot read property 'visibleRanges' of undefined

### ISSUE THREAD

**Issue by Jimbojones1** [VSCodeVim/Vim#5253] opened 2020-09-26 00:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'visibleRanges' of undefined
	at F.updateView (/Users/jimhaff/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:489744)
	at _ (/Users/jimhaff/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:230166)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/jimhaff/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235601)
	at async Object.runTasks (/Users/jimhaff/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-29 05:02
Duplicate of #5256

**Closed by J-Fields** 2020-09-29 05:02 UTC
Labels: kind/bug, status/duplicate
