### ISSUE TITLE
How can I map dH to delete all left in a line?

### ISSUE THREAD

**Issue by meteorsh** [VSCodeVim/Vim#4627] opened 2020-03-07 01:46 UTC
First, I want to thanks for the great work you're doing 👍

I was trying to map `dH` to delete all left and `dL` to delete all right in a line. But when I tried the following code in settings.json, it doesn't work.

```json
// I have mapped H to move to the head and L to move to the end
 "vim.normalModeKeyBindingsNonRecursive": [
 		{
            "before": [
                "d",
                "H"
            ],
            "after": [
                "d",
                "^"
            ]
        },
        {
            "before": [
                "d",
                "L"
            ],
            "after": [
                "d",
                "$"
            ]
        }
],
```
If I use <leader> H it actually work, but I am used to use `dH` to  delete all left in other vim editors.

So is there a way to do solve this problem with VScode-vim?

Thanks！

---

 **Environment**

- Operating system : macOS Majave Version 10.14.5
- Web browser : Version 80.0.3987.132
- VScode:  Version 1.42.1

**Comment by sqlkoala** [comment] 2020-03-07 14:11
Hi,
your mappings are correct in general. But, what you are looking for, is not possible for now. There are some issues with the same topic:
https://github.com/VSCodeVim/Vim/issues/3742
https://github.com/VSCodeVim/Vim/issues/3086

**Comment by J-Fields** [comment] 2020-03-08 16:05
Closing as duplicate of #3086

**Closed by J-Fields** 2020-03-08 16:05 UTC
Labels: area/remap, kind/enhancement
