### ISSUE TITLE
Failed to handle key= . Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by chad-marciniak** [VSCodeVim/Vim#5831] opened 2020-12-05 20:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key= . Cannot read property 'canBeRepeatedWithDot' of undefined
    at F.runAction (/Users/chad/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476382)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/Users/chad/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/chad/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/chad/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/chad/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:09
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:09 UTC
Labels: status/duplicate
