### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by itissidharth** [VSCodeVim/Vim#5943] opened 2020-12-29 23:14 UTC
**To Reproduce**

Happens randomly when I am developing in my iDE( Hard to repro consistently). I have to reload the IDE to get rid if it. Any key pressed in vim mode throws the above error.

**VSCodeVim version**: 1.17.1

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
	at h.setLastHistoryEndPosition (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:516515)
	at F.runAction (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:478718)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:59
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:59 UTC
Labels: status/duplicate
