### ISSUE TITLE
Failed to handle key=. Illegal value for `line`

### ISSUE THREAD

**Issue by hsaljuboori** [VSCodeVim/Vim#5932] opened 2020-12-26 00:55 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code 3.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/Applications/Visual Studio Code 3.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at Function.getFirstNonWhitespaceCharOnLine (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:14610)
	at R.run (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:47688)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.executeOperator (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:177332)
	at async F.runAction (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172320)
	at async F.handleKeyAsAnAction (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/humam.aljuboori/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:49
Duplicate of #6178

**Closed by J-Fields** 2021-03-24 17:49 UTC
