### ISSUE TITLE
Backspace sometimes deletes previous cursor position

### ISSUE THREAD

**Issue by yoongkang** [VSCodeVim/Vim#3027] opened 2018-09-05 11:42 UTC
**Describe the bug**
In INSERT mode, hitting backspace sometimes deletes at the previous cursor's position, rather than the current cursor position. 

**To Reproduce**
In INSERT mode, quickly click on a different part of the editor and hit backspace. Sometimes the deleted character is at the previous position.

**Expected behavior**
I expect hitting backspace will delete at the current cursor position.

**Screenshots**
N/A

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.16.2
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.26.1

**Additional context**
N/A

**Comment by esetnik** [comment] 2018-09-13 16:13
I can confirm i'm facing the same issue. It is sneaky because it will sometimes delete a seemingly random character in the same document.

**Comment by lincolnthree** [comment] 2019-01-31 02:40
Also having the same issue here on OSX. Extension version 1.0.3.

**Comment by jpoon** [comment] 2019-01-31 02:46
Dupe of https://github.com/VSCodeVim/Vim/issues/3157 which has been fixed with https://github.com/VSCodeVim/Vim/pull/3409 and will be included in our next release -- presumably, 1.0.4

**Closed by jpoon** 2019-01-31 02:46 UTC
