### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by YangMengHeng** [VSCodeVim/Vim#5384] opened 2020-10-12 06:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:424)
    at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
    at new l (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
    at a (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77602)
    at O.exec (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77647)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.exec (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:214409)
    at x.execCount (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
    at F.runAction (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
    at F.handleKeyAsAnAction (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/home/qmbz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 02:00
Duplicate of #5381, please post repro steps there.

**Closed by J-Fields** 2020-10-14 02:00 UTC
