### ISSUE TITLE
Multi cursor triggered unexpectedly when using vim to edit html files

### ISSUE THREAD

**Issue by kjgfcdb** [VSCodeVim/Vim#4494] opened 2020-01-14 04:41 UTC
**Describe the bug**
When cursor enters a tag of html file, multi cursor mode is automatically triggered and produces a new cursor.

**To Reproduce**

1.  Open a html file and type `<head></head>`
2.  Move the vim cursor on the `<head>` tag
3. A new cursor will appear on the `</head>` tag

**Screenshots**

Here is the screenshot:

![jieping](https://user-images.githubusercontent.com/15307944/72314655-bec38600-36ca-11ea-96be-fa5ed924821a.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: macOS catalina 10.15.2

**Comment by J-Fields** [comment] 2020-01-14 07:26
Duplicate of #4439

**Closed by J-Fields** 2020-01-14 07:26 UTC
