### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by yogh-TomTom** [VSCodeVim/Vim#6168] opened 2021-02-19 09:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
	at v._lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:1166)
	at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:95)
	at E.exec (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:462099)
	at E.execCount (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355716)
	at S.exec (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:460482)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async S.execCount (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355705)
	at async F.runAction (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
	at async F.handleKeyAsAnAction (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
	at async Object.runTasks (/home/yogh/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
