### ISSUE TITLE
getLineLength() called with out-of-bounds line 107

### ISSUE THREAD

**Issue by ajtdnta** [VSCodeVim/Vim#5263] opened 2020-09-27 06:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 107
	at Function.getLineLength (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.isLineEnd (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:14231)
	at l.getRightThroughLineBreaks (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11052)
	at Object.t.statusBarCommandText (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:31336)
	at Object.updateShowCmd (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:40543)
	at F.handleKeyEvent (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 16:18
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 16:18 UTC
