### ISSUE TITLE
ctrl o shortcut not work sometimes

### ISSUE THREAD

**Issue by winvocation** [VSCodeVim/Vim#3074] opened 2018-09-25 06:15 UTC
**Describe the bug**
when i use vscode-vim on vscode, i need to type "ctrl + o" two times to be effiective somtimes，i do not like use Ctrl + c or Ctrl + [ to change vim mode from insert to normal temporary，so can you answer why is it or how can i fix it ?

**To Reproduce**

1.  input string "aaaaaaaaaaaaa"
2.  Ctrl + o
3.  sometimes it work ,sometimes it not

**Expected behavior**
when i type Ctrl + o , i can change mode from insert to normal temporary , just like vim does.

**Comment by malevinson** [comment] 2018-12-07 15:06
This used to work but now rarely does. It also seems to interfere with other settings. `g;` `g,` and ```` also have similar issues.

**Comment by chhschou** [comment] 2018-12-17 01:13
This used to work with the jump to definition feature, allow me to jump back to where I was before but doesn't anymore. I had to use `^-` shortcut (Go Back) provided by vscode as a workaround.
It is very disruptive because `^o` takes me to a different place in the code and breaks my train of thought.

**Comment by jpoon** [comment] 2018-12-30 08:44
There are multiple issues being mentioned here.

For `ctrl+o` in normal mode (navigating back) @malevinson, @chhschou, do you have repro steps? Is this the same issue as described by https://github.com/VSCodeVim/Vim/issues/3277?

For `ctrl+o` in insert mode (one normal-mode command) @winvocation, I can't repro.

**Comment by chhschou** [comment] 2018-12-30 17:58
Confirm that my issue is duplicate of #3277, thanks for looking into this.

**Comment by jpoon** [comment] 2018-12-30 22:07
Cool.

In an effort to keep the issue list sane, I'm going to close this issue. Feel free to re-open @winvocation if you have further information to provide on your issue.

**Closed by jpoon** 2018-12-30 22:07 UTC
Labels: status/needs-more-info
