### ISSUE TITLE
Failed to handle key=<Esc>. e.getTransformation is not a function

### ISSUE THREAD

**Issue by Pand9** [VSCodeVim/Vim#5472] opened 2020-10-22 21:33 UTC
**To Reproduce**

...

I really can't tell what I did, I was just using VSCodeVim normally. I'm submitting because traceback might be useful.

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. e.getTransformation is not a function
	at b.exec (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:213576)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async b.execCount (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37008)
	at async F.runAction (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/ks/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-08-22 02:31
Duplicate of #7009

**Closed by J-Fields** 2021-08-22 02:31 UTC
