### ISSUE TITLE
Cursor jumps when editing same file in multiple editor groups

### ISSUE THREAD

**Issue by sgronblo** [VSCodeVim/Vim#2787] opened 2018-06-29 01:39 UTC
**BUG REPORT**

**What happened**:

- I open the same file in two "editor groups" (I think this the term for what vim would call "windows")
- I move the cursor to line 10 in EG1
- I switch over to EG2 and move the cursor to line 20
- I switch back to EG1 and press for example w
- The cursor jumps to line 20 (same as in EG2) before performing the move command

**What did you expect to happen**:

- The cursor should not jump away from line 10 to 20 before performing the move command

**Environment**:

- Extension (VsCodeVim) version: 0.14.0
- VSCode version: Version 1.24.1 (1.24.1)
- OS version: macOS High Sierra Version 10.13.5

**Comment by xconverge** [comment] 2018-06-29 02:34
duplicate of #2688

**Closed by xconverge** 2018-06-29 02:34 UTC
