### ISSUE TITLE
`\%V` not recognized in substitutions within visual selections.

### ISSUE THREAD

**Issue by Lugghawk** [VSCodeVim/Vim#4936] opened 2020-06-09 23:39 UTC
**Describe the bug**
In vim, if you want to do a substitution only on text within a visual selection, you need to use the `\%V` atom. See [vimwiki](https://vim.fandom.com/wiki/Search_and_replace_in_a_visual_selection#Substituting_in_a_visual_selection) on the subject.

However, in VSCode Vim, the same technique appears to just result in "E486: Pattern Not Found" instead of doing the substitution.

**To Reproduce**

1. Create a file with the text `"-Hello-There-"`
2. Visually select the `o-T` in the middle of Hello and There.
3. Run the command: `'<,'>s/\%V-//`
4. See "E486: Pattern Not Found"

**Expected behavior**
In Vim, the resulting text leftover after the above command is `"-HelloThere-"`. I expect the same from VSCode Vim.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.14.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.0-insider`

**Comment by J-Fields** [comment] 2021-04-14 21:11
Sort of a duplicate of #3996, though we may be able to fudge it without properly implementing vim's regex flavor

**Comment by alk-mandrianarijaona** [comment] 2021-06-03 15:24
Also search inside visual block using `'<,'>/\%Vfoo` is not working

**Closed** 2021-11-02 18:20 UTC
Labels: kind/bug
