### ISSUE TITLE
Windows 10 Emojis require two characters for navigation

### ISSUE THREAD

**Issue by liamdawson** [VSCodeVim/Vim#2722] opened 2018-06-11 13:15 UTC
Issue Type: <b>Bug</b>

**What happened**:
I typed the 🏢 emoji using the Windows 10 emoji picker, and it changed it to `��` in-editor when I closed the picker.

**What did you expect to happen**:
I expected it to retain the 🏢 emoji.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install this extension
2. Create a new file
3. Press `win`+`.` to open the emoji picker
4. Insert the 🏢 emoji
5. Press `ctrl`, `esc`, or any key that closes the emoji picker (or press the close button on the emoji picker)

Disabling the `vim` extension prevented the issue. Copying and pasting the emoji from Notepad also prevents the issue.

Extension version: 0.12.0
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17133

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (1.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe [project path]|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by liamdawson** [comment] 2018-06-11 13:20
I found a separate issue in that the extension also treats `🏢` as two characters for navigation purposes (e.g. I have to press `ll` or `2l` to move to the next character after the `🏢` character. Worth raising as a separate issue?

**Comment by jpoon** [comment] 2018-12-31 07:18
Workaround for the first issue, is to be in `insert` mode while using the emoji picker.

**Comment by J-Fields** [comment] 2021-04-14 21:28
Related: #2722

**Comment by J-Fields** [comment] 2021-07-21 02:04
Duplicate of #6046

**Closed by J-Fields** 2021-07-21 02:04 UTC
Labels: kind/bug
