### ISSUE TITLE
Bug when using /gc flag in text replacement

### ISSUE THREAD

**Issue by acicovic** [VSCodeVim/Vim#3015] opened 2018-08-31 10:50 UTC
**Describe the bug**
the /gc flag results in erroneous output when replacing text.

**To Reproduce**
Run :%s/mystring/mynewstring/gc confirming all replacements with y, on the following text:
mystring
mystring mystring
mystring mystring mystring

Result is:
mynewstring
mynewstring mynewstringing
mynewstring mynewstring mynewstringstringing

**Expected behavior**
Result should be:
mynewstring
mynewstring mynewstring
mynewstring mynewstring mynewstring

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.2
- VSCode version: 1.26.1
- OS: Windows 10

**Comment by khudyakoff** [comment] 2018-09-03 06:10
Possibly a duplicate of #2950

**Closed** 2019-08-24 03:31 UTC
