### ISSUE TITLE
Failed to handle key=<down>. getLineLength() called with out-of-bounds line 28

### ISSUE THREAD

**Issue by EKashpersky** [VSCodeVim/Vim#5454] opened 2020-10-19 19:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<down>. getLineLength() called with out-of-bounds line 28
	at Function.getLineLength (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getDownWithDesiredColumn (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11451)
	at N.execAction (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:190462)
	at Wt.execAction (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:221186)
	at Wt.createMovementResult (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at Wt.execActionWithCount (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/ekashpersky/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 19:00
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 19:00 UTC
