### ISSUE TITLE
Failed to handle key=r. Illegal value for `line`

### ISSUE THREAD

**Issue by greenymartini** [VSCodeVim/Vim#6064] opened 2021-01-29 15:35 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=r. Illegal value for `line`
	at d._lineAt (/private/var/folders/lp/myj434hs41v5drh03l20z23h0000gn/T/AppTranslocation/B1C67825-823D-4150-940F-B9FD04D68777/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/private/var/folders/lp/myj434hs41v5drh03l20z23h0000gn/T/AppTranslocation/B1C67825-823D-4150-940F-B9FD04D68777/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at le (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:206217)
	at n.execActionWithCount (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:206753)
	at F.executeMovement (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
	at F.runAction (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171527)
	at F.handleKeyAsAnAction (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at Object.promise (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216277)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/martingrunheit/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:05
Duplicate of #5869

**Closed by J-Fields** 2021-03-24 18:05 UTC
