### ISSUE TITLE
Cannot search in visual mode

### ISSUE THREAD

**Issue by adamelliottsweeting** [VSCodeVim/Vim#1520] opened 2017-04-18 02:06 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

1. Press `v` to enter visual block mode - optionally select some more text with `hjkl` keys.
1. Press `/` or `?` to enter forward or backward search respectively.
1. Type `start` to search for that word in the open file.

### What did you expect to happen?

I expected to find the word `start` in my open file.

### What happened instead?

The selected text is replaced with `tart`, as the initial `s` activated text substitution.
Pressing `/` or `?` does not appear to enter search mode.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: OS X El Capitan

**Comment by Chillee** [comment] 2017-04-24 00:10
I suspect that this would be very hard to implement as is, currently, since "search" mode is considered an entirely different mode from "visual" mode. It's trivial to make it possible to do search from visual mode, but that also results in dropping the selection.

**Comment by adamelliottsweeting** [comment] 2017-04-26 01:28
Interesting. It's something I use heavily.

I have also come across other similar issues where you simply can't do some things while in _visual block mode_, such as pasting. I.e.
1. Yank some text
2. Enter visual block mode, select text over multiple lines, attempt to paste.

**Comment by Chillee** [comment] 2017-04-26 22:13
This is actually also a duplicate of #298

**Closed** 2017-05-18 15:39 UTC
Labels: area/search, kind/feature
