### ISSUE TITLE
Undo/redo not working in notebook files using Microsoft's Jupyter extension

### ISSUE THREAD

**Issue by sammito1** [VSCodeVim/Vim#6275] opened 2021-03-14 18:47 UTC
**Describe the bug**
Vim-style undo (`u`) and redo (`ctrl-r`) do not work in Jupyter notebook files using Microsoft's Jupyter extension.

**To Reproduce**

1.  Install Microsoft's Jupyter extension.
2.  Create a new .ipynb file.
3.  Enter a new cell.
4.  In insert mode, write some text.
5.  Exit insert mode and try to undo your actions with (`u`).

**Expected behavior**
Nothing happens to text after pressing `u` in normal mode, with the extension showing that we are "already at oldest change". The same applies to `ctrl-r` (with the extension claiming we are "already at newest change") when trying to redo text that was undoed using the default `ctrl-z` shortcut, which works as expected (along with `ctrl-y`).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.9
- VSCode version: 1.54.2
- Jupyter Notebooks version: 2021.3.619093157
- OS: Windows 10 20H2

**Comment by ianzhuo** [comment] 2021-07-11 17:01
adding this into setting.json may fix the problem.
```
    "vim.normalModeKeyBindings": [
        {
            "before": ["u"],
            "commands": [
                "undo",
            ]
        },
        {
            "before": ["<C-r>"],
            "commands": [
                "redo",
            ]
        }
    ]
```

**Comment by JeroenPeterBos** [comment] 2021-11-30 13:36
I have the exact same problem with the following configuration:

Jupyter Notebooks version: v2021.10.1101450599
VSCode: Version 1.62.3
VSCode Vim: v1.21.10
OS: MacOS Monterey 12.0.1 (ARM architecture)

**Comment by J-Fields** [comment] 2021-12-10 03:35
Duplicate of #6960

**Closed by J-Fields** 2021-12-10 03:35 UTC
Labels: kind/bug, status/duplicate

**Comment by bulletmark** [comment] 2021-12-10 03:43
@J-Fields, normally one would make each new bug instance a duplicate of the old bug, not the other way round!
