### ISSUE TITLE
Pressing remapped Esc doesn't enter normal mode

### ISSUE THREAD

**Issue by navdeepio** [VSCodeVim/Vim#1797] opened 2017-06-01 11:19 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

** BUG REPORT**

**Environment**:

- **VSCode Version**: latest
- **VsCodeVim Version**: latest
- **OS**: archlinux/gnome/wayland

**What happened**:
Swapped caps with esc using the 'caps:swapescape' option, but pressing 'CAPS key' doesn't spawn normal mode.

**What did you expect to happen**: 
Normal mode
**How to reproduce it**:
On latest gnome, select 'swap with escape' in the Caps Lock behaviour heading in the Typing tab. Then try to edit code using vscode + vscodevim

**Comment by Chillee** [comment] 2017-06-01 17:01
This is a vscode bug. #1497

**Comment by Chillee** [comment] 2017-06-02 14:18
The issue is tracked here: https://github.com/VSCodeVim/Vim/issues/1479, so I'm going to close this issue.

**Closed by Chillee** 2017-06-02 14:18 UTC
