### ISSUE TITLE
o and O on indented line provide wrong indent / strip character

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#862] opened 2016-10-09 11:23 UTC
### What did you do?

Given a piece of (python) code with indenting

```
    # comment _
```

where _ marks the cursor, pressing O should add a line above and 'o' should add an indented line below
### What did you expect to happen?

A line to be added with the proper indent
### What happened instead?

Inserting the line above (O) seems to remove a character. The cursor seems to start at column two and then backspace to cursor one. However, the first space I hit seems to be ignored. I have to add 5 spaces in stead of 4 to match my indent below

Inserting below (o) does something similar: The cursor starts initially at the right indent but then jumps back one column
### Technical details:
- VSCode Version: 1.5.2
- VsCodeVim Version: 0.3.3
- OS: Ubuntu 16.04 64bit

**Comment by iivvoo** [comment] 2016-10-09 11:30
Perhaps introduced by the fix for issue #574

**Comment by iivvoo** [comment] 2016-10-09 12:16
Additionally, when I create a new empty file and hit 'i' to insert, the first two letters I type get swapped.

**Comment by xconverge** [comment] 2016-10-09 15:57
@iivvoo I am unable to reproduce this...can you provide me a bigger snippet for a complete file that I can use for testing? o and O are behaving as they are supposed to in this file for me

```
#test
if(True):
  print("test")
  #test
  #test
```

Regarding your second issue for the new file, and swapping the first two letters...I can't reproduce this either, can you open its own issue? How are you opening a new file

**Comment by xconverge** [comment] 2016-10-09 15:59
ah I think I can see your 2nd issue with files acting funny, I was able to reproduce it kind of

**Comment by johnfn** [comment] 2016-10-10 07:33
Yeah, you're totally right. Gonna look into this...

**Comment by johnfn** [comment] 2016-10-10 22:55
Ugh, this is really tricky to reproduce when you want to reproduce it.

**Comment by xconverge** [comment] 2016-11-20 04:55
Is this fixed now? I can't reproduce it anymore

**Comment by iivvoo** [comment] 2016-12-16 09:40
I can't reproduce this anymore. Close?

**Comment by inejge** [comment] 2017-01-24 09:24
(I found this issue while searching for the closest match for the bug I'm seeing.)

![ovsshifto](https://cloud.githubusercontent.com/assets/1049870/22241237/d0332e80-e21e-11e6-9cf2-bcd4fba4807b.gif)

VSC 1.8.1, Linux 32-bit (Debian), Vim 0.5.2.

**Comment by xconverge** [comment] 2017-03-03 15:59
@johnfn this looks like it can be closed

**Closed** 2017-03-03 16:10 UTC
Labels: bug
