### ISSUE TITLE
Can't use control characters in %s replace

### ISSUE THREAD

**Issue by eddieparker** [VSCodeVim/Vim#4334] opened 2019-12-06 16:27 UTC
Issue Type: <b>Bug</b>

**Describe the bug**
Often I want to replace four spaces with a tab, and %s/    /\t/g replaces four spaces with the literal string "\t".

**To Reproduce**

Install the addin, and use %s/    /\t/g and you don't see a tab.

**Expected behavior**
You should see a tab.

Extension version: 1.11.3
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (46.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by J-Fields** [comment] 2019-12-06 17:03
This probably works with neovim integration, but this should be a fairly easy fix.

**Comment by J-Fields** [comment] 2019-12-09 02:08
Unless this is broken for more than just `\t`, this is a dupe of #2501

**Closed by J-Fields** 2019-12-09 02:08 UTC
Labels: kind/bug
