### ISSUE TITLE
Cursor vertical movement on hitting boundary (caused by #2962)

### ISSUE THREAD

**Issue by hotpxl** [VSCodeVim/Vim#3006] opened 2018-08-29 18:48 UTC
**Describe the bug**
In vim, when you "j" to the bottom of the screen and keep pushing it, the screen will move line by line. That's the default behavior. It will NOT "move a half screen at a single time".

I found PR #2962 caused this issue. Reverting this patch (especially the lines in the `else` clause) will set it to the correct behavior.

PR #2962 wanted to change the behavior to, if I "j" to the bottom of the screen and "j" once more, it will move half a screen up, hence center the line I'm on. As I stated, that is not the default behavior and is very confusing.

On the other hand, PR #2962 is supposed to fix #2960 . The second point in #2960 (searching with `/`) is not fixed after the patch either. I don't use mark that often so I didn't test the first point.

All in all, I think we should revert PR #2962 . It's not fixing what it's supposed to do, and is introducing other issues.

**Comment by ahanusa** [comment] 2018-08-29 19:45
I'm also hitting this issue.

**Comment by jpoon** [comment] 2018-08-29 22:04
Dupe of https://github.com/VSCodeVim/Vim/issues/2998

**Closed by jpoon** 2018-08-29 22:04 UTC
Labels: status/duplicate
