### ISSUE TITLE
Fails to load in browser (github.dev)

### ISSUE THREAD

**Issue by diminutivesloop** [VSCodeVim/Vim#7519] opened 2022-02-18 13:18 UTC
**Describe the bug**

When loading a repo in a browser from github.dev the extension fails to activate. The following error appears in the Worker Extension Host log:
```
[2022-02-18 08:11:43.257] [exthost] [error] Activating extension vscodevim.vim failed due to an error:
[2022-02-18 08:11:43.259] [exthost] [error] ./src/util/externalCommand.ts/o<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:543468
./src/util/externalCommand.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:543558
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/cmd_line/commands/bang.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:337068
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/vimscript/exCommandParser.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:549445
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/cmd_line/commandLine.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:328402
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/commands/actions.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:138342
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/register/register.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:487731
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/operator.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:295039
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/include-main.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:254108
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
anonymous/</</<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612780
anonymous/</<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:613074
anonymous/<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:613080
anonymous/<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:84
anonymous@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:223
_loadCommonJSModule@../../../vs/workbench/services/extensions/worker/extensionHostWorker.js:79:603
```

In addition the following messages appear in the browser console:
```
WARN Ignoring the error while validating workspace folder vscode-vfs://github/VSCodeVim/Vim - No file system provider found for resource 'vscode-vfs://github/VSCodeVim/Vim' log.ts:307:11
Activating extension 'vscodevim.vim' failed: Cannot find module '../util/child_process'. mainThreadExtensionService.ts:95:10
    $onExtensionActivationError mainThreadExtensionService.ts:95
    _doInvokeHandler rpcProtocol.ts:472
    _invokeHandler rpcProtocol.ts:457
    _receiveRequest rpcProtocol.ts:373
    _receiveOneMessage rpcProtocol.ts:295
    u rpcProtocol.ts:160
    fire event.ts:628
    onmessage webWorkerExtensionHost.ts:201
```

**To Reproduce**

1. Open a repository on github.dev (https://github.dev/VSCodeVim/Vim)
2. Open a file and insert cursor

**Expected behavior**

Full vim functionality should be available for navigating the file in normal mode.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.22.1
- VSCode version: 1.64.2
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
- Embedder: github.dev

**Comment by J-Fields** [comment] 2022-02-18 17:21
Duplicate of #7469, which was just fixed on master; a new release will be available this afternoon

**Closed by J-Fields** 2022-02-18 17:21 UTC
