### ISSUE TITLE
Failed to handle key=k. getLineLength() called with out-of-bounds line 16

### ISSUE THREAD

**Issue by si9ma** [VSCodeVim/Vim#5657] opened 2020-11-15 15:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. getLineLength() called with out-of-bounds line 16
	at Function.getLineLength (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at $.execAction (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:191010)
	at $.createMovementResult (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at $.execActionWithCount (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/bytedance/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-17 21:35
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-11-17 21:35 UTC
Labels: status/duplicate
