### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Cypher423** [VSCodeVim/Vim#6935] opened 2021-07-30 12:15 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\nlv09166\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\nlv09166\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\nlv09166\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\nlv09166\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\nlv09166\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\nlv09166\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\nlv09166\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[32, 0] | [32, 0]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "i",
  "i",
  "t",
  "_",
  "<Esc>"
]
actionsRun: [
  "D",
  "Ve",
  "$",
  "C",
  "C",
  "$",
  "C",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 32,
      "character": 1
    },
    "text": "in",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 32,
        "character": 0
      },
      {
        "line": 32,
        "character": 3
      }
    ],
    "text": "uint8_t",
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 32,
      "character": 1
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:06
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:06 UTC
