### ISSUE TITLE
Add command history to VSCodeVim command line

### ISSUE THREAD

**Issue by casey-speer** [VSCodeVim/Vim#1491] opened 2017-04-10 16:47 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
Press `:` and enter a command in the VSCodeVim command line, e.g. `%s/"/'/g`. Press `:` to open the command line again. Press `UP_ARROW`.

### What did you expect to happen?
Last command I executed should populate in the command line. Pressing `UP_ARROW` again should cycle to second to last command etc.

### What happened instead?
Nothing. Command line stays empty.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.14
* OS: MacOS 10.11.6

**Comment by xconverge** [comment] 2017-04-10 17:43
duplicate of #779 please thumbs up that ticket

**Closed by xconverge** 2017-04-10 17:43 UTC
