### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by El-Moutaouakkil** [VSCodeVim/Vim#5729] opened 2020-11-21 22:38 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (c:\Users\el moutaouakkil\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
    at new _ (c:\Users\el moutaouakkil\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:513:424)
    at new _ (c:\Users\el moutaouakkil\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:511:436)
    at new l (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9299)
    at a (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:77602)
    at O.exec (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:77647)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475598)
    at F.rerunRecordedState (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:487117)
    at F.executeCommand (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:483915)
    at F.runAction (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475467)
    at F.handleKeyAsAnAction (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-06 21:11
Duplicate of #5556

**Closed by J-Fields** 2020-12-06 21:11 UTC
