### ISSUE TITLE
getLineLength() called with out-of-bounds line 4

### ISSUE THREAD

**Issue by QuocVietHa08** [VSCodeVim/Vim#5216] opened 2020-09-23 10:32 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 4
    at Function.getLineLength (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:22186)
    at l.getRight (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:10461)
    at F.updateView (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:491420)
    at _ (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:234397)
    at Object.runTasks (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-23 18:04
What were you trying to do when this happened?

**Comment by danawoodman** [comment] 2020-09-24 17:57
Dupe of #5180

**Closed** 2020-09-25 20:01 UTC
Labels: kind/bug, status/duplicate
