### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by munael** [VSCodeVim/Vim#5465] opened 2020-10-21 13:45 UTC
**To Reproduce**

1.  Create file with some lines and save.
2.  Use multi-cursor to select some separate lines.
3.  `y` to copy.
4.  Create new temp file by `:enew`
5.  Press `p` to paste.
6.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37457)
	at async n.execCount (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:411708)
	at async F.runAction (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
	at async F.handleKeyAsAnAction (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\a-munael\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:12
Duplicate of #5460

**Closed by J-Fields** 2020-11-12 23:12 UTC
