### ISSUE TITLE
Trailing space are ignored in commands like ":s/^/- "

### ISSUE THREAD

**Issue by jordanauge** [VSCodeVim/Vim#5064] opened 2020-07-22 13:57 UTC
**Describe the bug**
Trailing space are ignored in commands like ":s/^/- "

**To Reproduce**
1. Place the cursor on a line to edit in a random text file
2. For instance, type a command such as :s/^/-[SPACE]
3. Only the dash has been inserted

**Expected behavior**
All characters should have been inserted.
Note that a workaround is to add a slash at the end of the command (:s/^/- / works)

**Environment:**

- Extension (VsCodeVim) version: v1.16.0
- VSCode version:  1.47.2
- OS: Debian/bullseye

**Comment by J-Fields** [comment] 2020-07-22 14:33
Duplicate of #5039

**Closed by J-Fields** 2020-07-22 14:33 UTC
Labels: kind/bug, status/duplicate
