### ISSUE TITLE
getLineLength() called with out-of-bounds line 22

### ISSUE THREAD

**Issue by A-hash-program** [VSCodeVim/Vim#5441] opened 2020-10-17 14:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 22
	at Function.getLineLength (c:\Users\brand\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.getLineEnd (c:\Users\brand\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:13777)
	at F.handleSelectionChange (c:\Users\brand\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:468290)
	at Object.promise (c:\Users\brand\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235549)
	at Object.runTasks (c:\Users\brand\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621922)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:58
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:58 UTC
