### ISSUE TITLE
Keys and combinations fail in insert mode

### ISSUE THREAD

**Issue by deshiknaves** [VSCodeVim/Vim#2294] opened 2018-01-16 12:25 UTC
BUG REPORT

**What happened**:
As of the recent update to VSCode there is some weird behavior with VSVim. For example every now and then in insert mode, you can't use `tab`, `cmd+left`, `cmd+right`, `fn+delete`. Tab actually inserts `<tab>` and the others just do nothing. There may be other key combinations that don't work, but those are ones that I use often so I've noticed the behavior. I've tried this on two different Macs running 10.13.2 and they both have this behavior. Disabling VSVim fixes the issue. If you toggle between visual mode and then back to insert mode, it starts working as expected again.

**What did you expect to happen**:
`tab` should add a tab like it always used to
`cmd+right` should behave like the `end` key
etc.

**How to reproduce it (as minimally and precisely as possible)**:
I haven't found any particular event when this behavior starts. Every now and then (quite often) when it toggles from one mode to another, it start failing. I'll keep a look out to see if I can notice anything in particular that causes the issue. 

I've had this issues for quite a few days. I've tried removing all plugins and installing vim again, same issue.

**Environment**:
- Extension (VsCodeVim) version: 0.10.9
- VSCode version: 1.19.2
- OS version: Mac OSX 10.13.2

**Comment by alexciarlillo** [comment] 2018-01-16 15:31
I am having this exact issue but was hesitant to open a report because I was not 100% sure it was VSCVim. I have followed the same steps as you, disabling all other plugins and reinstalling and still experience the issue. I cannot find a way to trigger it 100% of the time yet. 

I am getting the same tab behavior, and home/end stop working as well. I do not see any debug messages or output.

**Comment by jpoon** [comment] 2018-01-23 12:25
Dupe of #730

**Closed by jpoon** 2018-01-23 12:25 UTC
