### ISSUE TITLE
Jump to Mark in Any file

### ISSUE THREAD

**Issue by kevinly24** [VSCodeVim/Vim#1692] opened 2017-05-11 20:31 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT **:

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: 

**What happened**:
Marks do not work across files  using command 
`{A-Z}	go to mark {A-Z} in any file

**What did you expect to happen**: 
Jump to mark in another file

**How to reproduce it**:
Have a different file active, jumping marks do not do anything

**Comment by Chillee** [comment] 2017-05-12 18:57
This is a dupe of this issue: https://github.com/VSCodeVim/Vim/issues/389, but I think this issue might be clearer.

**Comment by kristian-puccio** [comment] 2017-05-19 11:13
Maybe make it clear that it only applies to uppercase marks

**Comment by walston** [comment] 2017-10-02 21:48
This doesn't appear to be working in the current version.
`mA` doesn't seem to mark anything (no feedback) but if i navigate elsewhere in the same file pressing `` `A`` will jump me back to the mark, BUT does nothing in other files.

**Comment by walston** [comment] 2017-10-04 15:07
#564 is an abandoned PR, tho i'd love if it were finished and merged.

**Comment by yannvr** [comment] 2018-04-27 15:33
Any news on global markers? They are so useful!

**Comment by fabd** [comment] 2019-12-18 13:05
Why does this show as "done" [on the ROADMAP](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#marks-and-motions) if it doesn't work?

**Comment by eduardoarandah** [comment] 2020-02-19 18:09
😀 Global markers is a **deal-breaker** for me, when doing Laravel, 
I have to use many files:

M model
V view
C controler
D databse migration
R request validation
S style
W web routes
A api routes

**Closed** 2020-02-26 01:55 UTC
Labels: area/motion, kind/feature
