### ISSUE TITLE
Failed to handle key=k. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by norabal** [VSCodeVim/Vim#5850] opened 2020-12-08 06:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.4

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:159056)
    at h.setLastHistoryEndPosition (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:166662)
    at D.runAction (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:133333)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at D.handleKeyAsAnAction (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:129411)
    at D.handleKeyEvent (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:126220)
    at Object.promise (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:9:228221)
    at Object.runTasks (/Users/motoi_komatsu/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:285853)
```

</details>

**Comment by J-Fields** [comment] 2020-12-08 06:17
What were you trying to do when this happened?

**Comment by J-Fields** [comment] 2021-02-06 05:59
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:59 UTC
Labels: status/duplicate
