### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by BryceLohr** [VSCodeVim/Vim#5934] opened 2020-12-28 16:36 UTC
**To Reproduce**
Start with this 4-line example document:
```
Testing

Foo
Bar
```

1.  Go to line 1 and yank the text "Testing" (`ggyw`).
2.  Create two cursors, at the beginning of lines 3 and 4 each (`jj<Opt-Cmd-Down>`).
3.  Highlight both strings in visual mode (`ve`).
4.  Attempt to put the yanked text on the highlighted strings (`p`).
5. Error message appears: "Failed to handle key=p. ...".

Expected results:
Yanked text replaces all visual-highlighted strings on `p` to yield:
```
Testing

Testing
Testing
```

Note: this works as expected if using the normal copy & paste commands (`<Cmd-C>`/`<Cmd-V>`) instead of yank/put.

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
	at n.exec (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:103192)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async w.exec (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:107038)
	at async w.execCount (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641)
	at async F.runAction (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/blohr/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by BryceLohr** [comment] 2020-12-28 16:37
Note: issue #5755 is a duplicate of this one, but without the reproduce steps.

**Comment by sql-koala** [comment] 2020-12-28 19:07
Also duplicate of #5493 ;-)

**Comment by J-Fields** [comment] 2020-12-28 19:11
Ah, you're right - closing as duplicate of #5493.

I still can't reproduce this issue - any idea why that might be @sql-koala?

**Closed by J-Fields** 2020-12-28 19:11 UTC
Labels: kind/bug

**Comment by sql-koala** [comment] 2021-01-17 23:01
As a matter of fact, I do @J-Fields :D

You must be using the system clipboard for vim. In that case, the bug also does not happen (just tried ist).

**Comment by J-Fields** [comment] 2021-01-24 20:16
Ah, you're right @sql-koala. Thanks!
