### ISSUE TITLE
Failed to handle key=x. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by lalilulelost** [VSCodeVim/Vim#5277] opened 2020-09-28 11:17 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=x. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (c:\Users\arsac\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
	at new b (c:\Users\arsac\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:499:364)
	at new b (c:\Users\arsac\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:497:187)
	at new l (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9299)
	at h.updateAndReturnMarks (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:510467)
	at h.finishCurrentStep (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:513988)
	at F.runAction (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:477890)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\arsac\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by lalilulelost** [comment] 2020-09-28 11:18
OP is automated, but basically what happens is that when I delete the first line of a file this error pops up.

**Comment by J-Fields** [comment] 2020-09-29 05:30
Can you reproduce reliably?

Is this the right input? `ggVx`

**Comment by lalilulelost** [comment] 2020-09-29 11:27
> Is this the right input? `ggVx`
Yes, that's it exactly.

> Can you reproduce reliably?
Actually... I can't. It was happening in a single file in a single project. Just tried it since the file was still open, and it did give me the error every time I repeated the `ggVx` input. But then I closed the file and reopened it, and the error no longer shows up.

**Comment by connormanning** [comment] 2020-09-29 20:50
I am seeing the same issue, also in only one file which gives the error every time, but not other files in the project.  In fact it seems to happen with every combination I can think of that deletes a portion of the first line of this file.  Here are some combinations I've tried which all display the same error (with the "key" in the error message changing depending on the final keypress) and all involve the first line being deleted:
- `gg dk`
- `gg dd`
- `gg V x`
- `(navigate to line 2, "V" or "v" to enter visual and navigate up to include all/some of the first line) x`
- same as above and then `d`
- `(select all, via Ctrl+A, ggVG, or point-and-click) x`
- same as above and then `d`

Deleting the first line, or portions of it, in `insert` mode works as expected.  Note that the delete behavior works properly even though this error pops up.  If I `gg` and `dd` repeatedly, I get the error for every `dd` but the line is successfully deleted each time.

Happy to do test other commands or grab logs since I can currently reproduce this easily as long as I remember to leave this file open.  VSCodeVim version is 1.17.1

**Comment by YangChenyuan** [comment] 2020-12-07 09:14
I can reproduce it by click <dd> repeatedly in a multi-line file from the end. When delete the first line, the error message is displayed.

**Comment by berknam** [comment] 2020-12-07 18:35
@lalilulelost  @connormanning  @YangChenyuan 
For anyone having this issue, can you please test it again with the newer versions "1.18.x" to see if this is still happening and report back.

**Comment by YangChenyuan** [comment] 2020-12-08 07:23
@berknam 
I cannot reproduce it in the latest version v1.18.4.

**Comment by J-Fields** [comment] 2021-03-25 16:02
This should be fixed. Please open a new issue if it reoccurs.

**Closed by J-Fields** 2021-03-25 16:02 UTC
Labels: kind/bug, status/already-resolved
