### ISSUE TITLE
getLineLength() called with out-of-bounds line 15

### ISSUE THREAD

**Issue by mazisparrow** [VSCodeVim/Vim#5759] opened 2020-11-26 06:33 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 15
    at Function.getLineLength (/Users/mazisparrow/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.getLineEnd (/Users/mazisparrow/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13715)
    at F.handleSelectionChange (/Users/mazisparrow/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:468290)
    at Object.promise (/Users/mazisparrow/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235549)
    at Object.runTasks (/Users/mazisparrow/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621922)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:28
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 18:28 UTC
Labels: status/duplicate
