### ISSUE TITLE
Customizing vim command line shortcuts

### ISSUE THREAD

**Issue by skosch** [VSCodeVim/Vim#1901] opened 2017-07-04 14:48 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

I have a high-latency pinky finger and often inadvertently type `:W` instead of `:w`. I have remapped this in my vim config. Is this possible in VSCodeVim as well? (If it is not, consider this a feature request.)

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Linux

**Comment by Chillee** [comment] 2017-07-06 05:17
Unluckily, this isn't currently possible and isn't easy to add either with the current remapping system.

**Comment by jpoon** [comment] 2018-12-30 11:07
Closing this as a dupe of https://github.com/VSCodeVim/Vim/issues/1901

**Closed by jpoon** 2018-12-30 11:07 UTC
