### ISSUE TITLE
Visual Block can't paste as a block

### ISSUE THREAD

**Issue by abramyangCN** [VSCodeVim/Vim#3543] opened 2019-03-01 14:49 UTC
**What happened**:
![image](https://user-images.githubusercontent.com/19504192/53645359-ac3b8c00-3c73-11e9-943d-fc5c516a67e6.png)
It works in Vim that I can paste the paragraph as a block to the right side,
![image](https://user-images.githubusercontent.com/19504192/53645487-f0c72780-3c73-11e9-8eb2-45bdc912143c.png)
![image](https://user-images.githubusercontent.com/19504192/53645371-afcf1300-3c73-11e9-84dc-0fa4925c250b.png)
but it doesn't work in VScode,it inserts the block after that line.

**What did you expect to happen**:
![image](https://user-images.githubusercontent.com/19504192/53645359-ac3b8c00-3c73-11e9-943d-fc5c516a67e6.png)

thanks!

**Comment by drNoob13** [comment] 2019-05-04 11:11
Confirmed the same behavior happened for VSCodeVim on Ubuntu 16.04.

**Comment by yuppity** [comment] 2019-05-08 18:35
[Ace][ace] does this [perfectly][ex] (as far as I can see at least) and might provide hints as to how to go about fixing/implementing this.

[ace]: https://github.com/ajaxorg/ace
[ex]: https://img.papaija.com/a53ecc2a3428b4e209fb80012691cbba.gif

**Comment by dothan009** [comment] 2019-07-12 12:38
me too.

**Comment by savardiego** [comment] 2019-07-17 21:50
Same for me, both Linux Debian and Mac.

CTRL+v -> select with arrow -> y -> p  
the block is pasted in-line, not as a block like in vim.

**Comment by mplanchard** [comment] 2019-07-21 03:00
Same here on Version 1.36.1 (1.36.1) on macOS 10.14.5 (18F132)

**Comment by sarkig** [comment] 2019-08-07 19:43
Same here on version 1.36.1 rhel74.  Often times I will select a block and paste it over a separately selected block in vim.

**Comment by dcervenkov** [comment] 2019-10-16 05:02
A temporary workaround is to visual block copy in VSCodeVim, then make a selection with the **same number of lines** in visual block mode (the standard `CTRL+v` default) and use `CTRL+SHIFT+v` to paste it as a block while in visual block mode.

**Comment by flashhack** [comment] 2020-03-13 19:17
> A temporary workaround is to visual block copy in VSCodeVim, then make a selection with the **same number of lines** in visual block mode (the standard `CTRL+v` default) and use `CTRL+SHIFT+v` to paste it as a block while in visual block mode.

This works well for me, thanks for the tips!

**Comment by dimitry-ishenko** [comment] 2020-05-13 19:13
@J-Fields any idea when this will be fixed? This seems like a basic vim functionality... :disappointed:

**Comment by J-Fields** [comment] 2020-05-13 19:58
Soon (™)

**Comment by J-Fields** [comment] 2020-05-18 15:29
Closing as duplicate of #1796. This is mostly working on a local branch, I'm just fixing some edge cases and writing tests. Expect it to be included in the next release.

**Closed by J-Fields** 2020-05-18 15:29 UTC
Labels: area/content-change, kind/bug

**Comment by pangteypiyush** [comment] 2020-11-28 10:36
If I yank `two three` and then I cannot paste it over `four` selected in Visual block

```
one four eight
two three five
```

**Comment by XDongiang** [comment] 2021-01-06 07:05
@J-Fields 
I think you must be busy lately.
This bug still exists so far, please fix it as soon as possible!
Thank you.
