### ISSUE TITLE
Move selected code up/down using `j`/`k`

### ISSUE THREAD

**Issue by gilamran** [VSCodeVim/Vim#6638] opened 2021-05-19 21:05 UTC
In VSCode it is possible to move a selected code up or down using the Alt+Arrow key.
Is it possible to create some mapping that will allow me to move the selected down up/down using something like Alt-j/Alt-k? (Just wanna avoid the arrow kays)

Thanks

**Comment by prescottbreeden** [comment] 2021-05-31 06:03
standard vim mapping for this behavior is 

:m .-1<CR>==
:m .+1<CR>==
https://vim.fandom.com/wiki/Moving_lines_up_or_down

However :m (move) is not implemented yet in vscode

**Comment by w-cantin** [comment] 2021-06-03 20:36
Hello,

You can call vscode commands with vim keybindings like this in your file settings.json.
 ```
 {
            "before": ["leader", "j"],
            "commands": [
                "editor.action.moveLinesDownAction",
            ]
        },

```
For more commands you can find them in vscode docs here: https://code.visualstudio.com/docs/getstarted/keybindings

Unfortunately I dont think Alt combinations are yet remappable in vscodevim. A workaround could be using vscode keybindings.json directly with this remapping instead:
```
[
{
  "key": "Alt+j",
  "command":  "editor.action.moveLinesDownAction",
},
]
```

**Comment by J-Fields** [comment] 2021-10-14 18:13
Yeah, @w-cantin's suggestion is the best workaround for now. Marking as duplicate of #2472, because supporting `:m[ove]` would also allow you to do this.

**Closed by J-Fields** 2021-10-14 18:13 UTC
Labels: status/duplicate
