### ISSUE TITLE
Easy Motion looks weird/ is hard to read

### ISSUE THREAD

**Issue by vlurgio** [VSCodeVim/Vim#2820] opened 2018-07-09 17:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**What happened**: Easy motion key hits are off centered and mostly hidden

**What did you expect to happen**: have clear easy motion hints

**How to reproduce it (as minimally and precisely as possible)**: use <leader><leader>w to access easymotion

<img width="1052" alt="screenshot 2018-07-09 13 39 22" src="https://user-images.githubusercontent.com/34552973/42466670-8e912c14-837d-11e8-9e02-0516b9a98c09.png">

**Environment**: Mac osx

- Extension Name: vim
- Extension Version: 0.14.2
- OS Version: Darwin x64 17.6.0
- VSCode version: 1.25.0

**Comment by xconverge** [comment] 2018-07-09 19:13
Did you read https://github.com/VSCodeVim/Vim#vim-easymotion and the customization options available?

**Comment by xconverge** [comment] 2018-07-09 19:14
duplicate of #1746

**Closed by xconverge** 2018-07-09 19:14 UTC
