### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [VSCodeVim/Vim#6938] opened 2021-07-31 02:03 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\shakthim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\shakthim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\shakthim\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\shakthim\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\shakthim\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\shakthim\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\shakthim\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[166, 32] | [166, 31]]"
]
actionsRunPressedKeys: [
  "r",
  "<Esc>"
]
actionsRun: [
  "D",
  "Ve",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 160,
      "character": 24
    },
    "text": "req",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 160,
        "character": 22
      },
      {
        "line": 160,
        "character": 27
      }
    ],
    "text": "m_requestCache",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:06
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:06 UTC
Labels: status/duplicate
