### ISSUE TITLE
getLineLength() called with out-of-bounds line 879

### ISSUE THREAD

**Issue by chrkl** [VSCodeVim/Vim#5561] opened 2020-11-02 16:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 879
	at Function.getLineLength (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at l.getLeftThroughLineBreaks (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
	at Object.t.statusBarCommandText (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31413)
	at Object.updateShowCmd (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
	at F.handleKeyEvent (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/kleineweber/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:27
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:27 UTC
