### ISSUE TITLE
"y" copying in visual mode does not work as expected

### ISSUE THREAD

**Issue by AlseinX** [VSCodeVim/Vim#2093] opened 2017-10-25 10:06 UTC
when using “< C-v>y” copying in visual mode and "p" to paste, the selected content appears on a new line which means it regards the inline content as a line copying, while vim on linux does not have this problem.
example:
The content in the editor is:
123456789
in normal mode, press:
2l< C-v>4lyP
with vim on linux, it was
12345673456789
(inline copy and paste)
but with VSCodeVim, it turns to be
34567

123456789
(multiline copy and paste)

**Comment by maljukan** [comment] 2017-11-11 01:52
Confirming the issue:

Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T12:44:48.751Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by tankywoo** [comment] 2018-04-10 05:25
Have the same question. (Search issues and https://github.com/VSCodeVim/Vim/issues/2336 is the same problem)

Under vim, I always use `ctrl-v` into visual (block) mode, rarely use `v` into visual (character) mode 😢 , after search and remember that `v` can select character, and try on vscode-vim, found it works as expect.

But I still hope vscode-vim can fix `ctrl-v` manual different from vim in online select/copy and paste.

**Comment by chenghung** [comment] 2018-05-16 08:05
vim version: 0.11.6
vscode: 1.23.1
the same issue occurred.

**Comment by Kynolin** [comment] 2018-07-17 15:14
This bug is also mentioned in #1796.

**Comment by Kynolin** [comment] 2019-08-14 16:05
I just found what might be a workaround for the paste issue. Maybe this process could somehow be incorporated into the vim plugin's yank/put behavior for visual block?

1. In visual block, select and yank a block across multiple lines, somewhere in the middle of the lines.
2. Select a new location in visual block, one character, same number of vertical lines.
3. Press shift+i to go into multiline insert mode.
4. Press ctrl+shift+v while in insert mode, and the lines paste as would be expected with y/p.

In the following example, if you copy the block containing "one" and "two" and use the process to paste to the right of the "X", it'll paste without the newlines.

Example:
```
copy one copy
copy two copy

paste X paste
paste X paste
```

Result:
```
paste Xone paste
paste Xtwo paste
```

**Comment by J-Fields** [comment] 2020-05-20 16:15
Duplicate of #1796. This will be fixed in the next feature release.

**Closed by J-Fields** 2020-05-20 16:15 UTC
