### ISSUE TITLE
<C-u>/<C-b> don't move cursor if the first line is visible

### ISSUE THREAD

**Issue by kevinji** [VSCodeVim/Vim#3648] opened 2019-04-03 03:48 UTC
**Describe the bug**
Pressing `<C-u>` or `<C-b>` when the first line is visible doesn't do anything.

**To Reproduce**

1.  Open any file with multiple lines.
2.  Move the cursor somewhere down the page, keeping the first line visible.
3.  Press `<C-u>` or `<C-b>`.

**Expected behavior**
The cursor should move up a half / full screen, up to a character on the first line.

**Environment (please complete the following information):**
Extension version: 1.3.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by J-Fields** [comment] 2019-04-03 17:21
Duplicate of #3083, which has a PR pending.

**Comment by kevinji** [comment] 2019-04-08 12:46
I'm not sure if this is a complete duplicate; #3083 only mentions `<C-u>`, and the linked PR only seems to fix `<C-u>` as well.

**Comment by J-Fields** [comment] 2019-04-08 22:02
You're right; my mistake.

**Comment by jpoon** [comment] 2019-05-19 07:08
Closed with https://github.com/VSCodeVim/Vim/pull/3776

**Closed by jpoon** 2019-05-19 07:08 UTC
Labels: kind/bug

**Comment by kevinji** [comment] 2019-05-21 10:47
@jpoon Does this fix `<C-u>` (full page up) as well? The PR doesn't seem to mention anything about it.
