### ISSUE TITLE
`<Esc>` does not cancel multi-cursor

### ISSUE THREAD

**Issue by poliyka** [VSCodeVim/Vim#6719] opened 2021-06-10 06:20 UTC
**Describe the bug**
vim extension (v1.21.0) Multi-Cursor can't escape.

**To Reproduce**

1.  enable vim extension (v1.21.0)
2.  gb * 2
3.  esc 
4.  See error

**Expected behavior**
Escape to Normal mode.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.0
- VSCode version: 1.56.2
- OS: windows 10 subsystem ubuntu 20.04

**Comment by Knorway** [comment] 2021-06-10 09:25
in my case, extension adds "editor.tabSize": 8 to settings.json automatically everytime I open vscode.

**Comment by lleheny0** [comment] 2021-06-10 16:44
I'm getting this too. I'm guessing it has to do with this commit: https://github.com/VSCodeVim/Vim/commit/9091da09cc1c0a37bf3e659e11a7f2f9e0ea4999 but there are a few in the last changelog that are related to cursor so I'm not totally sure.

I noticed this problem because I'm used to the cursor being on a word, hitting ctrl+D a bunch of times to highlight multiples of the word, and hitting my `extension.vim_escape` key (for me it's ctrl+J) to lose the selection while maintaining multiple cursors. From there I can do whatever edits I need, and hit `extension.vim_escape` again to exit multiple cursors. That all works for me still except for the last part. With this update, `extension.vim_escape` does not exit multi-cursor mode anymore. I can map `removeSecondaryCursors` to be the same keybinding as `extension.vim_escape`, but then when I want to lose the selections I got with ctrl+D, I also lose multi-cursor.

**Comment by devert** [comment] 2021-06-10 17:00
Shift + Esc is another workaround for the time being.

**Comment by honkaboy** [comment] 2021-06-11 00:22
Shift + Esc worked for a little while for me and then inexplicably stopped working; another workaround I found was to undo (`u`) + redo (`ctrl-r`).

**Comment by sethmnielsen** [comment] 2021-06-11 17:51
I also have this issue on Arch Linux; I noticed this after upgrading my Vim extension to 1.21.1. VSCode version is 1.56.2.

Shift + Esc seems to be a reliable workaround for me, which I can deal with for now.

**Comment by J-Fields** [comment] 2021-06-11 18:10
Sorry about the regression! This will be fixed in `1.21.2`, which will be released today.

**Closed** 2021-06-11 18:09 UTC
Labels: kind/bug
