### ISSUE TITLE
getLineLength() s volána s out-of-bounds řádek 517

### ISSUE THREAD

**Issue by sollo-users** [VSCodeVim/Vim#5414] opened 2020-10-14 12:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 517
    at Function.getLineLength (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.isLineEnd (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:14231)
    at l.getRightThroughLineBreaks (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11052)
    at Object.t.statusBarCommandText (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:31336)
    at Object.updateShowCmd (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:40543)
    at F.handleKeyEvent (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:472169)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-15 18:36
Duplicate of #5180, if you can reproduce please post steps there.

**Closed by J-Fields** 2020-10-15 18:36 UTC
