### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by elitetouch** [VSCodeVim/Vim#6580] opened 2021-05-01 15:58 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53072)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50744)
    at Object.executeTransformations (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/src/transformations/execute.ts:124:29)
    at j.runAction (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:652:43)
    at j.async [as handleKeyEvent] (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:471:11)
    at Object.promise (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/extensionBase.ts:628:27)
    at Object.runTasks (/Users/emmanuelokonmah/.vscode/extensions/vscodevim.vim-1.20.1/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:49
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:49 UTC
Labels: status/duplicate
