### ISSUE TITLE
ModeHandler: error handling key=<C-w>, err=TypeError: Cannot read property 'selections' of undefined

### ISSUE THREAD

**Issue by kenorb** [VSCodeVim/Vim#3453] opened 2019-02-05 12:02 UTC
**Describe the bug**

The error happened when attempting to close the tab:

> ModeHandler: error handling key=<C-w>, err=TypeError: Cannot read property 'selections' of undefined

**To Reproduce**

1.  I had opened a few `README.md` files.
2.  I intuitively wanted to close some of the files by hitting Control-W, before I realized the shortcut is Control-F4
3.  I could see a few errors, one per file, but it's not always the case. I think I was in the command mode.

**Expected behavior**

I'm not sure. Maybe it's by design? If that's the case, please close it.

**Screenshots**

![image](https://user-images.githubusercontent.com/266306/52272036-522dfc00-293d-11e9-9a80-15aade1aca12.png)

**Environment (please complete the following information):**

Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Additional context**

Related: GH-3332

**Comment by J-Fields** [comment] 2022-03-09 02:10
Duplicate of https://github.com/VSCodeVim/Vim/issues/6139

**Closed by J-Fields** 2022-03-09 02:10 UTC
Labels: kind/bug
