### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by mzarnitsa** [VSCodeVim/Vim#6769] opened 2021-06-19 15:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at s._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52514)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:50206)
    at Object.executeTransformations (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/transformations/execute.ts:124:29)
    at I.runAction (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at I.rerunRecordedState (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/transformations/execute.ts:192:12)
    at I.actionToRecord [as runAction] (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:726:55)
    at I.handledAsAction [as handleKeyAsAnAction] (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (/Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:471:11)
    at /Users/mz/.vscode/extensions/vscodevim.vim-1.21.3/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
