### ISSUE TITLE
Intellisense does not work after fold

### ISSUE THREAD

**Issue by feilb** [VSCodeVim/Vim#1829] opened 2017-06-12 17:29 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**: 0.8.5
- **OS**: Win10x64

**What happened**:
Note: this issue does not happen with Vim disabled.

This issue occurs regardless of vim.foldfix setting.

Having any code folded in a file causes intellisense to stop working correctly after that fold. Typescript outputs the following error:
```
[Error  - 11:30:18 AM] 'completions' request failed with error.
Error: Cancelled Request 349
    at TypeScriptServiceClient.tryCancelRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:755:25)
    at token.onCancellationRequested (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:695:30)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:14715)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:53565)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56383)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56993)
    at n.Class.derive._oncancel.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57458)
    at n.Class.derive._oncancel._cancelAction (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:46586)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:42343)
    at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:44654)
```

**What did you expect to happen**:
Intellisense correctly exposes relevant properties, etc.

**How to reproduce it**:
Create a file (test.js for example):
```
var obj = { prop1: 0, prop2: 1 };

// <- After folding foldMe, intelisense still works here (i.e. start typing "obj.")

function foldMe() {
    return;
}

// <- After folding foldMe, intelisense no longer works properly here (i.e. start typing "obj.")

**Comment by Chillee** [comment] 2017-06-12 20:54
@feilb I'm gonna close this as a duplicate of #1827. Thanks!

**Closed by Chillee** 2017-06-12 20:54 UTC
