### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by adrianbg** [VSCodeVim/Vim#5723] opened 2020-11-20 23:06 UTC
**To Reproduce**

I have no idea how this happened. I'd just cut and pasted ~400 lines of Python (using visual-line mode and the `d` and `p` commands). It was extremely slow, on the order of minutes. Then, after a while, performance went back to normal so I continued editing, deleting a couple of blank lines at the top of the file (again using `d`). It was at that point that this exception appeared.

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:364)
	at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
	at new l (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at h.updateAndReturnMarks (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
	at h.finishCurrentStep (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
	at F.runAction (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/adrian/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-23 21:19
Duplicate of #5411.

**Closed by J-Fields** 2020-11-23 21:19 UTC
