### ISSUE TITLE
Cannot create a GoLang file(.go) from the explorer.

### ISSUE THREAD

**Issue by sus007** [VSCodeVim/Vim#2219] opened 2017-12-13 09:09 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
> BUG REPORT

**Environment**:

- **VSCode Version**: 1.19.0-insider
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows 10 Pro Insider Preview

**What happened**:
> While trying to create a GoLang file from the explorer with Vim Plugin enabled, typing `.go` (*file extension for Go file*) triggers 'g' navigation command of Vim disallowing me to create a `.go` file.

**Comment by jpoon** [comment] 2017-12-13 10:52
Sounds like a dupe of https://github.com/VSCodeVim/Vim/issues/2200

**Closed** 2017-12-14 22:38 UTC
Labels: kind/bug, status/duplicate
