### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Viko96** [VSCodeVim/Vim#3656] opened 2019-04-05 14:42 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 4.18.0-16-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/victor/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-04-08 05:31
Dupe of #3362 and there is also no cpuprofile attached...

**Closed by jpoon** 2019-04-08 05:31 UTC
