### ISSUE TITLE
Failed to handle key= . Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by rozin200** [VSCodeVim/Vim#6510] opened 2021-04-20 12:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key= . Overlapping ranges are not allowed!
    at T._applyEdit (c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:53072)
    at Object.edit (c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:50744)
    at Object.executeTransformations (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\src\transformations\execute.ts:124:29)
    at I.runAction (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:726:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:651:43)
    at I.text [as handleKeyEvent] (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:471:11)
    at Object.promise (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\extensionBase.ts:373:73)
    at Object.runTasks (c:\Users\Dell\.vscode\extensions\vscodevim.vim-1.20.0\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-21 19:44
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:44 UTC
Labels: status/duplicate
