### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kk-gfonseca** [VSCodeVim/Vim#5755] opened 2020-11-26 01:37 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
	at n.exec (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.exec (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:413539)
	at async y.execCount (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37457)
	at async F.runAction (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
	at async F.handleKeyAsAnAction (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\giova\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-28 18:15
Duplicate of #5934, which includes repro steps

**Closed by J-Fields** 2020-12-28 18:15 UTC
