### ISSUE TITLE
Split pane, same buffer, unexpected cursor behavior.

### ISSUE THREAD

**Issue by asilvadesigns** [VSCodeVim/Vim#3053] opened 2018-09-14 15:15 UTC
**Describe the bug**
When splitting the pane(editor group) such that you are now viewing the same file in two editor groups, the cursor behaves inconsistent considering the same scenario in Vim.

**To Reproduce**
NOTE: use vim keys to move the cursor, `h`,`j`,`k`,`l`.
- Open a file in vscode, split the editor group vertically. Let's call the left pane `L`, right pane `R`.
- The same file should now be open in two different editor groups, namely `L` and `R`.
- Focus on `L`, move the cursor somewhere, can be anywhere, just not the same as `R`.
- Focus on `R`, move the cursor.
Notice: The cursor should have jumped to the previous location in the previous pane.

**Expected behavior**
Cursors should not jump to previous location, but each editor group's cursor should move independently of each other.

**Environment (please complete the following information):**

Extension (VsCodeVim) version: 0.16.4
VS Code version: Code 1.27.1 (5944e81, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

**Comment by jpoon** [comment] 2018-09-15 01:45
Duplicate of https://github.com/VSCodeVim/Vim/issues/2688

**Closed by jpoon** 2018-09-15 01:45 UTC
Labels: status/duplicate
