### ISSUE TITLE
Backspace closes autocompletion popup

### ISSUE THREAD

**Issue by AndreiEres** [VSCodeVim/Vim#6303] opened 2021-03-19 10:16 UTC
**Describe the bug**
When I type something with autocompletion and then press backspace popup is disappeared.

**To Reproduce**
1.  Go to settings.json
2.  Start typing new setting until autocompletion fired.
3.  Press backspace.

**Expected behavior**
Backspace must not affect to autocompletion.

**Screenshots**
![Screen Recording 2021-03-19 at 13 09 04](https://user-images.githubusercontent.com/27277055/111765499-76e35480-88b5-11eb-8ebb-180a49499fc2.gif)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.18.9
- VSCode version: 1.54.3
- OS: macOS Big Sur

**Comment by J-Fields** [comment] 2021-03-22 00:17
Duplicate of #3613

**Closed by J-Fields** 2021-03-22 00:17 UTC
