### ISSUE TITLE
Failed to handle key=j. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by VirgilMa** [VSCodeVim/Vim#6102] opened 2021-02-05 15:49 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.8

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:680237)
	at h.setLastHistoryEndPosition (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:687859)
	at F.runAction (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:711079)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.handleKeyAsAnAction (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:707147)
	at async F.handleKeyEvent (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:703983)
	at async Object.promise (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:350696)
	at async Object.runTasks (c:\Users\Asus\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:754478)
```

</details>

**Comment by VirgilMa** [comment] 2021-02-05 15:50
Reopen vscode to fix it.

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
