### ISSUE TITLE
FEATURE REQUEST:Second navigation: A setting option for remapping 'hjkl'(←↓↑→) to 'jkil'(←↓↑→)

### ISSUE THREAD

**Issue by yunlongYoung** [VSCodeVim/Vim#4551] opened 2020-02-10 06:13 UTC
**The problem**
I have used vim for 3 years, but until now aways get wrong to use 'j' & 'k', I often will stop for a while to think about whick key is up/down, is that 'j' or 'k'? sometimes I will press 'j' & 'k'to try it out.

I thought that because from begining, the designer of vi take 'i'  as 'input' for it's easy to remember. So designer use 'hjkl' to handle (←↓↑→) . But it's not conforming our intuition very much.

**The solution**
Add a option for use 'jkil' to  substitute 'hjkl', for its shape like direction keys on keyboard(←↓↑→). 
```
   i              ↑
j  k  l        ←  ↓  →
```
And complete swap function of 'h' and 'i'('H' and 'I', 'i(', 'ib', 'iw' etc.).  

**Alternatives**
Allow us to config 'MoveInsideCharacterModeKeyBinding' in setting.json. 

**Additional context**
Fisrt I just use keymapping in setting.json, just like:
"vim.normalModeKeyBindingsNonRecursive": [
    { "before": [ "h" ], "after": [ "i", ] },
    { "before": [ "H" ], "after": [ "I", ] },
    { "before": [ "j" ], "after": [ "h", ] },
    { "before": [ "J" ], "after": [ "H", ] },
    { "before": [ "k" ], "after": [ "j", ] },
    { "before": [ "K" ], "after": [ "J", ] },
    { "before": [ "i" ], "after": [ "k", ] },
    { "before": [ "I" ], "after": [ "K", ] },
]
But I soon found that when I use 'c2l' or 'cib', I can not config that in setting.json. So It comes to a chaos.
The reason for use 'jkil' and not to use 'hjuk' to handle (←↓↑→) is that we often put our fingers on 'jkl' but not no 'hjk' when we doing nothing.
![image](https://user-images.githubusercontent.com/10031057/74126898-1266b800-4c14-11ea-8138-e96d09b82a4b.png)

**Comment by sqlkoala** [comment] 2020-02-11 21:40
Hi, the feature we need for this, is operator mode maps. See #3086

**Comment by J-Fields** [comment] 2020-02-16 22:19
Yeah, @sqlkoala's absolutely right - closing as a duplicate of #3086

**Closed by J-Fields** 2020-02-16 22:19 UTC
