### ISSUE TITLE
Search in Explorer gets stuck - j/k navigation doesn't work

### ISSUE THREAD

**Issue by Praful** [VSCodeVim/Vim#3527] opened 2019-02-26 22:17 UTC
**Describe the bug**
Normally when I'm in the Explorer pane, I can use the j and k keys to move down and up. To search for  a file, I can press forward slash (/) then type what I'm looking for. Sometimes, Explorer gets stuck in search mode. Then the j and k keys, when pressed, are part of the search string instead of navigating down and up. There is no way to get out of this mode except restarting VSCode (command: Reload Window).

**To Reproduce**
I can't reproduce this on demand but it happens fairly frequently.

**Expected behavior**
By default j and k should allow you to navigate down and up in the Explorer pane. Search is enabled by the forward slash and should be disabled either by pressing Enter or Escape. It may be prudent to disable/reset search mode when focus moves to or away from the Explorer pane.

**Screenshots**

**Environment (please complete the following information):**

- Extension Version: `1.1.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

**Additional context**

**Comment by jpoon** [comment] 2019-03-07 04:38
Dupe of https://github.com/VSCodeVim/Vim/issues/3560

**Closed by jpoon** 2019-03-07 04:38 UTC
Labels: status/duplicate
