### ISSUE TITLE
NeoVim update causes vim commands to no longer work on VSCode. 

### ISSUE THREAD

**Issue by elmlish** [VSCodeVim/Vim#1751] opened 2017-05-25 23:36 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: v0.8.0
- **OS**: Windows 10

**What happened**: Updated Vim in VSCode. Got a warning that I had to enable NeoVim by changing the settings. I added "vim.enableNeovim": true, to the User Settings, also tried setting it in the settings.json. After I did this, no vim related actions would work. I couldn't navigate with the jk keys, I couldn't use and : commands, I couldn't search, and I couldn't edit any files. 
I uninstalled vim from VSCode and reinstalled and the same situation arose. 

**What did you expect to happen**: Vim would work and be fabulous.

**How to reproduce it**: install Vim, Vim fails and files are uneditable. Though, I'm guessing it's more complicated than that.

**Comment by Chillee** [comment] 2017-05-25 23:38
Hmm, maybe I should have made it more clear. Enabling neovim is an optional setting, and you also need to have neovim installed in order for it to work. If you disable the setting again, it should work fine.

**Comment by Chillee** [comment] 2017-05-25 23:46
Also, https://github.com/VSCodeVim/Vim/issues/1735#issuecomment-304140909

**Comment by iliekturtles** [comment] 2017-05-26 00:14
Possibly related: `Ctrl-v`, select range, `c` is causing VsCodeVim to stop working since the latest update. Cursor changes to input mode but no VsCodeVim keyboard commands are effective until VSCode is restarted.

**Comment by Chillee** [comment] 2017-05-26 00:18
@iliekturtles You mean you enter visual block mode, select some stuff, and then press c?

**Comment by iliekturtles** [comment] 2017-05-26 00:19
@Chillee Correct. Regular visual mode works fine.

**Comment by awsp** [comment] 2017-05-26 00:20
OS: Elementary OS (Ubuntu 16.04)
VSCode Version: 1.12.2

Looks like it does not work at all on HTML files entirely even I disable the plugin. 
All keys are halted.
One more thing is when using j j or any keybinding will trigger the modified flag so VSCode thinks the file is modified even no changes was made. 

Anyway to downgrade it? Needed to get my work done by today ...No VIM = No Coding :D

**Comment by Chillee** [comment] 2017-05-26 00:21
@awsp It doesn't work even if VSCodeVim is disabled?

**Comment by awsp** [comment] 2017-05-26 00:21
@Chillee sorry typo, I meant NeoVim
"vim.enableNeovim": false

**Comment by Chillee** [comment] 2017-05-26 00:22
@awsp Have you restarted VSCode after toggling it off?

**Comment by awsp** [comment] 2017-05-26 00:22
@Chillee Yes, many times.

**Comment by awsp** [comment] 2017-05-26 00:23
@Chillee  
FYI: VSCode debugger shows no error message at all.

**Comment by Chillee** [comment] 2017-05-26 00:23
And it only doesn't work on HTML files?

**Comment by awsp** [comment] 2017-05-26 00:25
HTML: not work at all
JSON: intermittently
JS: intermittently

haven't tried other file types yet. 

I believe once it fails, keys on all files stop working.

**Comment by Chillee** [comment] 2017-05-26 00:26
@awsp We might decide to rollback this release, but for now, you can follow the instructions here: https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline

There's a `.vsix` download here: https://github.com/VSCodeVim/Vim/releases/tag/v0.6.20

**Comment by Chillee** [comment] 2017-05-26 00:43
@iliekturtles I can't seem to reproduce the issue. Could you post your settings?

**Comment by awsp** [comment] 2017-05-26 00:45
@Chillee 
I tried to install 0.6.20, other files are working except HTML files, strange...

Switched to Windows VSCode, using 0.7.1, working perfectly. 
Elementary OS was using 0.7.1 as well.

**Comment by Chillee** [comment] 2017-05-26 00:47
@awsp That's bizarre... Any other updates recently?

**Comment by awsp** [comment] 2017-05-26 00:54
@Chillee 
It turns out the extension I just installed, HTML Class Suggestions, conflicts with this extension. So now it works under 0.8.0.

But the problem for modified flag still exists for escape remapping.
Sorry about that man. 

Best

**Comment by Chillee** [comment] 2017-05-26 00:56
Thanks! I suspect the issues with the modified flag have always been present. Could you open up an issue for that when you have some time?

**Comment by iliekturtles** [comment] 2017-05-26 00:56
@Chillee I isolated the issue down to the following settings. Full settings at https://github.com/iliekturtles/dotfiles/blob/master/settings.json.

```json
    "vim.useSystemClipboard": true,
    "vim.otherModesKeyBindingsNonRecursive": [
        { "before": ["c"], "after": ["\"", "\"", "c"] },
    ],
```
`

**Comment by Chillee** [comment] 2017-05-26 00:59
@iliekturtles Thanks! Got it to repro.

**Comment by awsp** [comment] 2017-05-26 01:00
@Chillee 
Sure. Will do :D

**Comment by Chillee** [comment] 2017-05-26 05:31
@iliekturtles Tracking your issue here: https://github.com/VSCodeVim/Vim/issues/1758

**Comment by elmlish** [comment] 2017-05-26 18:03
Thank you @Chillee 
I didn't understand that neovim was something I had to install separately. Once I did that, everything was snazzy.

**Comment by Chillee** [comment] 2017-05-26 18:09
@elmlish Yep we could have done a better job documenting the new setting :) Glad to hear it's worked out for you now.

**Comment by Chillee** [comment] 2017-05-27 19:03
I'm going to close this issue, as the main issue that opened up this thread has been resolved.

**Closed by Chillee** 2017-05-27 19:03 UTC

**Comment by dimitrovskif** [comment] 2017-10-28 23:46
I'm having the same problem, except *I have* the `vim.neovimPath` set correctly to `/usr/bin/nvim` (which is a valid nvim executable with the correct permissions).

The dev console doesn't contain any errors, the VSCodeVim extension is loaded properly, but I can't leave NORMAL mode (none of the keys work, neither hjkl, or i).
