### ISSUE TITLE
Sometimes pressing <tab> inserts the literal string "<tab>"

### ISSUE THREAD

**Issue by dallas** [VSCodeVim/Vim#831] opened 2016-10-04 18:35 UTC
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

In normal mode, `o` to insert a newline in a file (with auto-indent, not sure if that's relevant), type some characters, hit `<tab>` key.
### What did you expect to happen?

Either it would accept the autocomplete suggestion or it would insert a tab whitespace character (or series of spaces for soft tabs).
### What happened instead?

Got literal `<tab>` string appended after my cursor instead.

NOTE: This literal string of `<tab>` insertion does not happen if pressing `<tab>` on my newline is the first thing I do, only if I press `<tab>` after typing some characters.
### Technical details:
- VSCode Version: 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d)
- VsCodeVim Version: _[please ensure you are on the latest]_ 0.3.0
- OS: macOS Sierra 10.12.1 Beta (16B2327e)

**Comment by johnfn** [comment] 2016-10-05 01:26
I found a really good way to reproduce this. `o<tab>` inserts `<tab> reliably 100% on my computer.

**Comment by dallas** [comment] 2016-10-05 01:38
Yup, in really quick succession, same outcome for me.

**Comment by mikehans** [comment] 2016-10-05 10:11
I'm getting the literal <tab> when I Tab to select from the auto-complete menu.
VSCode 1.5.3
VSCodeVim 0.3.0

**Comment by BenJBailey** [comment] 2016-10-10 18:21
+1 . It seems to have started happening this week. Happens often because I'm used to hitting tab to complete intelisense in VS proper.

**Comment by johnfn** [comment] 2016-10-10 23:08
Pretty sure this is fixed on master. Woo woo

**Comment by BenJBailey** [comment] 2016-10-11 00:08
Thanks!!

**Comment by Zyst** [comment] 2016-12-07 03:35
I'm getting this right now! @johnfn 

Code: Version 1.7.2 (1.7.2) - OS X: Version 10.12.1 - Vim plugin: Version 0.4.9

It's intermittent

**Comment by johnfn** [comment] 2016-12-07 08:06
@Zyst If you can dig up some steps to repro, that would be awesome. Do you just do `i<tab>` on an empty line or what?

**Comment by johnfn** [comment] 2016-12-07 08:07
Actually, nm, I can reproduce it, but it's very difficult for me to do so.

**Comment by Zyst** [comment] 2016-12-07 19:06
Yeah it is also very intermittent for me, I honestly don't know what conditions are required for it to happen, but it does happen once or twice throughout the work day.

**Comment by godbout** [comment] 2018-01-17 16:31
Same here. Need to close and open file again.

**Comment by jeffkillian** [comment] 2018-01-22 18:43
This is happening for me as well, haven't figured out how to reliably reproduce it. I am using VIM mode and it goes away for a bit if I exit insert mode and enter it again.

**Comment by jpoon** [comment] 2018-01-23 00:53
https://github.com/VSCodeVim/Vim/issues/1195

**Closed** 2018-01-23 00:54 UTC
Labels: status/duplicate

**Comment by godbout** [comment] 2018-01-23 06:06
@jeffkillian actually same here 😂️ I toggle VIM mode to go back to normal. I can't use cmd+left or right neither when it goes crazy.

**Comment by Chillee** [comment] 2018-02-04 03:57
@jpoon I can actually reliably reproduce at least one example of this bug.

Hold down `<ctrl+shift+down>` to create a whole bunch of multicursors. Then, hold down `<tab>`. It seems like this might be caused by changing between contexts extremely rapidly, so it may be a fundamentally different problem than previous versions (performance related, not bug related), but it'd probably be worth it to look into any other ways of handling this.

**Comment by HustLion** [comment] 2018-12-28 09:33
Just got this inserting `<tab>` literal bug again. I was using the latest version from extension tab. But when I checked the extension page again, I found "reload" available. So after pressing "reload", the issue's gone. Just a notifier for who may encounter the same problem later.

**Comment by jpoon** [comment] 2018-12-28 09:50
See https://github.com/VSCodeVim/Vim/issues/3298

**Comment by bradziolko** [comment] 2018-12-29 08:39
I also saw this issue, but as @jpoon states, it seems to be fixed in 0.17.2.  Thanks!
