### ISSUE TITLE
getLineLength() called with out-of-bounds line 116

### ISSUE THREAD

**Issue by mTvare6** [VSCodeVim/Vim#5688] opened 2020-11-18 08:09 UTC
```
Error: getLineLength() called with out-of-bounds line 116
    at Function.getLineLength (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.getRight (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10438)
    at F.updateView (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
    at _ (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/Users/me/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:28
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 18:28 UTC
Labels: status/duplicate
