### ISSUE TITLE
Failed to handle key=y. Illegal value for `line`

### ISSUE THREAD

**Issue by Tanyayx** [VSCodeVim/Vim#5519] opened 2020-10-28 16:00 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=y. Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:545:764)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:544:734)
	at Function.getLineAt (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22450)
	at ue (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:197467)
	at he (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:198835)
	at o.execActionWithCount (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:199161)
	at F.executeMovement (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at Object.promise (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/tanyapapworth/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:23
Duplicate of #5305

**Closed by J-Fields** 2020-12-05 18:23 UTC
