### ISSUE TITLE
Emojis are treated as two characters when moving cursor

### ISSUE THREAD

**Issue by fwcd** [VSCodeVim/Vim#6894] opened 2021-07-20 15:52 UTC
**Describe the bug**

Moving the cursor over an emoji character, e.g. 👍, causes it to 'swallow' the second press, presumably because it treats the emoji as two characters. This occurs both in insert and in edit mode, not however in VSCode's default editor with the extension disabled.

**To Reproduce**

1. Type some text with emoji
2. Move the cursor over it with h/l or the arrow keys

**Expected behavior**

The cursor/extension should treat the emoji as a single character.

**Environment:**

- Extension (VsCodeVim) version: 1.12.5
- VSCode version: 1.58.2
- OS: Ubuntu 20.04

**Additional context**
I think the issue is that the extension internally deals in terms of UTF-16 (?) code units rather than code points (or ideally grapheme clusters), causing the cursor to move "incorrectly" when a character is encoded with multiple code units. The same issue probably also occurs for other characters that aren't encoded as a single code unit.

Related issue, that complicates working with emojis currently: https://github.com/VSCodeVim/Vim/issues/6046

**Comment by J-Fields** [comment] 2021-07-21 02:04
Duplicate of #6046

**Closed by J-Fields** 2021-07-21 02:04 UTC
