### ISSUE TITLE
Failed to handle key=<left>. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by Eliot00** [VSCodeVim/Vim#5680] opened 2020-11-18 02:42 UTC
**To Reproduce**
type any key and get this error after I used 'u' to cancel an opration in normal mode

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<left>. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
	at h._isDocumentTextNeeded (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:511962)
	at h.addChange (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:512155)
	at F.handleKeyAsAnAction (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:473282)
	at F.handleKeyEvent (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/elliot/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:59
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:59 UTC
Labels: status/duplicate
