### ISSUE TITLE
Failed to handle key=<Esc>. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by dminkovsky** [VSCodeVim/Vim#5505] opened 2020-10-27 21:31 UTC
**To Reproduce**
Not sure how this happened, and I wouldn't have noticed an error occurred had a notification not popped up. That notification generated this report for me. Please feel free to close since no repro...

Thanks a lot for this plugin!

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
	at new l (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at h.updateAndReturnMarks (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
	at h.finishCurrentStep (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
	at F.runAction (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/dmitry/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-06 21:10
Duplicate of #5226

**Closed by J-Fields** 2020-12-06 21:10 UTC
