### ISSUE TITLE
"d" does not respect remappings of movement keys

### ISSUE THREAD

**Issue by insidewhy** [VSCodeVim/Vim#2234] opened 2017-12-18 13:58 UTC
Colemak users remap "hjkl" to "snei", after doing this:

`dn` -> should be equivalent to `dj` on a non-remapped config.

Instead `dn` does "delete to next match" as if `n` hadn't been remapped to `j`.

I tried to remap `dn` to `dj` using the config but that also didn't work.

**Comment by ohjames** [comment] 2017-12-18 13:59
This is similar to #2233 but more broken.

**Comment by aCuteLittleBox** [comment] 2017-12-26 02:18
This is actually expected vim behaviour the last I checked; and why I want langmaps added, which do exactly what you're looking for (issue #2217 )

**Comment by ohjames** [comment] 2017-12-26 11:19
@aCuteLittleBox actually this works fine in vim, definitely not expected behaviour. Vim manual also explains it. Been working this way for the last 10 years I've been using colemak.

**Comment by ohjames** [comment] 2017-12-26 11:49
Also langmaps aren't the solution for Dvorak/colemak, we went through this for weeks on a colemak mailing list and came to the conclusion that langmaps aren't fit for this purpose. They weren't built for this purpose, using them in this way is like using a spoon to unscrew a screw. Our community maintains a set of mappings that work great in vim/neovim and mostly work in VSCodeVim without using langmaps.

**Comment by jpoon** [comment] 2017-12-26 12:58
Can you share your user remapping configs @ohjames?

**Comment by ohjames** [comment] 2018-01-08 15:56
@jpoon 

```
  "vim.insertModeKeyBindings": [
    {
      "before": ["<c-n>"],
      "after": ["<cr>"]
    }
  ],
  "vim.insertModeKeyBindingsNonRecursive": [
    {
      "before": ["<c-j>"],
      "after": ["<c-n>"]
    }
  ],
  "vim.otherModesKeyBindings": [
    {
      "before": ["<c-n>"],
      "after": ["<cr>"]
    },
    {
      "before": ["n"],
      "after": ["<down>"]
    },
    {
      "before": ["e"],
      "after": ["<up>"]
    },
    {
      "before": ["i"],
      "after": ["<right>"]
    }
  ],
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [";"],
      "after": [":"]
    },
    {
      "before": ["<c-j>"],
      "after": ["<c-n>"]
    },
    {
      "before": ["k"],
      "after": ["n"]
    },
    {
      "before": ["K"],
      "after": ["N"]
    },
    {
      "before": ["u"],
      "after": ["i"]
    },
    {
      "before": ["U"],
      "after": ["I"]
    },
    // {
    //   "before": ["l"],
    //   "after": ["u"]
    // },
    {
      "before": ["L"],
      "after": ["U"]
    },
    {
      "before": ["N"],
      "after": ["J"]
    },
    {
      "before": ["E"],
      "after": ["K"]
    },
    {
      "before": ["I"],
      "after": ["L"]
    },
    {
      "before": ["j"],
      "after": ["e"]
    },
    {
      "before": ["J"],
      "after": ["E"]
    },
    {
      "before": ["l"],
      "after": [],
      "commands": [
        {
          "command": "undo",
          "args": []
        }
      ]
    },
    {
      "before": ["<C-r>"],
      "after": [],
      "commands": [
        {
          "command": "redo",
          "args": []
        }
      ]
    }
  ],
```

**Comment by ohjames** [comment] 2018-01-16 13:41
This is taken from this repository: https://github.com/ohjames/colemak/

It's a popular set of bindings for colemak users that make vim-like applications better for our keyboard layout. A few hundred people are using it.

**Comment by davidxmoody** [comment] 2018-02-11 19:33
I'm a Dvorak user who is also experiencing the same issue. I use "htns" instead of "hjkl" and pressing "dt" does the same thing as if I had not mapped "t" to "j".

A fix for this would be very much appreciated.

**Comment by ohjames** [comment] 2018-02-13 14:15
@davidxmoody I think it we want it one of us is going to have to do it ;) Unfortunately VsCodeVim is super buggy compared to vim plugins for other IDEs :( The awesome typescript/angular support VS Code offers make it worth putting up with though. I don't suppose you also suffer the problem where all of your keybindings stop working (after opening new tabs with ctrl-P and sometimes after saving or switching tabs)?

**Comment by DrBones** [comment] 2018-05-21 19:56
Sorry to comment on such an old thread but I had to mention that I am kind of glad to see that I am not the only one. I am using jkil though :). 

I would like to get my hands dirty but this extension is way to complicated for my baisc knowledge. Also I fear that it might be in vain since VsCodeNeovim is in progress (I hope still) which would make all our problems (also the horrible laggyness) go away! I would rather help that get along more quickly...although I fear that might be even more complex but if anyone has pointers I'd be happy.

My keybindings keep working when opening new tabs with ctrl-P, I have to restart VsCode to have it resister new ones though...

**Comment by nornagon** [comment] 2019-09-17 15:17
Related: https://github.com/VSCodeVim/Vim/issues/2466, https://github.com/VSCodeVim/Vim/issues/3086, https://github.com/VSCodeVim/Vim/issues/3413

**Comment by ollyhayes** [comment] 2020-02-18 16:07
If it's useful, I created this fork where I hardcoded the extension to you colemak remappings: https://github.com/ollyhayes/Colemak-Vim. You can install it from the extension store.

I've been using it for the last year and it's been working really well. Dvorak users or Colemak users that remap differently can make a fork themselves using the same technique probably.

**Closed** 2020-08-16 18:22 UTC
Labels: area/remap, help wanted, kind/bug
