### ISSUE TITLE
Cursor jumps after building with CMake

### ISSUE THREAD

**Issue by wesleygriffin** [VSCodeVim/Vim#3462] opened 2019-02-06 16:09 UTC
**Describe the bug**
I've tried to read all the previous issues with cursor jumps and I think this is a new one, although its possibly related to https://github.com/VSCodeVim/Vim/issues/3444

With the cursor anywhere in a source file after I hit F7 to build the project, pressing any of the hjkl motion keys causes the cursor to jump to somewhere in lines 25-54.

**To Reproduce**
1. Open a source file and position the cursor somewhere
2. Press F7 to build the project
3. Press any hjkl motion key
4. The cursor jumps to lines somewhere around lines 25-54

**Expected behavior**
The cursor shouldn't jump around.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.0.7
- VSCode version: 1.1.3
- OS: CentOS 7.6.1810

Developer: Show Running Extensions also shows:
Node Debug Auto-attach
Emmet
Git
Merge Conflict

**Additional Context**
Here is a series of commands and the results I'm seeing:
1. Open a source file.
2. Click in the text editor.
3. Enter ':0'
2. Press F7 to build the project
3. Press j
4. The cursor jumps to line 27
5. Press F7
6. Press j
7. The cursor doesn't jump lines
8. Press F7
9. Press l
10. The cursor jumps to line 26 (column 1)
11. Press F7
12. Press h
13. The cursor doesn't jump lines (but does move to column 0)
14. Enter ':100'
15. Hit F7
16. Press k
17. The cursor jumps to line 25
18. Enter ':100'
19 Hit F7
20. Hit j
21. The cursor jumps to line 27

**Comment by wesleygriffin** [comment] 2019-02-06 16:12
I meant to include that I've turned on "vim.debug.loggingLevelForConsole": "debug" but do not see any output in the Log (Extension Host), perhaps I need to look somewhere else?

**Comment by jpoon** [comment] 2019-02-07 04:02
Probably a dupe of https://github.com/VSCodeVim/Vim/issues/3444

**Closed by jpoon** 2019-02-07 04:02 UTC

**Comment by wesleygriffin** [comment] 2019-02-07 14:53
Yes it was a dupe of #3444 and updating to 1.0.8 fixed my issue as well.

Thanks!
