### ISSUE TITLE
Cursor location doesn't update on VSCode search / click on line

### ISSUE THREAD

**Issue by EdenGottlieb** [VSCodeVim/Vim#5221] opened 2020-09-23 13:50 UTC
**Describe the bug**
VSCodeVim doesn't always update cursor location when user changes it using VSCode (by clicking on a line / cycling through VSCode search results).

NOTE 1: This started with v1.17.0, I tested v1.16.0 and it works fine.
NOTE 2: This happens to me about 60% of the time, a few times I tried it worked fine, still really easy to reproduce 

**To Reproduce**

1. Go to a file
2. Search something using VSCode search (⌘ + F), cycle results to a result found in a different part of the file than the current cursor line
3. Move cursor using VSCodeVim (J/K/L/M/e/any other motion really)
4. Cursor jumps back to the previous cursor location (before search)

Or:
1. Go to a file
2. Place cursor on some line 
3. Click on another line (put cursor there)
4. Move cursor using VSCodeVim (J/K/L/M/e/any other motion really)
5. Cursor jumps back to the previous cursor location (before clicking on a line)

**Expected behavior**
Cursor location representation in VSCodeVim should be updated when it's moved to a different location using VSCode tools

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.0
- VSCode version: 1.49.1
- OS: macOS Catalina 10.15.5

**Additional context**
As mentioned above, this started with 1.17.0 (1.16.0 is fine). Something appears to be wrong with this version

**Comment by nemosmithasf** [comment] 2020-09-23 14:38
Experiencing same issue.

`hjkl` movements seem to use the cursor-selected position.
But commands like `x` or `dd` will use the prior position.

**Comment by patrickeibl** [comment] 2020-09-23 20:44
Also reported in #5212

**Comment by matvey-b** [comment] 2020-09-24 10:30
Experiencing same issue to :confused:

**Comment by belkka** [comment] 2020-09-24 20:54
`hjklwebf{}` commands do not use cursor-selected position. Looks for me like noting uses cursor-selected position

![image](https://user-images.githubusercontent.com/16609579/94199273-39cb7600-fec1-11ea-9d01-2b521937fd89.png)

**Comment by JosNun** [comment] 2020-09-24 22:02
Fwiw, I'd imagine this is the same underlying issue as https://github.com/VSCodeVim/Vim/issues/5212

**Comment by berknam** [comment] 2020-09-25 10:02
Can any of you post your logs here like explained [here](https://github.com/VSCodeVim/Vim#debugging-remappings)?

**Comment by DM-Berger** [comment] 2020-09-25 14:14
I'm having this same issue. This borderline breaks the extension, making it nearly unusable.

**Comment by taylorthurlow** [comment] 2020-09-25 16:29
Also having the same issue, unfortunately I'm also in the "nearly unusable" bucket.

**Comment by berknam** [comment] 2020-09-25 22:11
I'm pretty sure this is happening because of an issue of multicursor selections that might happen when using snippets, that makes it so that all selection changes are ignored, and the only way to fix it is either close and reopen the file or reloading the window.

If someone can post their logs I might be able to confirm that. I have a fix for the issue I mentioned that I will try to push soon.

**Comment by berknam** [comment] 2020-09-27 23:55
Can anyone here test PR #5250 to see if it fixes this issue and report back?

**Comment by exapsy** [comment] 2020-09-28 21:14
It's not even only on "mouse click". It's a more serious issue, as it breaks serious features of VSCode itself like "Ctrl+Shift+O" (Search by symbol/functions/variables). Now it's almost a useless feature, and it's one I'm using a lot.

**Steps to reproduce**

1. Ctrl+Shift+O
2. Select one option (arrow keys, mouse click or your chosen way)
3. Hit any of the keys `jklh`
4. See yourself go back to the previous line

**Comment by berknam** [comment] 2020-09-28 22:05
@exapsy If you close and reopen vscode or if you run the "Reload Window" from command palette can you still reproduce that? Or does it only start happening after some use?

**Comment by exapsy** [comment] 2020-09-28 22:26
@berknam No you're right. If you reload the window it doesn't happen. But now, I'm not sure how to reproduce it consistently to test your PR. I just know that it will happen again very soon, but not sure why. Any ideas on how to reproduce it?

**Comment by berknam** [comment] 2020-09-28 23:53
It might happen when using snippets but I know for sure that if you create two or more multicursors in visual mode and then move them until they combine together it would create that situation. Like this:
```
line |1
line |2
line 3
line 4
```
Where `|` are the cursors. If you then do `viw` to select 1 and 2 and then press `j` it would get you in that situation.

**Comment by chrisjaquet** [comment] 2020-10-05 20:01
Possibly related to this: using Ctrl + Left or Right Arrow key to move cursor over words does not update the vim cursor. Using v1.17.1 (which fixes a bunch of the other issues such as mouse clicks not updating the vim cursor).

**Comment by berknam** [comment] 2020-10-06 19:04
> Possibly related to this: using Ctrl + Left or Right Arrow key to move cursor over words does not update the vim cursor. Using v1.17.1 (which fixes a bunch of the other issues such as mouse clicks not updating the vim cursor).

Yes. If you are in the state where this is happening then any change of selection/cursor that is not made directly through Vim will not be recognized. For now until #5250 is released the only way to fix it is reloading the window or restarting vscode (actually closing the affected documents t and reopening then might work as well, haven't tested it yet)

**Comment by christoffertoft** [comment] 2020-10-08 10:36
Same for me using Ctrl+Arrow keys to move around, then when I press **I**, the insert will be at the location I was when I first started moving using Ctrl keys. Attaching a gif of the issue.
![ctrl_issue](https://user-images.githubusercontent.com/70325343/95447919-ce72b100-0962-11eb-925e-705328d69ef8.gif)

**Closed** 2020-11-01 21:12 UTC

**Comment by ahmedsaoudi** [comment] 2023-11-01 09:58
I noticed that this issue is still present in my setup. 
This is not new, however, I faced this problem multiple times in the past, but today it seemed to persist even more. 

I'm using: 

Version: 1.83.1
VSCode Vim: 1.26.2
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-86-generic snap

**Comment by BOTbkcd** [comment] 2023-11-24 09:20
Having the same issue as @ahmedsaoudi.
Using Vscode window reload as a temporary fix.

**Comment by realjoenguyen** [comment] 2023-12-23 23:48
I still have this problem in the latest version of vim and vsc

**Comment by thaiph99** [comment] 2024-03-04 07:35
Now, this problem still happens to me

**Comment by zakirullin** [comment] 2024-07-09 08:32
The issue isn't fixed. I press "cmd + f", I search for a token, token get focused, I press enter, cursor got moved to this new found token, I then press any of `hjkl` and the cursor got moved in old position, where it was before focusing on the new found token.

**Comment by a20r** [comment] 2024-10-25 17:10
> The issue isn't fixed. I press "cmd + f", I search for a token, token get focused, I press enter, cursor got moved to this new found token, I then press any of `hjkl` and the cursor got moved in old position, where it was before focusing on the new found token.

I'm experiencing the exact same issue
