### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by stoneyv** [VSCodeVim/Vim#3719] opened 2019-05-02 21:26 UTC
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3140006/vscodevim.vim-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.7.0`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/stoney/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-05-04 05:10
Dupe of https://github.com/VSCodeVim/Vim/issues/3362. Let's use that to track.

**Closed by jpoon** 2019-05-04 05:10 UTC
