### ISSUE TITLE
Failed to handle key=<left>. Illegal value for `line`

### ISSUE THREAD

**Issue by hanminTW** [VSCodeVim/Vim#5514] opened 2020-10-28 06:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<left>. Illegal value for `line`
	at d._lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:545:764)
	at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:544:734)
	at Function.getLineAt (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22450)
	at new t.ReplaceState (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:179660)
	at Ut.execAction (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:221431)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Ut.createMovementResult (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158241)
	at async Ut.execActionWithCount (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157898)
	at async F.executeMovement (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479435)
	at async F.runAction (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475336)
	at async F.handleKeyAsAnAction (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/twinny/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:23
Duplicate of #5305

**Closed by J-Fields** 2020-12-05 18:23 UTC
