### ISSUE TITLE
The red circle still here after undo change

### ISSUE THREAD

**Issue by RoXuS** [VSCodeVim/Vim#1464] opened 2017-04-04 07:58 UTC
Hello !

### What did you do?

I would like to know if it is the "normal" behavior. When I make a change to a file I have the circle red icon which appears in place of the "clear" icon. This icon is here to indicate that the file is edited.
Then I click on "u" to undo my change.

### What did you expect to happen?
I was expecting that the circle disapears like in vim no?

### What happened instead?
The circle is still here.

### Technical details:

* VSCode Version: latest
* VsCodeVim Version: latest
* OS: MacOS

**Comment by jpoon** [comment] 2017-04-22 07:46
Yes, that is "expected" behaviour in the sense that we understand the issue and that there needs to be further work to remove the modified flag. This is a duplicate of https://github.com/VSCodeVim/Vim/issues/565 and I'll close this issue in favor of that one.

**Closed by jpoon** 2017-04-22 07:46 UTC
Labels: status/duplicate
