### ISSUE TITLE
Failed to handle key={. Illegal value for `line`

### ISSUE THREAD

**Issue by msulton55** [VSCodeVim/Vim#5898] opened 2020-12-17 08:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key={. Illegal value for `line`
    at d._lineAt (/snap/code/51/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
    at Object.lineAt (/snap/code/51/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
    at Function.getLine (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:13043)
    at o (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:76680)
    at Object.t.getCurrentParagraphBeginning (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:76969)
    at Xe.execAction (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:218871)
    at Xe.createMovementResult (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:153262)
    at Xe.execActionWithCount (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:152919)
    at F.executeMovement (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
    at F.runAction (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171527)
    at F.handleKeyAsAnAction (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
    at F.handleKeyEvent (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/home/msultont/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:06
Duplicate of #6159

**Closed by J-Fields** 2021-03-24 18:06 UTC
