### ISSUE TITLE
is the .vimrc feature really working?

### ISSUE THREAD

**Issue by sbcmaxwell** [VSCodeVim/Vim#8663] opened 2023-10-12 14:52 UTC
I see there are vimrc enable item in the extension setting of vim. but after i select enable and choose the .vimrc path, and then add "set hlsearch" into it, nothing happenned. i still need to type ":set hlsearch" to let the hlsearch be setted.
Have this feature developped?

**Comment by TryerGit** [comment] 2023-10-13 16:20
I seem to recall that you need to actually enable neovim for this via the following settings in your `settings.json`

```
    "vim.enableNeovim": true,
    "vim.vimrc.enable": true,
    "vim.neovimPath": "/usr/bin/nvim",
    "vim.vimrc.path": "/home/path_to/.vimrc",
```
This seems to be working for me. I am unable to link to the current webpage which indicates that nvim is needed for proper sourcing of .vimrc. If you are on Windows/WSL, this issue may be relevant: https://github.com/VSCodeVim/Vim/issues/6939

**Comment by sbcmaxwell** [comment] 2023-10-14 13:03
thank you for your recommend.I'm not familar with github now,maybe i propose this issue in a wrong place. I'm actually using the vim extension for vs code "vscodevim" rather than in wsl, although i do use wsl for other things. Or this solution is for vscodevim?

**Comment by TryerGit** [comment] 2023-10-14 15:24
You can use VSCodeVim, in Windows, WSL or in a pure Ubuntu machine. The WSL and Windows do share some common settings files (keybindings.json and <filetype>.json snippets file).

So, your question is indeed in the right place.

**Comment by J-Fields** [comment] 2023-10-23 03:53
Duplicate of #7055

**Closed by J-Fields** 2023-10-23 03:53 UTC
