### ISSUE TITLE
Failed to handle key=j. Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by lynhan-tiki** [VSCodeVim/Vim#6334] opened 2021-03-23 04:15 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.18.9<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:546525)    at file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:544494    at Object.next (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:544599)    at file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:543511    at new Promise (<anonymous>)    at r (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:543256)    at e.$executeCommand (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:119:546396)    at e.doInvokeHandler (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:1:1153293)    at e.invokeHandler (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:1:1153026)    at e.receiveRequest (file:///Applications/Tiki MiniApp Studio.app/Contents/Resources/app.asar/lib/bundle.js:1:1152314)```</details>

**Comment by J-Fields** [comment] 2021-03-24 17:52
Duplicate of #5526

**Closed by J-Fields** 2021-03-24 17:52 UTC
