### ISSUE TITLE
Snippets Disorder in multi-cursor mode

### ISSUE THREAD

**Issue by im0qianqian** [VSCodeVim/Vim#2566] opened 2018-04-25 02:22 UTC
Issue Type: BUG REPORT

I am using the VsCodeVim default configuration.

I have a custom snippents (its role is to generate a for loop):
```
"for 0 -> n": {
	"prefix": "fori",
	"body": [
		"for (int ${1:i} = ${2:0}; ${1:i} < ${3:len}; ${1:i}++) {",
		"    $4;",
		"}",
	]
},
```

When I type `fori` and complete the code, the first time multiple cursors appear at the same time, this looks like this: (`|` represents the cursor)

```
for (int i| = 0; i| < len; i|++) {
    ;
}
```

I can change the names of these three variables at the same time by typing the characters, but if I press backspace, it will get messy and I don't know if this is a problem (disable vim plugin won't have this problem).

```
for (int  0; i < len; i++) {
    ;
}
```

- Extension (VsCodeVim) version: 0.11.5
- VSCode version: 1.22.2 x64
- OS version:  Windows 10 17134.1

**Comment by kalmanb** [comment] 2018-05-25 01:02
Seeing the same problem, here's a little more info. 
This is only an issue when:
- Using named parameters, eg ${1:name} AND
- Have multiple of that param, eg goes into multi-cursor mode

Another note, when you press delete it will delete the full name and that many characters in front of the variable too eg,
`"${1:abcd}1234567890 : ${1}"`
Will create
`abcd|1234567890 : abcd|`
Then pressing delete
`|567890 : abcd|`

**Comment by jpoon** [comment] 2018-05-25 07:35
Thanks @kalmanb. I'm going to close the bugs you listed as a dupe of https://github.com/VSCodeVim/Vim/issues/1946

**Closed by jpoon** 2018-05-25 07:35 UTC
