### ISSUE TITLE
Failed to handle key `.`: TextEditor(vs.editor.ICodeEditor:9,$model310) has been disposed

### ISSUE THREAD

**Issue by SerhiiSSS** [VSCodeVim/Vim#7287] opened 2021-11-28 15:20 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:9,$model310) has been disposed
    at n (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)
    at Za.$tryApplyEdits (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2341:16892)
    at f._doInvokeHandler (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:13095)
    at f._invokeHandler (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:12779)
    at f._receiveRequest (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:11441)
    at f._receiveOneMessage (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:10119)
    at vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:8215
    at l.fire (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at o.fire (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:16680)
    at d._receiveMessage (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:21950)
    at vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:18828
    at l.fire (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at m.acceptChunk (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:14041)
    at vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:13389
    at Socket.k (vscode-file://vscode-app/Users/serhiisapiannyk/iCloud Drive (archiwum)/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2967:47116)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by J-Fields** [comment] 2022-02-03 02:49
Duplicate of #6872

**Closed by J-Fields** 2022-02-03 02:49 UTC
