### ISSUE TITLE
Failed to handle key=D. getLineLength() called with out-of-bounds line 9

### ISSUE THREAD

**Issue by a-gemini** [VSCodeVim/Vim#5387] opened 2020-10-12 11:18 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=D. getLineLength() called with out-of-bounds line 9
    at Function.getLineLength (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.getLineEnd (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13715)
    at F.executeOperator (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480756)
    at F.runAction (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476279)
    at F.handleKeyAsAnAction (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/macbookpro/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 00:56
Duplicate of #5180

**Closed by J-Fields** 2020-10-14 00:56 UTC
