### ISSUE TITLE
Failed to handle key=<C-t>. Could NOT open editor for "omnisharp-metadata://$metadata$/Project/RoutingSample/Assembly/Microsoft/AspNetCore/Routing/Symbol/Microsoft/AspNetCore/Builder/[metadata] EndpointRoutingApplicationBuilderExtensions.cs".

### ISSUE THREAD

**Issue by mihaluo** [VSCodeVim/Vim#6856] opened 2021-07-08 09:52 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-t>. Could NOT open editor for "omnisharp-metadata://$metadata$/Project/RoutingSample/Assembly/Microsoft/AspNetCore/Routing/Symbol/Microsoft/AspNetCore/Builder/[metadata] EndpointRoutingApplicationBuilderExtensions.cs".
    at D.showTextDocument (c:\Users\yanwei\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:47446)
    at runMicrotasks (<anonymous>)
    at process.document (internal/process/task_queues.js:93:5)
    at t.JumpTracker.fileName [as performFileJump] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\jumps\jumpTracker.ts:111:14)
    at t.JumpTracker.vimState [as jumpThroughHistory] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\jumps\jumpTracker.ts:166:61)
    at t.JumpTracker.vimState (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\jumps\jumpTracker.ts:143:45)
    at tt.i [as exec] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\actions\commands\actions.ts:1646:50)
    at tt.execCount (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\actions\base.ts:198:42)
    at j.actionToRecord [as runAction] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:723:40)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at r (c:\Users\yanwei\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:501:15)
```

</details>

**Comment by J-Fields** [comment] 2021-11-05 18:06
Duplicate of #6445

**Closed by J-Fields** 2021-11-05 18:06 UTC
