### ISSUE TITLE
getLineLength() called with out-of-bounds line 76

### ISSUE THREAD

**Issue by desmith** [VSCodeVim/Vim#5231] opened 2020-09-24 03:31 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 76
    at Function.getLineLength (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:22124)
    at l.getUpWithDesiredColumn (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:11521)
    at l.getLeftThroughLineBreaks (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:10771)
    at Object.t.statusBarCommandText (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:31312)
    at Object.updateShowCmd (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:40442)
    at F.handleKeyEvent (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:472082)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:231560)
    at Object.runTasks (/Users/devaprastha/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by danawoodman** [comment] 2020-09-24 17:57
Dupe of #5180

**Closed** 2020-09-25 20:01 UTC
Labels: kind/bug, status/duplicate
