### ISSUE TITLE
Cursor Style incorrect all the time.

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#4358] opened 2019-12-10 11:31 UTC
Issue Type: <b>Bug</b>

It seems that with the latest version of either vim or vscode the Cursor styles got messed up.
It only switches between block and block-outline.

Extension version: 1.12.2
VS Code version: Code - Insiders 1.41.0-insider (bef029a9d21904c0085c4e8ef1335d9c33a28fa4, 2019-12-09T15:40:24.842Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|-psn_0_28765037|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brennongs** [comment] 2019-12-10 14:00
happening with me in v1.12.2, OSX as well.

**Comment by J-Fields** [comment] 2019-12-10 16:19
Closing as dupe of #4355

**Closed by J-Fields** 2019-12-10 16:19 UTC
