### ISSUE TITLE
Emulating `targets.vim`

### ISSUE THREAD

**Issue by wagk** [VSCodeVim/Vim#1767] opened 2017-05-27 17:20 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Hello,

Is it possible to emulate [`targets.vim`](https://github.com/wellle/targets.vim)? 

To elaborate `targets.vim` is a plugin that defines new text objects;

- Pair text objects (`[`, `]`, `(`, `)`, `{`, `}`, `<`, `>`, tags)
  - Vim already does this but the plugin makes it accept a count amongst other things
- Quote text objects (`'`, `"`, `` ` ``)
- Separator text objects (any separator-delimited list, supported separators being `, . ; : + - = ~ _ * # / | \ & $`)
- Argument text objects (function arguments, etc)

---

Anecdotally `targets.vim` matches `surround.vim` for sheer utility for my day to day tasks, being able to manipulate arguments as text objects (specifically) smooths over a lot things for me.

**Comment by Chillee** [comment] 2017-05-27 18:52
This is actually a duplicate of https://github.com/VSCodeVim/Vim/issues/601.

It's most likely that support for this will likely come through more neovim integration, imo.

**Comment by J-Fields** [comment] 2022-03-22 03:01
Duplicate of #601

**Closed by J-Fields** 2022-03-22 03:01 UTC
Labels: kind/feature, area/plugin
