### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by kornatskyi** [VSCodeVim/Vim#6315] opened 2021-03-20 17:13 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at filter (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:28)
    at a.operator (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:215:28)
    at a.isOperatorPending (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:287:12)
    at m.currentModeIncludingPseudoModes (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/state/vimState.ts:252:31)
    at I.updateView (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/mode/modeHandler.ts:1395:23)
    at _ (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/extensionBase.ts:58:22)
    at process.mh (internal/process/task_queues.js:97:5)
    at Object.promise (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/extensionBase.ts:371:13)
    at Object.runTasks (/home/laroma/.vscode/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-03-20 20:29
Duplicate of #6309

**Closed by J-Fields** 2021-03-20 20:29 UTC
