### ISSUE TITLE
Failed to handle key=<BS>. Illegal value for `line`

### ISSUE THREAD

**Issue by DavydJs** [VSCodeVim/Vim#6137] opened 2021-02-13 16:06 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Illegal value for `line`
	at v._lineAt (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:1166)
	at Object.lineAt (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:95)
	at E.exec (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:462099)
	at E.execCount (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355716)
	at F.runAction (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707796)
	at F.handleKeyAsAnAction (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707190)
	at F.handleKeyEvent (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704026)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
	at async Object.runTasks (/home/davyd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
