### ISSUE TITLE
. (dot) repeat last command mangles edit when used with completion

### ISSUE THREAD

**Issue by agilezebra** [VSCodeVim/Vim#6610] opened 2021-05-11 09:50 UTC
**Describe the bug**
If you use the . (repeat last) command after having used the completion drop down to select a value in your previous command, the resultant edit is mangled. 

**To Reproduce**

1) Start with this text in the buffer and your cursor at 1,1:
```
    response = do_thing()
    logging.info("response:%s", result)
    handle_thing(result)
```
2) `/` search for `result`
3) At the first `result`, use `cw` to start to change the word to `response` but
4) type only `res` and hit return to choose `response` from the completion menu.
5) Press escape to go back to command mode and `n` to move to the next `result`
6) Press `.` to repeat the edit. The result will be mangled as follows:
```
    response = do_thing()
    logging.info("response:%s", response)
    handle_thing(resresponse
```
**Expected behavior**
The operation should behave in the same way to Vim, if I used tab completion for my edit. 
Repeat the above in Vim and use tab completion (assuming you have tab completion enabled) to make the replacement and Vim's . command repeats the edit as one would wish.

**Environment:**

- Extension (VsCodeVim) version: v1.20.2
- VSCode version:
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T23:01:52.434Z (6 days ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.4.0
- OS: macOS 11.3.1

**Comment by airjp73** [comment] 2021-05-11 17:38
Came here to report the same thing. Here's a gif reproducing it in another way.

![dot-repeat-bug](https://user-images.githubusercontent.com/25882770/117860227-0d047d00-b25e-11eb-93ae-913eec1a4009.gif)

**Comment by albheim** [comment] 2021-05-12 09:45
I also came to report pretty much the same thing, though for me it interfered with a code plugin that automatically adds closing parens/quatations/brackets after the cursor when the opening one is typed. So if I enter insert mode, type `"hello<esc>` I now have the string `"hello"` on that row. Move down to next row and press `.` and I get this `""hello`.

**Comment by sql-koala** [comment] 2021-05-12 09:52
Does this repro when, in step 4, you use Tab or Ctrl+n to choose the completion?

**Comment by agilezebra** [comment] 2021-05-12 12:21
> Does this repro when, in step 4, you use Tab or Ctrl+n to choose the completion?

Yes, it's the same.

**Comment by agilezebra** [comment] 2021-05-12 12:28
It would seem that it is subsistuting both what you typed followed by the completion value, rather than just the completion value.

**Comment by sql-koala** [comment] 2021-05-12 12:54
Ok, I see.
This is also important for my workflow, cant repro though. But, I am running my custom build, which is master around Nov or Dec.
So you could try an earlier version like 1.19.x as temporary workaround. We will look into this ;-)

**Comment by J-Fields** [comment] 2021-05-12 14:27
Thanks for the report - I can reproduce and I'll investigate this ASAP. I did make some changes to this logic recently (in 7597e2bbe2dbe9d4697fd61954be9d255a8e9074) but I swear I tested this and it worked (actually I swear I do this all the time and it worked before just now 😄)

**Comment by sql-koala** [comment] 2021-05-12 15:58
Haha, thats freaky.
@J-Fields, I also look at that part of the code.
And also "promoted" DocumentContentChangeAction to BaseCommand, because that will fix "multicursor insert repeat".

I could not get  transformations to work there, resulted in weird text inserts.

**Closed** 2021-05-14 05:08 UTC
Labels: kind/bug
