### ISSUE TITLE
<space> key cannot be used to map unless it is the <leader>

### ISSUE THREAD

**Issue by Shane-XB-Qian** [VSCodeVim/Vim#4236] opened 2019-11-02 12:30 UTC
**Describe the bug**
looks key can not mapped to <space>

**To Reproduce**
e.g. key mapping to 'exit' :
```
        { 
            "before": ["<space>", "q"], 
            "after": [],
            "commands": [
                {
                    "command": "exit", 
                    "args": []
                }
            ] 
        },
```
// not sure the 'exit' command was, here just assume it is 'exit'.

**Expected behavior**
vsc exit.

**Screenshots**
n/a

**Environment (please complete the following information):**
vsc: 1.39.2
vim in vsc: 1.11.3
ubuntu 18.04

**Additional context**
n/a

**Comment by Shane-XB-Qian** [comment] 2019-11-02 12:31
looks it just allowed change the leader key to <space>, but not allow just using the <space> as the direct hotkey ?

**Comment by sqlkoala** [comment] 2019-11-02 17:29
Hi, there is no problem with mapping space. You can do this for example:
````      
{
            "before": ["<space>", "q"],
            "commands": ["workbench.action.closeActiveEditor"]            
        },
````
But I could not find a command to exit vscode; maybe there is no command to do that.

**Comment by Shane-XB-Qian** [comment] 2019-11-02 19:04
> Hi, there is no problem with mapping space. You can do this for example:
> 
> ```
> {
>             "before": ["<space>", "q"],
>             "commands": ["workbench.action.closeActiveEditor"]            
>         },
> ```
> 
> But I could not find a command to exit vscode; maybe there is no command to do that.

you modified the leader key to `<space>` ?
otherwise, i do not think so - that would not work ..

**Comment by J-Fields** [comment] 2019-11-02 19:32
I believe this is a duplicate of https://github.com/VSCodeVim/Vim/issues/2249

**Comment by Shane-XB-Qian** [comment] 2019-11-02 19:43
> I believe this is a duplicate of #2249

not sure if it was a duplicate of that ticket ..
in the 'real' vim, it can map a key (e.g. `<space>`) but did not say it had to be a 'leader' key first ..
but here - vim in vsc, looks it had to be, but if so, the leader key changed which i did not expect that ..

**Comment by J-Fields** [comment] 2019-11-02 19:48
You're right, I misread. We do support mapping space though - try this:

`    {
      "before": ["<space>", "n"],
      "commands": [":q"]
    },`

**Comment by Shane-XB-Qian** [comment] 2019-11-02 19:53
no, looks did not work.
looks `<space>` was a special key in vim-in-vsc, unless as that ticket said - only if it supported there were some 'leader-key' can be defined ..

**Comment by sqlkoala** [comment] 2019-11-02 20:06
Hi again,
the thing is: `<space>` has a function in normal vim: move cursor left.
This is also implemented in vscodevim and that why this mapping only works with <space> as a leader. Then, vscodevim waits for the second key.
So you can do (with space as leader):
````
{
            "before": ["<space>", "q"],
            "commands": ["workbench.action.closeActiveEditor"]            
        },
````
or
````
{
            "before": ["<space>"],
            "commands": ["workbench.action.closeActiveEditor"]            
        },
````

**Comment by Shane-XB-Qian** [comment] 2019-11-02 20:12
yes, but i do not believe someone would really use `<space>` to move cursor right in normal vim. -_-#
anyway, in the normal vim, `<space>` did not have to be a 'leader' key.
so now, the problem here vim-in-vsc, how to make it work without set `<space>` as leader key ?

**Comment by Shane-XB-Qian** [comment] 2019-11-02 20:16
your second option (just a `<space>`) - it works. but looks that's a bad mapping, single key to close a editor - looks had some risk ...

**Closed** 2020-08-16 18:22 UTC
Labels: area/remap
