### ISSUE TITLE
Problem with numeric key bindings

### ISSUE THREAD

**Issue by bradleyboy** [VSCodeVim/Vim#2000] opened 2017-09-03 15:48 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.15.1
- **VsCodeVim Version**: 0.10.0
- **OS**: macOS 10.12.6

**What happened**:

Using the following configuration:

```json
{
	"vim.otherModesKeyBindings": [
		{
			"before": ["0"],
			"after": ["^"]
		},
		{
			"before": ["4"],
			"after": ["$"]
		}
	]
}
```

Neither of these mappings seem to have any effect.

**What did you expect to happen**: 

I expected `0` to take me to the first non-whitespace character on the current line, and `4` to take me to the line end. Changing either "before" setting to a non-numeric character works as expected.

**Comment by davidhemphill** [comment] 2017-10-19 15:01
I can confirm this doesn't work and the first example is one of the handiest mappings to have. 😄

**Comment by jpoon** [comment] 2019-05-06 07:05
Dupe of https://github.com/VSCodeVim/Vim/issues/2831

**Closed by jpoon** 2019-05-06 07:05 UTC
