### ISSUE TITLE
Emoji entered with Windows Emoji Selector shown as "Unknown Glyph"

### ISSUE THREAD

**Issue by esarver** [VSCodeVim/Vim#7547] opened 2022-03-09 19:57 UTC
**Describe the bug**
When entering an emoji using the Windows symbol selection popup (accessed with <kbd>META</kbd>+<kbd>.</kbd>), the emoji is inserted but appears as the "unknown glyph" indicator (diamond shape with a `?` inside). If an emoji already exists in a document, it is displayed as expected.  If Vim mode is disabled, the emoji are correctly inserted. 

**To Reproduce**
On Windows (not tested on other platforms):
1.  Enable Vim mode
2.  Enter insert mode
3.  <kbd>META</kbd>+<kbd>.</kbd>, select any emoji to insert.
4.  Unicode was entered, but "unknown glyph" was shown.

**Expected behavior**
The emoji should be shown.

**Screenshots**
![Selecting Emoji](https://user-images.githubusercontent.com/4965633/157523167-a5585091-2fc3-4aad-b1e4-4d113b212c8b.png)
![Unknown Glyphs](https://user-images.githubusercontent.com/4965633/157523194-f1919a69-7399-4912-b3cd-5cd7cb275afa.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.22.2
- VSCode version: 1.65.1
- OS: Windows 10 Enterprise 1909

**Comment by esarver** [comment] 2022-03-09 20:09
Just tried copy and paste of an emoji and that seems to work correctly.

**Comment by marekjedrzejewski** [comment] 2022-04-30 10:40
Same happens on Linux with Gnome - `ctrl + .` `shrug` `space` `enter` and instead of 🤷️, which is visible after clicking `space` I get the question marks and cursor between them.
Copy-pasting works. And if I disable vscodevim it also works.

**Comment by pieterdd** [comment] 2022-05-22 14:14
@esarver I can confirm that copy/pasting works fine on my Windows machine. The problem seems to occur specifically with the OS' emoji keyboard.

**Comment by kartikfire** [comment] 2022-07-06 04:17
Same here...
![bug](https://user-images.githubusercontent.com/71930656/177467112-deacf38d-020a-42f2-a0e4-e25bbdf18384.gif)

**Comment by pohy** [comment] 2022-07-09 11:02
I have the same issue on Windows 10 using the Windows Emoji keyboard.  
But! The same emojis render correctly when inserted through the [Emoji Snippets extension](https://marketplace.visualstudio.com/items?itemName=devzstudio.emoji-snippets).
![Code_2022-06-28_10-59-40](https://user-images.githubusercontent.com/2036806/176138950-0a2cc958-d360-4b75-b6fd-7f3ef3fe99b6.gif)

**Comment by pieterdd** [comment] 2022-07-09 11:22
That's an interesting workaround.

Small caveat: this does not seem to work with the Plain Text file type. For those use cases, you may want to switch to the Markdown file type.

**Comment by MyriaCore** [comment] 2022-09-07 15:22
bump! I've been annoyed by the lack of emojis for a while now, didn't think it was coming from this extension though given how popular it is

**Comment by pieterdd** [comment] 2022-09-07 19:22
I noticed that this plugin has ~1300 open issues, so I think you're more likely to get the issue solved by contributing a patch than by poking the maintainers.

Alternatively - this is what I did - you can install [Neovim](https://github.com/neovim/neovim/releases) and a [VSCode plugin for Neovim](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim). Neovim can be embedded into other applications, which is exactly what this VSCode plugin does. Thanks to this feature, Neovim cam provide a real Vim experience, where VSCodeVim is only an emulator. Neovim does not seem to have trouble with emojis.

There's a bit of configuration involved. Here's what to do:

- Uninstall VSCodeVim to prevent conflicts.
- Install Neovim and VSCode Neovim.
- Go to VSCode's settings and enter `@ext:asvetliakov.vscode-neovim executable` in the search bar.
- For the setting matching your operating system, enter the full path to the Neovim executable on your system. I had to enter `C:\Program Files\Neovim\bin\nvim.exe` under 'Neovim Executable Paths: Win32'.
- _(Optional)_ You may want to configure VSCode Neovim to use different a settings file than your regular Neovim. If so, 'Neovim Init Vim Paths' is the setting you're looking for. Again, check that you have the right setting for your OS.
- Restart VSCode.

So far this seems to be working smoothly for me. Since it is native (but embedded) Vim, I also expect that will fix an occasional bug with the undo function that I experienced.

**Comment by Ya2gLu** [comment] 2022-09-21 04:22
The author said you don’t free-rider, contribute to the code🤣

**Comment by J-Fields** [comment] 2022-09-25 22:10
Duplicate of #6046; should be fixed by #7977

**Closed by J-Fields** 2022-09-25 22:10 UTC
