### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by zhengjiangjiang0724** [VSCodeVim/Vim#6380] opened 2021-03-30 07:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at t.ExtHostTextEditor._applyEdit (d:\Users\80244185\Downloads\VSCode-win32-x64-1.52.0\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:666)
    at t.ExtHostTextEditor.edit (d:\Users\80244185\Downloads\VSCode-win32-x64-1.52.0\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:201)
    at Object.executeTransformations (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\src\transformations\execute.ts:122:29)
    at I.runAction (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:94:5)
    at I.handledAsAction [as handleKeyAsAnAction] (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:469:11)
    at Object.promise (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\extensionBase.ts:632:27)
    at Object.runTasks (d:\Users\80244185\.vscode\extensions\vscodevim.vim-1.19.3\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-07 19:40
Duplicate of #5224. Please let me know if you can reproduce.

**Closed by J-Fields** 2021-04-07 19:40 UTC
