### ISSUE TITLE
Ctrl-T doesn't get back to the original location

### ISSUE THREAD

**Issue by aegiryy** [VSCodeVim/Vim#4482] opened 2020-01-09 05:51 UTC
Issue Type: <b>Bug</b>

When navigating C/C++ code, I often use Ctrl+] to find the definition of a function, and then use Ctrl+t to go back to the original code location.  This works perfectly in VIM, however, Ctrl+t in VS code (with VIM key binding) doesn't always get me back to the original spot.  Sometimes, it can even take me to where I have never been before.

Extension version: 1.12.4
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by J-Fields** [comment] 2020-01-09 06:19
Duplicate of #4479

**Closed** 2020-01-09 06:20 UTC
Labels: kind/bug
