### ISSUE TITLE
Failed to handle key=u. TextEditor(vs.editor.ICodeEditor:1,$model5) has been disposed

### ISSUE THREAD

**Issue by zg9uagfv** [VSCodeVim/Vim#5679] opened 2020-11-18 01:52 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model5) has been disposed
    at Object.t.disposed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:50:343)
    at e.$tryApplyEdits (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6483:655)
    at p._doInvokeHandler (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4475:707)
    at p._invokeHandler (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4475:399)
    at p._receiveRequest (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4474:59)
    at p._receiveOneMessage (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4472:886)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4471:34
    at c.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:476:523)
    at t.PersistentProtocol._receiveMessage (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:481:629)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:478:635
    at c.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at g.acceptChunk (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:473:978)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:473:330
    at Socket.t (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:483:276)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

</details>

**Comment by J-Fields** [comment] 2021-02-19 01:49
Duplicate of #5650

**Closed by J-Fields** 2021-02-19 01:49 UTC
