### ISSUE TITLE
getLineLength() called with out-of-bounds line 604

### ISSUE THREAD

**Issue by victormongi** [VSCodeVim/Vim#5297] opened 2020-09-30 01:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 604
	at Function.getLineLength (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:22186)
	at l.getLineEnd (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:13738)
	at F.handleSelectionChange (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:468904)
	at Object.promise (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235462)
	at Object.runTasks (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621835)
	at Object.enqueueTask (/home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:622868)
	at /home/vm/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235444
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:48
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:48 UTC
