### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by silviubogan** [VSCodeVim/Vim#6461] opened 2021-04-11 10:28 UTC
**To Reproduce**

Unknown. See error.

**VSCodeVim version**: 1.19.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at T._applyEdit (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:51884)
    at Object.edit (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49576)
    at Object.executeTransformations (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/src/transformations/execute.ts:122:29)
    at I.runAction (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:722:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/extensionBase.ts:632:27)
    at Object.runTasks (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.19.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
