### ISSUE TITLE
Failed to handle key=<Esc>. Promise.allSettled is not a function

### ISSUE THREAD

**Issue by jonathan-hopkinson** [VSCodeVim/Vim#6864] opened 2021-07-12 07:03 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Promise.allSettled is not a function
    at c:\Users\jonathan.hopkinson\.vscode\extensions\vscodevim.vim-1.21.3\extensionBase.ts:495:53
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 04:00
Duplicate of #6489

**Closed by J-Fields** 2022-03-09 04:00 UTC
