### ISSUE TITLE
[QUESTION] Copy `co` command

### ISSUE THREAD

**Issue by nrudnyk** [VSCodeVim/Vim#4390] opened 2019-12-16 12:11 UTC
Is it possible to copy selected range of lines and paste at cursor or selected line?
I thought it should be something like below for copying lines 10 to 15 and paste at cursor:

`:10,15co.`
`:10,15 co .`

Am I missing something?

**Comment by J-Fields** [comment] 2019-12-16 15:51
Try enabling neovim integration. I haven't tested, but it should work then.

**Comment by J-Fields** [comment] 2019-12-16 19:31
If someone decides to implement this without neovim, `:t` should do the same thing as `:co[py]`

**Comment by subhakarks** [comment] 2019-12-18 23:57
Hi @J-Fields `:t` works. Is there pointer to documentation on such commands?. TIA.

**Comment by J-Fields** [comment] 2019-12-19 01:25
@subhakarks `:t` only works with neovim integration. You can always take a look at [the source](https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/subparser.ts#L33) to see what commands are natively supported.

**Comment by J-Fields** [comment] 2021-04-14 21:15
Duplicate of #2472

**Closed by J-Fields** 2021-04-14 21:15 UTC
Labels: kind/question, status/duplicate
