### ISSUE TITLE
Pressing tab in insert-mode inserts the string `<tab>`

### ISSUE THREAD

**Issue by haf** [VSCodeVim/Vim#730] opened 2016-09-07 07:58 UTC
### What did you do?

Put the exact keys you pressed. `i[TAB]`
### What did you expect to happen?

I expected the two spaces I have configured to be inserted.
### What happened instead?

The string `<tab>` was inserted.
### Technical details:

Running ionide-fsharp, latest version
- VSCode Version: 1.4.0
- VsCodeVim Version: latest, updated today
- OS: OS X 10.11.6

<img width="150" alt="screen shot 2016-09-07 at 09 57 19" src="https://cloud.githubusercontent.com/assets/193115/18304255/a151b8d4-74e1-11e6-8c60-a2cac4974037.png">

<img width="326" alt="screen shot 2016-09-07 at 09 24 14" src="https://cloud.githubusercontent.com/assets/193115/18304266/ae808012-74e1-11e6-8602-af7da5d18f95.png">

**Comment by jpoon** [comment] 2016-09-07 09:50
I unfortunately can't repro this on v0.1.10 (latest). Does this happen on a new file? Can you share your user/workspace settings?

**Comment by haf** [comment] 2016-09-07 12:25
It happens once in a while when code is struggling to keep up with my typing and F# intellisense is also struggling to keep up and compile everything. Most of the time it works fine.

My settings:

```
// Place your settings in this file to overwrite the default settings
{
  "editor.fontSize": 12,
  "editor.tabSize": 2,
  // Inserting and deleting whitespace follows tab stops
  "editor.renderWhitespace": true,
  "FSharp.linter": false,
  "editor.useTabStops": true,
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "window.zoomLevel": -1,
  "search.exclude": {
    "**/node_modules": true,
    "**/build": true,
    "**/bower_components": true
  }
}
```

**Comment by rebornix** [comment] 2016-09-07 21:28
Is it a race condition while we handing the `type` event? I'd like to keep an eye on this issue as seems it has something to do with Code internal `type`

**Comment by johnfn** [comment] 2016-09-08 17:42
I can actually reproduce this trivially just by going into insert mode and holding down tab.

**Comment by rebornix** [comment] 2016-09-08 17:45
@johnfn any repro steps with env/config as I can't make it happen on my machine.

**Comment by johnfn** [comment] 2016-09-08 17:49
@rebornix osx 10.10.5, vsc insiders on latest, plugins: tslint, relative path, debugger for chrome, vim (though i doubt any of those other than vim are relevant).

I can troubleshoot this one when I have the time.

**Comment by johnfn** [comment] 2016-09-08 17:49
settings.json:

```
// Place your settings in this file to overwrite default and user settings.
{
	"files.exclude": {
		"out": false // set this to true to hide the "out" folder with the compiled JS files
	},
	"search.exclude": {
		"out": true // set this to false to include "out" folder in search results
	},
	"vim.insertModeKeyBindings": [
			{
					"before": ["j", "j"],
					"after": ["<esc>"]
			}
	],

	"vim.hlsearch": false,

	"typescript.tsdk": "./node_modules/typescript/lib", // we want to use the TS server from our node_modules folder to control its version
	"editor.tabSize": 2,
	"editor.insertSpaces": true,
	"vim.useCtrlKeys": true,
	"files.trimTrailingWhitespace": true
}```

**Comment by octref** [comment] 2016-09-09 17:29
I also can't repro this on my machine.
Maybe the culprit is https://github.com/ionide/ionide-vscode-fsharp?

**Comment by haf** [comment] 2016-09-12 17:14
It happens in other files than F# ones.

**Comment by jpoon** [comment] 2016-09-12 18:37
@haf does it happen consistently on your machine? Still looking for a consistent repro.

**Comment by haf** [comment] 2016-09-13 19:35
@jpoon No, it's not consistent.

**Comment by octref** [comment] 2016-09-14 19:05
Today this bug also happened to me while I was working on VSCode.

Specifically, I noticed I have a watch compile, and this happened when I entered insert mode before re-compilation is done.

I can't repro is consistently, though.

**Comment by rebornix** [comment] 2016-09-14 19:50
Not sure but maybe it's related to https://github.com/VSCodeVim/Vim/issues/771

**Comment by rebornix** [comment] 2016-09-19 22:02
Since we significantly changed the behavior of special keys, I'd like to close this issue first as I don't see this in current master bits. Anyone can reopen it if running into it again with our next version.

**Comment by johnfn** [comment] 2016-10-01 22:10
Yep, can't repro this one any more. :)

**Comment by BenJBailey** [comment] 2016-10-11 12:32
Thank you!!!

**Comment by haf** [comment] 2017-05-13 17:44
This needs to be reopened, since it's still an issue.

<img width="205" alt="screen shot 2017-05-13 at 19 44 09" src="https://cloud.githubusercontent.com/assets/193115/26027785/986d047a-3814-11e7-8794-51bf74b2d939.png">

**Comment by Chillee** [comment] 2017-05-18 21:30
@haf do you have a repro? Or is it random?

**Comment by haf** [comment] 2017-05-19 07:24
It's random.

**Comment by Chillee** [comment] 2017-05-19 07:26
@haf Do you notice it happening in any particular scenario? Or does it just happen randomly in insert mode?

**Comment by haf** [comment] 2017-05-19 07:51
It only happens when I push the editor via other extensions. So eg if Ionide is compiling my f# after a change and there is a bit lag in viscose then it happens much more often

**Comment by ivan-baldin** [comment] 2018-01-09 12:29
This bug also happens in search mode. Typing `/ tab` inserts and searches for `<tab>` string instead of `\t`. Same thing with `/ ctrl+v tab` sequence.

**Comment by bestv2** [comment] 2018-01-11 01:05
It also happen to me.  
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T06:08:10.994Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
gitlens|eam|7.2.0
auto-close-tag|for|0.5.5
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
recent-files|jun|1.1.9
endwise|kai|1.2.2
code-beautifier|mic|1.7.2
color-highlight|nau|2.3.0
Ruby|reb|0.15.0
vim|vsc|0.10.8
local-history|xyz|1.6.2

(1 theme extensions excluded)

</details></li>
</ul>
---

**Comment by phitruongdn** [comment] 2018-01-11 04:49
I got same problem:  

```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
Reloading vim only help temporarily

**Comment by philipmclifton** [comment] 2018-01-13 17:27
This one is driving me crazy. 

A quick fix toggle insert mode on and off.

**Comment by philipmclifton** [comment] 2018-01-16 20:44
The steps to trigger the issue are mentioned in https://github.com/VSCodeVim/Vim/issues/1195

I always use split mode like the people in linked issue.

Maybe the fix was removed accidentally?

**Closed** 2018-01-23 06:02 UTC
Labels: area/performance, help wanted, kind/bug

**Comment by philipmclifton** [comment] 2018-10-05 18:56
Is it possible this has come back in a new version of the plugin? It has occurred a few times for me in the past week.

**Comment by philipmclifton** [comment] 2018-10-05 19:10
Have two tabs open. Open another file. Close the file. Press tab.

https://www.icloud.com/iclouddrive/0m6znnqxbbBAcItbaMd1_i-BA#tab-issue

^^ Video of issue happening.

**Comment by shawnaxsom** [comment] 2018-10-05 19:20
I was able to reproduce similar to the video @philipmclifton, thanks for the video. I'll try to take a look this weekend.

I'm not sure if it could have re-emerged. There is a chance #3090 could affect the issue, which was merged and might be released this evening. It isn't the same issue fixed, but I can see how it could be relevant if there is some sort of remapping of `<Tab>`.

**Comment by shawnaxsom** [comment] 2018-10-06 01:12
This regression can be discussed in #3096.
