### ISSUE TITLE
Backspace does not honor "editor.useTabStops" setting.

### ISSUE THREAD

**Issue by hk0i** [VSCodeVim/Vim#1691] opened 2017-05-11 18:17 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

*BUG REPORT*

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: Linux Mint

**What happened**:

Wrong number of spaces deleted when pressing <kbd>Backspace</kbd>

**What did you expect to happen**: 

When pressing backspace in insert mode I expected my `editor.tabStop` number of spaces to be deleted (in this case 4 spaces)

**How to reproduce it**:

*When using `"editor.useTabStops": "true"` and using spaces for indentation:*

1. In insert mode, press <kbd>Tab</kbd>.  
*[4] spaces are inserted*
2. Press <kbd>Backspace</kbd>.  
*1 space is deleted.*

When disabling Vim plugin, the editor behaves as expected.

**Comment by Chillee** [comment] 2017-05-12 18:59
I can't reproduce this on Arch Linux, VsCode 1.12.1, and VsCodeVim 0.7.1

**Comment by renfredxh** [comment] 2017-11-04 23:14
I'm reproducing this exact issue on MacOS 10.12.6 VSCode 1.17.2 VSCodeVim 0.10.2. 

Make sure your editor is set to indent using spaces (run `> Indent Using Spaces`). 

This makes editing files that indent using spaces a pretty bad experience since you have to press backspace so many times to simply dedent.

**Comment by tadams42** [comment] 2018-05-29 14:10
I have a problem on Ubuntu 18.04, VSCode 1.23.1, VSCode Vim 0.12.0 that I believe belong here... If not, please tell, I'll open new issue...

Anyway, un-indenting using backspace in insert mode works only on empty line. If line is not empty, backspace will move by single space. Best shown with some pictures...

disabled VSCode Vim:
![disabled_vs_vim](https://user-images.githubusercontent.com/664505/40664050-5641ac3c-635a-11e8-93fc-d588446d4227.gif)

enabled VSCode Vim, insert mode:
![enabled_vs_vim](https://user-images.githubusercontent.com/664505/40664054-5dfd3d74-635a-11e8-80c7-d61c1a8b8fb5.gif)

enabled VSCode Vim, empy line, insert mode:
![enabled_vs_vim_spaces_only](https://user-images.githubusercontent.com/664505/40664229-bff436fe-635a-11e8-9ad7-52cec6ce8909.gif)

**Comment by teddyhwang** [comment] 2018-06-09 02:08
I can confirm @tadams42 behaviour on Version 1.24.0 (1.24.0) and vim 0.12.0

**Comment by AlexGuo1998** [comment] 2018-11-15 04:04
Hello, same issue here when editing files with space. There's another little demo (for `C`):

![gif](https://user-images.githubusercontent.com/25975864/48529435-0f283380-e8ce-11e8-91ee-f7c8fc48c42e.gif)

And the only extension enabled is `vscodevim`.

System info:
```
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by a-vrma** [comment] 2019-01-05 10:11
Can confirm with vscodevim 1.0.0 on macOS 10.13. VSCode 1.30.1
The same exact problem as AlexGuo1998.

**Comment by ZhengRui** [comment] 2019-01-16 18:11
Same issue here on macOS 10.13

**Comment by creo-verus** [comment] 2019-02-18 16:51
Using the **VSCodeVim** plugin along with **Backspace++** plugin seems to bring back the intended behavior (ie. delete full tab width on backspace instead of just one space). Temporary option for anybody else wanting that behavior.

OSX: 10.14.3
VSCode: 1.31.1
vscodevim: 1.0.8
backspace++: 0.0.17 (deprecated)

**Comment by st3iny** [comment] 2020-11-09 22:33
This can be fixed by remapping backspace to `extension.vim_shift+backspace`. Pressing shift + backspace will respect tab stops.

Add the following entries to your `keybindings.json`:
```json
[
  {
    "key": "backspace",
    "command": "extension.vim_shift+backspace",
    "when": "editorTextFocus && vim.active && vim.use<shift+BS> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || editorTextFocus && vim.active && vim.use<shift+BS> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  },
  {
    "key": "shift+backspace",
    "command": "-extension.vim_shift+backspace",
    "when": "editorTextFocus && vim.active && vim.use<shift+BS> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || editorTextFocus && vim.active && vim.use<shift+BS> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  },
  {
    "key": "backspace",
    "command": "-extension.vim_backspace",
    "when": "editorTextFocus && vim.active && !inDebugRepl"
  }
]
```

**Closed** 2021-06-11 19:21 UTC
Labels: kind/bug

**Comment by sboukortt** [comment] 2021-06-13 15:51
I have what I believe is the opposite problem: if the editor is not globally set to use tabs, but a certain buffer is, then pressing backspace in that buffer appears to delete as many tabs as they are wide, e.g. it removes 4 tabs if the tab size is set to 4. This is with VSCodeVim 1.21.2.

**Comment by J-Fields** [comment] 2021-06-14 17:00
@sboukortt Thanks for pointing this out. I've filed #6735 and should have it fixed in the next release (some time this week)
