### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by NguHoaDuy** [VSCodeVim/Vim#6876] opened 2021-07-15 05:16 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at i._applyEdit (c:\Users\nud4hc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\nud4hc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\nud4hc\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\nud4hc\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\nud4hc\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\nud4hc\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\nud4hc\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[8632, 45] | [8632, 44]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "<BS>",
  "<BS>",
  "<Esc>"
]
actionsRun: [
  "D",
  "b",
  "$",
  "C",
  "C",
  "$",
  "C",
  "C",
  "$",
  "C",
  "C",
  "C",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 8632,
      "character": 47
    },
    "text": "ateTyp",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 8632,
        "character": 39
      },
      {
        "line": 8632,
        "character": 53
      }
    ],
    "text": "InstantiateTypedTestSuitePClass",
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 8632,
      "character": 47
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 8632,
      "character": 46
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 8632,
      "character": 45
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:44
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:44 UTC
