### ISSUE TITLE
Undo is lost when switch tab

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1597] opened 2017-04-28 08:41 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

change test, gt to switch to another tab, and then gT to switch back, press **u**, nothing happened

### What did you expect to happen?
undo the modify
### What happened instead?
Nothing, but **ctrl-z** work correctly
### Technical details:
None

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.20
* OS: win 10

**Comment by Chillee** [comment] 2017-04-28 14:52
This is a duplicate of

https://github.com/VSCodeVim/Vim/issues/1503

**Comment by xconverge** [comment] 2017-04-29 01:04
closing as dupe

**Closed by xconverge** 2017-04-29 01:04 UTC
