### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by elinlinliu** [VSCodeVim/Vim#5260] opened 2020-09-27 04:08 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
	at new b (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:499:364)
	at new b (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:497:187)
	at new l (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9299)
	at h.updateAndReturnMarks (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:510467)
	at h.finishCurrentStep (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:513988)
	at F.runAction (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:477890)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\user\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-29 05:31
Duplicate of #5277

**Closed by J-Fields** 2020-09-29 05:31 UTC
