### ISSUE TITLE
Failed to handle key=<Esc>. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by DevGHalid** [VSCodeVim/Vim#5241] opened 2020-09-24 18:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
	at new l (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:9260)
	at h.updateAndReturnMarks (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:510380)
	at h.finishCurrentStep (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:513901)
	at F.runAction (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:477803)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:231560)
	at async Object.runTasks (/home/devhalid/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-25 20:27
Duplicate of #5226

**Closed by J-Fields** 2020-09-25 20:27 UTC
Labels: kind/bug, status/duplicate
