### ISSUE TITLE
Vscode vim sometimes shows tab key  <tab>

### ISSUE THREAD

**Issue by afaayerhan** [VSCodeVim/Vim#1202] opened 2016-12-30 08:10 UTC
![image](https://cloud.githubusercontent.com/assets/8157594/21561654/21cc1d66-ce78-11e6-8768-2420c6b803a9.png)

**Comment by xconverge** [comment] 2016-12-31 02:42
Dupe of #1195

**Closed** 2016-12-31 04:49 UTC
Labels: duplicate
