### ISSUE TITLE
Crash when repeating find

### ISSUE THREAD

**Issue by regisverdin** [VSCodeVim/Vim#6263] opened 2021-03-11 06:34 UTC
**To Reproduce**

1.  Open any plaintext file
2. Type `F`, then `Space`. (to jump to the previous space character).
3. Type `.` to repeat the search
4. It crashes

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
	at Object.k [as illegalArgument] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)
	at new m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:12337)
	at new m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:11705)
	at a (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
	at F.exec (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.runAction (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708017)
	at async F.rerunRecordedState (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:714422)
	at async y.execute (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:783471)
	at async F.runAction (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707854)
	at async F.handleKeyAsAnAction (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/rverd/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-16 17:36
Hmm, `F` can't be repeated with `.`. Can you reproduce this reliably?

**Comment by J-Fields** [comment] 2021-03-24 17:04
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:04 UTC
