### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by SAMUELODEKINA** [VSCodeVim/Vim#5882] opened 2020-12-13 17:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.4

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:424)
    at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
    at a (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:1:73671)
    at F.exec (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:1:73716)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at D.runAction (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:130247)
    at D.rerunRecordedState (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:136668)
    at v.execute (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:25623)
    at D.runAction (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:130084)
    at D.handleKeyAsAnAction (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:129411)
    at D.handleKeyEvent (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:126220)
    at Object.promise (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:9:228221)
    at Object.runTasks (/Users/samuelmondayodekina/.vscode/extensions/vscodevim.vim-1.18.4/out/extension.js:11:285853)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
