### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'cursorStartPosition' of undefined

### ISSUE THREAD

**Issue by davosolo** [VSCodeVim/Vim#5360] opened 2020-10-08 18:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'cursorStartPosition' of undefined
    at A.exec (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:437666)
    at A.execCount (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
    at F.runAction (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
    at F.handleKeyAsAnAction (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/David.Munoz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 22:59
Duplicate of #5628

**Closed by J-Fields** 2020-11-12 22:59 UTC
