### ISSUE TITLE
Failed to handle key `<right>`: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by rajivleon** [VSCodeVim/Vim#7502] opened 2022-02-15 17:49 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `<right>`: Cannot read property 'substring' of undefined
    at _.display (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:402:89)
    at statusBarText (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:199:35)
    at Object.clear (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:105:17)
    at j.updateView (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:1579:15)
    at j.handleKeyAsAnAction (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:673:16)
    at runMicrotasks (<anonymous>)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at j.mh [as handleKeyEvent] (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:478:11)
    at r (/home/rleon/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment] 2022-02-17 16:35
Duplicate of #7512

**Closed by J-Fields** 2022-02-17 16:35 UTC
