### ISSUE TITLE
Screen navigation doesn't work at top or bottom

### ISSUE THREAD

**Issue by arthurpaimarnold** [VSCodeVim/Vim#4207] opened 2019-10-22 17:59 UTC
**Describe the bug**
Screen navigation (ctrl+u, ctrl+d, ctrl+f, ctrl+b) doesn't work when the editor view is at the top or at the bottom of the file.

**To Reproduce**

1. Open a file.
2. Make sure to scroll all the way up. The cursor may be at any visible position.
3. Try pressing ctrl+d to move down. Nothing happens. Same goes for ctrl+u (in case the cursor is not already at the very top).

The same happens when you're at the bottom of the file. If the cursor is mid-line, any of the four shortcuts will cause it to move to the beginning of the line.

**Expected behavior**

Expected the cursor to move half a screen down (ctrl+d) or up (ctrl+u), or an entire screen down (ctrl+f) or up (ctrl+b).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.2
- VSCode version: 1.39.2
- OS: macOS Catalina 10.15 (19A602)

**Comment by J-Fields** [comment] 2019-10-22 19:35
Duplicate of #4179

**Closed by J-Fields** 2019-10-22 19:35 UTC
