### ISSUE TITLE
Cannot use space as leader key

### ISSUE THREAD

**Issue by liaohui5** [VSCodeVim/Vim#6839] opened 2021-07-06 16:50 UTC
**Describe the bug**
If you set "vim.leader" to "<space>", you cannot press the space twice in succession, that is, you cannot use easymotion

**Screenshots**

- Extension (VsCodeVim) version: `1.21.4`
- VSCode version:
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```

- OS: windows 10 (21h2)

**Comment by J-Fields** [comment] 2021-07-06 16:53
Duplicate of #6824 (will be fixed in new version out later today)

**Closed by J-Fields** 2021-07-06 16:53 UTC

**Comment by liaohui5** [comment] 2021-07-06 17:00
> Duplicate of #6824 (will be fixed in new version out later today)

Why not continue to support this feature in the new version? I think using <space> as the leader is a very common setting, for example, spaceVim does this
