### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by FXSuperLee** [VSCodeVim/Vim#5246] opened 2020-09-25 17:03 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
	at new b (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:499:364)
	at new b (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:497:187)
	at new l (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:9260)
	at h.updateAndReturnMarks (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:510380)
	at h.finishCurrentStep (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:513901)
	at F.runAction (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:477803)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474707)
	at async F.handleKeyEvent (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471516)
	at async Object.promise (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
	at async Object.runTasks (c:\Users\lichaochen\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-25 20:27
Duplicate of #5226

**Closed by J-Fields** 2020-09-25 20:27 UTC
