### ISSUE TITLE
dot repeat

### ISSUE THREAD

**Issue by BubbaBoBobBrain** [VSCodeVim/Vim#3953] opened 2019-08-06 03:02 UTC
**Describe the bug**

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by BubbaBoBobBrain** [comment] 2019-08-06 03:12
Dot/period (.) key repeat function doesn't work after inerting tabs.  Expected behavior: After inserting a number of tabs at beginning of existing lines, escaping out of insert, and moving to another line and hitting dot key the same number of tabs previously entered should be inserted.  What happens: nothing.  Note: noticed inserting a number of spaces is repeated when hitting dot key.

**Comment by J-Fields** [comment] 2019-08-06 03:20
Closing as duplicate of #2337

**Closed by J-Fields** 2019-08-06 03:20 UTC
