### ISSUE TITLE
Failed to handle key=P. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by HIEM-BOOP** [VSCodeVim/Vim#5493] opened 2020-10-27 01:59 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=P. Cannot read property 'split' of undefined
    at n.exec (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:409709)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at y.exec (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:413539)
    at y.execCount (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37395)
    at F.runAction (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
    at F.handleKeyAsAnAction (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\Asus\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by dstj** [comment] 2020-11-12 15:13
I often have the same issue, it happens when I try to paste using the multi-cursor to replace multiple words with the same copied value (doing `viwp` from a multi-cursor selection)

**Comment by J-Fields** [comment] 2020-11-12 18:01
@dstj Can you provide a minimal example that will trigger this?

**Comment by dstj** [comment] 2020-11-12 18:21
@J-Fields Here's a screen recording of the bug happening (unzip the file). It's from a no-workspace, no-project, clean startup VSCode.

[multi-cursor-viwp.zip](https://github.com/VSCodeVim/Vim/files/5532452/multi-cursor-viwp.zip)

Can't get any simpler than that ;)

The whole vim sequence is:
```
O
line1
line2
line3
ESC
gg
viwy
j
CTRL-ALT-Arrow down
viwp
```

**Comment by sql-koala** [comment] 2020-11-13 10:24
@dstj Thanks for the description and repro. This is the same issue as #5208. 

I have provided a workaround there:
https://github.com/VSCodeVim/Vim/issues/5208#issuecomment-700243223

**Comment by J-Fields** [comment] 2020-11-14 22:45
I think this is a duplicate of #5239. Closing it as such - let me know if that's wrong.

**Comment by sql-koala** [comment] 2020-11-18 14:13
Hi @J-Fields this is a bit different issue, which is not solved in master yet.
The problem part is the yanking of text, that will be pasted over.

We could do a simple fix, which does the text change but not the yank part (for multi cursor). This would stop the exception.

**Comment by sql-koala** [comment] 2020-11-20 12:40
Ok, so visual paste command has to branches: one for a characterwise yank, another for linewise yank.
Both "crash" on current master. Repros charwise we already have.

Here is for linewise yank:
1. yank a line: yy
2. create multi cursor: gbgb
3. (optional) select full line with:$ or V
4. paste

This will result in:
> Failed to handle key=p. No multi-cursor index when calling PutCommand#getText

We already have issues with this error, like here:
https://github.com/VSCodeVim/Vim/issues/5448
I would guess, it is cause by the above workflow.

For both branches, the yank part of the operation is the problem.
I dont have a complete fix, but a small workaround that at least stops the exception.

**Closed** 2021-03-16 23:04 UTC
Labels: status/duplicate
