### ISSUE TITLE
Unexpected behaviour when press ')'

### ISSUE THREAD

**Issue by ChrisShen93** [VSCodeVim/Vim#4366] opened 2019-12-11 02:59 UTC
**Describe the bug**
Where I press ')', an unexpected string `vClosePair(')')\n` will show up.

**To Reproduce**

Just press ')' and you will see this bug.

**Expected behavior**

Just ')' itself.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.40.2
- OS: macOS 10.15.1

**Additional context**

**Comment by Anlarry** [comment] 2019-12-11 14:39
I find 'backspace' will be the similar case.

**Comment by J-Fields** [comment] 2019-12-11 17:37
This looks similar to https://github.com/VSCodeVim/Vim/issues/4359. @Anlarry what OS are you on? Seems these issues are popping up on unix only.

**Comment by leshow** [comment] 2019-12-11 21:08
I am having some similar behaviour on 1.12.2 on linux. VSCode 1.40.

if I type
```
function foo() {
```
then press <enter>

the result is:

```
function foo() {
}
}
```

If I downgrade to 1.11 this issue goes away

**Comment by isdampe** [comment] 2019-12-12 01:10
+1 for this. 
`vscodevim 1.12.2` on `VS Code 1.39.2` on `Ubuntu 19.10`.

**Comment by Anlarry** [comment] 2019-12-13 09:01
> This looks similar to #4359. @Anlarry what OS are you on? Seems these issues are popping up on unix only.

Yes, my OS is manjaro.
`vscodevim 1.12.2` on 'vscode 1.39.2' on 'Manjaro 18.1.4'

**Comment by CVVPK** [comment] 2019-12-29 22:21
I've finally been able to reproduce one of these bugs that have been popping up lately. I had suspected they might be coming from conflicting vimrc configs, and it appears that might be correct. In particular I was able to reproduce the bug mentioned by @leshow by using a vimrc that I found around, in this case I tracked down the issue to this remap that is supposed to do autobracketing:

```
inoremap {<cr> {<cr>}<c-o><s-o>
```
I'm unsure how this particular case could be solved, in reality everything is working as intended, it's just that VSCode does the autobracketing and then this remap inserts the extra `}`. 

I think this might be a lead, and I could investigate it further if I can get more data, i.e. get the vimrc configs of the people experiencing them.

**Comment by isdampe** [comment] 2019-12-29 23:40
Good find. I didn't even realise my .vimrc was taken into account. I can confirm I am using a similar .vimrc entry to add some auto bracketing on `cr`.

Is there currently any way we can target VS Code in vimrc? Something like

```
if has("vscode")
    " Some rules
endif
```

Could be a good way to resolve this.

**Comment by J-Fields** [comment] 2019-12-30 04:41
> Edit: in other news, you can disable the extension from reading your .vimrc remaps by setting vim.vimrc.enable to false, which should stop the dual bracket behavior if you're using key mappings in your .vimrc file.

This was supposed to be `false` by default, but I think it slipped by me in review. That's fixed as of 1.12.4.

> Is there currently any way we can target VS Code in vimrc?

Nope. I'd like a way to designate certain settings as VSCode-only and as Vim-only. I do like your idea of `has("vscode")` or similar.

**Comment by leshow** [comment] 2019-12-30 19:01
I can confirm I have this in my vimrc. I didn't realise vscodevim was
reading my vimrc, I believe this behaviour changed in recent releases, I've
had the setting in vimrc for a while.

**Comment by J-Fields** [comment] 2019-12-30 19:05
Okay, this seems resolved, so I'm closing the issue.

I'll create another issue to tackle the Vim/VSCode-only settings

**Closed by J-Fields** 2019-12-30 19:05 UTC
Labels: kind/bug, system/linux, system/mac
