### ISSUE TITLE
The Plugin Stopped working after latest upgrade of VSCode

### ISSUE THREAD

**Issue by chattes** [VSCodeVim/Vim#2420] opened 2018-03-05 17:36 UTC
Bug:

The plugin stopped working after upgrading VSCode

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Windows 10

**Comment by jpoon** [comment] 2018-03-05 18:21
Likely a dupe of https://github.com/VSCodeVim/Vim/issues/2415 and closing it as such.

**Closed by jpoon** 2018-03-05 18:21 UTC
