### ISSUE TITLE
Being able to disable VIM on startup

### ISSUE THREAD

**Issue by zhangkaiyulw** [VSCodeVim/Vim#3783] opened 2019-05-20 02:36 UTC
**Is your feature request related to a problem? Please describe.**
I'm a mac user, an emacs user and a vim user. The system keys plays well with emacs and vim. However, there are some conflicts between emacs key and vim key, since control key is bind both on the two key systems. Currently, on VSCode startup, VIM enables even if disabled in last session. Most of the times when I don't want to use VIM mode, I need to disable by `Toggle Vim Mode` in my case it's `command+escape`, pretty intuitive.

**Describe the solution you'd like**
On startup, Vim is enabled by default. User must disable vim with shortcut key or command. I'd like to have `Toggle Vim Mode` remembers its state across every sessions.

**Describe alternatives you've considered**
We may have an option named `Disable VIM on startup` in the settings.

**Additional context**
No additional context.

**Comment by J-Fields** [comment] 2019-05-23 01:28
This isn't quite what you want, but `vim.disableExtension` disables VIM on startup.

**Comment by zhangkaiyulw** [comment] 2019-05-23 02:31
Hi @J-Fields , with `vim.disableExtension` enabled, on startup, in the status bar, `-- VIM: DISABLED --` is not visible. It's quite confusing.

**Comment by MCluck90** [comment] 2019-07-11 18:08
@zhangkaiyulw I don't know if something has changed between then and now but I just did this and `-- VIM: DISABLED --` appears as expected.

**Comment by jpoon** [comment] 2019-09-07 07:04
This is another option: https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension.

In any case, seems like `disableExtension` is working as intended and does what you need. Closing this issue.

**Closed by jpoon** 2019-09-07 07:04 UTC
