### ISSUE TITLE
otherModeNotRecursive mappings ignores the not-recursive part in visual block mode

### ISSUE THREAD

**Issue by Recognition101** [VSCodeVim/Vim#1869] opened 2017-06-23 05:25 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** Bug

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.7
- **OS**: Mac OSX 10.12.5

I went back and tested each version, looks like this issue was introduced in VsCodeVim 0.8.0.

**What happened**:

VSCodeVim freezes, you cannot use any Vim features anymore. Also, CodeHelper and VSCode start taking 100% CPU and gaining more and more memory (2GB in a few minutes)

**What did you expect to happen**: 

Text is deleted without yanking to the clipboard.

**How to reproduce it**:

1. Set up this mapping in settings.json: `{ "before": ["d"],  "after": ["\"", "_", "d"] }`
2. Press <kbd>ctrl</kbd><kbd>v</kbd> to go into visual mode in a document with some text.
3. Select some text (i.e. press <kbd>h</kbd> twice)
4. Press <kbd>d</kbd><kbd>l</kbd> in order to delete the text without yanking it.

**Comment by Chillee** [comment] 2017-06-23 23:48
This is a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/1758

I'm going to close the other issue in favor of this one (this one's more descriptive).

**Closed** 2017-12-13 00:36 UTC
Labels: area/remap
