### ISSUE TITLE
Failed to handle key=d. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by mauriciocartagena** [VSCodeVim/Vim#6739] opened 2021-06-15 06:30 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Overlapping ranges are not allowed!
    at s._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52517)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:50209)
    at Object.executeTransformations (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/src/transformations/execute.ts:124:29)
    at I.runAction (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/src/mode/modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/src/mode/modeHandler.ts:471:11)
    at Object.promise (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/extensionBase.ts:372:73)
    at Object.runTasks (/Users/user/.vscode/extensions/vscodevim.vim-1.21.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
