### ISSUE TITLE
Failed to handle key `h`: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by shindouhiro** [VSCodeVim/Vim#7198] opened 2021-10-26 02:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `h`: Cannot read property 'start' of undefined
    at v.exec (c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\src\actions\plugins\easymotion\easymotion.cmd.ts:368:70)
    at v.execCount (c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\src\actions\base.ts:231:20)
    at j.runAction (c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:714:20)
    at j.handleKeyAsAnAction (c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:665:16)
    at j.handleKeyEvent (c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:477:40)
    at process.text (internal/process/task_queues.js:93:5)
    at c:\Users\CloudToGo\.vscode\extensions\vscodevim.vim-1.21.10\extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 01:42
Duplicate of #7461

**Closed by J-Fields** 2022-03-09 01:42 UTC
Labels: kind/bug, area/plugin
