### ISSUE TITLE
Yank by line number

### ISSUE THREAD

**Issue by Salomanuel** [VSCodeVim/Vim#4938] opened 2020-06-10 14:43 UTC
**Is your feature request related to a problem? Please describe.**
In Vim, typing 
`:364y` would yank the line 364
`:364, 757y` would yank from line 364 to line 757

**Describe the solution you'd like**
it would be nice to have that behaviour in VSCodeVim as well :)

**Comment by J-Fields** [comment] 2020-06-11 17:54
Duplicate of #1902, works with neovim integration

**Closed by J-Fields** 2020-06-11 17:54 UTC
Labels: area/commandline, kind/enhancement, status/works-with-neovim
