### ISSUE TITLE
If you press <esc> in Normal Mode, we should close out of any tooltips/popups

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1104] opened 2016-12-01 22:38 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

It's annoying that I can't close out of documentation popups with `<Esc>` currently.

**Comment by johnfn** [comment] 2016-12-02 16:52
Weird, I can't reproduce this any more. Maybe it was some sort of insiders bug.

**Comment by matheusrocha89** [comment] 2017-10-10 14:41
I am having this problem, the tooltip only closes when I click anywhere on file. If I press esc the tooltip stills there. For me it would be nice to just remove the esc keybinding by settings and leave the default of vs code cause I don't use Esc to go to Normal Mode, I usually use `Ctrl+c` to do that on my mac.

**Comment by raiskila** [comment] 2019-12-03 13:30
I'm currently experiencing this issue, where documentation popups don't go away with escape. Let's say in a JavaScript project, you write:

```javascript
console.log('asd', 'def
```

It's important to give console.log two arguments for the problem to arise. We're now in insert mode, the cursor is after the "f" (and VS Code has auto-added the closing single quote and parenthesis). When hitting escape (multiple times), the documentation popup won't go away. Tested with stable VS Code and a clean user data directory.

**Comment by thekarel** [comment] 2020-06-16 10:26
I keep running into the same problem, it can be a bit annoying. I wonder if it is caused by a specific VS Code setting?

**Closed** 2020-06-16 15:15 UTC
Labels: kind/bug

**Comment by thekarel** [comment] 2020-06-17 06:30
Excellent, thank you @J-Fields !
