### ISSUE TITLE
getLineLength() called with out-of-bounds line 50

### ISSUE THREAD

**Issue by gcameron1962** [VSCodeVim/Vim#5743] opened 2020-11-24 14:24 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 50
	at Function.getLineLength (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
	at _ (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-24 17:42
Duplicate of #5180. If you can reproduce, please post steps on that ticket.

**Closed by J-Fields** 2020-11-24 17:42 UTC
Labels: status/duplicate
