### ISSUE TITLE
Failed to handle key=. Failed to attach to neovim process. Timeout

### ISSUE THREAD

**Issue by abeiertz** [VSCodeVim/Vim#6869] opened 2021-07-13 12:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. Failed to attach to neovim process. Timeout
    at p.run (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/neovim/neovim.ts:46:15)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at process.statusBarText (internal/timers.js:494:9)
    at Object.vimState [as Run] (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/cmd_line/commandLine.ts:79:19)
    at C.j [as exec] (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/actions/commands/commandLine.ts:144:50)
    at C.execCount (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/actions/base.ts:229:42)
    at j.actionToRecord [as runAction] (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:723:40)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /home/adriaanbd/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-10-14 18:38
Duplicate of #7148

**Closed by J-Fields** 2021-10-14 18:38 UTC
Labels: status/duplicate
