### ISSUE TITLE
Failed to handle key=k. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by iwonbigbro** [VSCodeVim/Vim#6085] opened 2021-02-02 17:04 UTC
**To Reproduce**
This just happens under general use.  Usually when hitting escape and navigating when not in insert mode.

One thing I have noticed is that I cannot undo more than one item in the history under any circumstances.  The undo history seems to be broken under vim.  I have to use Ctrl+Z to go back further.

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.setLastHistoryEndPosition (extensions/vscodevim.vim-1.18.5/out/extension.js:11:207915)
	at F.runAction (extensions/vscodevim.vim-1.18.5/out/extension.js:11:174898)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
