### ISSUE TITLE
Failed to handle key=/. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by DSky90** [VSCodeVim/Vim#7029] opened 2021-08-26 16:05 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.6

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=/. Cannot read property 'previousMode' of undefined
    at I.updateView (/Users/alekseidubrovskii/.vscode/extensions/vscodevim.vim-1.21.6/src/mode/modeHandler.ts:1170:50)
    at I.handleKeyAsAnAction (/Users/alekseidubrovskii/.vscode/extensions/vscodevim.vim-1.21.6/src/mode/modeHandler.ts:667:16)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at I.text [as handleKeyEvent] (/Users/alekseidubrovskii/.vscode/extensions/vscodevim.vim-1.21.6/src/mode/modeHandler.ts:472:11)
    at /Users/alekseidubrovskii/.vscode/extensions/vscodevim.vim-1.21.6/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:35
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:35 UTC
