### ISSUE TITLE
go to definition changes file, but then pressing motion key causes jump to last/previous cursor position in target file

### ISSUE THREAD

**Issue by sathishvj** [VSCodeVim/Vim#1201] opened 2016-12-29 13:51 UTC
### What did you do?
go to definition
keys pressed under a variable: gd

### What did you expect to happen?
go to definition of variable. (which it did)

### What happened instead?
but after that if I try any of the motion keys, the cursor jumps seemingly randomly to some other spot.
In fact, I think where it jumps to is the last location of the cursor in that file.  So I suppose the cursor position isn't being updated properly.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: mac

**Comment by xconverge** [comment] 2016-12-29 17:34
duplicate of #1171

**Comment by johnfn** [comment] 2017-03-03 09:42
Fixed.

**Closed by johnfn** 2017-03-03 09:42 UTC
