### ISSUE TITLE
Failed to handle key=0. getLineLength() called with out-of-bounds line 7

### ISSUE THREAD

**Issue by jwixel** [VSCodeVim/Vim#5424] opened 2020-10-15 12:05 UTC
**To Reproduce**

Err, no idea.  I used OpenWith from Finder window.  I looked away for a moment and when I returned, saw this message.
**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=0. getLineLength() called with out-of-bounds line 7
	at Function.getLineLength (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at F.executeMovement (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480271)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475336)
	at async F.handleKeyAsAnAction (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/jessewiles/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-15 18:35
Duplicate of #5180, if you can reproduce please post steps there.

**Closed by J-Fields** 2020-10-15 18:35 UTC
