### ISSUE TITLE
Failed to handle key=`. Could NOT open editor for "file:///Applications/XAMPP/xamppfiles/htdocs/axios/学习/1.htmlk".

### ISSUE THREAD

**Issue by Summers233** [VSCodeVim/Vim#6051] opened 2021-01-27 03:23 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=`. Could NOT open editor for "file:///Applications/XAMPP/xamppfiles/htdocs/axios/学习/1.htmlk".
	at t.ExtHostEditors.showTextDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:838:711)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async t.JumpTracker.performFileJump (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:58493)
	at async t.JumpTracker.jumpThroughHistory (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:59263)
	at async t.JumpTracker.jumpBack (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:58962)
	at async wt.exec (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:110224)
	at async wt.execCount (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24180)
	at async F.runAction (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/liuchuang/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-11-05 18:05
Duplicate of #6445

**Closed by J-Fields** 2021-11-05 18:05 UTC
