### ISSUE TITLE
Cannot read property 'getNextSearchMatchPosition' of undefined

### ISSUE THREAD

**Issue by NguyenUyen0904** [VSCodeVim/Vim#5417] opened 2020-10-14 15:41 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'getNextSearchMatchPosition' of undefined
    at F.updateView (/home/uyen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:490400)
    at _ (/home/uyen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/uyen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/home/uyen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:01
Duplicate of #5310

**Closed by J-Fields** 2020-11-12 23:01 UTC
Labels: status/duplicate
