### ISSUE TITLE
Trouble remapping some Ctrl keys

### ISSUE THREAD

**Issue by schontz** [VSCodeVim/Vim#2740] opened 2018-06-16 00:05 UTC
In my `.vimrc` I had:

```vim
noremap <C-K> <C-Y>
noremap <C-J> <C-E>
```

And then I added this in my VSCode settings:
```js
	"vim.otherModesKeyBindingsNonRecursive": [
		{
			"before": ["<C-J>"],
			"after": ["<C-E>"]
		},
		{
			"before": ["<C-K>"],
			"after": ["<C-Y>"]
		}
	]
```

But it doesn't work. Bug? Or did I miss something?

**Comment by jpoon** [comment] 2018-06-16 00:33
Dupe of https://github.com/VSCodeVim/Vim/issues/757

**Closed by jpoon** 2018-06-16 00:33 UTC
