### ISSUE TITLE
Search replace not working

### ISSUE THREAD

**Issue by technikhil314** [VSCodeVim/Vim#7449] opened 2022-02-02 04:13 UTC
**Describe the bug**
Search replace not working

**To Reproduce**

1. Write following function in vimrc
```
" case changer
function! ToKebabCase()
  :s#\%V[A-Z]*\%V#\L&#ge
  :s#\%V\s\+\%V#-#ge
  :s#\%V[_]\+\%V#-#ge
endfunction
vnoremap <leader>c- :call ToKebabCase()
```
2. Select any snake case work
3. and use the short cut (leader + c + -) to convert it to kebab case

**Expected behavior**
The search replace in function should work

**Actual behaviour**
Errors out with E488: Trailing characters

- Extension (VsCodeVim) version: 1.21.10 (with neovim enabled)
- VSCode version: 
    Version: 1.63.2
    Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
    Date: 2021-12-15T09:37:28.172Z (1 mo ago)
    Electron: 13.5.2
    Chromium: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Darwin x64 19.6.0
- OS: Mac OS 10.15.7

**Comment by J-Fields** [comment] 2022-02-02 17:34
Unfortunately vimscript support isn't nearly good enough at this point to allow something like this

Duplicate of #5100, I suppose

**Closed by J-Fields** 2022-02-02 17:34 UTC
