### ISSUE TITLE
Multiple cursors do not move up and down as expected, they gather in one place

### ISSUE THREAD

**Issue by HamzaBow** [VSCodeVim/Vim#7016] opened 2021-08-20 16:44 UTC
All cursors (when having multiple cursors) gather together in one place when I move up or down.

As soon as I press `j` or `k` in normal mode, or even  `Arrow Down` or `Arrow Up` in both insert and normal mode. All the cursors move together near one of the cursors (they move to adjacent lines near this one cursor which they gather around.) 

Environment
- Extension (VsCodeVim) version: v1.21.6
- VSCode version: 1.59.1
- OS: Ubuntu 20.04

When I disable VSCodeVim extension, multiple cursors behave normally as expected (each cursor moves to the line below/above it . so the source of problem seem to be the extension.

**Comment by J-Fields** [comment] 2021-08-31 05:06
Duplicate of #4585

**Closed by J-Fields** 2021-08-31 05:06 UTC
Labels: status/duplicate
