### ISSUE TITLE
Visual Line the cursor goes to the end of the string and not on the beginning

### ISSUE THREAD

**Issue by dagadbm** [VSCodeVim/Vim#2638] opened 2018-05-09 11:02 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**What happened**:

In Visual Line mode (Shift + V) when I am selecting several lines with j/k if  there is a really huge line the cursor pops to the end of the line while in standard vim the cursor remains on the same position

**What did you expect to happen**:
The cursor would remain on the same position

**How to reproduce it (as minimally and precisely as possible)**:

put this code in VsCode:

```
<svg width="96px" height="52px">
    <g stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g transform="translate(-309.000000, -152.000000)" fill="#E9ECEF" fillRule="nonzero">
            <g transform="translate(292.000000, 98.000000)">
                <path d="M17,85.2 L27.6666667,85.2 L27.6666667,74.8 L17,74.8 L17,85.2 Z M17,106 L27.6666667,106 L27.6666667,95.6 L17,95.6 L17,106 Z M17,64.4 L27.6666667,64.4 L27.6666667,54 L17,54 L17,64.4 Z M38.3333333,85.2 L113,85.2 L113,74.8 L38.3333333,74.8 L38.3333333,85.2 Z M38.3333333,106 L113,106 L113,95.6 L38.3333333,95.6 L38.3333333,106 Z M38.3333333,54 L38.3333333,64.4 L113,64.4 L113,54 L38.3333333,54 Z" />
            </g>
        </g>
    </g>
</svg>
```
gg
Shift+v j j j j 
Notice the cursor changing position

**Environment**:

- Extension (VsCodeVim) version: Latest as of now
- VSCode version: Latest as of now
- OS version: OSX

**Comment by xconverge** [comment] 2018-05-09 15:53
Duplicate of #1779

**Closed by xconverge** 2018-05-09 15:53 UTC
