### ISSUE TITLE
Failed to handle key=*. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by yyn19951228** [VSCodeVim/Vim#5993] opened 2021-01-13 18:31 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=*. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.setLastHistoryEndPosition (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:207915)
	at F.runAction (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:174898)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async F.handleKeyAsAnAction (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/yiningyang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
