### ISSUE TITLE
getLineLength() called with out-of-bounds line 9

### ISSUE THREAD

**Issue by swcho** [VSCodeVim/Vim#5651] opened 2020-11-14 08:36 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 9
    at Function.getLineLength (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getRight (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
    at F.updateView (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
    at _ (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/Users/swcho/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by eliassendaniel** [comment] 2020-11-16 09:13
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> ```

@swcho I believe you should answer questions 1-4 to determine what you did when this happened.

**Comment by J-Fields** [comment] 2020-11-17 21:35
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-11-17 21:35 UTC
Labels: status/duplicate
