### ISSUE TITLE
Fold should not open when your cursor is over it

### ISSUE THREAD

**Issue by peey** [VSCodeVim/Vim#5051] opened 2020-07-20 08:10 UTC
**Describe the bug**
In vim, folds don't open even if your cursor is over the `...` fold element. It only opens if you open it explicitly (e.g. `zO`)

**To Reproduce**

1.  Make a new JavaScript file
2.  Write a function
3.  Fold the function body
4.  Bring your cursor to the fold. Or just try to navigate to line below folded function using `j`.

**Expected behavior**
Fold shouldn't open.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.15.0
- VSCode version: 1.47.0
- OS: Ubuntu 20.04

**Comment by J-Fields** [comment] 2020-07-20 15:26
Duplicate of #1004, this is a result of VSCode's insufficient folding API. Try enabling `foldfix`; it's hacky and has other bugs, but it should resolve this particular issue

**Closed** 2020-07-20 16:30 UTC
Labels: kind/bug, status/duplicate, upstream/vscode
