### ISSUE TITLE
i got a problem about this command (:ab fsf sdfsdfsdf)

### ISSUE THREAD

**Issue by lzyuu** [VSCodeVim/Vim#7243] opened 2021-11-10 11:30 UTC
i use visual studio code by vim mode
and i try to use :ab fsf free software foundation
to insert fsf ...

but visual studio code just come out some error like 
E488: Trailing characters

i dont know how to fix it 
if i use vim without vscode , the comand line (:ab fsf free software foundation) 
is ok .
![image](https://user-images.githubusercontent.com/45255789/141105544-614acb91-7b8f-439b-8908-0b8823689276.png)

pls help me .

**Comment by J-Fields** [comment] 2021-11-10 19:30
`:ab[breviate]` isn't yet supported (duplicate of #2203). The bad error message has been fixed on `master`.

**Closed by J-Fields** 2021-11-10 19:30 UTC
