### ISSUE TITLE
Failed to handle key=ш. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by luckydevilru** [VSCodeVim/Vim#6096] opened 2021-02-03 21:25 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.8

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=ш. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:680237)
    at h._isDocumentTextNeeded (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:683240)
    at h.addChange (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:683433)
    at F.handleKeyAsAnAction (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:705625)
    at F.handleKeyEvent (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:703994)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:350696)
    at Object.runTasks (c:\Users\Kenny\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:754478)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
