### ISSUE TITLE
macOs copy and paste chinese will result messy code

### ISSUE THREAD

**Issue by wgx1116** [VSCodeVim/Vim#1392] opened 2017-03-12 03:08 UTC
### What did you do?

copy(⌘-c) 你好 paste(⌘-v)

### What did you expect to happen?

你好

### What happened instead?

‰Ω†Â•Ω

when is disable the vim extension, it is just ok, copy and paste work fine.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: *0.6.3*
* OS: macOs 10.12.3

**Comment by jpoon** [comment] 2017-03-12 07:59
I can't repro this. Same VSCode/Vim/MacOS versions. Tried `yy` and `cmd+c`.

**Comment by johnfn** [comment] 2017-03-12 12:14
Curiously I can reproduce it just fine on 0.6.5

**Comment by Laily123** [comment] 2017-03-15 15:52
macOS：10.12.3
vscode： 1.10.2 (1.10.2)
VSCodeVim：0.6.5
if I select some chinese or japanese words, press [command + c], and then [command + v], pasted nothing. But english words is ok.
And if I disable the plugin, everything is ok.

**Comment by tvhung83** [comment] 2017-03-16 11:27
Actually, it happens for every non Latin1 characters, for ex: • (which is Opt+8 on Mac), will become `‚Ä¢` in clipboard.

**Comment by xgfone** [comment] 2017-03-19 03:39
I meet with this case. When copy(⌘-c) `中国`, paste(⌘-v) `‰∏≠` instead. But it's ok when using `Edit` -> `Copy` and `Edit` -> `Paste`.

- VSCode is `1.10.2  8076a19fdcab7e1fc1707952d652f0bb6c6db331  2017-03-08T13:54:01.558Z`.
- OS is `macOS Sierra 10.12.3`.
- VSCodeVim is `0.6.10`.

I don't modify the default settings of VSCodeVim, only just Keyboard Shortcuts as follows.

```json
{ "key": "ctrl+x", "command": "editor.action.clipboardCutAction", "when": "editorTextFocus" },
{ "key": "ctrl+c", "command": "editor.action.clipboardCopyAction", "when": "editorTextFocus" },
{ "key": "ctrl+v", "command": "editor.action.clipboardPasteAction", "when": "editorTextFocus" }
```

When disabled VSCodeVim, it works, but not when enabled it.

**Comment by Voleking** [comment] 2017-03-19 08:53
Same case like @xgfone

**Comment by johnfn** [comment] 2017-03-19 08:59
Until we fix this, the workaround is simply to put `"vim. overrideCopy": false` into your preferences json file.

**Comment by yaodis** [comment] 2017-03-24 15:40
![pasted_image_at_2017_03_24_08_37_pm](https://cloud.githubusercontent.com/assets/6690217/24301583/eb26d408-10ea-11e7-8345-9f940561067f.png)
same problem here

- VSCode is `1.10.2`
- OS is macOS Sierra `10.12.3`
- VSCodeVim is `0.6.11`

**Comment by yunkai** [comment] 2017-04-06 06:52
Same problem to me.

The messy words only happen when using `⌘-c` then `⌘-v`, but it's ok when using Edit->Copy then Edit->Paste。

MacOS，VSCodeVim 0.6.14

**Comment by breestealth** [comment] 2017-04-08 23:40
Same Problem for me.

- VSCode is 1.11.1
- OS is macOS  10.11.6
- VSCodeVim is 0.6.15

**Comment by xconverge** [comment] 2017-04-09 17:50
This is happening due to the library we use to access the system clipboard, I will see if there is a different library we can try

**Comment by naiteluo** [comment] 2017-04-13 07:52
same problem, looking forward to the update fix

**Comment by xconverge** [comment] 2017-04-19 20:12
Next release should have this fixed for macOs and Linux, windows is still a work in progress

**Comment by xconverge** [comment] 2017-04-20 03:57
fixed on master

**Closed by xconverge** 2017-04-20 03:57 UTC

**Comment by IOriens** [comment] 2017-08-24 06:38
It happens again on my mac. @xconverge 

- VSCode is 1.15.1
- OS is macOS 10.12.6
- VSCodeVim is 0.9.0
