### ISSUE TITLE
:copy and :move do not work as extension in visual studio code 1.45.1

### ISSUE THREAD

**Issue by lauatic** [VSCodeVim/Vim#4885] opened 2020-05-21 02:38 UTC
**Describe the bug**
Copying and moving a block of code with marking does not work with vscocdevim.vim@1.14.4 and vscode 1.45.1

**To Reproduce**
In normal vim editing, I can `vi file.cc` and mark two locations within file.cc with "ma" and "mb".  I type G to get to the bottom of file.cc.  I issue this move command to move the lines between markers a and b to the end of the file.
```:'a,'bmove.```

Or, I can use the copy command to duplicate the lines like
```:'a,'bcopy.```

The move and copy commands as described do not work when performed with vscodevm.vim extension in Visual Studio Code.

**Expected behavior**
How do I get the same behavior for move and copy in vscodevim.vim extension?

The delete command works fine.
```
:'a,'bd
```

**Environment (please complete the following information):**

```
$ code --version 
1.45.1
$ code --list-extensions --show-versions 
vscodevim.vim@1.14.4
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by J-Fields** [comment] 2020-05-21 03:50
This should work with neovim integration.

**Comment by lauatic** [comment] 2020-05-21 05:17
I'm hoping that I only need to install one vim extension.  Anyone know neovim has other feature parity with vscodevim?

Since `:'a,'bd` works fine, is there work around for move and copy to work also?

**Comment by J-Fields** [comment] 2020-05-21 05:22
I don't mean the neovim plugin, I mean our [integration with neovim](https://github.com/VSCodeVim/Vim#neovim-integration). I'm sure move and copy will eventually be implemented without neovim, but it's low priority.

**Comment by lauatic** [comment] 2020-05-21 16:32
@J-Fields Thanks for you quick responses.

**Comment by J-Fields** [comment] 2021-04-14 21:15
Duplicate of #2472

**Closed by J-Fields** 2021-04-14 21:15 UTC
Labels: status/works-with-neovim
