### ISSUE TITLE
FEATURE REQUEST: Implement proper window managment with new workbench commands

### ISSUE THREAD

**Issue by adrianjord** [VSCodeVim/Vim#2844] opened 2018-07-16 16:50 UTC
With the [latest update](https://code.visualstudio.com/updates/v1_25) to vscode we now get proper support for splitting both vertically and horizontally at the same time. Please implement `:help split` properly with their <C-w> commands. (Override Ctrl+w closing a document possibly?)

**Comment by xconverge** [comment] 2018-07-16 17:10
Duplicate of #2696

**Closed by xconverge** 2018-07-16 17:10 UTC
