### ISSUE TITLE
getLineLength() called with out-of-bounds line 28

### ISSUE THREAD

**Issue by screech** [VSCodeVim/Vim#5420] opened 2020-10-14 17:45 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 28
	at Function.getLineLength (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at l.getLeftThroughLineBreaks (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
	at Object.t.statusBarCommandText (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31413)
	at Object.updateShowCmd (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
	at F.handleKeyEvent (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/home/shrijeet/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-15 18:35
Duplicate of #5180, if you can reproduce please post steps there.

**Closed by J-Fields** 2020-10-15 18:35 UTC
