### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by xie-wenjie** [VSCodeVim/Vim#5744] opened 2020-11-24 16:07 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:508963)
    at h.goBackHistoryStep (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:514093)
    at Ie.exec (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:101347)
    at Ie.execCount (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37019)
    at F.runAction (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475409)
    at F.handleKeyAsAnAction (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
    at F.handleKeyEvent (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\xie-wenjie\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:54
Duplicate of #5209

**Closed by J-Fields** 2020-12-05 18:54 UTC
