### ISSUE TITLE
Failed to handle key=`. Could NOT open editor for "file:///Users/apple/Documents/welcome/cmd/go.mod".

### ISSUE THREAD

**Issue by Bellulio** [VSCodeVim/Vim#6252] opened 2021-03-09 09:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=`. Could NOT open editor for "file:///Users/apple/Documents/welcome/cmd/go.mod".
	at C.showTextDocument (/private/var/folders/yg/6yb2_jqd4xn6swjn76xwg8t00000gn/T/AppTranslocation/8E8628E3-5BEB-4CB6-9AE0-EB926D377476/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:44108)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async t.JumpTracker.performFileJump (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:689801)
	at async t.JumpTracker.jumpThroughHistory (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:690564)
	at async t.JumpTracker.jumpBack (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:690272)
	at async bt.exec (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:396109)
	at async bt.execCount (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355240)
	at async F.runAction (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
	at async F.handleKeyAsAnAction (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/apple/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-11-05 18:05
Duplicate of #6445

**Closed by J-Fields** 2021-11-05 18:05 UTC
