### ISSUE TITLE
TaskQueue: Error running task. getLineLength() called with out-of-bounds line 137

### ISSUE THREAD

**Issue by boydy12** [VSCodeVim/Vim#4644] opened 2020-03-11 14:51 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/13649815/76429310-c5a70600-63a6-11ea-9809-a3958b355181.png)

On load of VSCode I get this error as soon as I enter insert mode. VIM locks up and can't move, insert. Everything becomes sluggish and VS Code starts using high CPU.

**Environment (please complete the following information):**
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by J-Fields** [comment] 2020-03-27 20:12
What did you do that caused this?

**Comment by TommyDew42** [comment] 2020-04-01 06:34
I encountered this as well. This happened after I pasted ~400 lines of codes into the current window. VIM seemed to be disabled and I couldn't type anything to the window. Everything became fine after I undid the paste by cmd+z. 

I got the same error message after a while when I tried pasting again. Thanks.

**Environment**
Version: 1.43.2
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by yeomanse** [comment] 2020-06-01 23:52
Also encountered this error after deleting ~350 lines after selecting them in visual mode.  Vim locks up and can only interact with the file via the normal VS code stuff.  The first time this happened I disabled vim and re-enabled it to get it to work.  After the re-enable the same operation worked with no issue.  The second time this happened, after about 5 mins of me searching for this issue, vim seemed to have recover on its own with out the disable/re-enable trick.

**Comment by fangbinwei** [comment] 2020-06-11 08:18
If I open a large file, (e.g. a large compressed css/js file), and I can't move my cursor.
Then, I open a new small file, I still can't move my cursor. (I guess vim is still parsing the last large file).
After a while, vscode show error message, and I can move my cursor in the small file.
```
TaskQueue: Error running task. getLineLength() called with out-of-bounds line 12.
```

**Comment by zbennett10** [comment] 2020-06-15 19:02
Having the same problem regarding the `getLineLength()` error. Latest extension version and vscode v1.46.0

**Comment by zbennett10** [comment] 2020-06-15 19:14
Not sure why the issue above is occurring...But my issue is almost certainly an edge case. I found that for a quick fix, I needed to disable the SQLTools extension in order to allow VIM to be usable within this huge SQL file. Must be some conflict having to do with syntax highlighting, formatting, etc. between the extensions combined with how big this SQL file is.

**Comment by tozaicevas** [comment] 2020-07-01 11:28
Encountered this issue when trying to search (?:) in a file with 3343 loc. Vim keybinds freeze and CPU seems to work more than it should.

**Comment by nsapse** [comment] 2020-07-22 02:30
I keep getting this issue on one python file in particular. Vim keybinds stop working or when they do work skip and/or point to improper lines. Any progress in diagnosing it?

**Comment by komiyakomiyakomiya** [comment] 2020-08-23 23:54
私も同じ問題に遭遇しました。
私の場合は`Prettier`が原因でした。
これをアンインストールすることで、問題はなくなりました。
同じ問題で困っている人の参考になれば嬉しいです。

バージョン: 1.48.1
コミット: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
日付: 2020-08-19T17:09:41.484Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by pikpo294321** [comment] 2020-09-14 06:43
any update in progress?

**Comment by driftingdream** [comment] 2020-09-30 01:52
Same here

**Comment by J-Fields** [comment] 2020-12-05 21:52
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:52 UTC
Labels: kind/bug, status/needs-more-info
