### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by Jesus5King** [VSCodeVim/Vim#5818] opened 2020-12-04 10:52 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
    at d._lineAt (c:\Users\epima\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:964)
    at Object.lineAt (c:\Users\epima\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:548:930)
    at Function.getLineAt (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:22388)
    at _.exec (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:216058)
    at _.execCount (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:37406)
    at x.exec (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:214331)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.execCount (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:1:37395)
    at F.runAction (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:475401)
    at F.handleKeyAsAnAction (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:471603)
    at Object.promise (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\epima\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 00:13
Duplicate of #5305

**Closed by J-Fields** 2020-12-05 00:13 UTC
