### ISSUE TITLE
Remapping of $ is remapped to L and H to ^ as per readme fails to be recognised

### ISSUE THREAD

**Issue by yunti** [VSCodeVim/Vim#5163] opened 2020-09-03 18:19 UTC
**Describe the bug**
The remap specified in the vscodevim readme fails to be recognised, other bindings work as expected.

"vim.operatorPendingModeKeyBindings": [
    {
      "before": ["L"],
      "after": ["$"]
    },
    {
      "before": ["H"],
      "after": ["^"]
    }
  ],

**To Reproduce**

Use the remapping suggested in the vscode vim readme as listed above.

**Expected behavior**
Keymap should be accepted as expected

**Screenshots**
In the screenshot below you can see it is faded (meaning that it isn't recognised or syntax issue?)
<img width="397" alt="image" src="https://user-images.githubusercontent.com/1826271/92152089-0d6c8e80-ee1a-11ea-9a10-a4d823a66047.png">

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.16.0
- VSCode version:
Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:09:41.484Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by berknam** [comment] 2020-09-05 15:17
Duplicate of #5134. This will be out on the next release. The README is already updated because it has been merged already but it will only work after the next release.

**Closed** 2020-09-05 18:23 UTC
Labels: status/duplicate
