### ISSUE TITLE
getLineLength() called with out-of-bounds line 5

### ISSUE THREAD

**Issue by yuber83** [VSCodeVim/Vim#5359] opened 2020-10-08 17:32 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 5
    at Function.getLineLength (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getRight (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
    at F.updateView (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
    at _ (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-11 02:58
Duplicate of #5180

**Closed by J-Fields** 2020-10-11 02:58 UTC
Labels: status/duplicate
