### ISSUE TITLE
<c-o>/<c-t> jump back to wrong location after 'gd'

### ISSUE THREAD

**Issue by drewthor** [VSCodeVim/Vim#4479] opened 2020-01-08 20:26 UTC
**Describe the bug**
Pressing <C-o> after 'gd' goes to a different file and not back to the previous location.

Re-reporting #3277 since this bug has not been re-introduced (I'm guessing after the 1s sleep was removed)

**To Reproduce**
Press 'gd'
Press <C-o>
Now in wrong location

**Expected behavior**
Going to the previous location

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: macOS 10.14.6

**Additional context**

**Comment by J-Fields** [comment] 2020-01-08 21:06
Duplicate of #4470. I'm pretty sure you're right that this broke after I removed the timeout. Maybe we can get around that, or maybe I need to add it back in a more limited context.

**Comment by troygibb** [comment] 2020-01-23 17:17
Workaround: https://github.com/VSCodeVim/Vim/issues/3277#issuecomment-577780535

**Comment by artempyanykh** [comment] 2020-01-23 21:47
> Workaround: #3277 (comment)
@troygibb does this work for you as intended? In my case, it seems that Vim extension hijacks `Go back`, so if I do `gd` and then `jjjjjjj` then `Go back` brings me to the previous line instead of the file I jump from.

As for `C-o` it seems broken on all `1.12.x` - I got reasonable behaviour only with `1.11.3`.

**Comment by yyn19951228** [comment] 2020-02-13 19:27
May I ask are there any fixes or updates?

**Comment by vvhitedog** [comment] 2020-02-14 08:47
This issue seems exacerbated when you open more than one file, especially if you have more than one file open in window splits (:vsp for example.) I find that the ctrl-t, ctrl-o works decently with just one window/tab open, but obviously that is pretty unusable. Hopefully, that gives a hint as to what might be going wrong. 

Just to add my two-cents: bugs like this make VSCodeVim pretty unusable to the point I just want to turn it off, and/or just stick to vim or qtcreator (which has a half decent FakeVim implementation.)

**Closed** 2020-02-25 01:59 UTC

**Comment by strobelight** [comment] 2021-08-04 15:31
Seems to me this is still broke. I use `ctrl-]` to get to definition, once there look at code, perhaps do searching, and find that `ctrl-t` takes me back up the searches I've done instead of to the previous file (or location in same file).

**Comment by zeroxia** [comment] 2022-02-10 10:23
I'm still having problem randomly with CTRL+T, it is not reliable, sometimes it won't bring my back to where I pressed `Ctrl+]`.

VSCode:
```
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:17:47.733Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-100-generic
```

vscodevim: 1.22.1
