### ISSUE TITLE
mouseSelectionGoesIntoVisualMode does not work in insert mode

### ISSUE THREAD

**Issue by 9527KGG** [VSCodeVim/Vim#3389] opened 2019-01-18 08:02 UTC
**Describe the bug**
mouseSelectionGoesIntoVisualMode does not work in insert mode.

**To Reproduce**

1.  set mouseSelectionGoesIntoVisualMode to true
2.  goto insert mode
3.  Use mouse to select a text
4.  However, vim is still in insert mode.

**Expected behavior**
Should be in Visual mode.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.2
- VSCode version: 1.30.2
- OS: Ubuntu 18 LTS

**Additional context**

**Comment by 9527KGG** [comment] 2019-03-27 03:31
The issue is insert mode, not normal mode. thanks.

**Comment by 9527KGG** [comment] 2019-03-29 04:24
I took a look at the code, modeHandler.ts has

        if (
          configuration.mouseSelectionGoesIntoVisualMode &&
          !this.currentMode.isVisualMode &&

        ) {
          await this.setCurrentMode(ModeName.Visual);

          // double click mouse selection causes an extra character to be selected so take one less character
        }
      } else if (this.vimState.currentMode !== ModeName.Insert) {
        await this.setCurrentMode(ModeName.Normal);
      }

May anyone please remove this line?

          this.currentMode.name !== ModeName.Insert

seems it will working. Thanks.

**Comment by J-Fields** [comment] 2020-03-25 20:56
Yeah, this was intentional. I wonder if we should have a separate option for insert mode...

**Comment by J-Fields** [comment] 2020-07-14 16:16
Duplicate of #4972

**Closed by J-Fields** 2020-07-14 16:16 UTC
Labels: area/selection, kind/bug

**Comment by uxmaster** [comment] 2021-03-26 11:00
@J-Fields 
> Yeah, this was intentional. I wonder if we should have a separate option for insert mode...

I do not see what was the intention here... Vim behaves differently, so it rather looks like a bug...
Moreover, the option name and description `mouseSelectionGoesIntoVisualMode` indicates it should work regardless of the current mode.

**Comment by kmmaru** [comment] 2023-12-15 16:02
I hope anyone fixed, because idea is this, and i want....
