### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by nishitsingh13** [VSCodeVim/Vim#6358] opened 2021-03-27 15:27 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:51884)
    at Object.edit (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49576)
    at Object.executeTransformations (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/src/transformations/execute.ts:122:29)
    at I.runAction (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/extensionBase.ts:632:27)
    at Object.runTasks (/home/nishit/.vscode/extensions/vscodevim.vim-1.19.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
