### ISSUE TITLE
Ctrl-o (go back) record every cursor move ?

### ISSUE THREAD

**Issue by WangRongda** [VSCodeVim/Vim#2461] opened 2018-03-20 10:07 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE
**What happened**:
When I use 'gd' to go defined, it dump to another file, and press ctrl-o to go back.
But go back in vscode is based on step that record every cursor move and the history stack is limited.If I move many time, I could not go back to the last file.
![wang2](https://user-images.githubusercontent.com/22711444/37648190-41f43db2-2c69-11e8-8c27-93a6337a90c6.gif)

**What did you expect to happen**:
Like the native vim: don't record every move or add new feature that support go-back-file-based.
![wang](https://user-images.githubusercontent.com/22711444/37648182-3dc2eacc-2c69-11e8-893a-35a0b9cec225.gif)

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version:0.11.2
- VSCode version:1.12.1
- OS version:4.15.9-1-ARCH

**Comment by alex-xnor** [comment] 2018-03-20 22:43
Vim does record certain movements within a file as well, but not nearly so many as VSCodeVim erroneously does. The complete list of movements that cause an entry in the jump list consulted by <kbd>CTRL-O</kbd> is available [in Vim's help, under `jump-motions`](https://vimhelp.appspot.com/motion.txt.html#jump-motions).

**Comment by WangRongda** [comment] 2018-03-21 05:40
@alex-xnor 
You are right!
I don't know how vim define a jumping, but It should not be a cursor move.

**Comment by jazmit** [comment] 2018-08-15 08:50
+1 This is really annoying

**Comment by axs221** [comment] 2018-08-27 02:05
Duplicate of #1933? I'm working on a potential solution. I'm tracking positions for any actions that occur within VSCodeVim, and then I'll look at also tracking some major external events like changing the editor or group. I'll then probably need to add a metadata tag on actions to specify whether they should be included in the jump list or not.

**Comment by alex-xnor** [comment] 2018-08-27 17:35
@axs221 Yes, I think this is a duplicate of #1933.

**Comment by jpoon** [comment] 2018-08-27 17:53
Indeed it as a duplicate and closing it as such.

**Closed by jpoon** 2018-08-27 17:53 UTC
