### ISSUE TITLE
Can ‘%’  support macro block jump?

### ISSUE THREAD

**Issue by jiaobendaye** [VSCodeVim/Vim#5805] opened 2020-12-02 04:01 UTC
In vsvim, '%' is support macro  block  ('#if' '#else' '#elif' '#endif') jump. Does VSCodeVim support?

**Comment by J-Fields** [comment] 2020-12-02 16:45
Not currently, though it's a reasonable request

**Comment by sql-koala** [comment] 2020-12-04 18:49
Could be seen as dupe of #1885

**Comment by J-Fields** [comment] 2020-12-04 19:54
I agree, closing as a duplicate of #1885 - I'll put a comment mentioning this specifically there.

**Closed by J-Fields** 2020-12-04 19:54 UTC
Labels: kind/enhancement, status/duplicate
