### ISSUE TITLE
Failed to handle key=S. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by mrlarios** [VSCodeVim/Vim#5285] opened 2020-09-28 19:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=S. Cannot read property 'stop' of undefined
	at p.get cursorStopPosition [as cursorStopPosition] (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
	at F.runAction (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475433)
	at F.handleKeyAsAnAction (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/carloslarios/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-29 05:03
Duplicate of #5284

**Closed by J-Fields** 2020-09-29 05:03 UTC
