### ISSUE TITLE
Fail to substitute target string to backslash

### ISSUE THREAD

**Issue by iiifr** [VSCodeVim/Vim#3904] opened 2019-07-18 19:25 UTC
Can't substitute target string to backslash correctly.

**Environment:**
VSCode Version: 1.36.1
VsCodeVim Version: 1.8.2
OS: Linux Mint

**What happened:**
If I had text like below:
```
aass;fff
;;ppod
{{;}}
```
and I want to replace `;` to `\` with command `:%s/;/\\/g`
After execution, the text become:
```
aass\\fff
\\\\ppod
{{\\}}
```
**What did you expect to happen:**
The text after substitution should be:
```
aass\fff
\\ppod
{{\}}
```
**How to reproduce it:**
* Type text:
```
aass;fff
;;ppod
{{;}}
```
* Execute command `:%s/;/\\/g`

**Comment by J-Fields** [comment] 2019-08-04 04:30
This works correctly with neovim integration enabled.

**Comment by J-Fields** [comment] 2019-08-04 21:48
Related: #1937

**Comment by iiifr** [comment] 2019-08-05 15:37
ok. Thanks for your reply.

**Comment by J-Fields** [comment] 2021-03-05 16:49
Duplicate of #2710

**Closed by J-Fields** 2021-03-05 16:49 UTC
Labels: kind/bug, status/works-with-neovim
