### ISSUE TITLE
Word wrap gets set to off on every startup

### ISSUE THREAD

**Issue by Tesohh** [VSCodeVim/Vim#6715] opened 2021-06-09 21:18 UTC
**Describe the bug**
Word wrap gets set to "off" on every startup

**To Reproduce**

1.  open vscode
2.  See error

**Expected behavior**
I expected that the setting would stay as i set it, wordwrap on.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.0
- VSCode version: 1.56.2
- OS: Windows 10

**Additional context**

**Comment by itscarlosecp** [comment] 2021-06-10 02:52
I have the same issue, some settings are rewritten every time I open VSCode. Unistalled all my extensions and VSCodeVim was causing the problem. These are the settings that were modified:
```json
{
    "editor.tabSize": 8,
    "editor.cursorStyle": "line",
    "editor.insertSpaces": false,
    "editor.lineNumbers": "on",
    "editor.wordSeparators": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-",
    "editor.wordWrap": "off"
}
```
* Extension version: 1.21.0
*  VSCode version: Stable 1.56.2 and Insiders .157.0
* OS: Windows 10 using Windows Subsystem for Linux

**Comment by K9-guardian** [comment] 2021-06-10 03:22
I have the same issue as well, with the exact same changes indicated by @itscarlosecp.

**Comment by gav-** [comment] 2021-06-10 04:06
Same issue, I incorrectly attributed this to a vs-code bug: microsoft/vscode#125893

- Extension (VsCodeVim) version: v1.21.0
- VSCode version: 1.56.2
- OS: Linux Mint 20.1 (Ubuntu 20.04)

**Comment by chewcw** [comment] 2021-06-10 08:26
I face the same issue in this version: v1.21.0, have to revert to previous version to solve it temporarily.

**Comment by J-Fields** [comment] 2021-06-10 16:59
Duplicate of #6717

**Closed by J-Fields** 2021-06-10 16:59 UTC
Labels: status/duplicate
