### ISSUE TITLE
Failed to handle key=. nvim_buf_set_lines: Buffer is not 'modifiable'

### ISSUE THREAD

**Issue by silviubogan** [VSCodeVim/Vim#5952] opened 2021-01-01 09:00 UTC
**To Reproduce**
This is what I did but after closing the tab and pasting the content in a new tab I cannot reproduce the issue, it seems to be gone.

1.  Create a new tab
2.  Add some lines to it:

```html
<ol>
	<li>
		<a href="/episodes/show-invisibles/"> Show invisibles
		</a>
	</li>
	<li>
		<a href="/episodes/tabs-and-spaces/"> Tabs and Spaces
		</a>
	</li>
</ol>
```

3.  Attempt to run command `:v/href/d`
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Error making request to nvim_buf_set_lines
	at c.request (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:1:159782)
	at c.setLines (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:9:95995)
	at p.syncVSCodeToVim (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:229325)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async p.run (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:228211)
	at async Object.Run (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:1:143430)
	at async C.exec (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:126055)
	at async C.execCount (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641)
	at async F.runAction (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/home/silviub/.vscode-oss/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 04:02
Duplicate of #7312

**Closed by J-Fields** 2022-03-09 04:02 UTC
Labels: status/duplicate
