### ISSUE TITLE
Failed to handle key=U. Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by Muhwahyu** [VSCodeVim/Vim#6417] opened 2021-04-04 03:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=U. Cannot read property 'start' of undefined
    at p.goBackHistoryStepsOnLine (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/history/historyTracker.ts:752:51)
    at Re.exec (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/commands/actions.ts:1158:56)
    at Re.execCount (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/base.ts:218:20)
    at I.runAction (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:719:20)
    at I.handleKeyAsAnAction (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:650:16)
    at I.handleKeyEvent (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:40)
    at runMicrotasks (<anonymous>)
    at process.text (internal/process/task_queues.js:97:5)
    at Object.promise (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:377:73)
    at Object.runTasks (/Users/Way/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-04 21:07
Duplicate of #6377

**Closed by J-Fields** 2021-04-04 21:07 UTC
