### ISSUE TITLE
getLineLength() called with out-of-bounds line 6951

### ISSUE THREAD

**Issue by dongdong7** [VSCodeVim/Vim#5409] opened 2020-10-14 03:33 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 6951
	at Function.getLineLength (/Users/davidlu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/davidlu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.handleSelectionChange (/Users/davidlu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:468290)
	at Object.promise (/Users/davidlu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235549)
	at Object.runTasks (/Users/davidlu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621922)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 03:56
Duplicate of #5180, please post steps to reproduce there

**Closed by J-Fields** 2020-10-14 03:56 UTC
