### ISSUE TITLE
conflicts with the Java Extension Pack

### ISSUE THREAD

**Issue by someoneonsmile** [VSCodeVim/Vim#3335] opened 2019-01-06 06:21 UTC
**Describe the bug**
The vim plugin conflicts with the Java Extension Pack, :w will have a promise error
**To Reproduce**
When I installed the Java Extension Pack, after typing :w, it showed the following error
![image](https://user-images.githubusercontent.com/24894650/50732885-ff3a1b00-11bd-11e9-91d4-e465b57445bd.png)

**Comment by jpoon** [comment] 2019-01-06 06:34
Dupe of https://github.com/VSCodeVim/Vim/issues/3330

**Closed by jpoon** 2019-01-06 06:34 UTC
