### ISSUE TITLE
Conversion from .vimrc

### ISSUE THREAD

**Issue by NelsonAPenn** [VSCodeVim/Vim#4231] opened 2019-10-31 14:54 UTC
So far, I do enjoy having Vim extensions on VSCode; however, I find the configuration of VSCodeVim through the `settings.json` to be tedious and unintuitive.

I (as well as other die-hard Vim users, I'm sure) maintain a separate `.vimrc` file which I port wherever I need it, but because of the difficulty of creating the settings for VSCodeVim I often find myself simply using Vim on the GNOME terminal alongside VSCode.

I understand not supporting `.vimrc`'s directly, but I think a tool should be added that will take a `.vimrc` file and create the matching settings from it. Of course, vimscript functions and other potentially unsafe code could be sanitized out. However, it would be a very nice addition to VSCodeVim to read from my `.vimrc` and automatically create the appropriate settings for key remappings, colorschemes, and the like.

**Comment by J-Fields** [comment] 2019-11-01 06:23
See https://github.com/VSCodeVim/Vim/pull/3908

**Comment by J-Fields** [comment] 2019-11-08 18:11
Closing this issue as basically a duplicate of https://github.com/VSCodeVim/Vim/issues/463. Remappings read directly from a `.vimrc` will likely be in the next release, and while we likely will never properly support vimscript, things like simple settings will be coming soon as well.

**Closed by J-Fields** 2019-11-08 18:11 UTC
