### ISSUE TITLE
s     Failed to handle key={. Illegal value for `line`

### ISSUE THREAD

**Issue by hanyingming** [VSCodeVim/Vim#5914] opened 2020-12-21 06:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key={. Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at Function.getFirstNonWhitespaceCharOnLine (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:14610)
	at t.u.Position.getLineBeginRespectingIndent (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:67285)
	at ft.execAction (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:221546)
	at ft.createMovementResult (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:153324)
	at ft.execActionWithCount (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:152981)
	at F.executeMovement (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
	at F.runAction (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171527)
	at F.handleKeyAsAnAction (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at Object.promise (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216277)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/zcq/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:49
Duplicate of #6178

**Closed by J-Fields** 2021-03-24 17:49 UTC
