### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ddeline** [VSCodeVim/Vim#6933] opened 2021-07-29 19:58 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\DDELINE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\DDELINE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\DDELINE\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\DDELINE\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\DDELINE\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\DDELINE\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\DDELINE\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[1140, 59] | [1140, 58]]"
]
actionsRunPressedKeys: [
  "n",
  "<Esc>"
]
actionsRun: [
  "ee",
  "$",
  "C",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 1140,
      "character": 58
    },
    "text": "OG_",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 1140,
        "character": 57
      },
      {
        "line": 1140,
        "character": 61
      }
    ],
    "text": "terms.LOG_LEVEL_ERROR",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:05
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:05 UTC
