### ISSUE TITLE
External substitute command doesn't work

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#4159] opened 2019-10-10 20:54 UTC
**Describe the bug**
When running external command :%s/fox/mouse/g I get the following error:
CommandLine: Error executing cmd=%s/fox/mouse/g. err=Error: nvim_buf_set_lines: Wrong type for argument 1, expecting Buffer.

**To Reproduce**
Enter command mode by typing `':'`.
Enter the following, using text that you can test with and hit enter: %s/target-text/replacement-text/g

**Expected behavior**
I expected the target text to be replaced.

**Screenshots**
![Screen Shot 2019-10-10 at 4 46 49 PM](https://user-images.githubusercontent.com/271288/66605206-9ed96f00-eb7d-11e9-82e4-b17b58780184.png)

![Screen Shot 2019-10-10 at 4 50 30 PM](https://user-images.githubusercontent.com/271288/66605439-19a28a00-eb7e-11e9-99f2-f30eb49eeed0.png)

![Screen Shot 2019-10-10 at 5 00 56 PM](https://user-images.githubusercontent.com/271288/66606231-a3068c00-eb7f-11e9-8078-6114a2680dde.png)

**Environment**
Mac OS v10.13.6
VSCode v1.39.0
Vim Extension v1.11.0
Neovim v0.3.8

**Comment by jpoon** [comment] 2019-10-14 06:44
Dupe of https://github.com/VSCodeVim/Vim/issues/4126

**Closed by jpoon** 2019-10-14 06:44 UTC
