### ISSUE TITLE
getLineLength() called with out-of-bounds line 117

### ISSUE THREAD

**Issue by wxw-matt** [VSCodeVim/Vim#5362] opened 2020-10-09 13:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 117
	at Function.getLineLength (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/user/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-11 02:57
Duplicate of #5180

**Closed by J-Fields** 2020-10-11 02:58 UTC
Labels: status/duplicate
