### ISSUE TITLE
VS Code Vim's undo history is out of sync with VS Code's history.

### ISSUE THREAD

**Issue by trusktr** [VSCodeVim/Vim#3871] opened 2019-07-08 05:31 UTC
**Describe the bug**

Sometimes, doing certain actions in VS Code doesn't go into Vim's undo stack (hitting `u` doesn't undo that item, but rather some previous item from the separate stack).

**To Reproduce**

Not sure. But sometimes I get into a state where pressing `cmd-z` and `cmd-Z` undo and redo everything as expected, but pressing `u` or `ctrl-r` seem to go to different text state that are on a different stack, and this other stack does not contain all the same states as the `cmd-z/Z` stack.

**Expected behavior**

It should use the same stack.

Does VS Code not let plugins hook into it properly?

**Screenshots**

N/A

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.35.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 363,
		"activateCallTime": 1,
		"activateResolvedTime": 325,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Additional context**

Not sure how to trigger it, but it happens quite often.

**Comment by xconverge** [comment] 2019-07-11 15:27
duplicate of #1490

**Closed by xconverge** 2019-07-11 15:27 UTC
