### ISSUE TITLE
Can't close editor suggestions when using vim plugin

### ISSUE THREAD

**Issue by alanchavez88** [VSCodeVim/Vim#3109] opened 2018-10-06 12:30 UTC
**Describe the bug**
Whenever the editor suggestions pop up in VS Code, normally you can close them by hitting `<Esc>`. However, when the vim plugin is enabled, the suggestion doesn't go away.

**To Reproduce**
1. Enable vim plugin. 
2. Create a javascript function, annotate it so that the pop-up suggestions shows up. 
3. Hit `<Esc>` to close it
4. Keep hitting `<Esc>` until your hands bleed
5. Pop up doesn't go away.

**Expected behavior**
When the vim plugin is enabled and the editor suggestion shows up, users should be able to close the editor suggestion by hitting `<Esc>`

**Screenshots**
N/A

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.7
- VSCode version: 1.27.2
- OS: MacOS High Sierra 10.13.6 (17G65)

**Comment by xconverge** [comment] 2018-10-06 15:28
shift+esc will work FYI but see discussion in duplicate issue

duplicate of #2258

**Closed by xconverge** 2018-10-06 15:28 UTC
