### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by linometry** [VSCodeVim/Vim#6143] opened 2021-02-15 00:59 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
	at Object.S [as illegalArgument] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)
	at new d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:20609)
	at new d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:19977)
	at a (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
	at F.exec (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.runAction (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708017)
	at async F.rerunRecordedState (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:714422)
	at async y.execute (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:783471)
	at async F.runAction (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707854)
	at async F.handleKeyAsAnAction (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/linogabriel/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
