### ISSUE TITLE
adding configs for `statusBarColorControl` and `statusBarColors` existing `workbench.colorCustomizations` settings are removed

### ISSUE THREAD

**Issue by thousand** [VSCodeVim/Vim#2150] opened 2017-11-15 02:43 UTC
**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.18.0
- **VsCodeVim Version**: 0.10.4
- **OS**: macOS 10.12.6

**What happened**: 

I enabled the   "vim.statusBarColorControl" user preference and added some `"vim.statusBarColors"` configs. Doing this wiped out my `workbench.colorCustomizations` for the cursor color. 

pre-existing customization:
```
"workbench.colorCustomizations": {
  "editorCursor.background": "#ff00ff"
}
```

added for vim: 
```
  "vim.statusBarColorControl": true,
  "vim.statusBarColors": {
    "normal": "#444444",
    "insert": "#226622",
    "visual": "#224466",
    "visualline": "#662244",
    "visualblock": "#224466",
    "replace": "#662222"
  }
```

new workbench.colorCustomizations:

```
  "workbench.colorCustomizations": {
    "statusBar.background": "#224466",
    "statusBar.noFolderBackground": "#224466",
    "statusBar.debuggingBackground": "#224466"
  },
```

**What did you expect to happen**: 
I would expect this to merge the status bar colors into the other color customization settings instead of replacing them.

**How to reproduce it**:
(see above)

**Comment by jpoon** [comment] 2017-11-15 04:24
Sounds like a dupe of https://github.com/VSCodeVim/Vim/issues/1654

**Comment by jpoon** [comment] 2017-11-16 14:21
Fixed with https://github.com/VSCodeVim/Vim/pull/2122

**Closed** 2017-11-16 14:21 UTC
