### ISSUE TITLE
Failed to handle key=<BS>. TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed muitos tavamentos e demora no crregamento das extensoes

### ISSUE THREAD

**Issue by carlos738** [VSCodeVim/Vim#6745] opened 2021-06-15 23:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.2

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed
    at Object.h [as disposed] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)
    at Yo.$tryApplyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:20305)
    at r._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11905)
    at r._invokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11597)
    at r._receiveRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1832:10259)
    at r._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1832:9062)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1832:7166
    at n.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at a.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16288)
    at i._receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21546)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18432
    at n.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at h.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13649)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12997
    at Socket.D (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2938:132926)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by J-Fields** [comment] 2021-07-06 17:03
Duplicate of #5650

**Closed by J-Fields** 2021-07-06 17:03 UTC
Labels: status/duplicate
