### ISSUE TITLE
getLineLength() called with out-of-bounds line 28

### ISSUE THREAD

**Issue by zengyuxing007** [VSCodeVim/Vim#5499] opened 2020-10-27 08:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 28
	at Function.getLineLength (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
	at _ (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/yuxingzeng/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-29 16:16
Duplicate of #5180; if you can reproduce, please post steps there.

**Closed by J-Fields** 2020-10-29 16:16 UTC
