### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by ququuy** [VSCodeVim/Vim#6974] opened 2021-08-10 04:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
    at j.updateView (c:\Users\\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:1171:50)
    at j.handleKeyAsAnAction (c:\Users\\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:662:16)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at j.mh [as handleKeyEvent] (c:\Users\\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:35
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:35 UTC
