### ISSUE TITLE
Insert mode mapped jk to <esc> always leaves the j before escaping

### ISSUE THREAD

**Issue by i-nino** [VSCodeVim/Vim#4789] opened 2020-05-03 12:18 UTC
**Describe the bug**
When I enter insert mode and want to exit it using my jk mapping, it exits fine but inserts the j before doing so, at the end of the line, and at times, will delete the first character of the line as well.

**To Reproduce**

1.  Go to 'settings.json"
2.  Add the following:
"vim.insertModeKeyBindings": [
        {
            "before": ["j", "k"],
            "after": ["\<esc\>"]
        },
]

**Expected behavior**
The jk mapping should work as expected, resulting in escaping insert mode without inserting either the j or k or any character, for that matter, and also not delete the first character of the current line.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.14.0 (2020-05-02)
- VSCode version: March 2020 (version 1.44)
- OS: Win10 1909

**Additional context**

**Comment by plitzenberger** [comment] 2020-05-03 12:23
Have the same issue, but it happens only every second time 🤔

**Comment by plitzenberger** [comment] 2020-05-03 12:26
Same like here #4787

**Comment by i-nino** [comment] 2020-05-03 12:30
@plitzenberger Thanks for referencing that!  This issue can then be closed since the other one is already open and the issues are identical.

**Comment by J-Fields** [comment] 2020-05-03 17:01
Dupe of #4787

**Closed by J-Fields** 2020-05-03 17:01 UTC
