### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by asgrom** [VSCodeVim/Vim#3692] opened 2019-04-19 02:57 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/alexandr/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-04-19 04:49
Dupe of #3362 and there is also no cpuprofile attached...

**Closed by jpoon** 2019-04-19 04:49 UTC
