### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hashhashu** [VSCodeVim/Vim#3366] opened 2019-01-14 06:18 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `0.16.6`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hurly/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-01-20 10:59
Dupe of https://github.com/VSCodeVim/Vim/issues/3362

**Closed by jpoon** 2019-01-20 10:59 UTC
Labels: status/duplicate, status/needs-more-info
