### ISSUE TITLE
The cursor jumps to the end of the file

### ISSUE THREAD

**Issue by llife09** [VSCodeVim/Vim#2136] opened 2017-11-11 10:27 UTC
**Environment**:
- **VSCode Version**: 1.18.0
- **VsCodeVim Version**: 0.10.2
- **OS**: macOS High Sierra 10.13.1

**What happened**:
I use vscode with the extension "Go" for golang develop.
When I modify and save a .go file, the cursor jumps to the end of the file.

**What did you expect to happen**: 
The cursor should stay in its original position.

**How to reproduce it**:
1. Install extension "Go" for Visual Studio Code.
1. Edit a .go source file.
1. Save the file.

**Comment by cpinto** [comment] 2017-11-11 14:08
@llife09 came here after spotting the same problem. Even disabling this plugin didn't fix it which led me to check what plugins I had installed as I suspected it might have something to do with either linting or code formatting triggered by a save. In my case, I had this JS-CSS-HTML Formatter plugin that I disabled and the problem went away. Might this be the case for you as well?

**Comment by llife09** [comment] 2017-11-11 16:15
@cpinto it works well before i upgrade the vscode to 1.18.0. The extension "Go" will format the file on save，but i need this feature.

**Comment by KurtRMueller** [comment] 2017-11-13 15:29
Same here. After upgrading to vscode 1.18, writing the file will make my cursor jump the end of the file. For me, I'm writing Elm and using the Elm plugin, which formats my Elm code to the language's coding style conventions.

**Comment by Stijnkool** [comment] 2017-11-22 18:05
This seems to be a regression in version 1.18.
An issue has been filed https://github.com/Microsoft/vscode/issues/38728.

**Comment by Chillee** [comment] 2017-11-22 21:27
This doesn't seem to be a VSCodeVim problem, from what people are saying.

I'm going to close this issue.

**Closed by Chillee** 2017-11-22 21:27 UTC

**Comment by systemovich** [comment] 2019-03-08 01:23
This happens a lot for me with different commands, e.g. when pressing `dd`, after pressing the first d, the cursor jumps to a different line, and the wrong lines gets deleted.

**Comment by krischer** [comment] 2019-03-26 14:05
> This happens a lot for me with different commands, e.g. when pressing `dd`, after pressing the first d, the cursor jumps to a different line, and the wrong lines gets deleted.

I have exactly the same. It notable happens after deleting a line with `dd`. No matter what other key I press afterwards the cursor jumps to the end of the file. It also only happens when using VSCode for a while but once it happens it happens every time making it unusable. The only remedy is to restart VSCode.

I'd be happy to help debug this but I don't really know where to start.

**Comment by aarontami** [comment] 2019-03-29 20:34
> > This happens a lot for me with different commands, e.g. when pressing `dd`, after pressing the first d, the cursor jumps to a different line, and the wrong lines gets deleted.
> 
> I have exactly the same. It notable happens after deleting a line with `dd`. No matter what other key I press afterwards the cursor jumps to the end of the file. It also only happens when using VSCode for a while but once it happens it happens every time making it unusable. The only remedy is to restart VSCode.
> 
> I'd be happy to help debug this but I don't really know where to start.

This has been happening to me too, but seems to only happen when i have the same file open twice in a vertical split and both files are in focus.

**Comment by loosebazooka** [comment] 2019-04-03 19:24
Should a new issue be opened?

**Comment by ConnorGray** [comment] 2019-04-08 18:03
I'm also experiencing this bug. `dd` followed by any other key jumps to the bottom of the file. A restart is necessary to fix the bug, but it always reappears eventually.

**Comment by jonkiersey** [comment] 2019-06-28 17:10
I haven't seen reproduction steps posted in detail, so here's what I've found:

When I have the same file open in a split window, if I delete a line with 'dd', the next keystroke will jump the cursor to the location of the cursor in the other window. Putting the cursor in the other split file in line 1 keeps this from happening. Definitely not a fix, but until one comes along, that's what I'm doing.

**Comment by kybishop** [comment] 2019-07-29 17:40
@Chillee this very specifically happens in the case @jonkiersey mentioned. Now that it has been triangulated to such a specific repro, it seems this issue should be re-opened.
