### ISSUE TITLE
Selection highlight display inconsistent

### ISSUE THREAD

**Issue by chestnutchen** [VSCodeVim/Vim#1455] opened 2017-03-31 06:52 UTC
Expect: Display selection highlight for `meta-d` and `Mouse Selection` the same as `Double Click`.

The weird thing disturbed me is the last character is not highlighting, but it will be copied when I do `y` or `Ctrl-c`.  

Btw, doing `vaw` on a word without special character at the end of a line may select `\n` and some spaces of next line.

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: OS X EI Capitan 10.11.6

**Comment by xconverge** [comment] 2017-04-09 17:39
I think I fixed the mouse selection/double click on master,

Your second issue is tracked here at #1350 can you go thumbs up it there

Closing this for now unless I misunderstood something.

The main issue was when you double click a word, it is displayed in the wrong place even though pressing x or y or something it was in the right place?

**Comment by chestnutchen** [comment] 2017-04-12 10:15
Double clicking a word displayed in the right place and it interacted correctly. The main issue is the highlighting selection region of `mouse selection`. Just as the follows image:

![image](https://cloud.githubusercontent.com/assets/2787987/24952577/7ab97fee-1faa-11e7-81aa-80bfc0da7bbc.png)

I don't know whether the last character 'm' is selected (Actually it is selected, but the highlighting of the references in other places of this document are wrong). 

And doing `double click` it display as follows:

![image](https://cloud.githubusercontent.com/assets/2787987/24952636/c6199852-1faa-11e7-9f77-5ad95c5d9b71.png)
 
I think the later display is better.

**Comment by xconverge** [comment] 2017-04-12 14:45
That is not how vim works though is the problem. What you are describing makes sense. As far as other references should be fully highlighted, is there an action that you run that needs this or is it just visual?

**Comment by chestnutchen** [comment] 2017-04-12 15:12
It is just visual problem. I agree with you that vim is innocent. But vscode is not vim. Just lisk Sublime, It works consistent with vintage. In Sublime, vmode selection is consistent with normal mouse selection. And we can do `<ctrl-d> -> <dd>` instead of doing `<vaw> -> <dd>` to save one operation (In multiple selection it saves more operations). But I think it may be my personal habit. 😅

**Comment by qws1986** [comment] 2017-04-17 10:04
@xconverge  @chestnutchen  Actually  the last character isn't selected in visual mode.
I think it's a bug cause by vim plugin.

https://github.com/VSCodeVim/Vim/issues/1441

https://github.com/VSCodeVim/Vim/blob/b8fd6a18cbb69cfbc34d47248dae1238dc50a8b1/src/mode/modeHandler.ts#L712

**Comment by lennylxx** [comment] 2017-04-18 07:36
@xconverge @chestnutchen I prefer to not only solve the visual problem, but also make copy-paste shortcuts of Windows work in normal mode.
I tried to turn on/off `vim.overrideCopy`, but it doesn't work neither.

## Reproduce steps
1. Change user settings:
` "vim.useCtrlKeys": false`
2. New a file with below content:
```
foobar
```
2. Press `Esc ` to switch back to Normal mode
3. Double click on the word `foobar`
4. Press `Ctrl+c`
5. Use mouse to move cursor to second line, and press `Ctrl+v`
 
## Expected
Whole word is pasted, i.e.:
```
foobar
foobar
```
## Actual
The word **without** the last character is pasted, i.e.:
```
foobar
fooba
```
## Technical details:
* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: Windows 10 1703 Build 15063.138

**Comment by chestnutchen** [comment] 2017-04-18 08:10
@qws1986 Actually it works fine like this in normal Vim editor because the cursor do not blink and there aren't same keywords highlighting. When you do `yank` or other copy commands it can work unambiguously. But in VSCode, it passes the value of the selection without the character pointed by the cursor to VSCode core . And when you do next command, it operates with this character as it is in the Vim editor. I think that is the main problem in this issue.

**Comment by unnamedcrewman** [comment] 2017-04-21 07:46
I think the biggest problem here is the difference between Vim and VScode selections.  In VSCode Vim, if you are yanking with "y",  the letter under the cursor is included.  However, anything that relies on what  vanilla VSCode considers a text selection will not actually include the letter under the cursor if the selection is made in visual mode in the same way as one does for yanking.

For what it's worth, this means that:

1.  The user has to remember that any selections in normal/visual (block cursor) mode look different depending on whether you are "yanking" (includes the letter under the cursor) or "copying" with ctrl-c or the Windows menu options (does not include the letter under the cursor). I suspect the average user in a Windows environment would assume yanking and copying to be the same thing. Probably many Vim users actually consider them pretty much as synonyms.

2.  Certain extensions might give unexpected results.  A user might be used to making a selection for "yanking" in visual/normal mode by ending with the cursor directly on the last character of the selection. But for an extension that manipulates text selections, the user has to remember to make sure that for any normal/visual mode selection the cursor must be placed one character past the end of the intended selection material to get the expected output.

Obviously, neither of these scenarios is a huge deal, but the second one could introduce problems that are not immediately obvious in casual reading of the output text (dropped punctuation, newlines, etc.).

**Comment by alfonsodev** [comment] 2017-04-22 10:28
There is a flow that is broken, I believe it was working before.  
When you copy and replace by clicking on words.
- Click on word `foo`
- cmd+c
- click on word `bar`
- cmd+v
results on `foor` 
![copy paste](https://media.giphy.com/media/l0Iy0ixhOxrH7uAkU/giphy.gif)

**Comment by johnfn** [comment] 2017-04-22 10:57
Thanks for the write up @unnamedcrewman. I think that provides very clear motivation to fix our dumb selection bug once and for all.

**Comment by qws1986** [comment] 2017-05-10 04:12
it's fixed in v0.7.1.

**Comment by Bittenbydog** [comment] 2017-05-10 04:17
Well, the selection issue is already fixed, but the copy-paste problem is still there.
As described by @lennylxx and @alfonsodev

**Comment by jpoon** [comment] 2017-05-10 04:50
> but the copy-paste problem is still there.

This doesn't repro for me. Following @lennylxx, I see the selection highlight of the last character that everyone is mentioning, but when doing a `ctrl+c` or a `y`, it copies the entire "foobar" word.

**Comment by andycmaj** [comment] 2017-05-12 16:40
But now try double clicking to select another full word, and use `cmd+v` to try to paste the copied word over it.

You'll see it doesn't replace the last character of the selected word.

Notes:
* This repros on osx. Haven't tested on other platforms
* Using `p` works fine. Repro only happens when using system paste command as opposed to vim's Put command

**Comment by donnielrt** [comment] 2017-05-16 21:41
I can confirm that I also see what @andycmaj has reported.

**Comment by jpoon** [comment] 2017-05-19 07:00
Copied from https://github.com/VSCodeVim/Vim/issues/1711 @sebastjaeger

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.7.1
- **OS**: MacOS 10.12.4 / Ubuntu 15.04

**What happened**:

There are multiple surprising effects when selecting e.g. a word in visual mode
- the last character is not highlighted like the rest of the selection
- when copying the word using `y` the entire word is copied and can be retrieved with `p` (as expected)
- the last character is lost when pasting the word via the selection clipboard (`*` buffer in vim, mouse middle click in linux) 
- vscode highlights not only all the other occurrences of the selected word, but everything that matches all but the last letter of the selection

**What did you expect to happen:**

Clearly show that the last character of the selection belongs to the selection. Make sure the last character is copied into the selection clipboard. Highlight other occurrences of the selection correctly.

**Comment by transtone** [comment] 2017-05-31 06:32
cursor 'I' like insert-mode will better than block.

**Comment by Chillee** [comment] 2017-06-24 07:24
Closed through https://github.com/VSCodeVim/Vim/pull/1862

**Closed by Chillee** 2017-06-24 07:24 UTC
Labels: area/selection-off-by-one, kind/bug

**Comment by evgenyneu** [comment] 2021-06-18 08:48
Was the last letter issue fixed? When I select with mouse from the right, it does not copy the last latter for me:

![vim_selection](https://user-images.githubusercontent.com/880411/122534173-9f6e1c80-d065-11eb-8e48-de635d42fcdd.gif)

Vscodevim version: v1.21.3 on Mac. Thanks!
