### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by gmrabbi** [VSCodeVim/Vim#5648] opened 2020-11-13 16:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:424)
	at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
	at new l (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at a (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77602)
	at O.exec (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77647)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.exec (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:214409)
	at async x.execCount (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:40
Duplicate of #5356, if you can tell me on that ticket what you were trying to do when this happened or if you can reproduce, that would be helpful.

**Closed by J-Fields** 2020-12-05 18:40 UTC
