### ISSUE TITLE
Make small movement command not registered to Ctrl+o

### ISSUE THREAD

**Issue by 5argon** [VSCodeVim/Vim#1933] opened 2017-07-18 06:23 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.1
- **VsCodeVim Version**: 0.9.0
- **OS**:  macOS Sierra

**What happened**:

When using movement like j or k, it should not be undoable with Ctrl+o.

When going to definition for example, it can be reverted with Ctrl+o however if I press j or k a bit I need more Ctrl+o to finally revert the go to definition. In the original vim, Ctrl+o is specifically for big movements

**Comment by Chillee** [comment] 2017-07-20 00:27
This is unluckily a limitation of our current jumplist. We rely on the VSCode "jumplist" (navigateback and navigateforward), which doesn't have the same notion as vim of a "jump".

**Comment by wzhliang** [comment] 2017-07-21 05:32
I was going to open a bug exactly like this one. Ctrl-O back to every line I visited is very annoying.

**Comment by Chillee** [comment] 2017-07-21 08:47
It is a somewhat tricky task to keep our own jumplist I think. Cross file jumping is the big concern.

https://github.com/VSCodeVim/Vim/pull/1897 is likely to be where proper jumplist support eventually comes from.

**Comment by jvican** [comment] 2017-07-30 15:40
I indeed think this is a very misleading behaviour, I'd say it's one of the keys I use the most in vim. @Chillee That PR you've linked is awesome. Really looking forward to it. I'll buy you a beer when you land it.

**Comment by jcjolley** [comment] 2017-08-02 19:55
I'll hop on the 'buy a beer' train as well!

**Comment by 5argon** [comment] 2017-08-15 16:29
I will also buy you a beer or coffee if I can!

**Comment by scottopell** [comment] 2018-04-07 18:07
maintainers (@Chillee @jpoon):
Would you accept a PR implementing a separate jumplist to more closely match vim's jumplist behavior?

**Comment by tyru** [comment] 2018-05-04 12:38
This is duplicate with #2461, however, @alex-xnor gave the useful link to implement this.

> Vim does record certain movements within a file as well, but not nearly so many as VSCodeVim erroneously does. The complete list of movements that cause an entry in the jump list consulted by CTRL-O [is available in Vim's help, under jump-motions](https://vimhelp.appspot.com/motion.txt.html#jump-motions).

**Comment by crachmanin** [comment] 2018-05-10 06:49
I mentioned this in #2460, but for some reason this is only an issue for 'j' and 'k', other movements like 'l', 'h', 'w', or 'b' do not affect the jump history.

**Comment by Chillee** [comment] 2018-05-12 16:26
@crachmanin That's interesting. Unluckily, I'm not sure there's any easy way of dealing with that.

When they announced it, I was hoping the stuff on line 72 would ameliorate this issue:
`		if (Math.abs(thisLineNumber - otherLineNumber) < TextEditorState.EDITOR_SELECTION_THRESHOLD) {
`
but it seems like the way they implemented it, that's not possible.

**Comment by killwing** [comment] 2018-07-06 04:04
Any workaround for this issue?

**Comment by doiken** [comment] 2018-08-17 02:07
Thank to @crachmanin, I tried to disable j and k, and up an down.
This works well in my environment as a workaround.

keybindings.json

```
    {
        "key": "j",
        "command": "cursorDown",
        "when": "editorTextFocus && vim.active && vim.mode == 'Normal' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
    {
        "key": "k",
        "command": "cursorUp",
        "when": "editorTextFocus && vim.active && vim.mode == 'Normal'&& !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
    {
        "key": "up",
        "command": "-extension.vim_up",
        "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
    {
        "key": "down",
        "command": "-extension.vim_down",
        "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    }
```

**Comment by axs221** [comment] 2018-08-26 21:33
I am going to play with this one.

I wonder what it would look like if we tracked history mainly from Vim actions + file changes + mouse clicks. The hooks from vscode don't look too helpful; `onDidChangeTextEditorSelection` only tells us "kind" of Keyboard/Mouse/Command. I don't know about other users, but as far as jumps in a file, I'd probably rather have it track just Vim actions rather than track what it is now, which is rarely useful to me.

**Comment by axs221** [comment] 2018-08-27 02:06
I'm working on a potential solution. So far so good. I'm tracking positions for any actions that occur within VSCodeVim, and then I'll look at also tracking some major external events like changing the editor or group. I'll then probably need to add a metadata tag on actions to specify whether they should be included in the jump list or not.

**Comment by axs221** [comment] 2018-09-01 18:03
Progress update: I found that Vim jumps work different than I anticipated. I added unit tests that verify against the behavior I found in vanilla Vim, and I have most cases working. I still have some TODOs like checking that a number prefix for jumping back/forward works.

I anticipate that I'll be ready for PR within a week.

**Comment by axs221** [comment] 2018-09-07 00:54
PR is up that implements our own jump list:

https://github.com/VSCodeVim/Vim/pull/3028

There are a few caveats as mentioned in there, but works well otherwise and I tried to match vanilla Vim as close as possible. Jumps between windows are tracked specially, as provided to us as events from vscode. I didn't add mouse clicks yet; I though I'd keep it simple and see if there are extra events that people want tracked as jumps.

Each key mapping that causes a jump in Vim has a flag in the code to record a jump. The jump list will be shared with any tabs inside the window (stored in global state); each window will have its own jump list.

**Comment by axs221** [comment] 2018-09-10 12:33
#3028 has been reviewed and is ready to merge, which resolves this #1933 as well as #2461. Feel free to let me know your feedback after it is merged. We have it tested pretty thoroughly with vscode, hopefully it plays nicely with your plugins.

**Closed** 2018-09-10 15:48 UTC

**Comment by davidmpc** [comment] 2020-07-27 17:27
It's 2020 and the problem is still there.

**Comment by J-Fields** [comment] 2020-07-27 17:30
@davidmpc Please open a new issue describing what you're experiencing

**Comment by mdentremont** [comment] 2020-12-23 14:33
@davidmpc Do you have EasyMotion enabled? I noticed that the issue goes away when I disable it. https://github.com/VSCodeVim/Vim/issues/5921

**Comment by tothedistance** [comment] 2021-04-26 07:07
as of 2021, the default behavior will not jump jkhl, but it will not jump f12 inside one file. f12 jump between different file is recorded. hope this can be added, though it seems to be a bit trickier, as we need to use f12 to jump to definition a lot.

**Comment by tothedistance** [comment] 2022-01-13 12:44
> @tothedistance
> 
> > **but it will not jump f12 inside one file**.
> 
> If an option for you, try to use vim 'gd' (go to definition) instead of f12. This seems to record jumps within the same file.

too late to know.
