### ISSUE TITLE
Doesn't work with latest insiders version

### ISSUE THREAD

**Issue by JulianCBC** [VSCodeVim/Vim#5786] opened 2020-11-29 23:21 UTC
Issue Type: <b>Bug</b>

The extension doesn't appear to load correctly, preventing you from entering any text in the editors.

Steps to reproduce:

1. Load Visual Studio Code Insiders with vim extension installed
2. Open a file
3. Press the "i" key to enable edit mode
4. Status bar shows "Activating Extensions" for a few seconds
5. Start typing

**Expected result:**

Typed text appears at the cursor

**Actual result:**

No text appears because the extension isn't working

Extension version: 1.17.1
VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:36:22.965Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.82GB free)|
|Process Argv|--crash-reporter-id a916d313-bf8d-4c15-a153-6ae0bffb7a49|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.87GB (7.82GB free)|
|VM|0%|
</details>

**Comment by J-Fields** [comment] 2020-12-02 16:49
Does this still happen after reinstalling the extension?

**Comment by marianozunino** [comment] 2020-12-04 15:43
For me `control+r` and `control+v` is not working. Vscode triggers his on shorcuts (recent proyects and paste in this case)

**Comment by berknam** [comment] 2020-12-04 15:58
Duplicate of #5819

**Closed** 2020-12-04 15:58 UTC
Labels: kind/bug
