### ISSUE TITLE
Failed to handle key=<BS>. Illegal value for `line`

### ISSUE THREAD

**Issue by isangbill** [VSCodeVim/Vim#6180] opened 2021-02-21 02:09 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Illegal value for `line`
    at v._lineAt (/Volumes/macOS - Data/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:1166)
    at Object.lineAt (/Volumes/macOS - Data/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:95)
    at E.exec (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:462099)
    at E.execCount (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355716)
    at F.runAction (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707796)
    at F.handleKeyAsAnAction (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707190)
    at F.handleKeyEvent (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704026)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.promise (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/Users/bill/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
