### ISSUE TITLE
vit then native pasting includes replaced last character

### ISSUE THREAD

**Issue by alnorris** [VSCodeVim/Vim#1022] opened 2016-11-01 10:45 UTC
Find a string with '' quotes and type  vi' inside it , it should select the enclosing string, then using native pasting, it does paste it but also leaves the last character of the replaced string. Visually it seems vi' doesn't seem not colour select the last character.

* VSCode Version: 1.6.1
* VsCodeVim Version: Latest
* OS: El Capitan

**Comment by xconverge** [comment] 2016-11-01 17:58
Can you give a more specific example?

"|test"

You are saying press vi" or vi'?

If you press vi" and y, the paste what do you get? I get test

**Comment by alnorris** [comment] 2016-11-02 09:44
Both, "lodash"  or 'lodash', then going cmd+c will copy only lodas, omitting the last h.

**Comment by xconverge** [comment] 2016-11-03 03:52
@johnfn @rebornix Any ideas about this?

y works, however cmd+c is 1 char short...

**Comment by alnorris** [comment] 2016-11-03 09:53
It also does it for viw and vi(

**Comment by xconverge** [comment] 2016-11-20 05:02
this looks to be a duplicate of #616 just noticed

**Comment by rebornix** [comment] 2016-11-23 22:46
Close as dup as mentioned by @xconverge

**Closed by rebornix** 2016-11-23 22:46 UTC
Labels: duplicate, needs more info
