### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by michaelkruglos** [VSCodeVim/Vim#6124] opened 2021-02-11 12:39 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.18.9<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:548679)    at https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:546656    at Object.next (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:546761)    at https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:545674    at new Promise (<anonymous>)    at r (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:545411)    at e.$executeCommand (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:160:548552)    at e.doInvokeHandler (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:19:773577)    at e.invokeHandler (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:19:773310)    at e.receiveRequest (https://moccasin-roundworm-q3eeg8ua.ws-eu03.gitpod.io/bundle.js:19:772602)```</details>

**Comment by J-Fields** [comment] 2021-02-18 23:23
Duplicate of #5526

**Closed by J-Fields** 2021-02-18 23:23 UTC
