### ISSUE TITLE
Failed to handle key=j. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by fumiya0312** [VSCodeVim/Vim#5421] opened 2020-10-15 05:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
    at h.setLastHistoryEndPosition (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:516515)
    at F.runAction (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:478718)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at F.handleKeyAsAnAction (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/f-sugino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:28
Duplicate of #5209, please post repro steps there if you can.

**Closed by J-Fields** 2020-11-12 23:28 UTC
