### ISSUE TITLE
/ searching uses magic regex by default

### ISSUE THREAD

**Issue by zingdle** [VSCodeVim/Vim#4018] opened 2019-08-29 13:59 UTC
**Describe the bug**
When using / searching, regex is turned on by default.

**To Reproduce**
```
I| 1567086309.602713
I| 1567086309.602773
I| 1567086309.612997
E| 1567086309.612997
```
when searching `/E| `, 5 characters (4 spaces and 1 `E`) are found. 

**Expected behavior**
Only 1 `E| ` is found.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.0
- VSCode version: 1.37.1
- OS: Win10

**Additional context**
Only `VsCodeVim` is enabled. No additional settings.

**Comment by J-Fields** [comment] 2019-08-29 14:57
Isn't this how vim behaves by default?

**Comment by zingdle** [comment] 2019-08-29 15:22
Actually it's not. You need to add `\` to escape, see [The definition of a pattern](http://vimdoc.sourceforge.net/htmldoc/pattern.html#search-pattern).

**Comment by J-Fields** [comment] 2019-08-29 16:02
Isn't this just a difference between vim's and javascript's regex syntaxes?
#3996

**Comment by zingdle** [comment] 2019-08-30 01:12
Yes, it's different from JS's regex syntax. There are 4 kinds of "pattern" after `/`, which are `\v`, `\m` (`magic`), `\M` (`nomagic`) and `\V`. It's `magic` by default.

**Comment by J-Fields** [comment] 2020-11-13 17:39
Closing as duplicate of #3996, since the issue really is that we don't have the concept of "magic" since we currently use JS's regex engine.

**Closed by J-Fields** 2020-11-13 17:39 UTC
Labels: area/search
