### ISSUE TITLE
getLineLength() called with out-of-bounds line 18

### ISSUE THREAD

**Issue by nikhilpatel87** [VSCodeVim/Vim#5570] opened 2020-11-03 23:08 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 18
	at Function.getLineLength (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.isLineEnd (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14231)
	at l.getRightThroughLineBreaks (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11052)
	at Object.t.statusBarCommandText (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31336)
	at Object.updateShowCmd (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
	at F.handleKeyEvent (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/nikhilpatel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:27
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:27 UTC
