### ISSUE TITLE
Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 129

### ISSUE THREAD

**Issue by jieniu** [VSCodeVim/Vim#5634] opened 2020-11-12 09:27 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 129
	at Function.getLineLength (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at /Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88711
	at Array.map (<anonymous>)
	at ne.exec (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88618)
	at ne.execCount (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
	at F.runAction (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
	at F.handleKeyAsAnAction (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/fengyajie/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:37
Duplicate of #5180. If you can reproduce, please post steps there.

**Closed by J-Fields** 2020-11-12 23:37 UTC
