### ISSUE TITLE
Failed to handle key=<down>. Illegal value for `line`

### ISSUE THREAD

**Issue by yuber83** [VSCodeVim/Vim#6305] opened 2021-03-19 19:38 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<down>. Illegal value for `line`
    at g._lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:1166)
    at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:95)
    at x.delete (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:519744)
    at x.run (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:520516)
    at F.executeOperator (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at F.runAction (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
    at F.handleKeyAsAnAction (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/home/yvasquez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:33
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:33 UTC
