### ISSUE TITLE
S deletes the whole line 

### ISSUE THREAD

**Issue by brhsiao** [VSCodeVim/Vim#4168] opened 2019-10-13 17:11 UTC
Vim's <kbd>S</kbd> preserves indentation. Here

```c
int main() {
  printf("%d", 1);
}
```
pressing <kbd>S</kbd> on `printf` clears the line but leaves the indentation of two spaces, putting the cursor on the third column.

VSCodeVim's <kbd>S</kbd> clears the whole line, spaces and all. This makes it much less useful because you then have to recreate the spaces. <kbd>cc</kbd> has the same problem.

I've fixed this temporarily with the setting

```json
{
  "vim.normalModeKeyBindings": [
    {
      "before": ["S"],
      "after": ["^", "c", "$"],
    },
  ]
}
```

but this isn't ideal.

**Comment by J-Fields** [comment] 2019-10-15 05:37
Duplicate of #3653.

**Closed by J-Fields** 2019-10-15 05:37 UTC
