### ISSUE TITLE
Write over virtual filesystem not working

### ISSUE THREAD

**Issue by claytongulick** [VSCodeVim/Vim#2986] opened 2018-08-23 20:58 UTC
**Describe the bug**
Using the new virtual filesystem api, like with ssh fs plugin, :w write doesn't work, it tries to save a local
file.

**To Reproduce**

1. Install ssh fs plugin
2. Edit a remote file
3. Try to save with :w

**Expected behavior**
The file should save the same way it does with CTRL-S.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.0
- VSCode version: 1.25.1
- OS: Win 10

**Comment by jpoon** [comment] 2018-08-25 05:13
Seems related: https://github.com/VSCodeVim/Vim/issues/2956

**Comment by jpoon** [comment] 2018-12-30 07:55
Closing as duplicate of #2956

**Closed by jpoon** 2018-12-30 07:55 UTC
Labels: status/duplicate
