### ISSUE TITLE
Failed to handle key=j. Cannot read property 'searchString' of undefined

### ISSUE THREAD

**Issue by ranjbar2446** [VSCodeVim/Vim#5444] opened 2020-10-18 13:32 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=j. Cannot read property 'searchString' of undefined
    at k.exec (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:436870)
    at k.execCount (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:36957)
    at F.runAction (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
    at F.handleKeyAsAnAction (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/sun/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 21:53
Duplicate of #5351 - if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 21:53 UTC
