### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Rami-Ismael** [VSCodeVim/Vim#6695] opened 2021-06-04 09:15 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at i._applyEdit (c:\Users\ramim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:52424)
    at Object.edit (c:\Users\ramim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:50096)
    at Object.executeTransformations (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\src\transformations\execute.ts:124:29)
    at j.runAction (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\src\mode\modeHandler.ts:728:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\src\mode\modeHandler.ts:653:43)
    at j.async [as handleKeyEvent] (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\src\mode\modeHandler.ts:472:11)
    at Object.promise (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\extensionBase.ts:627:27)
    at Object.runTasks (c:\Users\ramim\.vscode\extensions\vscodevim.vim-1.20.3\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
