### ISSUE TITLE
When I do the mapping, remap "<s-j> 4j", in my vimrc, the mapping is still the default join action in the editor

### ISSUE THREAD

**Issue by jteves** [VSCodeVim/Vim#6059] opened 2021-01-28 16:03 UTC
**Describe the bug**
When I include a couple mappings in my vimrc (ie `<s-j>` and `<s-u>`), it doesn't actually do the remappings in the editor

**To Reproduce**

1.  Enable vimrc
2.  Include the following to configurations in vimrc:
    * `map <s-j> 4j`
    * `nmap <s-u> <c-r>`

**Expected behavior**
1.  Go to editor and type in normal mode `<s-j>` and the action is join
1.  Go to editor and type in normal mode `<s-u>` and it doesn't perform the redo action (`<c-r>`)

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
![image](https://user-images.githubusercontent.com/7359133/106168032-d5187480-615b-11eb-8a95-046a1b7c1e35.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: Windows 10 Enterprise, Version 10.0.19042

**Additional context**

**Comment by sql-koala** [comment] 2021-01-30 19:07
hmm, you can map uppercase letters simply like so:
`nmap U <c-r>`

**Comment by J-Fields** [comment] 2021-02-08 20:58
Duplicate of #6110

**Closed by J-Fields** 2021-02-08 20:58 UTC
