### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by jlassi1** [VSCodeVim/Vim#6503] opened 2021-04-19 22:41 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53072)
    at Object.edit (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50744)
    at Object.executeTransformations (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/src/transformations/execute.ts:124:29)
    at I.runAction (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:726:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:651:43)
    at I.async [as handleKeyEvent] (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:471:11)
    at Object.promise (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/extensionBase.ts:628:27)
    at Object.runTasks (/home/khawla/.vscode/extensions/vscodevim.vim-1.20.0/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-21 19:44
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:44 UTC
Labels: status/duplicate

**Comment by jlassi1** [comment] 2021-04-22 15:16
@J-Fields just uninstall the vim extension "vscodevim" from your vscode and the problem solve
