### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by abutala** [VSCodeVim/Vim#5961] opened 2021-01-04 23:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
	at h.setLastHistoryEndPosition (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:516515)
	at F.runAction (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:478718)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async F.handleKeyAsAnAction (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/abutala/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by YLouWashU** [comment] 2021-01-06 01:35
same issue here. Can we roll back?

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
