### ISSUE TITLE
Selection usage in Visual Mode

### ISSUE THREAD

**Issue by forsigner** [VSCodeVim/Vim#2942] opened 2018-08-07 12:36 UTC
Can not use these command or extentions in Visual Mode: 
- command: `editor.action.smartSelect.grow`
- extention: [expand-region](https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region)
- extention: [very-smart-select](https://marketplace.visualstudio.com/items?itemName=closedcontour.very-smart-select)
- extention: [vscode-expand-selection-to-scope](https://github.com/SuperV1234/vscode-expand-selection-to-scope)

**Comment by J-Fields** [comment] 2019-09-03 19:40
More or less a duplicate of #1806

**Closed by J-Fields** 2019-09-03 19:40 UTC
Labels: area/selection, kind/bug
