### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by rudolpjo** [VSCodeVim/Vim#6927] opened 2021-07-28 20:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at t.ExtHostTextEditor._applyEdit (/private/var/folders/2v/dq_h9wdj0cxbjlcxxrg8h1rh0000gn/T/AppTranslocation/EE4E9464-C156-4F9E-B098-FEFCD26F865F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:666)
    at t.ExtHostTextEditor.edit (/private/var/folders/2v/dq_h9wdj0cxbjlcxxrg8h1rh0000gn/T/AppTranslocation/EE4E9464-C156-4F9E-B098-FEFCD26F865F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:201)
    at Object.executeTransformations (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at j.rerunRecordedState (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:207:12)
    at j.actionToRecord [as runAction] (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /Users/rudolphj/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[913, 62] | [913, 62]]"
]
actionsRunPressedKeys: [
  "<Esc>"
]
actionsRun: [
  "D",
  "b",
  "$",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 913,
      "character": 62
    },
    "text": "go",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 913,
        "character": 60
      },
      {
        "line": 913,
        "character": 64
      }
    ],
    "text": "nogoAimpointAxial",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-28 20:18
Duplicate of #6888

**Closed by J-Fields** 2021-07-28 20:18 UTC
