### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by darrenfu** [VSCodeVim/Vim#6000] opened 2021-01-15 21:53 UTC
**To Reproduce**

I'm working in VSCode to edit remote files with VIM extension installed. This issue has been randomly reproduced from time to time. Once it was reproduced, the whole VIM extension just didn't work any more until I restart the VSCode.

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.goBackHistoryStep (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:205433)
	at je.exec (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:1:98193)
	at je.execCount (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24191)
	at F.runAction (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171589)
	at F.handleKeyAsAnAction (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.promise (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/dofu/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
