### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by reyhansofian** [VSCodeVim/Vim#5633] opened 2020-11-12 05:12 UTC
**To Reproduce**

1. Use the multi-line cursor (alt+click)
2. Delete character using `x`

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:52)
	at t.ExtHostTextEditor.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:598)
	at F.executeCommand (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482834)
	at F.runAction (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475478)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/vicz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:07
I can't reproduce, can you please provide a minimal example?

**Comment by J-Fields** [comment] 2021-03-23 17:06
Closing as duplicate of #5633, which is a repro on most recent release

**Closed by J-Fields** 2021-03-23 17:06 UTC
Labels: kind/bug
