### ISSUE TITLE
getLineLength() called with out-of-bounds line 554

### ISSUE THREAD

**Issue by KingNels24** [VSCodeVim/Vim#5393] opened 2020-10-12 22:09 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 554
    at Function.getLineLength (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.getRight (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10438)
    at F.updateView (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
    at _ (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/Users/tonynelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-13 19:29
Duplicate of #5180, please post repro steps there.

**Closed by J-Fields** 2020-10-13 19:29 UTC
Labels: status/duplicate
