### ISSUE TITLE
I have configured the im-select.exe correctly, but vim still remind me this dialog

### ISSUE THREAD

**Issue by ysl970629** [VSCodeVim/Vim#5210] opened 2020-09-23 00:55 UTC
windows 10
Today I opened my vscode as usual, but suddenly it remind me this. I checked my im-select.exe file, opened it in powershell, and after making sure it is still exists in the correct path and outputs the correct result "1033" in powershell, I haven' t solved the error dialog problem.

![image](https://user-images.githubusercontent.com/39717545/93952014-69239b00-fd7a-11ea-924d-b5bdcf6f230f.png)

**Comment by wangyxuan** [comment] 2020-09-23 01:11
I have the same problem

**Comment by LimbicSys** [comment] 2020-09-23 02:04
I have the same problem. So I switched to version 1.16.0.

**Comment by JW9506** [comment] 2020-09-23 18:54
Turning off `Extensions: Auto Update` in vscode setting is the lesson here.

**Comment by J-Fields** [comment] 2020-09-25 18:30
Duplicate of #5229

**Closed by J-Fields** 2020-09-25 18:30 UTC
