### ISSUE TITLE
Profiling error

### ISSUE THREAD

**Issue by dev-warner** [VSCodeVim/Vim#2241] opened 2017-12-23 14:09 UTC
- Extension Name: vim
- Extension Version: 0.10.6
- OS Version: Darwin x64 16.5.0
- VSCode version: 1.19.0

json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 879,
		"activateCallTime": 31,
		"activateResolvedTime": 10,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by jpoon** [comment] 2017-12-24 04:34
Dupe of https://github.com/VSCodeVim/Vim/issues/2232

**Closed by jpoon** 2017-12-24 04:34 UTC
