### ISSUE TITLE
Backward History Key<C-o, C-t> doesn't work normally

### ISSUE THREAD

**Issue by yongminari** [VSCodeVim/Vim#5840] opened 2020-12-07 09:23 UTC
I worked with C code and back key was something strange. 

1. functionA()
2. jump to functionB from functionA using key `<C-]>`
3. functionB()
4. jump to functionC from functionB using key `<C-]>`
5. functionC()
6. jump to structure type from functionC using key `<C-]>`
7. defined struct in header file.
8. back to functionC using key `<C-o>`
9. jump to defined MACRO_A in header from functionC  using key `<C-]>`
10. back to functionC using key `< C-o>`

then 

If I press the short-cut `<C-o>` again, then I expected to back to functionB. But the cursor went to Macro in header file or sometimes go to struct defined.

And I press the short-cut `<C-o>` again and again and again ..., then I expected to go to functionA, but the cursor go to somewhere I jumped before.

I hope my meaning is delivered well.

**Comment by berknam** [comment] 2020-12-07 18:39
@J-Fields I thought this could be related to #5814, but from what I've checked the behavior described is the same on older versions as well.

Isn't this the same behavior as in normal VIM, though? @yongminari Have you tried running the same steps in VIM? What is the difference?

**Comment by yongminari** [comment] 2020-12-08 02:21
@berknam 

I've tested with Vim. As you mentioned, <C-o> was worked same.

Also I tested <C-t> in VSCode, it was same as <C-o>.
But, in vim, <C-t> worked that I want.

**Comment by J-Fields** [comment] 2020-12-08 04:30
This is the difference between the jump list and tag stack (we support the former, but not the latter). VSCode doesn't use tags (language server integration serves this purpose but much much better), but we could still store the jump locations after each `<C-]>`, which should work basically the same way, I think.

**Comment by J-Fields** [comment] 2020-12-08 04:45
Yeah I'm gonna close this as a duplicate of #2586 (and assign that to myself)

**Closed by J-Fields** 2020-12-08 04:46 UTC
Labels: status/duplicate
