### ISSUE TITLE
Failed to handle key=<BS>. Illegal value for `line`

### ISSUE THREAD

**Issue by El-Moutaouakkil** [VSCodeVim/Vim#5939] opened 2020-12-29 13:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Illegal value for `line`
    at d._lineAt (c:\Users\el moutaouakkil\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
    at Object.lineAt (c:\Users\el moutaouakkil\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
    at _.exec (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:196742)
    at _.execCount (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24652)
    at F.runAction (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171589)
    at F.handleKeyAsAnAction (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170985)
    at F.handleKeyEvent (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167823)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
    at Object.runTasks (c:\Users\el moutaouakkil\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
