### ISSUE TITLE
Not registering key presses

### ISSUE THREAD

**Issue by patrik-cihal** [VSCodeVim/Vim#8614] opened 2023-09-21 18:10 UTC
**Describe the bug**
When using the VIM plugin and trying to type fast, it is not registering many of the keys I press, when I disable the plugin, everything is back to normal.

**To Reproduce**
Install 1.26.0 version of VIM plugin on vscode and put use this configuration: 
`{
    "editor.suggestSelection": "first",
    "keyboard.dispatch": "keyCode",
    "vim.useCtrlKeys": false,
    "editor.fontSize": 18,
    "editor.acceptSuggestionOnCommitCharacter": false,
    "redhat.telemetry.enabled": false,
    "git.enableSmartCommit": true,
    "editor.inlineSuggest.enabled": true,
    "vim.normalModeKeyBindings": [
        {
            "before": [
                "U"
            ],
            "after": ["<C-r>"]  
        },
    ],
    "github.copilot.enable": {
        "*": false,
        "plaintext": false,
        "markdown": false,
        "scminput": false,
        "yaml": false,
        "rust": false,
        "python": false,
        "cpp": false,
        "haskell": false
    },
    "github.copilot.advanced": {
    
    },
    "editor.unicodeHighlight.invisibleCharacters": false,
    "rust-analyzer.cargo.target": null,
    "editor.minimap.renderCharacters": false,
    "haskell.manageHLS": "GHCup",
    "[rust]": {
        "editor.defaultFormatter": "rust-lang.rust-analyzer",
    },
    "[cpp]": {
        "editor.wordBasedSuggestions": false,
        "editor.suggest.insertMode": "replace",
        "editor.semanticHighlighting.enabled": true
    },
    "C_Cpp.autocomplete": "disabled",
    "cmake.configureOnOpen": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true,
        "**/*.olean": true
    },
    "workbench.colorTheme": "Ambiance [beta]"
}`

Now try typing fast.

**Expected behavior**
I want it to register all the keys I press even when typing fast.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1.82.2
- OS: Ubuntu

**Additional context**

**Comment by kfriend** [comment] 2023-09-21 19:57
duplicate of #8603?

**Closed** 2023-09-21 20:10 UTC
