### ISSUE TITLE
getLineLength() called with out-of-bounds line 36

### ISSUE THREAD

**Issue by huangqingxin** [VSCodeVim/Vim#5410] opened 2020-10-14 06:19 UTC
**To Reproduce**

*Can not reproduce*

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 36
    at Function.getLineLength (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.getRight (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10500)
    at F.updateView (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:491507)
    at _ (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:234397)
    at Object.runTasks (c:\Users\hqx\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-15 18:35
Duplicate of #5180

**Closed by J-Fields** 2020-10-15 18:35 UTC
Labels: status/duplicate
