### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by Seokeey** [VSCodeVim/Vim#5372] opened 2020-10-10 06:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:364)
	at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:507:436)
	at new l (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at h.updateAndReturnMarks (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
	at h.finishCurrentStep (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
	at F.runAction (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/seokeey/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 01:57
Duplicate of #5226, please post repro steps there.

**Closed by J-Fields** 2020-10-14 01:57 UTC
