### ISSUE TITLE
Enter visual mode whenever a selection is made

### ISSUE THREAD

**Issue by henrikrudstrom** [VSCodeVim/Vim#4034] opened 2019-09-03 19:24 UTC
**Is your feature request related to a problem? Please describe.**
sometimes i make selections using the keyboard that are not the result of using any vim command (for example arrow keys + shift, smartSelect.grow). when i make these selections vscodevim does not enter visual mode like it does when you select using the mouse. This is annoying because now i cannot use 'y' to yank or 'd' to delete. 

**Describe the solution you'd like**
Whenever there is a selection in the editor vim should be in visual mode.
Not sure what would be the best behaviour when a selection is made in insert mode, but to me it still seems most consistent to switch to visual mode as well.

**Comment by J-Fields** [comment] 2019-09-03 19:38
Duplicate of #1806

**Closed by J-Fields** 2019-09-03 19:38 UTC
Labels: area/selection, kind/bug, status/duplicate
