### ISSUE TITLE
Unable to remap vv to V in normal mode

### ISSUE THREAD

**Issue by hatelove85911** [VSCodeVim/Vim#3388] opened 2019-01-18 06:58 UTC
I put following in "vim.normalModeKeyBindingsNonRecursive", it doesn't work:
```
{
        "before": ["v", "v"],
        "after": ["V"]
}
```

vscode: 1.30.2
vscodevim: 1.0.2

**Comment by jpoon** [comment] 2019-01-31 01:15
Underlying reason is due to https://github.com/VSCodeVim/Vim/issues/1821#issuecomment-458436120. As the root cause is the same, closing this as a dupe of #1821.

**Closed by jpoon** 2019-01-31 01:15 UTC
