### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by mohamedelmririeg** [VSCodeVim/Vim#6284] opened 2021-03-16 12:55 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
    at Object.k [as illegalArgument] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)
    at new m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:12337)
    at new m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:11705)
    at a (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
    at F.exec (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at F.runAction (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708017)
    at F.rerunRecordedState (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:714422)
    at y.execute (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:783471)
    at F.runAction (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707854)
    at F.handleKeyAsAnAction (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
    at Object.runTasks (/Users/mohamedalmaririg/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:02
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:02 UTC
Labels: status/duplicate
