### ISSUE TITLE
Failed to handle key=<right>. getLineLength() called with out-of-bounds line 43

### ISSUE THREAD

**Issue by xoiopure** [VSCodeVim/Vim#5283] opened 2020-09-28 18:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<right>. getLineLength() called with out-of-bounds line 43
	at Function.getLineLength (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at ne.execAction (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:196066)
	at ne.createMovementResult (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at ne.execActionWithCount (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/xtrapure/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 18:16
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 18:16 UTC
