### ISSUE TITLE
Failed to handle key=<up>. getLineLength() called with out-of-bounds line 90

### ISSUE THREAD

**Issue by Ahsan40** [VSCodeVim/Vim#5551] opened 2020-11-01 10:00 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<up>. getLineLength() called with out-of-bounds line 90
	at Function.getLineLength (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.getUpWithDesiredColumn (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11622)
	at V.execAction (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:191010)
	at V.createMovementResult (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:158252)
	at V.execActionWithCount (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:157909)
	at F.executeMovement (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:479443)
	at F.runAction (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475347)
	at F.handleKeyAsAnAction (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
	at F.handleKeyEvent (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\Ahsan\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:28
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:28 UTC
