### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by dpereaepayco** [VSCodeVim/Vim#5837] opened 2020-12-07 00:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
	at Object.promise (/home/epayco/.vscode/extensions/vscodevim.vim-1.18.0/out/extension.js:9:229185)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/home/epayco/.vscode/extensions/vscodevim.vim-1.18.0/out/extension.js:11:285853)
```

</details>

**Comment by J-Fields** [comment] 2020-12-07 01:11
Duplicate of #5306. What were you trying to do when this happened?

**Closed by J-Fields** 2020-12-07 01:11 UTC
Labels: status/duplicate

**Comment by berknam** [comment] 2020-12-07 16:07
@dpereaepayco Where you trying to run the "Vim: Remap..." command from command palette?
