### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by vimniky** [VSCodeVim/Vim#5364] opened 2020-10-09 14:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
    at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
    at new l (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
    at h.updateAndReturnMarks (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
    at h.finishCurrentStep (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
    at F.runAction (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/xxx/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 01:57
Duplicate of #5226, please post repro steps there.

**Closed by J-Fields** 2020-10-14 01:57 UTC
