### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by freedxmgxd** [VSCodeVim/Vim#3702] opened 2019-04-24 12:48 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Linux x64 5.0.7-200.fc29.x86_64`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/davinci/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-04-24 19:37
1. you didn't attach a cpuprofile
2. this is a dupe of https://github.com/VSCodeVim/Vim/issues/3362

**Closed by jpoon** 2019-04-24 19:37 UTC
