### ISSUE TITLE
Paste (single cursor) after multicursor yank is broken. Error: Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by sql-koala** [VSCodeVim/Vim#5460] opened 2020-10-20 19:07 UTC
**Describe the bug**
Ok, today I hit this bug, too. So I could get to the bottom of it.

**To Reproduce**
1.  create multi cursor
2.  yank (either from visual mode or with a textobject).
3.  remove multi cursor with Esc
4.  paste

This will result in the above error.

**Expected behavior**
D'oh. ;-)

**Additional context**
The problem is that there is no handling for this situation in the code ( checking if register.text is an array or not). Pasting in insert mode (C-r") does this, so it is easy to adapt and fix the bug. I have update one of my PR.

**Comment by J-Fields** [comment] 2020-11-12 23:14
Thanks @sql-koala, I'll try to get your PR merged today. Marking as duplicate of #5239, which I think has the best discussion.

**Closed by J-Fields** 2020-11-12 23:14 UTC
Labels: status/duplicate
