### ISSUE TITLE
Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by YLouWashU** [VSCodeVim/Vim#5965] opened 2021-01-06 01:35 UTC
**To Reproduce**

1.  Just type any vim command, like `:w enter`, or `esc` 

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.setLastHistoryEndPosition (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:207915)
	at F.runAction (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:174898)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async F.handleKeyAsAnAction (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/home/louy/.vscode-fb/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by oyvindkinsey** [comment] 2021-01-06 18:08
Seeing the same pretty consistently

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
