### ISSUE TITLE
:w and :wa don't work properly with SSHFS and LiveShare guest

### ISSUE THREAD

**Issue by wilbur4321** [VSCodeVim/Vim#3304] opened 2018-12-29 20:41 UTC
**Describe the bug**
:w produces an "ENOENT: no such file or directory, access C:\..." when you are saving a file opened through the SSHFS extension.  :wa works with this extension.  Ctrl-S to save works as well.

With VS LiveShare (as a guest), both show success, but they appear to just write to the local file, and not save on the server.  Again, Ctrl-S works properly.

**To Reproduce**

Add the "SSH FS" extension from https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs.  Configure a remote connection and add it to your workspace.  Open a file within, and observe the above behavior when using :w.

Configure LiveShare.  Share your session (the system doing the sharing doesn't even need VSCodeVim).  Connect to LiveShare from a VSCode with VSCodeVim (aka, client).  Open the same file on both, make a change in the client, use :w to save, and observe that the other system shows the file as not having been written.  Now, use Ctrl-S to save, and observe that the other system shows the file as having been written.

**Expected behavior**
:w should write the file the same as Ctrl-S.  :wa should do the same as a save-all.

**Environment (please complete the following information):**
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.30.1`

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 188,
		"activateCallTime": 0,
		"activateResolvedTime": 998,
		"activationEvent": "*"
	}
}
```

**Comment by jpoon** [comment] 2018-12-30 07:56
Closing as duplicate of #2956

**Closed by jpoon** 2018-12-30 07:56 UTC

**Comment by wilbur4321** [comment] 2018-12-30 22:07
Sorry about the duplicate, and thanks for the fix!  I greatly appreciate it!! 👍
