### ISSUE TITLE
Display for using registry command in visual mode got cutoff before the command finish

### ISSUE THREAD

**Issue by Multirious** [VSCodeVim/Vim#7621] opened 2022-04-10 06:06 UTC
**Describe the bug**
While in visual mode, typing registry command like `"a` will *empty* or *cutoff* (I'm not sure what is the term here) the display before next command is present like `y`.

**To Reproduce**
1. Go visual mode.
2. Type `"{any registry}` then see the display got cutoff.
3. Then type some registry command and the command will works just fine.

**Expected behavior**
Should display `"{any registry}` and the display will cutoff later after typing some command, like in normal mode.

**Screenshots**
![Code_C5mYkEAAG8](https://user-images.githubusercontent.com/77918086/162604612-0e8de9f3-7ed9-4dd4-b174-ebd6cf3521ae.gif)
`"ayy"ap` In normal mode
`^v$"byj"bP` In visual mode

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.22.2
- VSCode version: 1.66.1
- OS: Window 10

**Additional context**
I'm not sure if this is a bug but it has been bugging me these 3 days as a newbie.

**Comment by J-Fields** [comment] 2022-04-10 16:57
Duplicate of #6424

**Closed by J-Fields** 2022-04-10 16:57 UTC
