### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by SaurabhKumarVerma** [VSCodeVim/Vim#5356] opened 2020-10-08 11:28 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/snap/code/46/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/snap/code/46/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:424)
	at new b (/snap/code/46/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
	at new l (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at a (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77602)
	at O.exec (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:77647)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.exec (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:214409)
	at async x.execCount (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/saurabh/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: kind/bug, status/duplicate
