### ISSUE TITLE
Word seperate doesn't works well

### ISSUE THREAD

**Issue by yifeidai** [VSCodeVim/Vim#3665] opened 2019-04-08 06:27 UTC
**Describe the bug**
The word-seperate doesn't work well. For example, "a.b.c" is regarded as a word but not three words. In function "hellowWorld(param1, param2)", "hellowWorld(param1" is regarded as a word. It works well a few days ago, but it works wrong now. I don't change any configuration these days. So I can't use keys like "w", "e", "b", "*" properly.
It is now proved that **in old vim version: "v1.2.0"** it works well.

**To Reproduce**
Here is my vim config in vscode.
```
    "vim.disableExtension": false,
    "vim.easymotion": true,
    "vim.sneak": true,
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.hlsearch": true,
    "vim.leader": "<space>",
    "vim.handleKeys": {
      "<C-a>": false,
      "<C-f>": false,
      "<C-c>": false,
      "<C-v>": false,
      "<C-h>": false,
      "<C-shift-l>": false,
      "<C-alt-up>": false,
      "<C-alt-down>": false,
      "<C-[>": false,
      "<C-]>": false,
      "<C-w>": false,
      "<C-x>": false,
    },
```
And here is word seperate config.
```
    "editor.wordSeparators": "`~!@%^&*()=+[{]}\\|;:'\",.<>-/?",
```

The vscode's word seperate works well. It means that if I use Ctrl+arrow, "a.b.c" isn't regarded as a whole word.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.3.0
- VSCode version: 1.32.3
- OS: Windows_NT x64 10.0.17134

**Comment by ajalab** [comment] 2019-04-08 12:11
The recent change in terms of word separation is responsible for me.
I pasted your configuration script to my `settings.json` and tried it, but actually the problem was not reproduced on my Windows machine.
Would you please show the whole text which produces the problem?

Environment:

- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

I also tried it on VsCodeVim version `1.3.0`.

**Comment by hugoj-goncalves** [comment] 2019-04-08 23:08
may this be related with this? Working with diacritics is really annoying atm...
![issue-2019-04-08 20-04](https://user-images.githubusercontent.com/10927715/55762584-d7b35280-5a39-11e9-93c1-baec8a0f66b0.gif)

**Comment by ajalab** [comment] 2019-04-09 00:02
@hugoj-goncalves Thanks for reporting the issue. I didn't notice that... [src/common/motion/position.ts](https://github.com/VSCodeVim/Vim/blob/316594b108630ff95a6e65599e5b5dada10c9693/src/common/motion/position.ts#L898) currently recognizes a sequence of ASCII characters (except for keywords) and that of diacritics as individual words. They should belong to the same `CharKind`.

**Comment by jpoon** [comment] 2019-04-17 16:39
Resolved with https://github.com/VSCodeVim/Vim/pull/3667 thanks to @ajalab

**Closed by jpoon** 2019-04-17 16:39 UTC
Labels: kind/bug
