### ISSUE TITLE
Failed to handle key=<C-c>. TextEditor(vs.editor.ICodeEditor:1,$model12) has been disposed

### ISSUE THREAD

**Issue by srahkmli** [VSCodeVim/Vim#6113] opened 2021-02-09 00:31 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model12) has been disposed
    at Object.c [as disposed] (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5:1581)
    at Qo.$tryApplyEdits (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1980:25043)
    at h._doInvokeHandler (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:9678)
    at h._invokeHandler (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:9370)
    at h._receiveRequest (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:8040)
    at h._receiveOneMessage (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:6842)
    at file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:4970
    at u.fire (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at o.fire (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21379)
    at file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18273
    at u.fire (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at Socket.I (file:///C:/Users/srahk/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2653:112473)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

</details>

**Comment by J-Fields** [comment] 2021-02-19 01:49
Duplicate of #5650

**Closed by J-Fields** 2021-02-19 01:49 UTC
