### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by VimiummuimiV** [VSCodeVim/Vim#5698] opened 2020-11-19 03:00 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (c:\Users\Luzer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
    at new _ (c:\Users\Luzer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:513:364)
    at new _ (c:\Users\Luzer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:511:436)
    at new l (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9237)
    at h.updateAndReturnMarks (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:510467)
    at h.finishCurrentStep (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:513988)
    at F.runAction (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:477890)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\Luzer\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-23 21:18
Duplicate of #5411. If you can repro, please post steps there.

**Closed by J-Fields** 2020-11-23 21:18 UTC
