### ISSUE TITLE
Issue with Korean characters when pressing spacebar in version 1.26.0

### ISSUE THREAD

**Issue by ByeongUkChoi** [VSCodeVim/Vim#8635] opened 2023-09-30 02:44 UTC
**Describe the bug**
When typing in Korean in version 1.26.0 of the VSCode Vim plugin, pressing the spacebar causes unexpected changes to the typed characters.

**To Reproduce**

1. Install VSCode Vim plugin version 1.26.0.
2. Switch your input method to Korean.
3. Start typing Korean characters in any editable area.
4. Press the spacebar.
5. Observe the unexpected changes to the typed characters.

**Expected behavior**
Upon pressing the spacebar, the typed Korean characters should remain unchanged and a space should be inserted.

**Screenshots**

https://github.com/VSCodeVim/Vim/assets/43606066/30605d24-bc93-4b5f-baa1-ef55d3ef1570

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1.82.2 (Universal)
- OS: Mac OS 13.5.2 (ventura)

**Additional context**
This issue is specifically related to the Korean input method and the spacebar behavior in the mentioned version. This does not seem to occur in previous versions.

**Comment by Zeta611** [comment] 2023-09-30 09:26
This is a duplicate of #8570.

**Closed** 2023-09-30 15:02 UTC
