### ISSUE TITLE
jk doesn't respect tab size

### ISSUE THREAD

**Issue by falsandtru** [VSCodeVim/Vim#3796] opened 2019-05-27 03:02 UTC
**Describe the bug**

**To Reproduce**
```go
func f() {
	return
}
```

1.  Put cursor on `r`.
2.  Type `k`.
3.  Cursor moves onto `u`.

**Expected behavior**
Cursor moves onto `n`.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.8.1
- VSCode version:1.34.0
- OS:Ubuntu 18.04

**Additional context**
This is a problem especially with go lang because go formatter replaces spaces with tabs.

**Comment by ctidd** [comment] 2019-07-05 04:33
For the maintainers (if you prefer to dedupe issues) the following are related: #2458, #2913

This has been reproduced on Linux, MacOS, and Windows.

**Comment by J-Fields** [comment] 2019-09-27 01:00
Closing in favor of #2458

**Closed by J-Fields** 2019-09-27 01:00 UTC
Labels: area/motion, good first issue, help wanted, kind/bug
