### ISSUE TITLE
getLineLength() called with out-of-bounds line 15

### ISSUE THREAD

**Issue by Shubham25-cmd** [VSCodeVim/Vim#5475] opened 2020-10-23 02:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 15
    at Function.getLineLength (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getUpWithDesiredColumn (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
    at l.getLeftThroughLineBreaks (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
    at Object.t.statusBarCommandText (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31413)
    at Object.updateShowCmd (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
    at F.handleKeyEvent (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/shubhammishra/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:58
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:58 UTC
