### ISSUE TITLE
cursor movement in insert mode broken

### ISSUE THREAD

**Issue by rajinder-yadav** [VSCodeVim/Vim#926] opened 2016-10-16 05:22 UTC
When in insert mode the cursor movement using cursor key is broken, cursor jumps back several characters.
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
In an html file type:
```
{{title}}
```

from the same line, press the home key to bring cursor, then end key, then left arrow keys 

some occurs for line like:

```
<app-simple-form></app-simple-form>
```

from same line press end, then left arrow key several time, then end, left arrow keys and you will see jerky movements. same for home and right key combinations.

### What did you expect to happen?
cursor should only move a single character left

### What happened instead?
jump several characters back

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.3.7
* OS: Linux

**Comment by rebornix** [comment] 2016-10-16 05:30
@rajinder-yadav thanks for reporting this issue. It's duplicate of #924 , let's track it there.

**Closed by rebornix** 2016-10-16 05:30 UTC
