### ISSUE TITLE
j/k command considers tab as one char in navigation?

### ISSUE THREAD

**Issue by ThomsonTan** [VSCodeVim/Vim#6920] opened 2021-07-27 23:14 UTC
**Describe the bug**
For source files contain tab, `j` or `k` command seems considering it as a single space which is weird.

For below example with curcur on `n` in `func`, press `n` to move to the next line would move the cursor to `m` in `fmt`. Moving to the first tab(`\t`) which is what gvim does could make more sense.

```go
func main() {
	fmt.Println("hello world")
}
```

**To Reproduce**

See above descriptions.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.5
- VSCode version: 1.58.2
- OS: Windows 10 19043

**Additional context**

**Comment by Ace-tyl** [comment] 2021-08-02 03:47
I have the same problem.

**Comment by w-cantin** [comment] 2021-08-03 02:56
Hello @ThomsonTan. I have tried it with configured tabs instead of spaces in VSCode and I can reproduce your issue. If possible I would suggest to configure tabs as spaces in VSCode and it would do the trick. If this is not possible then I can't really help you.

### To any maintainer of this project:
The issue seems to be running pretty deep and might require some serious code refactoring as it has to do with how every Positions are handled and particularly how Position.with() is written by Microsoft. It just naively handles "\t" as a single character. The class [CursorColumns](https://github.com/microsoft/vscode/blob/9539f015b18dc2103e41b75d6c20f02c8c9d77ff/src/vs/editor/common/controller/cursorCommon.ts#L429) inside VSCode's source code is directly related to this problem. They solve it by differentiating between "VisibleColumns" and regular column (what VSCodeVim is currently using).

**Comment by ThomsonTan** [comment] 2021-08-03 03:56
@w-cantin thanks. How could I configure tabs as space? I've already have below config in my settings.

```json
    "editor.tabSize": 4,
```

**Comment by w-cantin** [comment] 2021-08-03 13:55
@ThomsonTan You can also add 

`    "editor.insertSpaces": true, `

in your settings.json. A way to check what settings VSCode is currently using for the current file is at the bottom right. If it says spaces instead of tabs you should be good. If not then you can simply click on it and a menu should pop up

![image](https://user-images.githubusercontent.com/43618947/128027492-c837ae06-d11b-44f7-acdd-2211cfdf1fe4.png)

**Comment by J-Fields** [comment] 2021-08-04 15:58
Duplicate of #2458

**Closed by J-Fields** 2021-08-04 15:58 UTC
