### ISSUE TITLE
Visual Mode + 'S' Not Working

### ISSUE THREAD

**Issue by DanDPanda** [VSCodeVim/Vim#4072] opened 2019-09-13 14:39 UTC
**Describe the bug**
When I grab multiple lines of text in visual mode and click `S`, it is expected that it deletes all lines that are selected and puts me into insert mode. But what is happening instead is that it puts me into insert mode and allows me to insert one character at the start and beginning of the selection.

**To Reproduce**

1.  Open the file and focus to some text.
2. Click `v` to enter visual mode.
3. Click `jj` to select two lines down.
4. Click `S` to attempt to delete the selected lines.
5. Click `e` to see that an 'e' has been inserted into the location where you started and ended the selection.

**Expected behavior**
When I grab multiple lines of text in visual mode and click `S`, it is expected that it deletes all lines that are selected and puts me into insert mode.

**Screenshots**
![Select](https://user-images.githubusercontent.com/15399401/64870675-59229880-d609-11e9-880b-1ce99f62b35c.gif)

**Environment (please complete the following information):**

Extension (VsCodeVim) version: 1.10.2
VSCode version: 1.38.1
OS: macOS Mojave 10.14.6

**Additional context**
I'm no VIM expert, but it seems like `S` isn't the only key to have issues in visual mode. Selecting in visual mode and clicking `I` or `A` also seem to reproduce unintentional behavior.

**Comment by DanDPanda** [comment] 2019-09-16 15:13
So just a quick question, was there ever a version in which this command worked as intended? I swear I had no problem with this plugin back then, but ever since I tried it out again recently, it has been the only thing that has been holding me back from using the plugin.

**Comment by J-Fields** [comment] 2019-09-16 16:57
No, as far as I can tell, it's never been supported in visual mode. I'll get to this when I have the chance; in the meantime, you can use `c` in visual-line mode to get the same effect, though I know changing muscle is stubborn.

**Comment by 1ntEgr8** [comment] 2019-10-11 13:55
@J-Fields I want to give this a try

**Comment by J-Fields** [comment] 2019-10-11 14:15
@1ntEgr8 Awesome, thanks! I'll assign the issue to you.

**Comment by micklett** [comment] 2019-11-24 17:33
Hi, myself and @bdomanski would like to take a look at this one as well as we are close to finishing up our first PR.

**Comment by J-Fields** [comment] 2019-11-24 21:05
Sweet, thanks @micklett!

**Comment by anuragsati** [comment] 2020-08-10 11:11
Hello @J-Fields i would love to work on this issue.

**Comment by J-Fields** [comment] 2020-08-13 15:28
Duplicate of #4812

This was fixed by https://github.com/VSCodeVim/Vim/commit/d43a6e1ef49da86a4e6978760299f5196d137431

**Closed by J-Fields** 2020-08-13 15:28 UTC
Labels: good first issue, kind/bug, status/duplicate

**Comment by loganbnielsen** [comment] 2023-03-17 05:01
Hi, this behavior appears to conflict with what's expected with vim.surround plugin which comes with the extension.

With vim.surround the expected behavior in visual mode is this:

`here is some text`

Image in that I'm in visual mode and have `is some` highlighted.

Pressing S)

should convert this to

`here (is some) text`

Should I open another ticket for this?
