### ISSUE TITLE
Failed to handle key `o`: No cursor index - this should never ever happen!

### ISSUE THREAD

**Issue by acrobaticcow** [VSCodeVim/Vim#7944] opened 2022-09-06 14:48 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.23.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key `o`: No cursor index - this should never ever happen!
    at doTextEditorEdit (c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\transformations\execute.ts:77:15)
    at c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\transformations\execute.ts:113:13
    at Object.edit (c:\Users\singe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:54216)
    at executeTransformations (c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\transformations\execute.ts:111:31)
    at N.runAction (c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\mode\modeHandler.ts:744:13)
    at process.actionToRecord (node:internal/process/task_queues:96:5)
    at N.handledAsAction [as handleKeyAsAnAction] (c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\mode\modeHandler.ts:689:43)
    at N.text [as handleKeyEvent] (c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\src\mode\modeHandler.ts:506:11)
    at c:\Users\singe\.vscode\extensions\vscodevim.vim-1.23.2\extensionBase.ts:359:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[1295, 16] | [1295, 16]]"
]
actionsRunPressedKeys: [
  "v",
  "i",
  "t",
  "<left>",
  "<left>",
  "<left>",
  "<right>",
  "<left>",
  "o",
  "u",
  "<Esc>"
]
actionsRun: [
  "de",
  "Rt",
  "ne",
  "ne",
  "ne",
  "ie",
  "ne",
  "Ee"
]
textTransformations: [
  {
    "type": "moveCursor",
    "diff": {
      "type": 1,
      "line": 0,
      "character": 26
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by acrobaticcow** [comment] 2022-09-06 14:50
really it not  a big problem, I didn't mind it at all. Just think it would be better that you guys know. Love your work btw

**Comment by J-Fields** [comment] 2022-10-31 02:23
Treating this as duplicate of #7991, since that has more detail. It'll be fixed in the next release.

**Closed by J-Fields** 2022-10-31 02:23 UTC
