### ISSUE TITLE
dot command does not work properly when inserting <Tab>/"/'/(/{/[

### ISSUE THREAD

**Issue by o-lim** [VSCodeVim/Vim#1674] opened 2017-05-08 16:55 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.x
- **VsCodeVim Version**: 0.7.0
- **OS**: Linux

Failure mode for tabs as spaces with the dot command:

**What happened**:
1. Press `i` to enter insert mode
2. Press `<Tab>` to insert tabs as spaces
3. Press `<ESC>` to exit insert mode
4. Press `.` to repeat the last command

**What did you expect to happen**: 
* Insert another `<Tab>` (as spaces)

**What happened instead**: 
* Cursor moves left one character and nothing was inserted

Failure mode for inserting `"` (double quote) with the dot command (the same behavior happens when inserting any of the following chars `(`, `{`, `'`, `[`):

**What happened**:
1. Go to the first line of an indented paragraph
2. Press `i` to enter insert mode
3. Press `"` (double quote), to insert a double quote
4. Press `<ESC>` to exit insert mode
5. Go down one line by pressing `j`
6. Press `.` to repeat the last command
7. Go down one line by pressing `j`
8. Press `.` to repeat the last command yet again

**What did you expect to happen**: 
* Insert a `"` (double quote) to the beginning of the next line

**What happened instead**: 
* Cursor moves left one character each time the "dot" command is used
  * This causes the insertion of the next `"` (double quote) to be in the wrong place

**Comment by Chillee** [comment] 2017-05-08 16:57
The first part is a duplicate of #612 , which is also fixed by PR #1663 . I believe the cause of the second part is also fixed by PR #1663, although I haven't tested it yet.

**Comment by Chillee** [comment] 2017-05-08 17:12
This is the part of code that's causing issues: https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts

It's not always true that vscode will insert a paired character. It depends on context.

**Closed** 2017-05-21 03:01 UTC
Labels: area/content-change, kind/bug
