### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by halikov** [VSCodeVim/Vim#3655] opened 2019-04-05 10:18 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.3.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mika_\vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JerareYoshi** [comment] 2019-04-07 21:41
Probably the same issue:

- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.3.0`
- OS Version: `Windows_NT x64 10.0.1
- VSCode version: `1.33.0`
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3052062/vscodevim.vim-unresponsive.cpuprofile.txt)
7763`

**Comment by jpoon** [comment] 2019-04-08 05:31
Dupe of #3362 and there is also no cpuprofile attached...

**Closed by jpoon** 2019-04-08 05:31 UTC
