### ISSUE TITLE
cit for embedded html tag

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#1300] opened 2017-02-15 01:24 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
    <div>
      |
      <div></div>
    </div>
```

`cit`

### What did you expect to happen?

```
    <div>|</div>
```
  

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: OS X 10.11.6

**Comment by xconverge** [comment] 2017-02-15 04:55
think this is a dupe of #1108

**Comment by xlaech** [comment] 2017-02-15 08:21
There are still some things to improve
e.g.:
- The search regex for the tags
- an option for including the tag or not (@xconverge: where is this used?)

I also found another bug which is not caused by the it movement but by the Changecommand "c"
When the end of the selection (cit or visual mode) is at the beginning of line, it will delete the first character of this line.
=> I open a new Issue and fix it in another branch

**Comment by johnfn** [comment] 2017-05-02 08:49
This has been fixed and will be out in the next version of VSCodeVim. :)

**Comment by johnfn** [comment] 2017-05-02 08:58
_Now_ this has been fixed and will be released in the next version of VSCodeVim.

**Closed** 2017-05-02 08:58 UTC
