### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by FarhanSyedain** [VSCodeVim/Vim#6031] opened 2021-01-25 14:41 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
	at d._lineAt (c:\Users\Farhan Syedain\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
	at Object.lineAt (c:\Users\Farhan Syedain\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
	at B.exec (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:201294)
	at B.execCount (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24652)
	at x.exec (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:195125)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.execCount (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24641)
	at async F.runAction (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171581)
	at async F.handleKeyAsAnAction (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
	at async F.handleKeyEvent (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
	at async Object.promise (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
	at async Object.runTasks (c:\Users\Farhan Syedain\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
