### ISSUE TITLE
Repeat command (.) stops working once the buffer is saved

### ISSUE THREAD

**Issue by rubiot** [VSCodeVim/Vim#7378] opened 2022-01-06 15:03 UTC
### Repeat command (.) stops working once the buffer is saved
The repeat command (.) works fine as long as the user doesn't save the buffer. This is not the behavior in vim, in which the repeat command continues to work regadless of the state of the buffer.

**To Reproduce**

1.  Enter in edit mode (i) and make any edit.
2.  Exit edit mode (Escape).
3.  Press the . key to repeat the edit. It works fine.
4.  Save the buffer (:w or Ctrl+S or something).
5.  Press the . key to repeat the last edit. It won't anymore.

**Expected behavior**
In vim saving the buffer doesn't reset the repeat command, it should continue to work.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.10
- VSCode version: 1.63.2
- OS: Windows 10

**Comment by J-Fields** [comment] 2022-01-26 17:15
Duplicate of #6829

**Closed by J-Fields** 2022-01-26 17:15 UTC
