### ISSUE TITLE
Activating extension 'vscodevim.vim' failed: process is not defined.

### ISSUE THREAD

**Issue by SaahilClaypool** [VSCodeVim/Vim#7143] opened 2021-10-10 00:45 UTC
**Describe the bug**
When installed on `github.dev`, the extension fails to load. 
**To Reproduce**
- Go to any repository on github
- Press `.` to open github.dev
- install the extension (currently v`1.21.8`)
- open the browser console or extension log, or run the command "toggle vim mode"
- open the browser console and see the error:
    > Activating extension 'vscodevim.vim' failed: process is not defined.

**Expected behavior**
Extension works

**Environment (please complete the following information):**

github.dev

**Additional context**

Downgrading to v`1.21.7` fixes the issue

**Comment by J-Fields** [comment] 2021-10-14 08:24
Duplicate of #6826

**Closed as completed by J-Fields** 2021-10-14 08:24 UTC
Labels: kind/bug, status/duplicate, system/web
