### ISSUE TITLE
Toggling Vim Mode using keybindings is broken

### ISSUE THREAD

**Issue by dpacmittal** [VSCodeVim/Vim#2381] opened 2018-02-13 16:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**What happened**: I setup keybinding to toggle vim mode. When I press the shortcut, it turns off vim mode just fine, but when I turn it back on, it doesn't work. I need to switch to another file and back for it to take effect.

**What did you expect to happen**: Toggle vim mode.

**How to reproduce it (as minimally and precisely as possible)**: Setup keybindings to toggle vim mode, and try to turn on and off the vim mode.

Keybindings set: Ctrl + Alt + Shift + V

**Environment**: KDE Neon 16.04. VSCode version 1.20.0, commit - c63189deaa8e620f650cc28792b8f5f3363f2c5b

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.20.0
- OS version: KDE Neon 16.04

**Comment by Chillee** [comment] 2018-02-14 07:10
Could you post your config for how you're binding it?

**Comment by jpoon** [comment] 2018-02-19 17:11
Likely a dupe of https://github.com/VSCodeVim/Vim/issues/2198

**Comment by jpoon** [comment] 2018-05-25 08:03
Closing as we haven't had any further info.

**Closed by jpoon** 2018-05-25 08:03 UTC
Labels: status/needs-more-info
