### ISSUE TITLE
Failed to handle key=d. getLineLength() called with out-of-bounds line 26

### ISSUE THREAD

**Issue by fregas** [VSCodeVim/Vim#5637] opened 2020-11-12 15:56 UTC
**To Reproduce**

1.  I selected all text
2.  Deleted everything
3.  Hit "i" for insertion mode
4.  Crash

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. getLineLength() called with out-of-bounds line 26
	at Function.getLineLength (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.executeOperator (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480756)
	at F.runAction (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476279)
	at F.handleKeyAsAnAction (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/user1/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:37
Can you reliably reproduce using those steps?

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
