### ISSUE TITLE
getLineLength() called with out-of-bounds line 76

### ISSUE THREAD

**Issue by Mostafaarju** [VSCodeVim/Vim#5261] opened 2020-09-27 05:35 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 76
    at Function.getLineLength (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.isLineEnd (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14169)
    at l.getRightThroughLineBreaks (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10990)
    at Object.t.statusBarCommandText (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31274)
    at Object.updateShowCmd (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40481)
    at F.handleKeyEvent (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/mohammadrezwan/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 16:17
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 16:17 UTC
Labels: kind/bug, status/duplicate
