### ISSUE TITLE
Failed to handle key=<Esc>. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by shihabmahamud** [VSCodeVim/Vim#5352] opened 2020-10-08 06:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:187)
	at new l (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
	at h.updateAndReturnMarks (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
	at h.finishCurrentStep (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
	at F.runAction (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/shihab/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by shihabmahamud** [comment] 2020-10-08 06:13
fix it

**Comment by J-Fields** [comment] 2020-10-14 01:57
Duplicate of #5226, please post repro steps there.

**Closed by J-Fields** 2020-10-14 01:57 UTC
