### ISSUE TITLE
C+o not work

### ISSUE THREAD

**Issue by longhaiqwe** [VSCodeVim/Vim#4376] opened 2019-12-13 10:09 UTC
Issue Type: Bug

C+o jump to older position messed up.
And I rolled back to 1.11.3 and everything worked fine.

Extension version: 1.12.2
VS Code version: Code 1.40.2
OS version: Win10

**Comment by J-Fields** [comment] 2019-12-15 23:45
Can't reproduce (also on windows 10). Make sure there aren't any remaps which could be interfering in either settings.json or your .vimrc

**Comment by charlietran** [comment] 2019-12-16 17:39
This is happening to me as well on MacOS Catalina. Ctrl+O jumps into another random file.

**Comment by longhaiqwe** [comment] 2019-12-18 03:13
@J-Fields Thanks for you reply.
I tried removing all vim settings in settings.json and .vimrc, and the error still exists.

**Comment by zhengbli** [comment] 2019-12-19 14:15
Happened to me on Linux with 1.12.2 as well. "gd" goes to the definition location, but then `<c-o>` jumps to a random file.

**Comment by jfrid** [comment] 2019-12-20 10:47
Same for me. Ubuntu 18.04, VS Code 1.41.0, Vim plugin 1.12.2.

**Comment by rockindy** [comment] 2019-12-26 03:30
I got the same problem. Ubuntu 18.04, VS Code 1.41.1, Vim plugin 1.12.3

I rolled back to 1.11.3 and it worked fine.

**Comment by Ciebiada** [comment] 2019-12-26 11:12
Same issue here: OS X  10.15.2, VSCode 1.41.1, Vim plugin 1.12.3

**Comment by kevindevos** [comment] 2020-01-22 11:55
MacOS Catalina 10.15.2 on plugin 1.12.4, i see that this happens when you switch to a file with cmd+p and it ends up opening a wrong file after i press Ctrl-o

**Comment by albuscrow** [comment] 2020-02-23 12:30
Extension version: 1.12.4
VS Code version: Code 1.42
OS version: OSX

"gd" goes to the definition location, but then <c-o> jumps to a new tab named "tasks".

**Comment by J-Fields** [comment] 2020-02-26 19:18
Fixed via #4581

**Closed by J-Fields** 2020-02-26 19:18 UTC
Labels: kind/bug
