### ISSUE TITLE
Fix quick jump visual error

### ISSUE THREAD

**Issue by nikitavoloboev** [VSCodeVim/Vim#3816] opened 2019-06-06 11:00 UTC
Is it possible to fix this visual error in quick jumping so the letters are placed inside actual red boxes (so it's readable).

![2019-06-06 at 11 59](https://user-images.githubusercontent.com/6391776/59028053-82859880-8852-11e9-9315-17f9a653190b.png)

**Comment by nikitavoloboev** [comment] 2019-08-27 10:08
Does anyone know what part of code I should edit to edit the styling of this?

 @johnfn @xconverge

**Comment by nikitavoloboev** [comment] 2019-08-29 08:26
Thank you. 

```
  "vim.easymotion": true,
  "vim.easymotionMarkerBackgroundColor": "yellow",
  "vim.easymotionMarkerForegroundColorOneChar": "black",
  "vim.easymotionMarkerForegroundColorTwoChar": "black",
  "vim.easymotionMarkerFontSize": "17",
  "vim.easymotionMarkerHeight": 22,
  "vim.easymotionMarkerYOffset": 4,
```

These solves it for me.

One other thing, I can open new issue about it. But is it possible to instead of `;` keys have `:` keys in the markers?

![2019-08-29 at 09 26](https://user-images.githubusercontent.com/6391776/63923813-196f8480-ca3f-11e9-9a77-5527b1dc1397.png)

I would love a setting for it.

**Comment by J-Fields** [comment] 2019-08-29 16:17
@nikitavoloboev Feel free to open a ticket. Why do you prefer `:`? Does the original easymotion plugin have this option?

**Comment by nikitavoloboev** [comment] 2019-08-29 16:20
I remapped `;` with `:` as I use it more often. Thus for me `:` is much more preferred than `;`.

I am not sure if it does as I never used it.

**Comment by J-Fields** [comment] 2020-02-27 04:38
Closing as duplicate of #2938

**Closed by J-Fields** 2020-02-27 04:38 UTC
