### ISSUE TITLE
Failed to handle key=d. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by Gloudzhangkai** [VSCodeVim/Vim#6089] opened 2021-02-03 02:47 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.8

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=d. Cannot read property 'canBeRepeatedWithDot' of undefined
	at F.runAction (/Users/gloud/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:708609)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/gloud/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:707147)
	at async F.handleKeyEvent (/Users/gloud/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:703983)
	at async Object.promise (/Users/gloud/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:350696)
	at async Object.runTasks (/Users/gloud/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:754478)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:08
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:08 UTC
Labels: status/duplicate
