### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 113

### ISSUE THREAD

**Issue by bamboo-cp3** [VSCodeVim/Vim#5262] opened 2020-09-27 05:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 113
	at Function.getLineLength (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:22186)
	at F.executeMovement (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:480184)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:475249)
	at async F.handleKeyAsAnAction (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:231560)
	at async Object.runTasks (/Users/cheng/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 16:18
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 16:18 UTC
Labels: kind/bug, status/duplicate
