### ISSUE TITLE
Provide more accurate highlight in visual mode

### ISSUE THREAD

**Issue by Ethefor** [VSCodeVim/Vim#1863] opened 2017-06-22 15:34 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: Ubuntu 16.04 LTS

**What happened**:
I have for example following code snippet:
```
pathToModel
pathToModel
pathToModel
```
My cursor is placed at the beginning of first word. Now I type `ve`.
My cursor is placed now over letter `l`. When I yank now, whole word will be copied. Unfortunately nice highlighting is not present over last letter (is only from p to e), which is misleading (as yanked is whole word, also with last letter).

**What did you expect to happen**: 
I expect, that when I select word in visual mode, whole word will be highlighted (including last letter).

**How to reproduce it**:
Place cursor in normal mode in beginning of some word, then type `ve`. Last letter will not be highlighted (but it will be yanked when you press y).

**Comment by xconverge** [comment] 2017-06-22 16:14
duplicate of #1455

also see https://github.com/VSCodeVim/Vim/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fselection-off-by-one

**Closed by xconverge** 2017-06-22 16:14 UTC
