### ISSUE TITLE
Illegal value for `line`

### ISSUE THREAD

**Issue by yash19pro** [VSCodeVim/Vim#5906] opened 2020-12-18 14:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at Function.getCharAt (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:13177)
	at F.updateView (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:184243)
	at F.handleSelectionChange (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:164427)
	at Object.promise (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:215959)
	at Object.runTasks (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327652)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:02
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:02 UTC
