### ISSUE TITLE
Failed to handle key `<C-o>`: Could NOT open editor for "vscode-interactive-input:/InteractiveInput-2".

### ISSUE THREAD

**Issue by natwille1** [VSCodeVim/Vim#7221] opened 2021-11-03 14:58 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
Error: Failed to handle key `<C-o>`: Could NOT open editor for "vscode-interactive-input:/InteractiveInput-2".
    at S.showTextDocument (c:\Users\nwillems\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:63884)
    at runMicrotasks (<anonymous>)
    at process.document (internal/process/task_queues.js:93:5)
    at t.JumpTracker.fileName [as performFileJump] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\jumps\jumpTracker.ts:113:14)
    at t.JumpTracker.vimState [as jumpThroughHistory] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\jumps\jumpTracker.ts:171:61)
    at t.JumpTracker.vimState (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\jumps\jumpTracker.ts:148:45)
    at Ze.i [as exec] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\actions\commands\actions.ts:1602:50)
    at Ze.execCount (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\actions\base.ts:199:42)
    at j.actionToRecord [as runAction] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:713:47)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:662:43)
    at j.mh [as handleKeyEvent] (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\src\mode\modeHandler.ts:477:11)
    at r (c:\Users\nwillems\.vscode\extensions\vscodevim.vim-1.21.10\extensionBase.ts:501:15)
```

</details>

**Comment by J-Fields** [comment] 2021-11-05 18:06
Duplicate of #6445

**Closed by J-Fields** 2021-11-05 18:06 UTC
Labels: kind/bug, status/duplicate
