### ISSUE TITLE
J in visual mode doesn't join lines

### ISSUE THREAD

**Issue by vbvyas** [VSCodeVim/Vim#910] opened 2016-10-12 21:31 UTC
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Shift+V - Select whole line in Visual Mode
Use either j or k to select more lines
Press J (Shift+J)

### What did you expect to happen?

Selected lines in Visual mode get joined into a single line

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.7
* OS: OS X El Capitan

**Comment by johnfn** [comment] 2016-10-13 08:41
Duplicate of #906. Thanks for the report, though! :)

**Closed by johnfn** 2016-10-13 08:41 UTC
