### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 180

### ISSUE THREAD

**Issue by KingNels24** [VSCodeVim/Vim#5547] opened 2020-11-01 01:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 180
	at Function.getLineLength (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at F.executeMovement (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480271)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475336)
	at async F.handleKeyAsAnAction (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/pharaoh_nelson/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:28
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:28 UTC
