### ISSUE TITLE
getLineLength() called with out-of-bounds line 14

### ISSUE THREAD

**Issue by nghiepnguyen520** [VSCodeVim/Vim#5311] opened 2020-10-01 07:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 14
	at Function.getLineLength (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.isLineEnd (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14231)
	at l.getRightThroughLineBreaks (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11052)
	at Object.t.statusBarCommandText (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31336)
	at Object.updateShowCmd (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
	at F.handleKeyEvent (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/asta/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:47
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:47 UTC
