### ISSUE TITLE
Unable to remap <C-s> in insert mode

### ISSUE THREAD

**Issue by alexriedl** [VSCodeVim/Vim#2411] opened 2018-03-02 15:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**What happened**:
Mapped `<C-s>` using vim.insertModeKeyBindingsNonRecursive and was unable to the mapped commands to happen. Mapped `<C-n>` to the same commands and that worked.

**What did you expect to happen**:
While in insert mode I should be able to press `<C-s>` or `<C-n>` to save the file and exit insert mode.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add to your user settings:
```
"vim.insertModeKeyBindingsNonRecursive": [
    {
        "before": [ "<C-s>" ],
        "commands": [
            { "command": "workbench.action.files.save" },
            { "command": "extension.vim_escape" }
        ]
    },
    {
        "before": [ "<C-n>" ],
        "commands": [
            { "command": "workbench.action.files.save" },
            { "command": "extension.vim_escape" }
        ]
    }
],
```
2. Reload window
3. Open a file and enter insert mode (make a change)
4. Hit `<C-s>`, nothing will happen. Hit `<C-n>` File will be saved and you will be taken out of insert mode.

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Ubuntu 17.10

**Comment by AntonPuko** [comment] 2018-03-05 21:39
The same issue with `<C-;>` in insert mode.

**Comment by jpoon** [comment] 2018-06-15 09:49
Our extension doesn't bind to those keys (https://github.com/VSCodeVim/Vim/blob/master/package.json#L140), hence they go straight to the editor and vscodevim has no history of it.

If we do bind to them, that means we'll need to handle whatever `<c-n>` and `<c-s>` are supposed to do (ie. new window, and save).

**Comment by jpoon** [comment] 2018-06-16 00:33
Dupe of https://github.com/VSCodeVim/Vim/issues/757

**Closed by jpoon** 2018-06-16 00:33 UTC
Labels: area/remap
