### ISSUE TITLE
Support `when` for contextual keybindings

### ISSUE THREAD

**Issue by denisidoro** [VSCodeVim/Vim#3994] opened 2019-08-25 14:18 UTC
**Is your feature request related to a problem? Please describe.**
I'm not able to set keybindings contextually. For example, I would like to set `<leader> + m + p` as an action to preview content, and that depends on the programming language. At a higher level, I'm trying to replicate Spacemacs's major modes.

Using `when` seems to be a no-op. In the example below, both commands are executed regardless of the current `editorLangId`. 

**Describe the solution you'd like**
To support `when` in elements inside `commands`, as in: 

```json
{"before":   ["<leader>", "m", "p"], 
 "after":    [], 
 "commands": [{"command": "markdown.showPreviewToSide", "args": [], "when": "editorLangId == 'markdown'"},
              {"command": "html.previewPage", "args": [], "when": "editorLangId == 'html'"}]}
```

Alternatively, `when` could be supported in the command root:
```json
{"before":   ["<leader>", "m", "p"], 
 "after":    [], 
 "when":     "editorLangId == 'markdown'",
 "commands": [{"command": "markdown.showPreviewToSide", "args": []}]}
```

**Describe alternatives you've considered**
Set shorcuts in `keybindings.json`. I wouldn't be able to differ between vim modes, though. And I guess it would make my `<leader>` inconsistent.

**Comment by J-Fields** [comment] 2019-08-26 02:38
Closing as duplicate of #2030

**Closed by J-Fields** 2019-08-26 02:38 UTC
Labels: area/remap, kind/enhancement
