### ISSUE TITLE
Vim cursor does not move with "Go to Next Problem"

### ISSUE THREAD

**Issue by nzig** [VSCodeVim/Vim#5746] opened 2020-11-24 16:49 UTC
**Describe the bug**
When using the keyboard shortcut for "Go to Next Problem", the focus and cursor move to the next problem in the file. However, using any vim action starts from where the cursor was last, before the keyboard action.

**To Reproduce**

1.  Create a file with linting enabled (I used Python with Pylance language server).
1. Make a syntax error somewhere down the file
1. Position cursor in beginning of file
1. Trigger "Go to Next Problem" keyboard action (by default `F8` on my machine).
1. press `l`.
1. The cursor will move to one character after it was before the keyboard action.

**Expected behavior**
The cursor should be one character after the problem that "Go to Next Problem" jumped to.

**Screenshots**
None

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.51.1
- OS: Ubuntu 20.04

**Additional context**
None

As an aside, it would also be nice to have a vim action for "next problem".

**Comment by JW9506** [comment] 2020-11-25 08:29
Hi, check out the latest commits and build it manually, this problem has been fixed a while ago via[#5250]

**Comment by berknam** [comment] 2020-12-07 16:16
Closing since this should be fixed on the new version "1.18" out now. If you still experience this feel free to reopen.

**Closed by berknam** 2020-12-07 16:16 UTC

**Comment by jeffomatic** [comment] 2021-02-12 06:32
I'm using v1.18.9 of the extension (VSC Insiders, commit `93f705ab`) and I still observe this problem. The cursor visually appears to move when calling "Go to next problem", but performing a motion (`hjkl`) updates the _previous_ location of the cursor.

A similar thing occurs if you choose a problem in the "Problems" tab of the lower panel.

**Comment by i-am-the-slime** [comment] 2021-02-27 20:47
This regressed in 1.18.9. I just tried with 1.18.8 and it works there.

**Comment by jeffomatic** [comment] 2021-02-27 21:27
Confirmed that installing 1.18.8 fixes.

@berknam Would it be possible to re-open this issue?

**Comment by dmbfm** [comment] 2021-04-04 18:26
This issue is still happening in the latest release...

**Comment by JW9506** [comment] 2021-04-04 23:39
> This issue is still happening in the latest release...

Closing and reopening can clear the issue, I can confirm that the issue does actually surface from time to time after a long usage. I don't know exactly how to reproduce the problem at my will though.  And plus it is not a huge deal because closing and reopening do not take much time.

**Comment by dmbfm** [comment] 2021-04-06 14:13
@JW9506 It's difficult to know exactly when it happens. It seems after you use goto definition and/or jump around files and issues this happens after a while. Still it is very annoying having to close and open. This issue should be reopened and fixed.

**Comment by i-am-the-slime** [comment] 2021-04-16 10:42
@JW9506 closing and reopening what? Depending on the PL you use opening can take minutes.

**Comment by i-am-the-slime** [comment] 2021-05-31 14:00
This regressed again in the latest version.

**Comment by i-am-the-slime** [comment] 2021-09-26 07:44
This keeps on coming back and it's driving me crazy. Is there any workaround for this?

**Comment by ndevvy** [comment] 2021-11-22 20:20
this is back in 1.62.3

**Comment by molysgaard** [comment] 2022-02-15 18:56
I can confirm this issue happens.

Steps to reproduce:

1. Use vim extension
2. Use a language server or similar that lets you "go to next error"
3. Press Shift+Ctrl+P "Go to next Problem (Error, Warning, Info)"
4. Observe that the view moves to the next problem, and the caret is visually moved to the problem
5. Press any vim movement command, eg. hjkl
6. When movement is done, the view and caret pops back to the previous position

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-46-generic
```

**Comment by TomYeoman** [comment] 2023-01-06 15:40
I have this issue when using several pieces of core functionality;
- Go to error
- Go to symbol
- Using gd to go to a definition

Sometimes it will just go back to the old cursor when I do any any action (move around, or go into insert), this is driving me a little crazy

**Comment by jackcasey** [comment] 2023-04-12 07:48
Just FYI: 
I had this issue and ended up here after searching for what was causing it. 
Closing the editor for that file (actually multiple editors for that file, not sure if relevant) and re-opening seemed to fix it for now as per others' experience.

**Comment by ZorikVar** [comment] 2023-06-15 11:53
The issue still exists. In some circumstances movements get broken: the editor shows the movement for several milliseconds then reverts to the previous position. Movements like "normal mode hjkl", "jump to next git diff" and "clangd goto definition". Entering insert mode fixes movements, reopening the editor doesn't.

In what circumstances does the problem occur?
1. Every time I open a git diff.
2. After making several folds (e.g. via normal mode "zM"). Opening the folds via "zR" fixes the problem.

This is an extremely irritating problem which happens all the time (not some corner case), makes normal (the most valuable mode) mode effectively useless in diffs and has been there for the last three years. Please, give it more priority.

**Comment by BickfordA** [comment] 2023-12-05 18:45
Is there any command we can add to the keybinding to force the vim cursor location to update?

**Comment by austin-beer** [comment] 2024-02-02 19:54
I'm still experiencing this issue as well with Visual Studio Code 1.86.0 and VSCodeVim 1.27.2. It only happens occasionally, so I'm not sure how to reproduce it reliably either. And closing and re-opening the file does seem to fix the issue for me, at least temporarily.

**Comment by luan** [comment] 2024-02-04 18:52
I've developed a terrible muscle memory of CLICKING after hitting to to next diagnostic to work around this issue. I'm pretty surprised this has been an issue for this long. I've only recently moved to VSCode from Vim proper due to tooling fatigue at work and this has been my number one drawback.

**Comment by jjerryyz** [comment] 2024-02-23 20:55
I'm using VsCode 1.86.2 and VSCodeVim 1.27.2,  Press Shift+Ctrl+P “Toggle Vim Mode” and Again to work around.

**Comment by lucaSartore** [comment] 2024-07-03 07:39
An ugly but effective solution I found to the problem... inspired by  @jjerryyz 

> I'm using VsCode 1.86.2 and VSCodeVim 1.27.2, Press Shift+Ctrl+P “Toggle Vim Mode” and Again to work around.

Is to switch off vim mode mode before going to the next error, and then switch it on again. This could be automated by adding the following keybinding to your settings.json.
 ```json
{
    "vim.normalModeKeyBindings": [
        // go to next error
        {
            // keybinding for going to the next error
            "before": [
                "<leader>",
                "]"
            ],
            "commands": [
                // disable vim extension
                "toggleVim",
                // go to the next error (using third party extenson)
                "go-to-next-error.nextInFiles.warning",
                // re enable vim extension
                "toggleVim",
                // go back to normal mode (otherwise you will stay in insert mode)
                {
                    "command": "vim.remap",
                    "args": {
                        "after": [
                            "<esc>"
                        ]
                    }
                }
            ]
        }
    ]
}
```

Note that this works best with the [Go-to-Next-Error](https://marketplace.visualstudio.com/items?itemName=yy0931.go-to-next-error) extension. I found some weird behaviors when trying to do the same with the native VsCode command.


Note that when the extension is turned off and on again you lose all the “Vim Memory” (Yanked text, macro, undo history ecc.)

**Comment by edemaine** [comment] 2024-07-03 13:03
FWIW, you can instead use the command `"extension.vim_escape"` for the last step (but that's a neat trick with `"vim.remap"`!)
(I learned about this from https://github.com/VSCodeVim/Vim/issues/9029#issuecomment-2130972680 )

**Comment by gdoteof** [comment] 2025-03-27 15:34
Thought I'd add here that 

1.  Closing an re-opening the file solves the issue for that file.
2.  Anytime a file is re-opened, it 'unfixes' any other files that were previously fixed.
3.  The plugin `vim-leave-insertmode` by @xaviargmail , seems to be the real culprit for me.  After uninstalling this the behavior goes away.

**Comment by gdoteof** [comment] 2025-03-27 15:35
Thought I'd add here that 

1.  Closing an re-opening the file solves the issue for that file.
2.  Anytime a file is re-opened, it 'unfixes' any other files that were previously fixed.
3.  The plugin `vim-leave-insertmode` (by @xaviergmail), seems to be the real culprit for me.  After uninstalling this the behavior goes away.
