### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by houdunwang** [VSCodeVim/Vim#6325] opened 2021-03-21 09:29 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at filter (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:28)
    at a.operator (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:215:28)
    at a.isOperatorPending (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:287:12)
    at m.currentModeIncludingPseudoModes (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/state/vimState.ts:252:31)
    at I.updateView (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/mode/modeHandler.ts:1395:23)
    at I.handleSelectionChange (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/mode/modeHandler.ts:281:20)
    at Object.promise (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/extensionBase.ts:341:18)
    at Object.runTasks (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:37:20)
    at Object.enqueueTask (/Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:108:12)
    at /Users/hd/.vscode/extensions/vscodevim.vim-1.19.0/extensionBase.ts:340:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

</details>

**Comment by J-Fields** [comment] 2021-03-21 18:57
Duplicate of #6309

**Closed by J-Fields** 2021-03-21 18:57 UTC
