### ISSUE TITLE
<C-[> not work when in insert mode and macOS Chinese Simplified IM

### ISSUE THREAD

**Issue by kawaiidora** [VSCodeVim/Vim#3699] opened 2019-04-22 18:28 UTC
**Describe the bug**
When in the Chinese Simplified IM and the insert mode, using key `C-[` (features are similar to `ESC`) cannot back to normal mode. Maybe this is caused by `im-select` because Japanese Hiragana doesn't have that unexpected behavior.

**To Reproduce**

1.  Set following configs in Environment

2. Go to insert mode in any text editing area

3. Switch to Chinese Simplified Input Method

4. Press `<C-[>` in order to back to normal mode

**Expected behavior**
VSCodeVim backed to normal mode just like pressing `ESC`

**Screenshots**
Screenshots doesn't help

**Environment (please complete the following information):**

using `im-select` to switch input method (following readme)

Config:
```
"vim.autoSwitchInputMethod.enable": true,
"vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
"vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
"vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}"
```

- Extension Version: `1.4.0`
- OS Version: `Darwin x64 18.5.0` `macOS Mojave 10.14.4 (18E226)`
- VSCode version: `1.33.1`

English: `com.apple.keylayout.ABC`
Simplified Chinese: `com.apple.inputmethod.SCIM.ITABC`
Japanese Hiragana: `com.apple.inputmethod.Kotoeri.Japanese`

**Additional context**

**Comment by tddschn** [comment] 2020-12-12 01:23
Same issue here.

**Comment by berknam** [comment] 2020-12-12 13:37
I can't reproduce this on Windows 10.

Can you check the logs (read [here](https://github.com/VSCodeVim/Vim#debugging-remappings)). Confirm that when you press the ctrl+key combination something like this shows on console ("Help -> Toggle Developer Tools" then switch to "Console" tab):
```
[Extension Host] ModeHandler: debug: handling key=<C-[>.
```

Also try pressing just the key without pressing "ctrl", does it input '【'? And see if this is what you're getting on console:
```
[Extension Host] ModeHandler: debug: handling key=【.
```

**Comment by tddschn** [comment] 2020-12-12 14:23
@berknam Nothing related showed up in the Console in the Dev Tools. Maybe it's caused by how macOS handles ^[ when the input method is switched to zh_TW / zh_CN?

**Comment by berknam** [comment] 2020-12-12 16:31
> @berknam Nothing related showed up in the Console in the Dev Tools. Maybe it's caused by how macOS handles ^[ when the input method is switched to zh_TW / zh_CN?

You need to change the setting "vim.debug.loggingLevelForConsole" to "debug"

**Comment by tddschn** [comment] 2020-12-13 00:24
I set the log level to "debug", entered Insert Mode, switched the input method to zh_CN and cleared the Console. 
Then I pressed `[` and `^[` and here's the Console output:
![image](https://user-images.githubusercontent.com/45612704/101999912-85e9c200-3d1c-11eb-8324-04ae648920a5.png)

**Comment by berknam** [comment] 2020-12-13 01:19
Please confirm if any of the following things might be the issue:
- Do you have "vim.useCtrlKeys" set to false? It needs to be `true` so that all ctrl key combinations like `<C-[>` can work.
- Do you have `^[` bound to something else?! (check your "Keyboard Shortcuts") It might be rebound to something else or some other extension might be capturing it.
- Check that you don't have something like this on your 'settings.json':
    ```jsonc
    "vim.handleKeys": {
        "<C-[>": false,
    }
    ```

**Comment by tddschn** [comment] 2020-12-13 02:44
- No, `vim.useCtrlKeys` is set to `true`.
- No, that key binding is reserved for vim only (vim in the terminal, vimium in the browser and other vim-like programs). `^[` works as long as the input method is not set to zh_TW / zh_CN or other input methods that display a popup box when you type, like this:
![image](https://user-images.githubusercontent.com/45612704/102001657-9ce5df80-3d2f-11eb-9c0a-b08f291d0b61.png)
Users need to manually choose which words they intend to input (by pressing 1-6) under these input methods, i.e. the typed letters are not automatically inserted before the cursor when typing.
- No, there isn't <C-[> anywhere in the settings.json.

**Comment by berknam** [comment] 2020-12-13 13:23
Did you check vscode's "Keyboard Shortcuts" to see what is bound to "ctrl+["?

This works as expected for me on Windows 10. Using Chinese IM on insert mode the popux box shows. You can't press "ctrl+[" when the popup box is open because then every key stroke is capture by vscode, but after choosing one of the inputs or pressing `<Enter>`/`<Esc>` to get out of the popup box, if I press "ctrl+[" it exits InsertMode to NormalMode.

From your console output, the key `[` -> '【' is being captured by VSCodeVim but the key combination "ctrl+[" is not! There is an error in your console that I don't know that it is, it doesn't appear to be from VSCodeVim, you would have to check vscode logs to try to find out about it.

Another thing you can try to do is the following:
1. Go to "Keyboard Shortcuts"
2. Change your input method to Chinese
3. Press the "Record Keys" button (`alt+k`)
4. Then press the key combination "ctrl+[" to see what shows up
5. If you can post a print screen of that

**Comment by tddschn** [comment] 2020-12-13 13:57
Nope, `^[` works (brings me back to Normal Mode) when the input method (keyboard) is en_US. 

Here's what showed up in the Keyboard Shortcuts:
- en_US:
![image](https://user-images.githubusercontent.com/45612704/102013903-ecf38f00-3d8d-11eb-880d-5fcf4d847f3b.png)

- zh_CN:
![image](https://user-images.githubusercontent.com/45612704/102013905-efee7f80-3d8d-11eb-8098-70fb30dc08ea.png)

I hope this is helpful. :)

**Comment by berknam** [comment] 2020-12-13 15:57
Are you pressing the "Alt" key as well? Or was that there just from using "alt+tab"?

This might be an issue with the keyboard codes. I don't think I've ever seen that "ctrl+[BracketLeft]". Sometimes depending on the keyboard and the keyboard layout, pressing the same key results in different key codes.

For instance, for me pressing I need to press my "+" key in order to get `[` when using en_US and that same key results in  '【' when using Chinese. But when looking it with "Record Keys" when on en_US it shows as "ctrl+[" but in Chinese it shows as "ctrl+oem_4" but it still shows the "extension.vim_ctrl+[" keybinding every time. Yours should do too.

Can you check in some website like this https://keyboardchecker.com/ if when pressing the key that results in `[` in both input methods makes the same key `[` light up on that website?

**Comment by tddschn** [comment] 2020-12-14 00:34
There is no 'alt', but I use the Option (Alt) key to take the screenshot, and that key was recorded too.

On keyboardchecker.com, only en_US makes `[` light up, for zh_CN, `[` didn't light up:
![image](https://user-images.githubusercontent.com/45612704/102028862-18ef2e80-3de7-11eb-8e60-ec57d64e23a1.png)

**Comment by berknam** [comment] 2020-12-15 10:36
I think that might be the issue, your keyboard is not sending that key combination as a `ctrl+[` when you are on zh_CN. Try to see if there is any other key that when pressing with zh_CN makes `[` light up.

I think you should try to open up an issue on vscode for this to see they can help you, but to be honest this might be expected behavior, since when changing input methods it is normal for keys to have a different meaning. For instance, for me to able to get `[` in en_US or zh_CN I'm actually pressing my `+` key.

As a workaround you can try to add the following to your "keybindings.json":
```jsonc
    {
        "key": "ctrl+[BracketLeft]",
        "command": "vim.remap",
        "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert'",
        "args": {
            "after": ["<C-[>"],
        }
    },
```

**Comment by tddschn** [comment] 2020-12-15 11:13
@berknam Thanks for the hack! It works like a charm! :)

I think this should be the solution for macOS users.

**Comment by berknam** [comment] 2020-12-15 19:47
I'm closing this one since this is an upstream issue in vscode that should recognize the `ctrl+[BracketLeft]` as a `ctrl+[`.

It can be fixed for Vim users with the workaround mentioned above.

@tddschn I still think you should create an issue on vscode repo about this, so that they can look into it.

**Closed by berknam** 2020-12-15 19:47 UTC
Labels: kind/bug, upstream/vscode
