### ISSUE TITLE
"," cannot be remapped when {"vim.leader": ","}

### ISSUE THREAD

**Issue by haberdashPI** [VSCodeVim/Vim#2932] opened 2018-08-03 18:02 UTC
**Describe the bug**
If you remap the leader to "," there's no way to reference the old functionality of ",".

**To Reproduce**
Replace settings.json with the following text:

```json
{
  "vim.leader": ",",
  "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["^"],
            "after": [","]
        }
    ],
}
```

Place the following text in a new file

```
testing testing testing
```

Place the cursor on the start of the line. In insert mode, "fe;" will jump to the first "e" and then the second "e". Now press "^". Nothing will happen.

(Note: "^" also does not act as a leader. Commands I've mapped to leader do not work when using "^" in the above scenario).

**Expected behavior**

I would expect that pressing "^" would move the cursor back to the first "e" in the above example.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.15.7
- VSCode version: 1.25.1
- OS: Mac OS X 10.11.6

**Comment by jpoon** [comment] 2018-08-14 03:53
Related: https://github.com/VSCodeVim/Vim/issues/2735

**Comment by jpoon** [comment] 2018-08-14 04:01
I think you meant to swap the before and after in your configuration.

The PR fixes the above issue but exposes a larger issue. As we don't do any look-ahead, if there is an immediate matching action for the key, the extension will immediately execute it. For instance, if you bind your leader key to an existing VIM key (e.g. `,`), when you have remappings such as:

before: <leader>, f, e, s
after: v

When you press , (which is the leader key), we will immediately execute: https://github.com/VSCodeVim/Vim/blob/9cff13d43d40e2b3e717f0234ff7520338030747/src/actions/motion.ts#L749 and not wait for further keys.

**Comment by haberdashPI** [comment] 2018-08-14 14:56
Interesting, I misunderstood the meaning of "before" and "after" here. 

Thanks for your work and energy looking into this. I'm eagerly awaiting a fix of the larger issue.

**Comment by jpoon** [comment] 2019-01-29 07:31
I'm going to close this as a dupe of https://github.com/VSCodeVim/Vim/issues/1821 as it's the same root cause.

**Closed by jpoon** 2019-01-29 07:31 UTC
Labels: kind/bug
