### ISSUE TITLE
Intellisense with word wrap breaks below the wrap

### ISSUE THREAD

**Issue by Apostolique** [VSCodeVim/Vim#1836] opened 2017-06-13 17:22 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**:  0.8.5
- **OS**: Windows 10 Pro

**What happened**: Intellisense with word wrap breaks below the wrap when using vscodevim.vim https://clips.twitch.tv/WiseExcitedKleeVoteNay

**What did you expect to happen**: Intellisense should show up.

**How to reproduce it**:

0. Have the vscodevim.vim extension.
1. Activate Word Wrap.
2. Have a line that is long enough to wrap.
3. Intellisense works above the wrap but stops working below it.

This was originally posted as a vscode issue until I found out it was related to vscodevim.vim.
https://github.com/Microsoft/vscode/issues/28559

**Comment by Chillee** [comment] 2017-06-13 18:10
@Apostolique It's a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/1827

The cause is some change to the VSCode API between VSCode 1.12 and 1.13. It's somewhat difficult to figure out.

**Closed by Chillee** 2017-06-13 18:10 UTC
