### ISSUE TITLE
Setting cursorStylePerMode for visual mode does not work as expected

### ISSUE THREAD

**Issue by seanwyndellque** [VSCodeVim/Vim#5855] opened 2020-12-08 16:42 UTC
**Describe the bug**
Setting cursorStylePerMode to underline for visual mode does not work as expected
![Screen Shot 2020-12-09 at 12 33 40 AM](https://user-images.githubusercontent.com/14856076/101513192-dc6e9d80-39b6-11eb-96ee-cf11088b6b9f.png)
![Screen Shot 2020-12-09 at 12 34 21 AM](https://user-images.githubusercontent.com/14856076/101513200-df698e00-39b6-11eb-9743-743fa7f21d69.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.4
- VSCode version: 1.51.1
- OS: MacOS 10.15.7

**Comment by J-Fields** [comment] 2020-12-08 17:34
Did this ever work? Vim and VSCode disagree on where the cursor should be drawn in visual mode, so we have to draw a fake cursor in the right place. We should forego drawing that if `cursorStylePerMode.visual` is set, but even that seems suboptimal because it'll show up after the selection, not on the last character of the selection.

**Comment by J-Fields** [comment] 2021-10-15 16:27
Duplicate of #3972

**Closed by J-Fields** 2021-10-15 16:27 UTC
Labels: kind/bug, status/duplicate
