### ISSUE TITLE
gf: 'try to find it with the same extension'-code doesn't work

### ISSUE THREAD

**Issue by pikulev** [VSCodeVim/Vim#3310] opened 2018-12-30 16:27 UTC
**Describe the bug**

`gf` under the `require('some_file')` in .js file says "Vim: This file /Users/vvp/test/some_file.js does not exist.".

**To Reproduce**
1.  `echo '// some_file' > file.js && touch some_file.js`
2.  `code file.js`
3.  `gf` under the `some_file`
4.  See error

**Expected behavior**
some_file.js has opened

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.17.3
- VSCode version: 1.30.1
- OS: Mac OS 10.13.4

**Comment by jpoon** [comment] 2018-12-30 22:05
Dupe of https://github.com/VSCodeVim/Vim/issues/3233?

**Comment by pikulev** [comment] 2018-12-30 22:09
> Dupe of #3233?

Seems to be a dup, yes

**Comment by jpoon** [comment] 2018-12-30 22:11
Cool cool. Let's use that one.

**Closed by jpoon** 2018-12-30 22:11 UTC
Labels: status/duplicate
