### ISSUE TITLE
getLineLength() called with out-of-bounds line 4

### ISSUE THREAD

**Issue by QuocVietHa08** [VSCodeVim/Vim#5235] opened 2020-09-24 10:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 4
    at Function.getLineLength (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:22186)
    at l.isLineEnd (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:14192)
    at l.getRightThroughLineBreaks (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:11013)
    at Object.t.statusBarCommandText (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:31297)
    at Object.updateShowCmd (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:40504)
    at F.handleKeyEvent (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:472082)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
    at Object.runTasks (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by danawoodman** [comment] 2020-09-24 17:57
Dupe of #5180

**Closed** 2020-09-25 20:00 UTC
Labels: kind/bug, status/duplicate
