### ISSUE TITLE
Failed to handle key=<BS>. Illegal value for `line`

### ISSUE THREAD

**Issue by samstiyer** [VSCodeVim/Vim#5453] opened 2020-10-19 18:25 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Illegal value for `line`
	at d._lineAt (c:\Users\samst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:222)
	at Object.lineAt (c:\Users\samst\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:181)
	at Function.getLineAt (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22450)
	at _.exec (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:216058)
	at _.execCount (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37468)
	at F.runAction (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475409)
	at F.handleKeyAsAnAction (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
	at F.handleKeyEvent (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\samst\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 21:57
Duplicate of #5305; if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 21:57 UTC
