### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Sanjay-Kickdrum** [VSCodeVim/Vim#6932] opened 2021-07-29 16:23 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at n._applyEdit (/snap/code/70/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/snap/code/70/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/home/hp/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/home/hp/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/hp/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/home/hp/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at r (/home/hp/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:501:15)
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[10, 7] | [10, 7]]"
]
actionsRunPressedKeys: [
  "<C-a>",
  "<C-a>"
]
actionsRun: [
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 5,
      "character": 70
    },
    "text": "f2f2",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 5,
        "character": 69
      },
      {
        "line": 5,
        "character": 74
      }
    ],
    "text": "

**Comment by J-Fields** [comment] 2021-08-03 00:05
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:05 UTC
