### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by etby** [VSCodeVim/Vim#6734] opened 2021-06-13 02:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at s._applyEdit (c:\Users\Etby Gao\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52517)
    at Object.edit (c:\Users\Etby Gao\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:50209)
    at Object.executeTransformations (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\src\transformations\execute.ts:124:29)
    at I.runAction (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\src\mode\modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\src\mode\modeHandler.ts:652:43)
    at I.async [as handleKeyEvent] (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\src\mode\modeHandler.ts:471:11)
    at Object.promise (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\extensionBase.ts:627:27)
    at Object.runTasks (c:\Users\Etby Gao\.vscode\extensions\vscodevim.vim-1.21.2\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
