### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by mcastrogg** [VSCodeVim/Vim#6690] opened 2021-06-02 22:23 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
    at j.updateView (/home/matias/.vscode/extensions/vscodevim.vim-1.20.3/src/mode/modeHandler.ts:1180:50)
    at j.handleKeyAsAnAction (/home/matias/.vscode/extensions/vscodevim.vim-1.20.3/src/mode/modeHandler.ts:663:16)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at j.async [as handleKeyEvent] (/home/matias/.vscode/extensions/vscodevim.vim-1.20.3/src/mode/modeHandler.ts:472:11)
    at Object.promise (/home/matias/.vscode/extensions/vscodevim.vim-1.20.3/extensionBase.ts:627:27)
    at Object.runTasks (/home/matias/.vscode/extensions/vscodevim.vim-1.20.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:34
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:34 UTC
