### ISSUE TITLE
Failed to handle key=a. Illegal value for `line`

### ISSUE THREAD

**Issue by yornipaz** [VSCodeVim/Vim#6001] opened 2021-01-16 02:49 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. Illegal value for `line`
	at d._lineAt (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at Function.getCharAt (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:13177)
	at L.execAction (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:192209)
	at L.createMovementResult (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:153324)
	at L.execActionWithCount (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:152981)
	at F.executeMovement (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
	at F.runAction (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171527)
	at F.handleKeyAsAnAction (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at Object.promise (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216277)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/home/yfbp/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:02
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:02 UTC
