### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by pacomendez12** [VSCodeVim/Vim#6166] opened 2021-02-19 06:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
	at d._lineAt (/private/var/folders/8f/_cs6g4b54p962sm262c2_qw80000gn/T/AppTranslocation/262ECE92-953A-4407-B187-AE9E6D4E8522/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:545:764)
	at Object.lineAt (/private/var/folders/8f/_cs6g4b54p962sm262c2_qw80000gn/T/AppTranslocation/262ECE92-953A-4407-B187-AE9E6D4E8522/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:544:734)
	at x.delete (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:519744)
	at x.run (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:520516)
	at F.executeOperator (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
	at async F.handleKeyAsAnAction (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/pacomendez/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:31
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:31 UTC
