### ISSUE TITLE
Zpracování klíče=<C-a>se nezdařilo. getLineLength() s volána s out-of-bounds řádek 319

### ISSUE THREAD

**Issue by sollo-users** [VSCodeVim/Vim#5416] opened 2020-10-14 12:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. getLineLength() called with out-of-bounds line 319
    at Function.getLineLength (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.getLineEnd (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:13777)
    at sr.getSearchRanges (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:135272)
    at sr.exec (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:133936)
    at sr.execCount (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37468)
    at F.runAction (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475409)
    at F.handleKeyAsAnAction (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
    at F.handleKeyEvent (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\sollo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-15 18:35
Duplicate of #5180, if you can reproduce please post steps there.

**Closed by J-Fields** 2020-10-15 18:36 UTC
