### ISSUE TITLE
Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()

### ISSUE THREAD

**Issue by s4ki3f** [VSCodeVim/Vim#6193] opened 2021-02-23 17:48 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()
	at ur.getSearchRanges (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:418574)
	at ur.exec (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:416698)
	at ur.execCount (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:355716)
	at S.exec (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:460482)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async S.execCount (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:355705)
	at async F.runAction (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707788)
	at async F.handleKeyAsAnAction (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707179)
	at async F.handleKeyEvent (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704015)
	at async Object.promise (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:346362)
	at async Object.runTasks (c:\Users\sakif\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-04-19 15:36
Duplicate of #6500

**Closed by J-Fields** 2021-04-19 15:36 UTC
