### ISSUE TITLE
Implement :>n for tabbing

### ISSUE THREAD

**Issue by kfmfe04** [VSCodeVim/Vim#7636] opened 2022-04-15 05:01 UTC
In regular vim, you can

- `:>>>5` to tab 3 times for the next 5 rows

This feature doesn't exist in VSCodeVim/Vim.

**Comment by J-Fields** [comment] 2022-05-19 01:22
Duplicate of #3733, will be fixed in next version

**Closed by J-Fields** 2022-05-19 01:22 UTC
