### ISSUE TITLE
getLineLength() called with out-of-bounds line 27

### ISSUE THREAD

**Issue by chrispin2510** [VSCodeVim/Vim#5583] opened 2020-11-05 14:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 27
	at Function.getLineLength (/home/chrispin/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/home/chrispin/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.handleSelectionChange (/home/chrispin/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:468991)
	at Object.promise (/home/chrispin/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235549)
	at Object.runTasks (/home/chrispin/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621922)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:26
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:26 UTC
