### ISSUE TITLE
Failed to handle key=<up>. getLineLength() called with out-of-bounds line 11

### ISSUE THREAD

**Issue by creativereason** [VSCodeVim/Vim#5677] opened 2020-11-17 19:54 UTC
**To Reproduce**

1.  Be creating HTML in VIM
2.  Use cut shortcut to reposition an element
3.  Get error 

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<up>. getLineLength() called with out-of-bounds line 11
	at Function.getLineLength (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at V.execAction (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:191010)
	at V.createMovementResult (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at V.execActionWithCount (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/brian.schwartz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-17 21:36
Duplicate of #5180

**Closed by J-Fields** 2020-11-17 21:36 UTC
