### ISSUE TITLE
Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by VuongTran21** [VSCodeVim/Vim#5771] opened 2020-11-27 14:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'stop' of undefined
	at i (/home/vuongtran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:490133)
	at Array.every (<anonymous>)
	at F.updateView (/home/vuongtran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:490222)
	at _ (/home/vuongtran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/vuongtran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235688)
	at async Object.runTasks (/home/vuongtran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:50
Duplicate of #5284

**Closed by J-Fields** 2021-02-04 20:50 UTC
