### ISSUE TITLE
Motion up with 'k' in visual mode not working as expected

### ISSUE THREAD

**Issue by poorren** [VSCodeVim/Vim#4850] opened 2020-05-14 04:11 UTC
**Describe the bug**
Motion up with 'k' in visual mode not working as expected

**To Reproduce**
1.  Ctrl+v go to visual mode
2.  press 'k' to move up
3.  when press motion to third line, the cursor will go back second line.
4.  Even, repeat pressing 'k' in visual mode won't bring further, while the 'j' could go as expected.

**Expected behavior**
press 'k' will always move up.

**Screenshots**
![Ax5iHrPk3G](https://user-images.githubusercontent.com/10894183/81891759-dad52680-95db-11ea-9084-3e0b294797ca.gif)

**Environment (please complete the following information):**
- VSCode version:: 1.14.2
- VSCode Info
=======================
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Additional context**
N/A

**Comment by J-Fields** [comment] 2020-05-14 04:15
Duplicate of #4848

**Closed by J-Fields** 2020-05-14 04:15 UTC
