### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by raphaeloJordao13** [VSCodeVim/Vim#6186] opened 2021-02-22 14:15 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
	at Object.S [as illegalArgument] (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)
	at new d (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:20609)
	at new d (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:19977)
	at a (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
	at F.exec (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async S.exec (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:460560)
	at async S.execCount (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355705)
	at async F.runAction (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
	at async F.handleKeyAsAnAction (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
	at async Object.runTasks (/home/matheus/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
