### ISSUE TITLE
Incomplete selection/copy

### ISSUE THREAD

**Issue by Ashod** [VSCodeVim/Vim#1755] opened 2017-05-26 01:39 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.1 (though the issue was introduced a couple versions back)
- **OS**: Ubuntu 16.04

**What happened**:
A couple of versions back, text selection bounds changed.

In Visual mode, I double-click and hit Ctrl+Shift+F to search in all files quite often. Since double-clicking selects the complete word, Ctrl+Shift+F copies the word into the search box. With this bug, the last character is not copied. This is especially annoying when Match Whole Word is enabled (which is typically the case, since I'm expecting to find all exact matches to the selected word).

After double-clicking a word, right-click, tap Copy, then paste elsewhere to see the same issue.

The issue doesn't exist in Insert mode.

Note: without vim (i.e. when disabled) double-clicking words followed by Copy or Ctrl+Shift+F shows the full word, including the last character. So this is a vim plugin issue.

**What did you expect to happen**: 
Full word to be copied / shown in the search box.

**How to reproduce it**:
In Visual mode, double-click a word then Ctrl+Shift+F, expect the search box to contain the full word, including last character.

**Comment by Chillee** [comment] 2017-05-26 05:07
Are you sure there was ever a version in which this bug wasn't fixed?

**Comment by Ashod** [comment] 2017-05-27 12:56
@Chillee when I saw #1590 I thought it would fix it, but it didn't. Please try to reproduce it, it's really easy to do (just double click on a word in Visual mode and Ctrl+Shift+F, you won't get the last char).

Would really like to see this working again, as it's very annoying.
Thanks.

**Comment by Chillee** [comment] 2017-05-27 14:34
@ashod Trust me, I would love to fix this. However, there are some fundamental issues that prevent that. In Vscode, a selection is `|abcde|`. However, in vim, a selection looks like `abcd|e|`. In addition, Vscode does not support ranges in which the cursor is not at the beginning or start. 

There might be some hacks we can do to try and fix it, but we're running into a fundamental mismatch between how vscode and vim represent selections.

**Comment by Ashod** [comment] 2017-05-27 16:08
@Chillee Thanks for the explanation. I wonder how, then, it used to work. I'm fairly certain it worked perfectly well back in 0.4 or thereabout (and older). Something changed that trimmed the last character in this case. And sure that thing could be VSCode (though also notice that when vim is disabled, it works correctly, as expected, it's the interaction between the two).

I don't know how to downgrade vim (or VSCode, for that matter), but I'm willing to try older versions of both to answer the question of which combination (if any) breaks, or whether it's certainly a bug in one or the other. I'm willing to run those tests if one helps me (safely) downgrade (or install specific builds on a clean VM).

P.S. I'm on Ubuntu (though have VSCode with vim on Windows, it's not handy at the moment, and haven't used it in some months).

**Comment by alexgorbatchev** [comment] 2017-06-02 15:29
Selection issues are really irritating. Copying and pasting around in normal mode is essentially broken. Double clicking on a word and pressing `cmd+c` copies N-1 characters. Pasting over a double-clicked word leaves out one remaining character. Trying to delete that character with `x` deletes something completely random.

Here's what I mean.

![vscodevim](https://cloud.githubusercontent.com/assets/65633/26732715/64fdfe9c-476d-11e7-855c-fb6f53d4481c.gif)

Personally I would prefer this to work with VScode model, even if it's slightly different than vim model. IMO a working "non-vim" version is better than broken "vim-version". Perhaps compatibility can be addressed in the future.

What do you think?

**Comment by Chillee** [comment] 2017-06-02 15:40
@alexgorbatchev There's pretty much only one option, and that is to remove the block cursor entirely in visual mode, and replace it with a decorator.

http://i.imgur.com/zXHXkUv.jpg

I'm not sure it's feasible to do it with a flag; it would just be way too much maintenance work that I don't think we should handle.

**Comment by alexgorbatchev** [comment] 2017-06-02 15:59
> And I'm fairly certain that some people will not like this new behavior.

@Chillee I feel it's a trade off... either a pretty much broken selection behavior or this... Am I correct to assume that block cursor in visual mode exists just to differentiate between visual and insert? Can this be indicated in some other way that is as obvious or nearly as obvious? Perhaps with a marker on the gutter? Or a different color cue?

Is there a corresponding discussion on VSCode repo? Lets loop in some wonderful folks from there (cc @waderyan @tyriar @bpasero)

What do you think?

**Comment by Chillee** [comment] 2017-06-02 16:09
@alexgorbatchev First of all, I would disagree that it's broken. It works for pretty much all of the cases in which you are using vim motions to accomplish your goal. The main thing that seems to bother people is the double click on word and then paste on another word behavior, which isn't very vimlike.

Basically, my reservations on fixing it are this: Changing it to the decorator fixes the behavior for the people who use that pattern I described above. However, changing it to the decorator also worsens the behavior for everybody who doesn't use that pattern. Typically, the common solution here is to just put it behind a flag and call it a day. However, for maintenance reasons, I am currently against that idea.

**Comment by alexgorbatchev** [comment] 2017-06-02 16:16
@Chillee what are your thoughts on multiple selections? It feels pretty broken to me with the current implementation. Here's an example:

![multiple-selection](https://cloud.githubusercontent.com/assets/65633/26734747/07196b98-4774-11e7-95aa-10c656b749be.gif)

It selects `user` twice then selects `use` twice.

**Comment by Chillee** [comment] 2017-06-02 16:19
@alexgorbatchev I agree. That's one of the use cases which have a broad impact across many users.

This is definitely a tricky issue. Could you try one of the other vim extensions (amVim or vimStyle), and tell me how you feel about how they handle visual selection? They handle selections in a way similar to what you're advocating for.

**Comment by Chillee** [comment] 2017-06-02 16:30
@Tyriar I think @rebornix said this was already something he was planning on looking into at some point.

However, this issue isn't properly solvable unless VSCode supports selections for which the cursor is not at one of the ends (which doesn't seem like something that would/should be added).

**Comment by taxilian** [comment] 2017-06-05 23:41
Sublime Text's vintageous plugin had some similar issues; they didn't have block cursor support at all natively.  It might be worth looking at how they solved it, because while it wasn't exactly like vim it also wasn't fundamentally broken, which the current state is.  Personally I'd far rather have the block cursor go away completely when in visual mode and just rely on the normal select mode (no decorator needed) because while it's not exactly like vim it still at least behaves in a predictable and understandable way.  As it is right now the only thing consistent thing is that it probably won't do what I want it to =]

Just FWIW.  I wish I had time to learn the specifics and help out a bit; I'm so swamped right now I barely see my kids.  Sorry to throw in opinions without offering to help.  Happy to test things, if that's helpful.

**Comment by m47730** [comment] 2017-06-06 07:07
@Chillee vimStyle definetely handles it better. Has some other glitches, but the copy&paste experience is definetely smoother (or at least usable).
I appreciate your hard work, but for me copy&paste is a must-have even with vi emulation; so i switched to this plugin. I still have your plugin installed, and every update i try if this major issue (for me) is fixed.
Please, not consider this comment as a rant, but a positive point of view

**Comment by Chillee** [comment] 2017-06-06 16:39
@m47730 What's wrong with using `y` for copy?

**Comment by paween1980** [comment] 2017-06-07 06:47
Finally, can cmd+v, double click (to select word) then cmd+p (to replace word) use? 

Now, I use copy with y and paste with p, it's work fine but it's not convenient. Because I use left hand to key command and right hand to move and select word. If I have to use y, p to copy, paste I have to use right hand to type them. My coding efficiency is reduce 15% :p

**Comment by snewell92** [comment] 2017-06-07 15:17
@paween1980 I'm not 100% on what you mean, but you can use `yiw` to yank in word. no selection required, cursor just needs to be anywhere in word. If you the cursor is at the first char, `yw` will work, if at the last char, `yb` will work. Than you can `dw` and `P` to replace another word with your yanked word quickly. This way both hands stay on the keyboard. :+1:

Keep yo hands off that mouse bruh! <3<3

🤷‍♂️
/$.02

**Comment by alexgorbatchev** [comment] 2017-06-07 15:59
I think the crux of the issue is that VIM key users split into two buckets:

1. People who "Keep yo hands off that mouse" :)
2. People who mix keyboard and mouse

I don't know what the actual split is, and i guess nobody does. Personally I switched to VIM keys 6 or so years ago, but I still use mouse pretty heavily. I can't call myself VIM key expert by any means, so to me it's either `1462G /attr <enter> ve` or I can point to `attr` and double click. I find the latter to be faster. The mouse is also used a lot for scrolling around.

**Comment by m47730** [comment] 2017-06-07 17:01
@Chillee i agree with @alexgorbatchev.
I'm not a vi purist, i don't know tons of magic combo, but it's the reason that i use vscode over gvim.
For example i don't use "hjkl" keys for navigation, i use the arrow keys.
I like the power of vi, but i also like the no-brain easy selection of mouse. :-)

**Comment by snewell92** [comment] 2017-06-07 20:00
Fair enough. That's each person's prerogative for sure.

My first instinct is to map double clicking to the `viw` command in normal mode instead of straddling visual selection VSCode way in visual mode, but proposing a change to make mouse clicking selection stay in normal mode rather than go into visual mode would be a huge shift. I'll need to go do my homework before I say anything else! xD Just a crazed idea 😃 

Hope people smarter than me can figure out a good compromise.

**Comment by Chillee** [comment] 2017-06-21 03:55
@snewell92 I think going into visual mode when something is selected is a good idea.

**Closed** 2017-06-24 07:16 UTC
Labels: area/selection-off-by-one, kind/bug
