### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 221

### ISSUE THREAD

**Issue by gcameron1962** [VSCodeVim/Vim#5798] opened 2020-12-01 15:11 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 221
	at Function.getLineLength (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:11622)
	at l.getLeftThroughLineBreaks (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:10872)
	at /home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:475270
	at Array.map (<anonymous>)
	at F.runAction (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:475217)
	at F.handleKeyAsAnAction (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:474805)
	at F.handleKeyEvent (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:231560)
	at async Object.runTasks (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
