### ISSUE TITLE
Key Bindings for Command Mode

### ISSUE THREAD

**Issue by azizj1** [VSCodeVim/Vim#5613] opened 2020-11-09 23:39 UTC
I would like to make a keybinding for "workbench.action.closeEditorsInGroup", which closes all files in a "tab". I'd like to do this via ":qt". I tried making the following key binding in `vim.normalModeKeyBindingsNonRecurisve` to no avail:
```
        }, {
          "before": [":", "q", "t"],
          "after": [],
          "commands": [{
            "command": "workbench.action.closeEditorsInGroup"
          }]
        }, {
```
I even tried `"before": [":qt"]`, but that also failed. Any suggestions?

**Comment by J-Fields** [comment] 2020-11-12 19:29
Duplicate of #4454

**Closed by J-Fields** 2020-11-12 19:29 UTC
