### ISSUE TITLE
Serious issues with Korean typing after the latest version(v1.26.0) update

### ISSUE THREAD

**Issue by Baejw0111** [VSCodeVim/Vim#8570] opened 2023-09-10 02:07 UTC
After updating to the latest version, when typing in korean, I have a problem with strange typing like below.

I hope to resolve this issue as soon as possible.

![vim_issue](https://github.com/VSCodeVim/Vim/assets/87963766/fe5e0cf1-feeb-4809-b6e9-27256d2a636d)

**Comment by slackjawed12** [comment] 2023-09-10 13:25
Occurs in version 1.26.0, not in version 1.25.2.

**Comment by polamjag** [comment] 2023-09-11 03:33
I'm experiencing similar problem while typing in Japanese.

https://github.com/VSCodeVim/Vim/assets/685936/3f63aff3-8340-40b4-a4a5-7661086056b1

(Copilot is activated in this video, but disabling Copilot did not change this behavior)

My environment:

- macOS 13.5.2 (22G91)
- VSCodeVim v1.26.0
- VS Code: Version: 1.82.0 (Universal) Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
- IME: Google 日本語入力 2.28.5050

**Comment by MH4GF** [comment] 2023-09-11 05:20
I am a Japanese speaking user and had the same problem. Then I downgraded the version to `vscodevim.vim@1.25.2` and it solved the problem.

My environment:

- macOS 13.4.1 (c)（22F770820d）
- VSCodeVim v1.26.0
- VS Code: Version: 1.81.1 Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- IME: default

**Comment by Baejw0111** [comment] 2023-09-11 06:11
Wow, by the way, I've never seen Japanese keyboard typing before. It's so interesting!

**Comment by hachi8833** [comment] 2023-09-11 06:58
I'm Japanese speaker and I also encounterd the same issue with Google IME (2.28.5050.1) and VSCodeVim v1.26.0.
The workaround is to downgrade VSCodeVim to v1.25.2 by now.

Seems like the symptom is irrelevant to Google IME, so this may occur with other Japanese (or Korean or other) IMEs.
I'm also afraid that the OS environment is irrelevant either.

## Steps to reproduce

- VSCodeVim : v1.26.0
- VSCode: 1.82.0
- Some Japanese IME such as Google IME
- OS: macOS Ventura 13.5.2

1. Open the VSCode and switch to Japanese IME mode.
2. Enter `koreranofairuha` via IME（meaning `これらのファイルは`, equivalent to `These files are`）
3. Press `Space` key to convert the text, showing the result `これらのファイルは`
4. Immediately enter `,` via IME and press `Space` key to convert the comma.

> Note that step 3. and 4. should be performed continuously to reproduce the issue.
If you wait around 1 or more seconds between step 3. and 4, the issue may not be reproduced. 

* Expected result: `これらのファイルは、`, with the trailing big comma.
* Actual result: `、これらのファイルは、`, which of the leading big comma `、` is redundant

FYI: the entire result of the  incorrect `、これらのファイルは、` is targeted for undo-buffer, so pressing Command-Z erases the entire `、これらのファイルは、` . The fact disturbs me when fixing the results.

Best regards,

**Comment by hachi8833** [comment] 2023-09-11 09:26
FYI: I see the following similar issues in Korean:

https://github.com/VSCodeVim/Vim/issues/8577
https://github.com/VSCodeVim/Vim/issues/8571

**Comment by jmatsuzawa** [comment] 2023-09-12 03:00
I've got the same issue using Japanese Microsoft IME on Windows 10.

**Comment by Kimnabin** [comment] 2023-09-13 02:58
Since it may take some time to be fixed, here's a small workaround: use previous version
I deleted the vim extension from VSCode and ran this command in the terminal.

code --install-extension vscodevim.vim@1.25.2

This should do until the issue is resolved.
Happe Coding.

for Mac users

to enable the code command in the terminal, you need to cmd + shift + p and choose Shell Command: Install 'code' command in PATH
also cmd  + shift + p and select Extensions: Disable Auto Update for All Extensions to prevent auto update

**Comment by Baejw0111** [comment] 2023-09-13 07:54
@Kimnabin 터미널 안써도 vscode 내에서도 다운그레이드가 가능합니다. 참고하세요.

![image](https://github.com/VSCodeVim/Vim/assets/87963766/1208de73-0bce-4035-9ef7-29a9812d8ed6)

**Comment by xsrvmy** [comment] 2023-09-13 15:38
This is a problem with Chinese as well. I am using RIME on windows. It seems that the problem occurs if the IME translates the input string into the target character without pressing the space key (such as when using wubi), so I can see why this would happen with Korean.

**Comment by nebocco** [comment] 2023-09-15 06:54
same here in Japanese

**Comment by xsrvmy** [comment] 2023-09-15 17:58
BTW disable vim mode doesn't fix the problem. Only disabling the extension completely fixes it.

**Comment by hojongs** [comment] 2023-09-16 05:09
I am also experiencing the same problem (Korean)

**Comment by rosenbaum** [comment] 2023-09-20 00:09
I use a tool for text expansion called Espanso - https://espanso.org which replaces strings of text using match rules (e.g. `:uuid` replaces the string with a random UUID).

I was seeing similar errors, and I suspect it's related to this ticket.  Downgrading the extension solved the issues I was facing.

**Comment by brandonwie** [comment] 2023-09-22 07:47
> Since it may take some time to be fixed, here's a small workaround: use previous version I deleted the vim extension from VSCode and ran this command in the terminal.
> 
> code --install-extension vscodevim.vim@1.25.2
> 
> This should do until the issue is resolved. Happe Coding.
> 
> for Mac users
> 
> to enable the code command in the terminal, you need to cmd + shift + p and choose Shell Command: Install 'code' command in PATH also cmd + shift + p and select Extensions: Disable Auto Update for All Extensions to prevent auto update

@Kimnabin Dude, I'm not even saying my comment is worth mentioning or whatever, it's just about using the previous version. However, it's a weird experience seeing someone actually copying and pasting 100% of my comment and using it as if you wrote it. 😂 Happy Coding man.

[Link to the comment](https://github.com/VSCodeVim/Vim/issues/8571#issuecomment-1713113963)

**Comment by lsahn-gh** [comment] 2023-09-30 14:04
Thanks to @Kimnabin, it works well!

**Comment by makotot** [comment] 2023-10-05 08:03
At least in this case, [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim) seems to work without any problems, so if you have no problem changing the extenstion, you may want to use that one.

**Comment by maskelog** [comment] 2023-10-07 11:43
The same problem occurs in version 1.26. I have no problem with the 1.25.1 version.

**Comment by J-Fields** [comment] 2023-10-10 00:54
This should be fixed in v1.26.1

**Closed by J-Fields** 2023-10-10 00:54 UTC

**Comment by mun9769** [comment] 2023-11-26 07:34
> @Kimnabin 터미널 안써도 vscode 내에서도 다운그레이드가 가능합니다. 참고하세요.

I downgrade the vsvim version@1.25.2, but it doesn't work... anyone solve this?

**Comment by Baejw0111** [comment] 2023-11-26 08:33
> > @Kimnabin 터미널 안써도 vscode 내에서도 다운그레이드가 가능합니다. 참고하세요.
> 
> I downgrade the vsvim version@1.25.2, but it doesn't work... anyone solve this?


The version has been updated and the problem has already been resolved.
