### ISSUE TITLE
Visual mode indents are incorrect when visual selection is done backwards/upwards

### ISSUE THREAD

**Issue by k0ala** [VSCodeVim/Vim#2182] opened 2017-11-29 11:58 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT** :

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: El Capitan

**What happened**:

```
// WHEN DOING FORWARD VISUAL SELECT, REPEAT WORKS AS EXPECTED

// start file, four lines:
a
b
c
d

// visual select lines b and c with Shift-V 
// (starting at line b) and indent with '>':
a
  b
  c
d

// repeat action by pressing '.', indents lines b and c again, as expected:
a
    b
    c
d


// WHEN DOING BACKWARD VISUAL SELECT, REPEAT DOES NOT WORK AS EXPECTED

// start file, four lines:
a
b
c
d

// visual select lines b and c with Shift-V 
// (starting at line c) and indent with '>':
a
  b
  c
d

// repeat action by pressing '.', indents lines a and b instead of b and c: 
  a
    b
  c
d
```

**What did you expect to happen**: 

I expected the result of repeating the indentation (both with forward and backward visual selection) to be the following:

```
a
    b
    c
d
```

**How to reproduce it**:

See above.

**Comment by Chillee** [comment] 2017-11-29 18:58
I believe this is a duplicate of https://github.com/VSCodeVim/Vim/issues/549.

Closing for issue maintenance. Thanks!

**Closed by Chillee** 2017-11-29 18:58 UTC

**Comment by k0ala** [comment] 2017-11-29 19:06
Indeed! apologies
