### ISSUE TITLE
2gt not goes to the right tab

### ISSUE THREAD

**Issue by sumanx** [VSCodeVim/Vim#2789] opened 2018-06-29 02:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug.

**What happened**:
command "2gt" not navigates to the 2nd tab, but to the 3rd tab like 3gt.
3gt navigates to the 3rd tab.

**What did you expect to happen**:

2gt goes to the 2nd tab.
3gt goes to the 3rd tab.

- Extension (VsCodeVim) version: latest version
- VSCode version: latest version

**Comment by xconverge** [comment] 2018-07-05 18:55
can you confirm that gT DOES work as intended? To me gt with a count acts very unpredictably, but gT works "perfectly". So the fix for this can be modeled by comparing gt to gT which has some slight differences for some reason

**Comment by bluetech** [comment] 2018-07-25 17:41
@xconverge I don't think this is fixed. I am using VsCodeVim version 0.15.7.

#### What happened:

`10gt` goes to the next tab 10 times. For example if I am at tab 5 then `10gt` gets me to tab 15.

#### What did you expect to happen:

The `<count>` in `<count>gt` should not behave like a repeat count, it should behave like an index. For example if I am at tab 5, or any other tab, then `10gt` should get me to tab 10.

Note: unlike `<count>gt`, the count in `<count>gT` *does* behave like a repeat count and not like an index.

In order to try this in `vim`, just run `:tabnew` a few times and see how `<count>gt` behaves.

See also the Vim documentation: http://vimdoc.sourceforge.net/htmldoc/tabpage.html#:tabnext

**Comment by xconverge** [comment] 2018-07-25 17:49
Ah you are absolutely right! I expected gT and gt to behave the same!

From the docs:

```
gT		Go to the previous tab page.  Wraps around from the first one
		to the last one.
{count}gT	Go {count} tab pages back.  Wraps around from the first one
		to the last one.
```

```
gt		Go to the next tab page.  Wraps around from the last to the
		first one.
{count}gt	Go to tab page {count}.  The first tab page has number one.
```

**Comment by xconverge** [comment] 2018-07-27 02:57
Does anyone ever use more than 9 tabs? Filed this just incase

https://github.com/Microsoft/vscode/issues/55205

**Closed** 2018-07-27 03:18 UTC
Labels: kind/bug

**Comment by bluetech** [comment] 2018-07-27 06:17
Thank you @xconverge!
