### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by zodiake** [VSCodeVim/Vim#5990] opened 2021-01-13 09:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:200309)
	at h._isDocumentTextNeeded (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:203302)
	at h.addChange (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:203495)
	at F.handleKeyAsAnAction (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:169454)
	at F.handleKeyEvent (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167823)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
	at async Object.runTasks (c:\Users\wangq20\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
