### ISSUE TITLE
Cannot read property 'getNextSearchMatchPosition' of undefined

### ISSUE THREAD

**Issue by euccas** [VSCodeVim/Vim#5428] opened 2020-10-16 01:37 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'getNextSearchMatchPosition' of undefined
	at F.updateView (/Users/euccaschen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:490400)
	at _ (/Users/euccaschen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/euccaschen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235688)
	at async Object.runTasks (/Users/euccaschen/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:01
Duplicate of #5310

**Closed by J-Fields** 2020-11-12 23:01 UTC
Labels: status/duplicate
