### ISSUE TITLE
Failed to handle key=L. Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by Mwarumba-H** [VSCodeVim/Vim#6527] opened 2021-04-22 07:52 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=L. Cannot read property 'active' of undefined
    at Oe.execActionWithCount (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\actions\motion.ts:90:59)
    at I.executeMovement (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:952:37)
    at runMicrotasks (<anonymous>)
    at process.recordedState (internal/process/task_queues.js:97:5)
    at I.actionToRecord [as runAction] (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:718:7)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:651:43)
    at I.text [as handleKeyEvent] (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:471:11)
    at Object.promise (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\extensionBase.ts:373:73)
    at Object.runTasks (c:\Users\harry\.vscode\extensions\vscodevim.vim-1.20.0\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-22 15:44
Duplicate of #6454

**Closed by J-Fields** 2021-04-22 15:44 UTC
