### ISSUE TITLE
Failed to handle key=<Esc>. Promise.allSettled is not a function

### ISSUE THREAD

**Issue by jiangbojacob** [VSCodeVim/Vim#6602] opened 2021-05-08 16:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Promise.allSettled is not a function
    at H.exec (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/actions/commands/actions.ts:404:23)
    at H.execCount (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/actions/base.ts:218:20)
    at j.runAction (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:724:20)
    at j.handleKeyAsAnAction (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:655:16)
    at j.handleKeyEvent (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/mode/modeHandler.ts:471:40)
    at process.async (internal/process/task_queues.js:89:5)
    at Object.promise (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/extensionBase.ts:628:27)
    at Object.runTasks (/home/yungao.wjb/gdisk-mnt/test/.vscode-server/extensions/vscodevim.vim-1.20.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-05-09 03:14
Duplicate of #6489

**Closed by J-Fields** 2021-05-09 03:14 UTC
