### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by malikabakhtiyorova** [VSCodeVim/Vim#6239] opened 2021-03-06 10:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
    at Object.k [as illegalArgument] (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)
    at new m (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:12337)
    at new m (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:11705)
    at a (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
    at F.exec (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at S.exec (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:460560)
    at S.execCount (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355705)
    at F.runAction (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
    at F.handleKeyAsAnAction (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/home/utrujjah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
