### ISSUE TITLE
Failed to handle key `o`: Cannot read property 'selections' of undefined

### ISSUE THREAD

**Issue by xplosionmind** [VSCodeVim/Vim#7235] opened 2021-11-05 15:18 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `o`: Cannot read property 'selections' of undefined
    at getCursorsAfterSync (/Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/src/util/util.ts:12:42)
    at Qe.execCount (/Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/src/actions/commands/actions.ts:1570:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at j.actionToRecord [as runAction] (/Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/src/mode/modeHandler.ts:713:47)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/src/mode/modeHandler.ts:662:43)
    at j.text [as handleKeyEvent] (/Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/src/mode/modeHandler.ts:477:11)
    at /Users/tommi/.vscode-oss/extensions/vscodevim.vim-1.21.10/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 02:09
Duplicate of #6139

**Closed by J-Fields** 2022-03-09 02:09 UTC
Labels: status/duplicate
