### ISSUE TITLE
<C-n> and <C-p> for autocomplete does not work

### ISSUE THREAD

**Issue by milesxu** [VSCodeVim/Vim#4014] opened 2019-08-29 04:07 UTC
**Describe the bug**
After updated the Vscode VIM to 1.10, I found that the `<C-n>` and `<C-p>` shortcuts for autocomplete does not work new.
Whenever I use `<C-n>`, a new file will always be created; and when I use `<C-p>`, file select dialog will be displayed.
**I cannot select items in autocomplete menu now.**

**To Reproduce**

1.  In a source code file, input some code until the autocomplete menu is displayed.
2.  use `<C-n>` or `<c-p>`
3.  then we can find they does not work

**Expected behavior**
`<C-n>` and `<C-p>` can be used to select items in autocomplete menu.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.0
- VSCode version: 1.37.1
- OS: Manjaro x86-64

**Additional context**

**Comment by J-Fields** [comment] 2019-08-29 04:11
Duplicate of #4011

**Closed by J-Fields** 2019-08-29 04:11 UTC
Labels: kind/bug, status/duplicate
