### ISSUE TITLE
Failed to handle key=<up>. getLineLength() called with out-of-bounds line 84

### ISSUE THREAD

**Issue by asdaudit** [VSCodeVim/Vim#5701] opened 2020-11-19 10:31 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<up>. getLineLength() called with out-of-bounds line 84
    at Function.getLineLength (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getUpWithDesiredColumn (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
    at V.execAction (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:191010)
    at V.createMovementResult (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
    at V.execActionWithCount (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
    at F.executeMovement (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
    at F.runAction (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
    at F.handleKeyAsAnAction (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/fjavierruizredondo/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-24 17:43
Duplicate of #5180. If you can reproduce, please post steps on that ticket.

**Closed by J-Fields** 2020-11-24 17:43 UTC
Labels: status/duplicate
