### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by maugravena** [VSCodeVim/Vim#3651] opened 2019-04-03 21:28 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `~/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-04-04 21:50
Dupe of https://github.com/VSCodeVim/Vim/issues/3362 and there is also no cpuprofile attached...

**Closed by jpoon** 2019-04-04 21:50 UTC
