### ISSUE TITLE
smartRelativeLine setting counts folded lines but jump n lines doesn't

### ISSUE THREAD

**Issue by freezlite** [VSCodeVim/Vim#6849] opened 2021-07-07 11:53 UTC
**Describe the bug**
When some lines folded(e.g function) plugin still counts folded lines, but when you try to jump over n lines you will be much lower then you expected.

**To Reproduce**
Set  in settings: 
```
{
    "vim.foldfix": true,
    "vim.smartRelativeLine": true,
}
````
And jump over folded lines

**Expected behavior**
jump to n lines consistent with number of lines shown with smartRelativeLine setting

**Screenshots**
![Peek 2021-07-07 14-48](https://user-images.githubusercontent.com/3983804/124754351-c74cf380-df32-11eb-85f0-aba52ad39753.gif)

**Environment:**

- Extension (VsCodeVim) version:
- VSCode version: 1.21.5
- OS: ubuntu

**Comment by J-Fields** [comment] 2021-10-15 20:24
Duplicate of #5722

**Closed by J-Fields** 2021-10-15 20:24 UTC
Labels: status/duplicate, upstream/vscode
