### ISSUE TITLE
 INSERT MODE ctrl+d don't  add Selection To Next Find Match

### ISSUE THREAD

**Issue by zhouxq555** [VSCodeVim/Vim#1535] opened 2017-04-20 06:32 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

In INSERT MODE click ctrl+d don't  **add Selection To Next Find Match** 
just like VScode default setting

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *[please ensure you are on the latest]* latest
* OS:  win10 64

**Comment by zhouxq555** [comment] 2017-04-20 07:06
//vim config
    "vim.easymotion": true,
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": false,
    "vim.hlsearch": true,
    "vim.startInInsertMode": true,
    "vim.insertModeKeyBindings": [
        {
            "before": [
                "j",
                "j"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ],
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": [
                "<leader>",
                "d"
            ],
            "after": [
                "d",
                "d"
            ]
        },
        {
            "before": [
                "<C-n>"
            ],
            "after": [],
            "commands": [
                {
                    "command": ":nohl"
                }
            ]
        }
    ],
    "vim.leader": "<space>",
    "vim.handleKeys": {
        "<C-a>": false,
        "<C-f>": false,
        "<C-d>": false
    }

**Comment by RodrigoRoaRodriguez** [comment] 2017-04-24 06:44
I think this is a duplicate of #1311. However what I find strange is that you have `"vim.handleKeys": {"<C-d>": false}` which is a workaround for this issue but results in #1467 nonetheless, hence not really solving the problem of multi-cursor functionality in insert mode.

**Comment by Chillee** [comment] 2017-04-29 05:24
The problem with implementing this is that in order to do a ctrl+d, vscode needs to select the word first.

However, for us, selecting a range necessarily puts us into visual mode (I think). It's fairly trivial to enable D-d in insert mode, but that would drop you into visual mode.

I'll try to find a solution, but it might be difficult.

**Closed** 2017-05-09 06:23 UTC
Labels: kind/bug

**Comment by binarious** [comment] 2017-05-12 12:54
This still doesn't work for me.

Without vim (as expected):
![withoutvim](https://cloud.githubusercontent.com/assets/200375/25998734/ace05e04-3722-11e7-8fda-bb31c9f2b345.gif)

With vim (only adds selection to the whole word):
![withvim](https://cloud.githubusercontent.com/assets/200375/25998759/bc5b7350-3722-11e7-812f-23d60a84c348.gif)

**Comment by Chillee** [comment] 2017-05-16 05:21
@binarious That's a bit different of an issue. Could you open up another issue for that?

**Comment by binarious** [comment] 2017-05-16 17:38
Ok, done: https://github.com/VSCodeVim/Vim/issues/1705

**Comment by dytra** [comment] 2020-01-22 07:01
> I think this is a duplicate of #1311. However what I find strange is that you have `"vim.handleKeys": {"<C-d>": false}` which is a workaround for this issue but results in #1467 nonetheless, hence not really solving the problem of multi-cursor functionality in insert mode.
this solution works if you have vim installed
