### ISSUE TITLE
[insert mode] ALT+Delete followed by a DELETE removes wrong character

### ISSUE THREAD

**Issue by awinecki** [VSCodeVim/Vim#5658] opened 2020-11-15 20:18 UTC
**Describe the bug**

With VIM extension enabled, when I go to insert mode, deleting **whole words** with ALT modifier key (ALT+Delete) deletes the world correctly, but if I **release the ALT** and do one more Delete right after, it deletes a character at a wrong position.

**To Reproduce**

1. Create a new file, e.g. an HTML with the following code:
```
    <div class="container mx-auto pt-20 bg-gray-500 max-w-screen-lg min-h-screen">
```
2. Place the cursor on `mx-auto[]`
3. Press and hold ALT
4. Press DELETE / BACKSPACE (I'm on macOS so DELETE) ; `auto` should get deleted
5. Release ALT key
6. Press DELETE one more time; `-` gets deleted from a nearby `pt-20` **[WRONG BEHAVIOUR, should delete `-` from `mx-`**

**Expected behavior**

Since the cursor is at `mx-[]` position, it should delete `-` from there.

**Screenshots**

![nj-screenshot 2020-11-15 at 21 07 45](https://user-images.githubusercontent.com/656694/99195530-a444b800-2786-11eb-9b6c-70b6cd1aa995.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: Version: 1.51.1, Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- OS: macOS Big Sur 11.0.1 (I've just upgraded; this was happening before on Catalina as well)

**Additional context**

My "running extensions":

![nj-screenshot 2020-11-15 at 21 16 05@2x](https://user-images.githubusercontent.com/656694/99195723-cdb21380-2787-11eb-9dda-1daf8676ff67.png)

_P.S.: I'm extremely grateful for this plugin – let me know if you can reproduce this guys; it seems pretty annoying to me. If I can help in any way, let me know. I might find a moment to try to tackle it myself, but I haven't hacked around vscode yet, so it'll be a struggle 😓_ 

Also, I'm guilty – I haven't yet tried installing a raw install of vscode with just vscodevim plugin to check this happens. So it's possible some of my setup seems to conflict with this (I'll try this when I find a moment).

**Comment by leighmcculloch** [comment] 2020-12-06 07:57
I think this delete other characters happens in other situations too, not just in the ALT situation, so. 

I've noticed that auto-complete is another case that is happening sometimes for me. If I auto-complete a word in insert mode, then press back, it deletes the last character I typed rather than the last character auto-completed. I've just tried to replicate it, without success. I'll capture a screen recording the next time it happens.

**Comment by berknam** [comment] 2020-12-06 19:16
This should be related to an issue that has been fixed with #5250 and #5814. It should be out on the next version.

**Comment by berknam** [comment] 2020-12-07 18:46
Versions "1.18.x" out now should have fixed this. Can any of you check if this is still happening on the newer versions?

**Comment by leighmcculloch** [comment] 2020-12-08 02:10
@berknam I've upgraded. I'll keep an eye out for it. It wasn't occurring consistently for me and was intermittent, so I probably won't know for a little while if it's fixed or not. I'll keep an eye on it and if you close this issue I'll reopen it if I see it occur again.

**Comment by Xetera** [comment] 2020-12-10 01:26
This happens to me when ctrl + backspace deleting. If you're having the same issue, vim actually lets you use `C-w` in edit mode to delete the last word so you can use that without running into bugs but the ctrl backspace is a tough habit to break.

**Comment by berknam** [comment] 2020-12-10 02:09
> 
> 
> This happens to me when ctrl + backspace deleting. If you're having the same issue, vim actually lets you use `C-w` in edit mode to delete the last word so you can use that without running into bugs but the ctrl backspace is a tough habit to break.

@Xetera Are you using the latest version (1.18.4)? I can use `<C-BS>` without a problem and any subsequent backspace or delete works as intended.

**Comment by Xetera** [comment] 2020-12-10 13:43
Just updated it and I haven't been getting it so far, looks like this is fixed 👌.

**Comment by awinecki** [comment] 2020-12-16 09:16
@berknam Upgraded to v1.18.5. Seems to be working fine! Thanks!

**Closed** 2020-12-16 09:16 UTC
