### ISSUE TITLE
Viewport/Scrollposition should not change during typing in "/"-search mode

### ISSUE THREAD

**Issue by CombeeMike** [VSCodeVim/Vim#5207] opened 2020-09-21 19:12 UTC
**Disclaimer first:** I'm a pretty new user of this extension and VIM in general and I'm not sure whether this is a bug report or a mere ask for help 🤷‍♂️

**The Issue**
When searching using `/searchterm`, the viewport sometimes jumps around during entering the search term (before pressing `enter`). This does not happen in "pure" VIM on my Ubuntu Bash so I'm not sure whether this is an issue with the extension, a configuration issue on my side or something else (interference with some other extensions etc.).

**To Reproduce**

![2020-09-21_20h57_17](https://user-images.githubusercontent.com/30658772/93809109-2c0dba80-fc4d-11ea-9cbe-5e6babccae66.gif)

In that GIF you can see that I only type `/some` (2 times, finishing both with `esc`, no `enter`) which causes the viewport to jump around multiple times which I find highly disruptive.

**Expected behavior**
Viewport/Scroll position should not change until I press `enter` and "submit" my search.

**Environment:**

- Extension (VsCodeVim) version: `v1.16.0`
- VSCode version: `1.49.1`
- OS: `Win 10, v2004 (OS build 19041.508)`

**Ps.:**
Feel free to suggest a better title. I'm not that familiar yet with VIM vocabulary so there's probably something more technical correct than `"/"-search mode` 😉

**Comment by J-Fields** [comment] 2020-12-09 20:19
`incsearch` should control this, but it's implemented incorrectly. Closing as a duplicate of #3049, I'll try to get around to fixing this soon.

**Closed by J-Fields** 2020-12-09 20:19 UTC
