### ISSUE TITLE
getLineLength() called with out-of-bounds line 125

### ISSUE THREAD

**Issue by gcameron1962** [VSCodeVim/Vim#5697] opened 2020-11-18 20:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 125
	at Function.getLineLength (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at l.getLeftThroughLineBreaks (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
	at Object.t.statusBarCommandText (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31413)
	at Object.updateShowCmd (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
	at F.handleKeyEvent (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/gcameron/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-24 17:43
Duplicate of #5180. If you can reproduce, please post steps on that ticket.

**Closed by J-Fields** 2020-11-24 17:43 UTC
Labels: status/duplicate
