### ISSUE TITLE
Failed to handle key=f. Failed to handle key=a. Illegal value for `line`

### ISSUE THREAD

**Issue by tyetyetye** [VSCodeVim/Vim#5919] opened 2020-12-22 17:06 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=f. Failed to handle key=a. Illegal value for `line`
    at d._lineAt (c:\Users\jtye\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
    at Object.lineAt (c:\Users\jtye\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
    at Function.getFirstNonWhitespaceCharOnLine (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:14610)
    at Y.execAction (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:203117)
    at Y.createMovementResult (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:153324)
    at Y.execActionWithCount (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:152981)
    at F.executeMovement (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:175649)
    at F.runAction (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171527)
    at F.handleKeyAsAnAction (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170985)
    at F.handleKeyEvent (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167823)
    at F.handleMultipleKeyEvents (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:166052)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at m.handleRemapping (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:193159)
    at m.sendKey (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:191368)
    at t.Remappers.sendKey (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:187784)
    at F.handleKeyEvent (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167480)
    at Object.promise (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
    at Object.runTasks (c:\Users\jtye\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:49
Duplicate of #6178

**Closed by J-Fields** 2021-03-24 17:49 UTC
