### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by reza-akbari** [VSCodeVim/Vim#6792] opened 2021-06-24 08:06 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at s._applyEdit (...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52514)
    at Object.edit (...\AppData\Local\Programs\Microsoft VS Code\resou

**Comment by J-Fields** [comment] 2021-07-23 04:46
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:46 UTC
