### ISSUE TITLE
[feature]: `:e` -> `File: Revert File`

### ISSUE THREAD

**Issue by NGenetzky** [VSCodeVim/Vim#3264] opened 2018-12-13 22:37 UTC
**Is your feature request related to a problem? Please describe.**
I hate when I do `:e` and it tries to open a file in the current directory. In vim this will reload the current file. Incidentally `File: Revert File` for vscode also does this behavior.

**Describe the solution you'd like**
Have `:e` trigger `File: Revert File` when there is no argument to `:e`. For instance, `:e ./filename.txt` should probably still open a file.

**Describe alternatives you've considered**
Use `File: Revert File`

**Comment by jpoon** [comment] 2018-12-30 08:17
Dupe of https://github.com/VSCodeVim/Vim/issues/3178

**Closed by jpoon** 2018-12-30 08:17 UTC
Labels: status/duplicate
