### ISSUE TITLE
Failed to handle key `g`: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by wugensheng-code** [VSCodeVim/Vim#7511] opened 2022-02-17 06:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `g`: Cannot read property 'start' of undefined
    at t.SearchByCharCommand.exec (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/plugins/easymotion/easymotion.cmd.ts:82:70)
    at t.SearchByCharCommand.fire (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/plugins/easymotion/easymotion.cmd.ts:169:16)
    at g.exec (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/plugins/easymotion/easymotion.cmd.ts:335:20)
    at process.j (internal/process/task_queues.js:93:5)
    at g.execCount (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/base.ts:229:42)
    at j.actionToRecord [as runAction] (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:714:47)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:663:43)
    at j.text [as handleKeyEvent] (/home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:478:11)
    at /home/shinu/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:372:73
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 01:38
Duplicate of #7461

**Closed by J-Fields** 2022-03-09 01:38 UTC
