### ISSUE TITLE
Dot command does not respect tab-insertion

### ISSUE THREAD

**Issue by jeremyong** [VSCodeVim/Vim#5109] opened 2020-08-04 03:28 UTC
**Describe the bug**
Dot commands do not respect insertion of tabs or 4-spaces due to a `tab` keypress in any context

**To Reproduce**
1. Enter insert mode (`I` or `i` or `o`, etc.)
2. Insert a tab character or four spaces by pressing the tab key
3. Return to normal mode
4. Invoke the `.` command

**Expected behavior**
The action should repeat

**Environment (please complete the following information):**

Reproduces on Windows and Linux

**Comment by J-Fields** [comment] 2020-08-04 16:45
Duplicate of #2337

**Closed by J-Fields** 2020-08-04 16:45 UTC
