### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by sim218664xslnokey** [VSCodeVim/Vim#6141] opened 2021-02-14 15:12 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.18.9<details><summary>Stack trace</summary>```Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!at I._applyEdit (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:36773)at I.edit (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:36308)at y.execute (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:782440)at F.runAction (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707900)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:97:5)at async F.handleKeyAsAnAction (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)at async F.handleKeyEvent (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)at async Object.promise (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)at async Object.runTasks (/home/retr0/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)```</details>

**Comment by sim218664xslnokey** [comment] 2021-02-14 15:17
I accidentally press CTRL+a 
![Bildschirmfoto von 2021-02-14 16-12-58](https://user-images.githubusercontent.com/63190694/107880589-15a81a00-6ee0-11eb-917b-c774204b6099.png)

**Comment by J-Fields** [comment] 2021-02-18 23:22
Duplicate of #5224. What were you trying to do when this happened? (What mode were you in? Did you have multiple cursors?)

**Closed by J-Fields** 2021-02-18 23:22 UTC
