### ISSUE TITLE
Failed to handle key=j. Cannot read property 'searchString' of undefined

### ISSUE THREAD

**Issue by melodyVoid** [VSCodeVim/Vim#5371] opened 2020-10-10 02:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=j. Cannot read property 'searchString' of undefined
    at k.exec (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:436870)
    at k.execCount (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
    at F.runAction (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
    at F.handleKeyAsAnAction (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/botao/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 03:25
What were you trying to do when this happened? Can you reproduce?

**Comment by J-Fields** [comment] 2020-10-14 03:26
Duplicate of #5351

**Closed by J-Fields** 2020-10-14 03:26 UTC
