### ISSUE TITLE
Failed to handle key=<BS>. Illegal value for `line`

### ISSUE THREAD

**Issue by yash19pro** [VSCodeVim/Vim#5905] opened 2020-12-18 14:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at _.exec (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:196742)
	at _.execCount (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24652)
	at F.runAction (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171589)
	at F.handleKeyAsAnAction (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/Users/yashpatel/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
