### ISSUE TITLE
Paste [cmd+v] to selected word not replace to last character (blink cursor)

### ISSUE THREAD

**Issue by paween1980** [VSCodeVim/Vim#1798] opened 2017-06-02 08:54 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT.

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: macOS 10.11.6

**What happened**:
When I paste [cmd+v] something to selected word not replace to last character (on blinking cursor).
For example, I copy word, 'ABC' and I need to replace it to 'XYZ'. I double click to 'XYZ'. Word, 'XYZ' shall be selected and cursor blinks on 'Z'. When I parse by cmd+v on it, final word will be 'ABCZ' with cursor blink on Z. Actually, it should be 'ABC' not 'ABCZ'.

**What did you expect to happen**: 
Replace word should completely fill until last character which cursor blink on.

**How to reproduce it**:
Copy word ABC and replace it on XYZ by cmd+v. The result word should be ABC not ABCZ.

**Comment by Chillee** [comment] 2017-06-02 15:54
I'm going to close this issue as a duplicate of this one: https://github.com/VSCodeVim/Vim/issues/1590

Thanks for the feedback!

**Closed by Chillee** 2017-06-02 15:54 UTC
