### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by vip2514287** [VSCodeVim/Vim#6278] opened 2021-03-15 10:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
    at Object.k [as illegalArgument] (i:\Program Files (x86)\vscode\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
    at new m (i:\Program Files (x86)\vscode\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:12337)
    at new m (i:\Program Files (x86)\vscode\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:11705)
    at a (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:360191)
    at F.exec (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:360236)
    at S.exec (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:460568)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at S.execCount (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:355705)
    at F.runAction (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707788)
    at F.handleKeyAsAnAction (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707179)
    at F.handleKeyEvent (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704015)
    at Object.promise (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:346362)
    at Object.runTasks (c:\Users\alva\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:02
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:02 UTC
Labels: status/duplicate
