### ISSUE TITLE
Changing into insert mode does not indent

### ISSUE THREAD

**Issue by c10b10** [VSCodeVim/Vim#2652] opened 2018-05-12 22:15 UTC
Entering into insert mode by using a `change inner` command should place the caret at the proper indentation. Currently it is placed at the beginning of the line.

**Comment by FlyingFishBird** [comment] 2019-08-21 02:38
I find the same issue.

**Comment by J-Fields** [comment] 2019-08-21 03:04
If I understand correctly, this is a duplicate of https://github.com/VSCodeVim/Vim/issues/3934

**Comment by J-Fields** [comment] 2019-12-30 22:14
Closed in favor of #3934

**Closed by J-Fields** 2019-12-30 22:14 UTC
