### ISSUE TITLE
Failed to handle key=<. getLineLength() called with out-of-bounds line 522

### ISSUE THREAD

**Issue by jjamshidi** [VSCodeVim/Vim#5478] opened 2020-10-23 23:52 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<. getLineLength() called with out-of-bounds line 522
	at Function.getLineLength (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.executeOperator (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480756)
	at F.runAction (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476279)
	at F.handleKeyAsAnAction (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/jjamshidi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:59
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:59 UTC
