### ISSUE TITLE
Feature request: allow hiding of mode indicator in status bar

### ISSUE THREAD

**Issue by ismay** [VSCodeVim/Vim#1922] opened 2017-07-12 13:06 UTC
I've not been able to find in the docs that this is currently a possibility. For me the cursor indicates clearly whether I'm in insert mode or not, so I'd prefer hiding the mode indicator.

Would be nice if it were configurable. Maybe `noshowmode` is appropriate since that's what vim uses.

**Comment by Chillee** [comment] 2017-07-13 22:05
This is a duplicate of https://github.com/VSCodeVim/Vim/issues/1576. I'm going to close this issue in favor of that one due to age.

Thanks!

**Closed by Chillee** 2017-07-13 22:05 UTC

**Comment by ismay** [comment] 2017-07-14 06:30
Cool, thanks!
