### ISSUE TITLE
'Error running task' in 1.13.0

### ISSUE THREAD

**Issue by Dustii77** [VSCodeVim/Vim#4630] opened 2020-03-07 20:20 UTC
When navigating in Normal Mode, I randomly get some variation of the following error:
> TaskQueue: Error running task. Failed to handle key=d. Unknown PositionDiffType: 2.

When this happens, the editor loses focus and doesn't recognize my key strokes until it is refocused.

I'm unable to reproduce the issue consistently. It happens very often, perhaps every other time I go from Insert Mode -> Normal Mode -> Insert Mode. 

My temporary solution is downgrading to 1.12.4.

- Extension (VsCodeVim) version: 1.13.0
- VSCode version: 1.42.1
- OS: Windows

**Comment by J-Fields** [comment] 2020-03-08 16:04
Do you have `startofline = false`?

**Comment by Dustii77** [comment] 2020-03-08 17:50
I did. I've just removed that line and reloaded 1.13.0. No error yet.

**Comment by J-Fields** [comment] 2020-03-08 17:51
Closing as the root cause is identical to #4607

**Closed by J-Fields** 2020-03-08 17:51 UTC
Labels: kind/bug
