### ISSUE TITLE
C-w, v not working recently

### ISSUE THREAD

**Issue by bluddy** [VSCodeVim/Vim#9105] opened 2024-07-01 13:11 UTC
**Describe the bug**
Pressing ctrl-w,v no longer splits the window vertically. AFAIK I didn't change anything. I'm on the latest vscode (1.90.2) and vim extension (1.27.3) versions.

**To Reproduce**
Press C-w,v

**Expected behavior**
A new vertical split is made.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.27.3
- VSCode version: 1.90.2
- OS: Windows 10

**Additional context**

**Comment by J-Fields** [comment] 2024-07-01 14:04
Duplicate of #9061

**Closed by J-Fields** 2024-07-01 14:04 UTC
