### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by hritikvalluvar** [VSCodeVim/Vim#6233] opened 2021-03-05 04:45 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
	at p._lineAt (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:1166)
	at Object.lineAt (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:95)
	at x.delete (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:519744)
	at x.run (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:520516)
	at F.executeOperator (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.runAction (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
	at async F.handleKeyAsAnAction (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/home/hritikvalluvar/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:31
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:31 UTC
