### ISSUE TITLE
Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()

### ISSUE THREAD

**Issue by luongcongthi** [VSCodeVim/Vim#5533] opened 2020-10-30 04:27 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()
    at sr.getSearchRanges (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:135742)
    at sr.exec (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:133874)
    at sr.execCount (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37406)
    at x.exec (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:214331)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.execCount (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37395)
    at F.runAction (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
    at F.handleKeyAsAnAction (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\User03\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:21
Duplicate of #5397, please post steps there if you can reproduce.

**Closed by J-Fields** 2020-11-12 23:21 UTC
