### ISSUE TITLE
Failed to handle key=M. Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by gsbakshi** [VSCodeVim/Vim#5960] opened 2021-01-04 19:22 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=M. Cannot read property 'active' of undefined
    at Ie.execActionWithCount (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:196491)
    at F.executeMovement (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171516)
    at F.handleKeyAsAnAction (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-04-22 15:44
Duplicate of #6527

**Closed by J-Fields** 2021-04-22 15:44 UTC
