### ISSUE TITLE
<C-d/u> does not work correctly in normal mode

### ISSUE THREAD

**Issue by michaelHL** [VSCodeVim/Vim#2775] opened 2018-06-26 14:58 UTC
**BUG REPORT**

In new version of VSCodeVim, <kbd>C-d</kbd> or <kbd>C-u</kbd> does not work correctly in normal mode:

![](https://i.imgur.com/4ggUjXo.gif)

The cursor get stuck in the top of editor area when I hit <kbd>C-d</kbd>, which doesn't perform a half-page scrolling. There is also a problem with <kbd>C-u</kbd>.

---

- Extension (VsCodeVim) version: 0.14.0
- VSCode version: 1.24.1
- OS version: Windows 10,  Build 16299

---

VSCodeVim Settings:

```json
{
    "vim.surround": true,
    "vim.disableExtension": false,
    "vim.useSystemClipboard": false,
    "vim.hlsearch": true,
    "vim.leader": " ",
    "vim.easymotion": true,
    "vim.easymotionMarkerFontFamily": "Microsoft Yahei Mono",
    "vim.easymotionMarkerFontSize": "15",
    "vim.easymotionMarkerHeight": 16,
    "vim.easymotionMarkerWidthPerChar": 11,
    "vim.easymotionMarkerBackgroundColor": "#000000",
    "vim.easymotionMarkerForegroundColorOneChar": "#ffffff",
    "vim.easymotionMarkerForegroundColorTwoChar": "#ffffff",
    "vim.easymotionMarkerYOffset": 13,
    "vim.statusBarColorControl": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [ "leader", "w" ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                }
            ]
        },
        {
            "before": [ "leader", "e" ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.revert",
                    "args": []
                }
            ]
        },
        {
            "before": [ "leader", "s" ],
            "after": [ "leader", "leader", "s" ]
        },
        {
            "before": [ "leader", "p" ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.closeEditorsInGroup",
                    "args": []
                }
            ]
        },
        {
            "before": [ "leader", "q" ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.closeActiveEditor",
                    "args": []
                }
            ]
        },
        {
            "before": [ "leader", "l" ],
            "after": [],
            "commands": [
                {
                    "command": "editor.action.trimTrailingWhitespace",
                    "args": []
                }
            ]
        },
        {
            "before": [ "U" ],
            "after": [ "<C-r>" ]
        },
        {
            "before": [ "k" ],
            "after": [ "g", "k" ]
        },
        {
            "before": [ "j" ],
            "after": [ "g", "j" ]
        },
        {
            "before": [ "=" ],
            "after": []
        },
        {
            "before": [ "n" ],
            "after": [ "n", "z", "z"
            ]
        },
        {
            "before": [ "N" ],
            "after": [ "N", "z", "z" ]
        },
        {
            "before": [ "{" ],
            "after": [ "{", "z", "z" ]
        },
        {
            "before": [ "}" ],
            "after": [ "}", "z", "z" ]
        }
    ],
    "vim.handleKeys": {
        "<C-d>": true,
        "<C-u>": true,
        "<C-o>": false,
        "<C-i>": false,
        "<C-h>": false,
        "<C-s>": false,
        "<C-f>": false,
        "<C-j>": false,
        "<C-c>": false,
        "<C-n>": false,
        "<C-k>": false
    }
}
```

**Comment by xconverge** [comment] 2018-06-26 15:10
Do you have editor.smoothScroll set to true? False should fix it for now

**Comment by michaelHL** [comment] 2018-06-26 15:14
@xconverge Thanks for quick reply! It performs as expected when I toggle `editor.smoothScrolling` to `False`.

**Comment by jpoon** [comment] 2018-06-26 15:37
Dupe of #2754 then.

**Closed by jpoon** 2018-06-26 15:37 UTC
