### ISSUE TITLE
Visual mode (V) + remapped (j -> gj) doesn't select lines

### ISSUE THREAD

**Issue by josiahbgrace** [VSCodeVim/Vim#1499] opened 2017-04-11 20:27 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Remapped `j` to `gj` in my settings.json
```json
  "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": [
                "j"
            ],
            "after": [
                "g",
                "j"
            ]
        },
        {
            "before": [
                "k"
            ],
            "after": [
                "g",
                "k"
            ]
        }
    ]
```

Enter visual mode `V`
Press `j`

### What did you expect to happen?

Expected standard behavior, adding a single line to the selection on each `j` keypress.

### What happened instead?

The video line selection doesn't hold the place of the first `V` line (video shows it clearly, not the best quality gif, but it should work).

![out](https://cloud.githubusercontent.com/assets/3061661/24929317/60e5adcc-1eba-11e7-890b-36570edc7202.gif)

### Technical details:

* VSCode Version: 1.12.0 Insiders
* VsCodeVim Version: *0.6.15*
* OS: El Capitan

**Comment by xconverge** [comment] 2017-04-11 21:22
duplicate of #1377

can you thumbs up that issue please, thanks

**Closed by xconverge** 2017-04-11 21:22 UTC
