### ISSUE TITLE
Remapped keys (escape) in VSCode 1.11 

### ISSUE THREAD

**Issue by JasonAsmk** [VSCodeVim/Vim#1479] opened 2017-04-06 15:48 UTC
### What did you do?
Tried to use an OS remapped key, namely Caps which should produce an Escape. 

### What did you expect to happen?
Expected to exit from insert to normal mode in file.

### What happened instead?
Nothing happened, remapped key does nothing.
### Technical details:
Used to work in previous version of VSCode and latest VSCodeVim, now it doesn't. AFAIK they changed the way keybinding works, so that might be a breaking change.
The mapping works fine in every other context except from VSCodeVim (e.g. in my case pressing Caps to dismiss a VSCode popup). Layout is standard US .

* VSCode Version: 1.11
* VsCodeVim Version: 0.6.14
* OS: Linux

**Comment by Valve** [comment] 2017-04-06 16:03
I remapped CAPS to ESC everywhere because of MBP 2016 and now it's not working :cry:  
Please let me know if this is an issue which should be better addressed in the core editor

**Comment by dannyob** [comment] 2017-04-07 03:37
I think this problem is caused by VS Code's work on native keymaps. Rolling back to an earlier version of VS Code fixed it for me.

**Comment by johnfn** [comment] 2017-04-07 06:27
To those having issues, VSCode has a workaround here: 

https://github.com/Microsoft/vscode/issues/23991

**Comment by xconverge** [comment] 2017-04-09 00:46
@Valve You know that in macOS you can open the keyboard settings and click modifier keys, and then set caps lock to esc.

**Comment by Valve** [comment] 2017-04-09 01:40
Yes, I did exactly that. And to be consistent I remapped caps to esc on my
linux desktop too and it broke with 1.11

**Comment by xconverge** [comment] 2017-04-13 18:16
Looks like vscode just pushed an update that should have fixed this perhaps?

Looking for some of you to confirm then we can close the ticket :)

**Comment by spiffytech** [comment] 2017-04-14 01:15
Negative, version 1.11.2 doesn't enter Vim normal mode when I hit my remapped Caps Lock key.

**Comment by xconverge** [comment] 2017-09-27 01:29
Is anyone still experiencing this issue?

**Comment by Chillee** [comment] 2017-09-28 06:14
@xconverge Yes. It's very annoying.

**Comment by adelsz** [comment] 2018-01-21 17:53
This setting fixed the mapping for me:
```json
{
    "keyboard.dispatch": "keyCode"
}
```

**Comment by jpoon** [comment] 2018-06-15 09:20
Closing as it seems like we have a workaround. Also see https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Closed by jpoon** 2018-06-15 09:20 UTC
Labels: kind/bug, upstream/vscode
