### ISSUE TITLE
Failed to handle key=k. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by itgou** [VSCodeVim/Vim#5566] opened 2020-11-03 01:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:508963)
    at h._isDocumentTextNeeded (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:511962)
    at h.addChange (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:512155)
    at F.handleKeyAsAnAction (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:473282)
    at F.handleKeyEvent (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\linjiang\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:28
Duplicate of #5209, please post repro steps there if you can.

**Closed by J-Fields** 2020-11-12 23:28 UTC
