### ISSUE TITLE
Intellisense menu goes away on every second keystroke

### ISSUE THREAD

**Issue by sgronblo** [VSCodeVim/Vim#1841] opened 2017-06-15 03:27 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.13.1 (1.13.1)
- **VsCodeVim Version**: 0.8.5
- **OS**: MacOS 10.12.5

**What happened**:

I'm editing a .js file. I type in for example the string navigator in insert mode. When I press the first n, the Intellisense menu shows up showing navigator as a possible suggestion (among others). When I type an additional 'a', the Intellisense menu goes away. I type an additional 'v' and the Intellisense menu is back. I type 'i' and the menu goes away. And so on. Very frustrating.
 

**What did you expect to happen**:

I expect the IntelliSense menu to stay open while I am typing something which matches any of the suggestions and not being displayed and hidden alternately on each keystroke.

**How to reproduce it**:

The reason I file this as a bug report for VSCodeVim is that I started trying to enable plugins one by one and checking the input again. When I disabled VSCodeVim the IntelliSense menu worked as expected, and when re-enabling VSCodeVim the IntelliSense menu starts disappearing on every second keystroke again.

**Comment by Chillee** [comment] 2017-06-15 03:47
Thanks! This is a really annoying bug, and I'm really surprised more people haven't reported it. I have a fix here that I'll probably push in a release tonight: https://github.com/VSCodeVim/Vim/pull/1832

Duplicate of https://github.com/VSCodeVim/Vim/issues/1827 and the result of a breaking change by VSCode in 1.13.

**Closed by Chillee** 2017-06-15 03:47 UTC
