### ISSUE TITLE
`go to defined` works fine but error when jumping back（ctrl + o）

### ISSUE THREAD

**Issue by ihaveadrame** [VSCodeVim/Vim#4470] opened 2020-01-04 05:10 UTC
**Describe the bug**
`go to defined` works fine but error when jumping back（ctrl + o）. I found that this problem is normal in the old version, such as 1.11.3 I use now。

**To Reproduce**
Update to the latest version

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS:   windows_NT x64  10.0.18362

**Additional context**
pass

**Comment by J-Fields** [comment] 2020-01-09 19:38
Closing in favor of #4479

**Closed by J-Fields** 2020-01-09 19:38 UTC

**Comment by troygibb** [comment] 2020-01-23 17:05
@J-Fields FYI #4479 was closed as a duplicate of this ticket -- is there another issue we should subscribe to for updates?

**Comment by J-Fields** [comment] 2020-01-31 16:09
#4479 is open - that's the one you should follow
