### ISSUE TITLE
Ability to view marks set in the file.

### ISSUE THREAD

**Issue by atishay** [VSCodeVim/Vim#5119] opened 2020-08-10 17:59 UTC
**Is your feature request related to a problem? Please describe.**
Marks are not visible and there is no way to confirm where marks are present in the file.

**Describe the solution you'd like**
Extension https://github.com/kshenoy/vim-signature implementation

**Comment by J-Fields** [comment] 2020-08-13 16:53
Sort of a duplicate of #3963/#4710 for which PR #4715 exists, though showing what the mark is rather than just a generic symbol would be ideal.

**Closed** 2020-12-28 19:57 UTC
Labels: kind/feature
