### ISSUE TITLE
incsearch does not work in visual mode

### ISSUE THREAD

**Issue by ghost** [VSCodeVim/Vim#1498] opened 2017-04-11 18:00 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Comment by johnfn** [comment] 2017-04-12 02:24
Mind filling out that whole template that we provide? I dunno what you mean.

**Comment by alha02** [comment] 2017-04-12 05:46
### What did you do?

Press v to enter visual mode. Then press / (or ?) to start incsearch.

### What did you expect to happen?

Incsearch start so I can type the search string.

### What happened instead?

It did not start. Instead, when I type a string either the cursor jumps around or nothing happens.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: OSX Sierra

**Comment by Chillee** [comment] 2017-05-06 12:12
Duplicate of #298 and #1520 I think.

**Comment by jpoon** [comment] 2017-05-06 20:18
Cool.  I'll close this issue as such. Let's use those issues to track.

**Closed by jpoon** 2017-05-06 20:18 UTC
Labels: kind/feature, status/duplicate
