### ISSUE TITLE
Direct lookup changes for matching braces

### ISSUE THREAD

**Issue by JUSTWILLPOWER** [VSCodeVim/Vim#7557] opened 2022-03-12 02:11 UTC
**Is your feature request related to a problem? Please describe.**

vim has a very nice function, that is, when moving to a line, instead of looking for matching brackets like (), "", <>, you can directly use ci (or ci", etc. to directly find the matching brackets and perform subsequent operations , but I found that currently only "" will work, other matching symbols will not

**Describe the solution you'd like**

Add support for other matching symbols

**Additional context**

`in vim`
![1](https://user-images.githubusercontent.com/63777069/157999739-32f8d2e6-4ad4-4907-a2d6-6048e0e42edc.gif)

**Comment by J-Fields** [comment] 2022-03-12 04:05
Duplicate of #7346

**Closed by J-Fields** 2022-03-12 04:05 UTC
