### ISSUE TITLE
Failed to handle key=<. getLineLength() called with out-of-bounds line 533

### ISSUE THREAD

**Issue by krewmarco** [VSCodeVim/Vim#5319] opened 2020-10-01 23:13 UTC
**To Reproduce**

1.  Don't remember well.  I cleared a file with Cmd-A Cmd-X then I hit a key that may have been <
**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<. getLineLength() called with out-of-bounds line 533
	at Function.getLineLength (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.executeOperator (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480756)
	at F.runAction (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476279)
	at F.handleKeyAsAnAction (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/marcozirino/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:47
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:47 UTC
Labels: kind/bug, status/duplicate
