### ISSUE TITLE
Failed to handle key=d. getLineLength() called with out-of-bounds line 6

### ISSUE THREAD

**Issue by a01aou** [VSCodeVim/Vim#5363] opened 2020-10-09 13:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. getLineLength() called with out-of-bounds line 6
    at Function.getLineLength (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22163)
    at l.getUpWithDesiredColumn (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11560)
    at l.getLeftThroughLineBreaks (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10810)
    at c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475270
    at Array.map (<anonymous>)
    at F.runAction (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475217)
    at F.handleKeyAsAnAction (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
    at F.handleKeyEvent (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\lenovo\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-11 02:57
Duplicate of #5180

**Closed by J-Fields** 2020-10-11 02:57 UTC
Labels: status/duplicate
