### ISSUE TITLE
EasyMotion not being applied to every word

### ISSUE THREAD

**Issue by baldore** [VSCodeVim/Vim#2016] opened 2017-09-11 14:31 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report 

**Environment**:

- **VSCode Version**: 1.14
- **VsCodeVim Version**: 0.10.0
- **OS**: MacOS Sierra 10.12.6

**What happened**:

Just two weeks ago, VSCode was updated and then when I try to use EasyMotion, it just display a few options to jump. Here is an example:

![image](https://user-images.githubusercontent.com/3131037/30279678-83ec8d04-96d3-11e7-86b7-8a576f3824d8.png)

I tried to set `vim.easymotionKeys` but it didn't make any change. Also it shows that that option is unknown. 

**What did you expect to happen**: 

It should display all the options (includes every single letter and groups of letters like `aa`, `ab`, `ac`, etc)

**How to reproduce it**:

Simply running EasyMotion. If anybody has this problem maybe you can tell me how to restart everything so it works as expected. Thanks a lot.

**Comment by simonwjackson** [comment] 2017-09-11 16:28
@baldore I don't think `vim.easymotionKeys` is available until the next release

**Comment by Chillee** [comment] 2017-09-11 19:44
@baldore Sorry, this was a regression caused by the recent EasyMotion refactoring. It has been fixed, and a release will go out sometime soon.

**Comment by Chillee** [comment] 2017-09-17 19:30
This should have been fixed in the latest release. Closing for now.

**Closed by Chillee** 2017-09-17 19:30 UTC
