### ISSUE TITLE
Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()

### ISSUE THREAD

**Issue by berabappaditya** [VSCodeVim/Vim#5780] opened 2020-11-29 10:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()
    at sr.getSearchRanges (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:135804)
    at sr.exec (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:133936)
    at sr.execCount (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37468)
    at x.exec (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:214331)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.execCount (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37457)
    at F.runAction (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
    at F.handleKeyAsAnAction (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\Bappaditya Bera\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by berknam** [comment] 2020-12-03 09:50
@berabappaditya  What were you doing when this happened?

**Comment by berknam** [comment] 2020-12-03 09:54
Duplicate of #5397. If you can reproduce this please post your steps on that issue.

**Closed** 2020-12-03 17:53 UTC
Labels: status/duplicate
