### ISSUE TITLE
getLineLength() called with out-of-bounds line 58

### ISSUE THREAD

**Issue by flappybriefs** [VSCodeVim/Vim#5300] opened 2020-09-30 03:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 58
	at Function.getLineLength (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.promise (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/luoyang/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:48
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:48 UTC
Labels: kind/bug, status/duplicate
