### ISSUE TITLE
getLineLength() called with out-of-bounds line 160

### ISSUE THREAD

**Issue by a-sunny-day** [VSCodeVim/Vim#5710] opened 2020-11-20 06:25 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 160
    at Function.getLineLength (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22163)
    at l.getUpWithDesiredColumn (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11560)
    at l.getLeftThroughLineBreaks (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10810)
    at Object.t.statusBarCommandText (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:31351)
    at Object.updateShowCmd (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:40481)
    at F.handleKeyEvent (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:472169)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\Christopher\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-24 17:42
Duplicate of #5180. If you can reproduce, please post steps on that ticket.

**Closed by J-Fields** 2020-11-24 17:42 UTC
Labels: status/duplicate
