### ISSUE TITLE
:sp should split horizontally

### ISSUE THREAD

**Issue by pzelnip** [VSCodeVim/Vim#2810] opened 2018-07-05 22:47 UTC
**FEATURE REQUEST**

Now that VS Code 1.25 is out with the grid editor layout feature (https://code.visualstudio.com/updates/v1_25#_grid-editor-layout) it's now possible to split windows "horizontally".  Doing a ```:sp``` in Vim mode still splits vertically though.  Ideally I'd like this command to match what happens in Vim.

**What happened**:

```:sp``` still splits "vertically" -- ie creates a new column

**What did you expect to happen**:

It should split "horizontally" -- ie create a new row

**How to reproduce it (as minimally and precisely as possible)**:

In NORMAL mode type ```:sp```.  Note that instead of splitting the current buffer horizontally, it opens a new buffer to the left.

**Environment**:

- Extension Name: vim
- Extension Version: 0.14.1
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.25.0

**Comment by jpoon** [comment] 2018-07-06 05:37
Duplicate of https://github.com/VSCodeVim/Vim/issues/2696

**Closed by jpoon** 2018-07-06 05:37 UTC
