### ISSUE TITLE
getLineLength() called with out-of-bounds line 390

### ISSUE THREAD

**Issue by justinhaubrich** [VSCodeVim/Vim#5392] opened 2020-10-12 19:46 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 390
	at Function.getLineLength (c:\Users\jhaubrich.ECHO\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.getLineEnd (c:\Users\jhaubrich.ECHO\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:13777)
	at F.handleSelectionChange (c:\Users\jhaubrich.ECHO\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:468290)
	at Object.promise (c:\Users\jhaubrich.ECHO\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235549)
	at Object.runTasks (c:\Users\jhaubrich.ECHO\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621922)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by justinhaubrich** [comment] 2020-10-12 19:47
Also please note the issue, I am not able to use Ctrl+Y or Redo. It is very frustrating.

**Comment by J-Fields** [comment] 2020-10-13 19:29
Duplicate of #5180, please post repro steps there.

**Closed by J-Fields** 2020-10-13 19:29 UTC
Labels: status/duplicate
