### ISSUE TITLE
Swap Escape with CapsLock doesn't works

### ISSUE THREAD

**Issue by Applemann** [VSCodeVim/Vim#1849] opened 2017-06-16 14:06 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: Ubuntu 16.04 LTS

**What happened**:
I have swap Escape with CapsLock by Gnome Tweak tool. Everywhere in my Ubuntu distribution it is switched, but in VSCodeVim not.

**What did you expect to happen**: 
CapsLock make same things like Escape.

**How to reproduce it**:
Install Gnome Tweak tool and swap Escape with CapsLock

**Comment by xconverge** [comment] 2017-06-16 14:12
duplicate of https://github.com/VSCodeVim/Vim/issues/1479

please check out some solutions there, I believe there is a workaround

If that does not resolve it please feel free to reopen this ticket, I think it is the same

**Closed by xconverge** 2017-06-16 14:12 UTC
