### ISSUE TITLE
Changing file under certain circumstances throws exception.

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#775] opened 2016-09-15 22:11 UTC
Stacktrace:

```
reason:  TypeError: Cannot read property 'document' of undefined
    at Function.readLineAt (/Users/bowei/code/Vim/out/src/textEditor.js:114:53)
    at Function.getLineLength (/Users/bowei/code/Vim/out/src/motion/position.js:444:40)
    at Position.getLineEnd (/Users/bowei/code/Vim/out/src/motion/position.js:372:49)
    at ModeHandler.<anonymous> (/Users/bowei/code/Vim/out/src/mode/modeHandler.js:436:58)
    at next (native)
    at __awaiter (/Users/bowei/code/Vim/out/src/mode/modeHandler.js:7:65)
    at __awaiter (/Users/bowei/code/Vim/out/src/mode/modeHandler.js:3:12)
    at global.constructor.vscode.window.onDidChangeTextEditorSelection (/Users/bowei/code/Vim/out/src/mode/modeHandler.js:410:61)
    at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13653)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:15829)
rejected promise not handled with 1 second
```

---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

Open file "FOO".

Close all other files.

Edit file "FOO".

Use Vscode native ctrl-shift-f to search for string "bar" across files.

Make sure there are at least 3 files, including "FOO", containing the string bar.

Use the mouse to navigate between the 3 files that show up in vscode's native results.

Click back and forth repeatedly a couple of times.
### What did you expect to happen?

Nothing.
### What happened instead?

Nothing, but the debugger caught the exception.
### Technical details:
- VSCode Version: 1.6.0 Insider 50bb7aad57cbf1924e28472de52734be49645558
- VsCodeVim Version: V0.10, Master, hash c16a57c551c2709f203e8082a9f4cea42f61e438
- OS: OSX 10.10

**Comment by johnfn** [comment] 2016-09-15 22:37
It's the click itself that appears to trigger the exception? This is super bizarre. 

I guess it's vaguely conceivable that could be our fault, but I'm having trouble thinking of a way that that could be.

**Comment by rebornix** [comment] 2016-09-16 18:57
@johnfn ran into this issue a couple of times and apparently we are not checking `activeTextEditor`'s existence every time but I haven't find the root cause.

**Comment by jpoon** [comment] 2018-08-09 04:41
To keep our issue list sane, closing this issue as it hasn't gained much traction.

**Closed by jpoon** 2018-08-09 04:41 UTC
Labels: kind/bug
