### ISSUE TITLE
Please support :term command

### ISSUE THREAD

**Issue by rafid149** [VSCodeVim/Vim#6975] opened 2021-08-10 06:32 UTC
I think it would be great if there was a :term command to open terminal :)

**Comment by Komar0ff** [comment] 2021-08-17 06:00
I think it's a [duplicate](https://github.com/VSCodeVim/Vim/issues/6873)

**Comment by J-Fields** [comment] 2021-08-31 02:00
Duplicate of #6873

**Closed by J-Fields** 2021-08-31 02:00 UTC
