### ISSUE TITLE
Make input method switch platform-specific

### ISSUE THREAD

**Issue by MoetaYuko** [VSCodeVim/Vim#7343] opened 2021-12-22 07:22 UTC
**Is your feature request related to a problem? Please describe.**
Input method implementation is absolutely platform-dependent. However, the `vim.autoSwitchInputMethod.*` settings don't honor different platforms. This is problematic for people working with different OS and use the settings sync feature to sync their configurations.

**Describe the solution you'd like**
Make separate `vim.autoSwitchInputMethod.*` settings for Win, Linux and Mac.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by J-Fields** [comment] 2022-12-30 06:52
Duplicate of #7695 (will be fixed in upcoming release)

**Closed by J-Fields** 2022-12-30 06:52 UTC
