### ISSUE TITLE
Is there a way to repeat a CLI command?

### ISSUE THREAD

**Issue by edasaki** [VSCodeVim/Vim#1775] opened 2017-05-29 00:05 UTC
For example, can we repeat a :s/foo/bar/g without retyping it?
I've looked around but haven't been able to find anything about this (maybe I've missed it)

**Comment by Chillee** [comment] 2017-05-29 00:09
https://github.com/VSCodeVim/Vim/issues/779 is a duplicate of this.

**Comment by edasaki** [comment] 2017-05-29 00:11
Gotcha - is there a command for this in the meantime (something we could bind to a key ourselves)? If not I may try to add it and PR

**Comment by Chillee** [comment] 2017-05-29 00:18
Unluckily, it's not really possible right now. VSCode doesn't allow us to modify the box that pops up for Ex commands.

It would be possible if we decided to move Ex-commands to the bottom status bar, but that doesn't seem worth it to me right now.

**Comment by edasaki** [comment] 2017-05-29 00:33
I mean like, what if we just made some keybind that runs the last command without any sort of interface popup?

So I type :s/foo/bar/g
Press enter to do the replace
go to some other line
press some key combination to rerun the same command again on that line

**Comment by Chillee** [comment] 2017-05-29 00:39
Oh, hmm. That's definitely possible. That would not be a core vim feature though.

**Comment by oschr** [comment] 2017-12-25 06:38
It actually is a core vim feature, namely typing @: in vim repeats the last command (to be more precise, the last command is saved in the special : register)

**Comment by reminia** [comment] 2018-01-05 08:19
+1

**Comment by J-Fields** [comment] 2019-05-04 15:02
This should come for "free" with #2193 and #3605

**Closed** 2019-05-06 04:06 UTC
Labels: help wanted, kind/feature
