### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by AnuragRai017** [VSCodeVim/Vim#6905] opened 2021-07-22 14:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\Anurag\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\Anurag\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at j.rerunRecordedState (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:207:12)
    at j.actionToRecord [as runAction] (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\Anurag\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[19, 35] | [19, 35]]"
]
actionsRunPressedKeys: [
  "<up>",
  "<down>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<down>",
  "<up>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<down>",
  "<up>",
  "<left>",
  "<left>",
  "<left>",
  "<left>",
  "<BS>",
  "<BS>",
  "<BS>",
  "9",
  "0",
  "<BS>",
  "<BS>",
  "1",
  "3",
  "5",
  "0",
  "<BS>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<BS>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<up>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<BS>",
  "<BS>",
  "8",
  "0",
  "<up>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<down>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<right>",
  "<left>",
  "<left>",
  "<left>",
  "<BS>",
  "1",
  "0"
]
actionsRun: [
  "ee",
  "q",
  "$",
  "C",
  "C",
  "C",
  "C",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 19,
      "character": 35
    },
    "text": "I",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 19,
        "character": 30
      },
      {
        "line": 19,
        "character": 36
      }
    ],
    "text": "parseFloat",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:44
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:44 UTC
