### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by OoThan** [VSCodeVim/Vim#5987] opened 2021-01-12 02:22 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
	at d._lineAt (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at _.exec (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:196742)
	at _.execCount (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24652)
	at x.exec (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:195125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.execCount (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641)
	at async F.runAction (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/home/maungoothan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by lynx5120** [comment] 2021-01-12 07:00
Got the same issue here

**To Reproduce**
Steps to reproduce the behavior:

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key==. Illegal value for `line`
	at d._lineAt (c:\Users\ruolan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:740)
	at Object.lineAt (c:\Users\ruolan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:570:715)
	at Function.getFirstNonWhitespaceCharOnLine (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:14610)
	at R.run (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:47688)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async R.runRepeat (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:42235)
	at async F.executeOperator (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:177289)
	at async F.runAction (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:172320)
	at async F.handleKeyAsAnAction (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
	at async F.handleKeyEvent (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
	at async Object.promise (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
	at async Object.runTasks (c:\Users\ruolan\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:39
Duplicate of #6331

**Closed by J-Fields** 2021-03-24 17:39 UTC
