### ISSUE TITLE
    "<C-d>": false, has not efect

### ISSUE THREAD

**Issue by metasong** [VSCodeVim/Vim#1947] opened 2017-08-01 06:01 UTC
"<C-d>": false, has not effect

**Comment by zmoazeni** [comment] 2017-10-12 02:03
I believe I figured out the issue is this line: https://github.com/VSCodeVim/Vim/blob/bee6ac6088223efd6596ccae547b263d21145f36/package.json#L91

which was changed in https://github.com/VSCodeVim/Vim/pull/1631

It looks like adding `&& vim.use<C-d>` causes other problems that the PR fixed. 

So I had to open up the keybindings, searched for `vim_ctrl+d` and deleted the key binding.

**Comment by granteagon** [comment] 2017-11-29 22:30
Seeing the same issue, which is not allowing the [new Ctrl-D](https://github.com/Microsoft/vscode/issues/8869) functionality to work correctly.

**Comment by jpoon** [comment] 2018-01-16 05:15
Should be fixed with https://github.com/VSCodeVim/Vim/pull/2269. See the table in the PR about the expected behaviour.

**Closed by jpoon** 2018-01-16 05:15 UTC
