### ISSUE TITLE
Find/Replace on visual block selection is not working

### ISSUE THREAD

**Issue by srki80** [VSCodeVim/Vim#1250] opened 2017-01-26 16:46 UTC
Doing find/replace on the visual block selection replaces only the first occurrence instead of all occurrences in the selection. 

-----

### What did you do?

1. v - and select the block of code
2. :s/searchterm/replaceterm/g

### What did you expect to happen?
All searchterm occurrences within the selection should have been replaced with replaceterm.

### What happened instead?
Only the first occurrence of the searchterm was replaced with replaceterm.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: OS X

**Comment by bschlenk** [comment] 2017-01-31 04:32
When you press `:` after selecting a visual block, you'll notice that the command does start with `'<,'>`. The problem is that it comes preselected, so if you start typing you type over it and the command only works on a single line. The workaround is to hit the right arrow key before typing your search string, so the `'<,'>` is still there.

I thought it wasn't supported at first too. It should definitely be changed to not start out selected.

**Comment by bschlenk** [comment] 2017-01-31 04:36
This is tracked in #1207.

**Comment by srki80** [comment] 2017-01-31 13:57
You are right. The workaround works. Thanks. I use this a lot.

**Comment by lucastheisen** [comment] 2017-03-10 20:18
This issue should probably be closed as a duplicate of #792.  Also, don't forget to _thumbs up_ #792...

**Comment by johnfn** [comment] 2017-03-11 12:09
@lucastheisen Correct! Even better than that would be to go and make some noise over on VSCode: https://github.com/Microsoft/vscode/issues/10582

**Closed by johnfn** 2017-03-11 12:09 UTC
