### ISSUE TITLE
Failed to handle key=. nvim_buf_set_lines: Buffer is not 'modifiable'

### ISSUE THREAD

**Issue by Magamex** [VSCodeVim/Vim#5897] opened 2020-12-17 03:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Error making request to nvim_buf_set_lines
    at c.request (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:159720)
    at c.setLines (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:95995)
    at p.syncVSCodeToVim (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:229325)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at p.run (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:228211)
    at Object.Run (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:143368)
    at C.exec (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:126055)
    at C.execCount (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24579)
    at F.runAction (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171581)
    at F.handleKeyAsAnAction (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
    at F.handleKeyEvent (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
    at Object.promise (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
    at Object.runTasks (c:\Users\mangeluk\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 04:02
Duplicate of #7312

**Closed by J-Fields** 2022-03-09 04:02 UTC
Labels: status/duplicate
