### ISSUE TITLE
Failed to handle key=d. getLineLength() called with out-of-bounds line 1082

### ISSUE THREAD

**Issue by jnis77diver** [VSCodeVim/Vim#5531] opened 2020-10-29 20:47 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. getLineLength() called with out-of-bounds line 1082
    at Function.getLineLength (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.getUpWithDesiredColumn (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11622)
    at l.getLeftThroughLineBreaks (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10872)
    at c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475270
    at Array.map (<anonymous>)
    at F.runAction (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475217)
    at F.handleKeyAsAnAction (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
    at F.handleKeyEvent (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
    at Object.runTasks (c:\Users\jsnis\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:28
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:28 UTC
