### ISSUE TITLE
Failed to handle key=<tab>. Failed to handle key=j. Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by spatel2693** [VSCodeVim/Vim#6462] opened 2021-04-11 19:16 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<tab>. Failed to handle key=j. Cannot read property 'start' of undefined
    at x.exec (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/plugins/easymotion/easymotion.cmd.ts:85:70)
    at x.execCount (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/base.ts:249:20)
    at I.runAction (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:719:20)
    at I.handleKeyAsAnAction (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:650:16)
    at I.handleKeyEvent (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:40)
    at I.handleMultipleKeyEvents (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:367:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at m.handleRemapping (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/configuration/remapper.ts:483:73)
    at m.sendKey (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/configuration/remapper.ts:367:42)
    at t.Remappers.handledAsRemap [as sendKey] (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/configuration/remapper.ts:39:7)
    at I.async [as handleKeyEvent] (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:451:9)
    at Object.promise (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:632:27)
    at Object.runTasks (/Users/sagar.patel/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 01:42
Duplicate of #7461

**Closed by J-Fields** 2022-03-09 01:42 UTC
Labels: status/duplicate
