### ISSUE TITLE
Last character in selection

### ISSUE THREAD

**Issue by sebastjaeger** [VSCodeVim/Vim#1711] opened 2017-05-17 20:47 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.7.1
- **OS**: MacOS 10.12.4 / Ubuntu 15.04

**What happened**:

There are multiple surprising effects when selecting e.g. a word in visual mode
- the last character is not highlighted like the rest of the selection
- when copying the word using `y` the entire word is copied and can be retrieved with `p` (as expected)
- the last character is lost when pasting the word via the selection clipboard (`*` buffer in vim, mouse middle click in linux) 
- vscode highlights not only all the other occurrences of the selected word, but everything that matches all but the last letter of the selection

**What did you expect to happen:**

Clearly show that the last character of the selection belongs to the selection. Make sure the last character is copied into the selection clipboard. Highlight other occurrences of the selection correctly.

**Comment by Chillee** [comment] 2017-05-17 22:02
Thanks for listing the ways in which our current selection is flawed... But seriously, thanks for listing the ways our selection is messed up. I might actually try and spend the time to get this problem fixed :)

**Comment by jpoon** [comment] 2017-05-19 06:59
Duplicate of https://github.com/VSCodeVim/Vim/issues/1711

**Closed** 2017-05-19 07:00 UTC
Labels: area/selection-off-by-one, status/duplicate
