### ISSUE TITLE
delete lines not function

### ISSUE THREAD

**Issue by qidolihaku** [VSCodeVim/Vim#1771] opened 2017-05-27 23:17 UTC
Delete number of lines command not working.  (example  d3d should delete 3 lines code)

**Comment by Chillee** [comment] 2017-05-27 23:18
A temporary regression and duplicate of this. 

3dd still works so use that.

**Comment by Chillee** [comment] 2017-05-29 05:54
Fixed on master.

**Closed by Chillee** 2017-05-29 05:54 UTC
