### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2232] opened 2017-12-18 08:25 UTC
- Extension Name: vim
- Extension Version: 0.10.6
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.20.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 230,
		"activateCallTime": 5,
		"activateResolvedTime": 4,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```
![image](https://user-images.githubusercontent.com/30625381/34096382-671fc43a-e3d5-11e7-8a8b-176dd84cb2af.png)

**Comment by jpoon** [comment] 2017-12-20 08:35
Thanks for reporting. Dupe of https://github.com/VSCodeVim/Vim/issues/2184

**Closed by jpoon** 2017-12-20 08:35 UTC
