### ISSUE TITLE
# Regsiter get not filled/updated

### ISSUE THREAD

**Issue by lalexf** [VSCodeVim/Vim#7324] opened 2021-12-15 06:50 UTC
**Describe the bug**
The `#` register get not filled or if something is already in there it does not get updated on changing files.
This means toggling between alternate files `<C-^>` does not work.

**To Reproduce**
1. Open a  file
2. Open an other file
3. Try to toggle between the files/ look at `:reg` 

**Expected behavior**
The `#` register should contain "an other file"

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.21.10`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.63.1`

**Comment by J-Fields** [comment] 2022-03-17 06:20
Duplicate of #7357

**Closed by J-Fields** 2022-03-17 06:20 UTC
