### ISSUE TITLE
cw on "1," deletes the comma as well as the 1

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#605] opened 2016-08-14 07:33 UTC

**Comment by sectioneight** [comment] 2016-08-15 16:22
I believe this is the same root problem as https://github.com/VSCodeVim/Vim/issues/563#issuecomment-238992281

**Comment by sectioneight** [comment] 2016-08-15 16:44
@johnfn do you have an idea of why this happens? i was banging my head against #563 for a while trying to figure out how selections works (what is the start? what is the end? is a 1-character match a match with start==end)?

**Comment by johnfn** [comment] 2016-08-15 18:14
My guess is we just don't handle the 0 case very well. If start = end, the selection is 1 character. I know it seems crazy- that's just the way Vim works.

**Comment by xconverge** [comment] 2016-09-14 04:36
is this fixed now? I don't remember when/how but I can't reproduce it

**Comment by johnfn** [comment] 2016-10-01 23:15
I don't even know who fixed this bug but someone definitely fixed it. So thanks to that guy. You're a cool dude.

**Closed** 2016-10-01 23:15 UTC
