### ISSUE TITLE
getLineLength() called with out-of-bounds line 19

### ISSUE THREAD

**Issue by OzHegazy77** [VSCodeVim/Vim#5329] opened 2020-10-04 16:04 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 19
    at Function.getLineLength (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at l.isLineEnd (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:14231)
    at l.getRightThroughLineBreaks (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11052)
    at Object.t.statusBarCommandText (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:31336)
    at Object.updateShowCmd (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:40543)
    at F.handleKeyEvent (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:472169)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\sesa379424\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by OzHegazy77** [comment] 2020-10-04 16:07
I can't delete or copy in VSCODE i don't know where's the problem but I noticed that the below of the page changed to --NORMAL-- or --INSERT--

could you please help

**Comment by J-Fields** [comment] 2020-10-13 19:30
Duplicate of #5180, please post repro steps there.

**Closed by J-Fields** 2020-10-13 19:30 UTC
