### ISSUE TITLE
Support vim set scrolloff ?

### ISSUE THREAD

**Issue by leeyongda** [VSCodeVim/Vim#2561] opened 2018-04-24 02:15 UTC
## vscode-vim version (0.11.5)
## Vscode version (1.22.2)

**Comment by jpoon** [comment] 2018-04-24 04:51
It'd be nice if folks filled out the template :)

related: https://github.com/Microsoft/vscode/issues/12048

**Comment by cjbassi** [comment] 2018-07-15 18:38
Seems like a duplicate of #1427

**Comment by jpoon** [comment] 2018-07-15 19:06
You are correct. Thanks @cjbassi. Closing as duplicate of https://github.com/VSCodeVim/Vim/issues/1427

**Closed** 2018-07-15 19:06 UTC
Labels: help wanted, kind/feature, status/duplicate
