### ISSUE TITLE
Illegal value for `line`

### ISSUE THREAD

**Issue by hmendozap** [VSCodeVim/Vim#6265] opened 2021-03-11 11:25 UTC
**To Reproduce**

1.  Edit a line in notebook
2.  go to normal mode (esc)
3.  Press enter (to enter cell) use insert mode (i)
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Illegal value for `line`
	at p._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:82:1166)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:82:95)
	at Function.getCharAt (c:\Users\hmend\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:756624)
	at F.updateView (c:\Users\hmend\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:720435)
	at M (c:\Users\hmend\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:344960)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (c:\Users\hmend\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:349203)
	at async Object.runTasks (c:\Users\hmend\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:01
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:01 UTC
