### ISSUE TITLE
  no work

### ISSUE THREAD

**Issue by xtzt** [VSCodeVim/Vim#4346] opened 2019-12-09 10:53 UTC
the vscodevim of version 1.12.0 is not working!

**Comment by samsiu** [comment] 2019-12-09 10:55
#4340

**Comment by LebranceBW** [comment] 2019-12-09 11:36
+1. the version **1.12.0** for me don't work either. Going back to **1.11.3** could repair it.

**Comment by galois-advertising** [comment] 2019-12-09 11:53
me too

**Comment by victorvarenic** [comment] 2019-12-09 12:20
+ 1

**Comment by Vinnl** [comment] 2019-12-09 12:24
Duplicate of #4340. Please do not add "me too" comments there - click the "Thumbs up" on the original issue.

**Comment by armoucar** [comment] 2019-12-09 13:12
> +1. the version **1.12.0** for me doesn't work either. Going back to **1.11.3** could repair it.

Does someone know how to rollback temporally while current version is broken?

**Comment by tcfunk** [comment] 2019-12-09 13:16
@armoucar click the gear next to the Vim extension, and select "Install another version"

**Comment by anonoh** [comment] 2019-12-09 13:16
@armoucar 

Go to extensions tab, right click the Vim plugin and select "Installl another version"

![image](https://user-images.githubusercontent.com/27064280/70438552-61666480-1a8e-11ea-957f-acab2575e650.png)

**Comment by jesHrz** [comment] 2019-12-09 13:27
not working +1, and roll back...

**Comment by EdwinYoon** [comment] 2019-12-09 14:12
It does not work for me either.
When I started the vscode, it did not even start the vim
so reinstall the extension after I removed the extension from vscode and as well as from the "$HOME/.vscode/extensions"   

Then It starts vim but the key mappings are mess

**Comment by dcolthorp** [comment] 2019-12-09 14:40
It's not working for me and the rest of my team on macos, code 1.40.2. (vim 1.12.0)

**Comment by pvinis** [comment] 2019-12-09 14:56
I think we can stop commenting here. If someone can, please close this issue.

Link to duplicate issue: https://github.com/VSCodeVim/Vim/issues/4340
Current workaround: Install version 1.11.3
Steps to execute workaround: https://github.com/VSCodeVim/Vim/issues/4346#issuecomment-563233380

**Comment by rebornix** [comment] 2019-12-09 17:02
Fixed in 1.12.1, sorry for the trouble.

**Closed by rebornix** 2019-12-09 17:02 UTC

**Comment by rebornix** [comment] 2019-12-09 17:12
There are still some issues ppl are seeing now, let's track it in https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563338094.
