### ISSUE TITLE
Failed to handle key=<up>. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by aerijman** [VSCodeVim/Vim#5660] opened 2020-11-16 15:34 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<up>. Cannot read property 'canBeRepeatedWithDot' of undefined
	at F.runAction (/home/ariel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476382)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/ariel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/ariel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/ariel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/ariel/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-16 17:29
Duplicate of #5468. If you can repro, please post steps there.

**Closed by J-Fields** 2020-11-16 17:29 UTC
