### ISSUE TITLE
Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by Frankuwl214** [VSCodeVim/Vim#5594] opened 2020-11-07 05:34 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'stop' of undefined
	at p.get cursorStopPosition [as cursorStopPosition] (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
	at Function.fromStateNow (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:161339)
	at Object.promise (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234459)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:51
Duplicate of #5284

**Closed by J-Fields** 2021-02-04 20:51 UTC
Labels: status/duplicate

**Comment by Frankuwl214** [comment] 2021-02-05 00:32
thanks bro 

am new student trying to learn coding 
so how did you manage to oick up this thread

**Comment by J-Fields** [comment] 2021-02-05 19:04
Hmm?
