### ISSUE TITLE
Text entry lag and lost keypresses on v1.26.0

### ISSUE THREAD

**Issue by agrieser** [VSCodeVim/Vim#8573] opened 2023-09-10 16:26 UTC
**Describe the bug**
After updating to 1.26.0 (automatic, so it was initially quite confusing), vscode vim began eating keystrokes when typing. This is present when doing basic text entry in insert mode. For example, typing: `hello world`, will result in `heloword` or maybe `hllo wrld`. It is not deterministic. If I type slow enough, it seems to work.

Reverting to 1.25.2 resolves all issues.

In debugging this, I removed all of my config customization. The problem persisted on 1.26.0.

**To Reproduce**

1.  Update to 1.26.0
2.  Switch to insert mode
3.  Attempt to type
4.  Some letters are missing (eaten) from result

Steps to resolve: revert to 1.25.2

**Expected behavior**
Keypresses in insert mode should be preserved

**Screenshots**
N/A

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version:1.82.0
- OS: ChromeOS 116, arm64 5.15.117-19680-g54e910f94133
- Device: HP chromebook x2, 8 core 8gb memory

**Additional context**
Happy to help debug and assist in testing on chromeOS

**Comment by Koishiiko** [comment] 2023-09-11 01:21
+1 on Windows10

**Comment by PromethiumL** [comment] 2023-09-11 04:13
+1 on Debian Bulleyes

**Comment by PromethiumL** [comment] 2023-09-11 04:19
+1 on Debian Bullseye

**Comment by julmue** [comment] 2023-09-11 06:58
+1 on Windows10

**Comment by sp3ctum** [comment] 2023-09-11 07:04
I can confirm downgrading to `v1.25.2` fixes this issue for me.

To save others some time, the downgrade can be done from the `Extension: Vim` screen by selecting the `Install another version` option:
<img width="649" alt="Screenshot 2023-09-11 at 10 03 44" src="https://github.com/VSCodeVim/Vim/assets/300791/dc9f412f-c83c-4b5d-9ee9-807504a1944d">

**Comment by joehillen** [comment] 2023-09-11 07:43
I use Arch, BTW

**Comment by salcedo** [comment] 2023-09-11 14:34
This is happening on Arch, BTW.
Also macOS.

**Comment by liam-murphy14** [comment] 2023-09-11 17:54
+1 on macOS

**Comment by jabczyk** [comment] 2023-09-11 20:01
+1 on Win10, downgrading works for me

**Comment by davdmoo** [comment] 2023-09-12 02:48
+1 on windows 11. I thought my laptop was going crazy yesterday :(

**Comment by CommunityBoxDev** [comment] 2023-09-12 18:18
+1 on Windows 10 / vscode 1.82.1 - downgrading to 1.25.2 fixes it for me ✅

**Comment by davdmoo** [comment] 2023-09-13 07:03
> +1 on Windows 10 / vscode 1.82.1 - downgrading to 1.25.2 fixes it for me ✅

Yeah - with this and issue https://github.com/VSCodeVim/Vim/issues/8574 I'm just gonna downgrade for now.

**Comment by Mohamed-Zhran-MD** [comment] 2023-09-13 10:53
+1 on manjaro

**Comment by loquilloll** [comment] 2023-09-13 15:38
+1 Ubuntu 23.04

**Comment by Acrylic125** [comment] 2023-09-14 07:55
+1 MacOS

**Comment by Fabianthorsen** [comment] 2023-09-14 12:32
+ 1 Windows 11

**Comment by joehillen** [comment] 2023-09-14 17:15
STOP SPAMMING YOUR OS

**Comment by salcedo** [comment] 2023-09-14 17:24
@Fabianthorsen It doesn't appear this issue is limited to specific keyboards. I first noticed it on the Moonlander myself, which did make me first assume it had to be a configuration or driver with my keyboard. Since then, I've encountered the issue on multiple machines with different OS and VSCode versions. In each case, downgrading to 1.25.2 has resolved this.

**Comment by Acumane** [comment] 2023-09-14 19:25
Also seeing duplication of input and chars appearing after the cursor.
e.g. `something|` (where `|` is cursor) can look like `someti|ngo`

**Comment by PuckCh** [comment] 2023-09-15 06:45
> Also seeing duplication of input and chars appearing after the cursor. e.g. `something|` (where `|` is cursor) can look like `someti|ngo`

Same here with:
- macOS Ventura 13.5.2
- MacBook Pro M1
- Moonlander keyboard, or Macbook Pro laptop keyboard directly
- Visual Studio Code 1.82.1
- vscodevim v1.26.0

Downgrade vscodevim remove the problem.

I suspect that the full char is not skipped, and sometime it's recognised as another key sequence, causing some (random) char inserted AFTER the cursor.

**Comment by jbsilva** [comment] 2023-09-15 16:37
Same here.

- Windows 10 + WSL 2
- VS Code 1.82.2
- VsCodeVim 1.26.0

Downgrading to 1.25.2 works

**Comment by tudor** [comment] 2023-09-29 18:40
Same here. macOS 13.4.1, VS Code 1.82.2, VSCodeVim 1.26.0.

**Comment by tudor** [comment] 2023-09-29 19:52
Errors reported by clangd are mutating the current editor (by adding error squiggles underneath pieces of code), I don't know if this is relevant or not.

**Comment by J-Fields** [comment] 2023-10-28 23:51
Should be fixed in v1.26.1

**Closed by J-Fields** 2023-10-28 23:51 UTC

**Comment by CommunityBoxDev** [comment] 2023-10-30 17:51
@J-Fields great news - do you know which commit fixed the issue? I had a look at the repository history for the past week or so but none of the commits stood out as *the* fix (apologies if I missed a very obvious commit message 😅)
