### ISSUE TITLE
Editor freezes on CMD+S

### ISSUE THREAD

**Issue by haf** [VSCodeVim/Vim#1551] opened 2017-04-22 10:02 UTC
Please see https://github.com/Microsoft/vscode/issues/25183 – cross posting because it's an interaction between editor and two plugins, or editor and one plugin.

...or it doesn't freeze and `i` to insert doesn't work.

**Comment by johnfn** [comment] 2017-04-22 10:04
I can't understand how VSCodeVim is implicated here. We don't bind Cmd-S.

**Comment by haf** [comment] 2017-04-22 10:05
Updated issue.

**Comment by johnfn** [comment] 2017-04-22 10:24
It sounds to me like the other extension is probably busy-waiting or hogging all the resources somehow. I really don't think that `i` failing to work could possibly be a bug on the VSCodeVim side - it's just too core of functionality, and we've never heard of anything like that happening.

I'd love to be proved wrong, though! But I don't think it's going to happen.

**Comment by haf** [comment] 2017-04-22 10:26
@johnfn Maybe yes. Can we just keep this open for reference? I'm not sure where the issue lies.

**Comment by johnfn** [comment] 2017-04-22 10:48
Sure.

**Comment by johnfn** [comment] 2017-04-22 10:49
(come to think of it, the fact that the cmd-s breaks is proof positive that the bug lies on the other side.)

**Comment by haf** [comment] 2017-04-22 12:05
It's not CMD+S that breaks, it's the editor that hangs after pressing it.

**Comment by johnfn** [comment] 2017-04-22 12:07
Yeah but in either case we could not ever be responsible for a bug involving cmd-s in any way 😉

**Comment by xconverge** [comment] 2017-04-25 15:33
https://www.reddit.com/r/vscode/comments/65vnxj/vscode_freezing_after_upon_save/

**Comment by xconverge** [comment] 2017-04-25 15:34
Some good ideas here, format on save enabled or anything?

**Comment by jpoon** [comment] 2017-11-15 05:48
Please try https://code.visualstudio.com/docs/extensions/debugging-extensions#_profiling-your-extension to see if you can get a repro. In the meantime, close this issue.

**Closed by jpoon** 2017-11-15 05:48 UTC
Labels: status/needs-more-info, upstream/vscode

**Comment by haf** [comment] 2017-11-23 15:43
Everyone blames everyone else.

**Comment by Chillee** [comment] 2017-11-23 16:32
For the record, I wouldn't be completely surprised if this was due to vscodevim. There have been a couple other high cpu bugs caused by interactions between vscodevim and another extension.

**Comment by jpoon** [comment] 2017-11-23 17:42
I blame @haf  =P

**Comment by haf** [comment] 2017-11-27 09:25
Haha :) @jpoon

**Comment by geksilla** [comment] 2017-12-14 12:57
Hi all. I observe same issue on Angular project on file save. I found that keyboard input hangs between two events:

```
[Extension Host] 2017-12-14T12:21:40.172Z - debug: [DeclarationIndexMapper] rebuilding index for index "/path/to/project"
.....
[Extension Host] 2017-12-14T12:21:46.693Z - info: [DeclarationIndexMapper] rebuilt index for workspace "project-name" {"durationMs":6521}
```

After last events all input start to apply so for example:
- Vim is in normal mode
- Hit save <kbd>Ctrl+s</kbd>
- First `DeclarationIndexMapper` event occurs (start rebuilding index)
- Enter insert mode and type some text e.g. <kbd>isometext</kbd>
- Nothing happens, vim still in normal mode
- Second `DeclarationIndexMapper` event occurs (finish rebuilding index)
- Vim enters insert mode and typed text appears

UI works normally between these two events, which means that I can click mouse in editor, select another tab and events passes normally, but Vim waiting until rebuilding index finish.
When Vim extension disabled all input events occurs normally so I can move cursor by arrow keys and type some text between these two events.

**Comment by geksilla** [comment] 2017-12-14 15:15
Quick update: in my case this hang was caused by `typescript-hero` extension. Described events goes from this package. When I disabled `typescript-hero` extension I don't observe any hangs.
