### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by adderrrallll** [VSCodeVim/Vim#5381] opened 2020-10-11 13:41 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
    at new _ (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:509:424)
    at new _ (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:507:436)
    at new l (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9299)
    at a (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:77351)
    at O.exec (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:1:77396)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:122119)
    at F.rerunRecordedState (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:133638)
    at F.executeCommand (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:130436)
    at F.runAction (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:121988)
    at F.handleKeyAsAnAction (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:121315)
    at F.handleKeyEvent (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:118124)
    at Object.promise (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:9:234345)
    at Object.runTasks (c:\Users\jawhe\.vscode-oss\extensions\vscodevim.vim-1.17.1\out\extension.js:11:282242)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 02:00
Duplicate of #5381, please post repro steps there.

**Closed by J-Fields** 2020-10-14 02:00 UTC
