### ISSUE TITLE
Indentation repeat bug

### ISSUE THREAD

**Issue by sumanx** [VSCodeVim/Vim#2788] opened 2018-06-29 02:03 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug.

**How to reproduce it (as minimally and precisely as possible)**:

Press V(shift+v) into visual mode, use k to select several lines, for example from line 10 to line 5, then press >(shift+.) to indent right, then press . to repeat.

It will not act like that select from line 5 to line 10, then indent and repeat.

**Environment**:

- Extension (VsCodeVim) version: all versions
- VSCode version: all versions

**Comment by xconverge** [comment] 2018-06-29 02:29
Duplicate of #2606

**Closed by xconverge** 2018-06-29 02:29 UTC
