### ISSUE TITLE
exiting insert mode moves cursor to previous non-blank line

### ISSUE THREAD

**Issue by subhakarks** [VSCodeVim/Vim#5726] opened 2020-11-21 08:17 UTC
**Description**
- I type `A` to insert at end of line.
- Type couple 2 or 3 enters
- Then exit insert mode. This moves the cursor to the end of previous non-blank line.

**To Reproduce**
Consider below code.
```
def some_func():
   statement-1
   statement-2
   statement-3  <type A to get into insert mode at EOL>
   <enter>
   <enter>
   <enter>
   <type esc to exit insert mode> (Issue: Cursor moves back to end of line on statement-3)
```
**Expected behavior**
Cursor should just stay in the same line when insert mode is existed

**Screenshots**

**Environment (please complete the following information):**
- VSCode:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
- Extension (VsCodeVim) version: v1.17.1
- OS: MacOS Catalina

**Additional context**
I am seeing this issue only from the recent updated version of (ie October, 2020 update) of VSCODE.

**Comment by berknam** [comment] 2020-12-07 17:03
@subhakarks I can't reproduce this. Does this happen every time to you? Even after restarting vscode? Do you have any remaps or keybindings setup? Can you test this with the new version "1.18.x" and see if this is still an issue?

**Comment by subhakarks** [comment] 2020-12-07 17:19
@berknam 
Thanks. I upgraded to vscode-vim extension version `v1.18.3` and I DID NOT see above issue.
It works fine now.

**Comment by berknam** [comment] 2020-12-07 17:40
Closing this for now. If you see this again you can reopen it.

**Closed by berknam** 2020-12-07 17:40 UTC
