### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ManasaVarudu** [VSCodeVim/Vim#5886] opened 2020-12-14 13:42 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (c:\Users\Manasa varudu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:666)
	at t.ExtHostTextEditor.edit (c:\Users\Manasa varudu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:201)
	at v.execute (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:66108)
	at F.runAction (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171693)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
	at async F.handleKeyEvent (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
	at async Object.promise (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
	at async Object.runTasks (c:\Users\Manasa varudu\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2020-12-14 16:45
Duplicate of #5224. What were you trying to do when this happened?

**Closed by J-Fields** 2020-12-14 16:45 UTC
