### ISSUE TITLE
Support `<C-w>s` for window splitting

### ISSUE THREAD

**Issue by edwintorok** [VSCodeVim/Vim#2379] opened 2018-02-12 20:41 UTC
**BUG REPORT**:

**What happened**: 
`<C-w>v` doesn't work correctly if editor layout is toggled

**What did you expect to happen**:
* `<C-w>s` should split horizontally
* `<C-w>v` splits only vertically

Although VSCode itself does not support grid layout yet (https://github.com/Microsoft/vscode/issues/14909) it does support toggling layouts between horizontal and vertical.
I think that the Vim extension should check which layout mode VSCode is in currently and enable the appropriate `<C-w>s` or `<C-w>v` keybinding.

**How to reproduce it (as minimally and precisely as possible)**:
* View -> Toggle Editor Group Layout
* `<C-w>v` wrongly splits horizontally instead of vertically
* `<C-w>s` does nothing

**Environment**:

Linux

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.20.0 c63189deaa8e620f650cc28792b8f5f3363f2c5b x64
- OS version: Ubuntu 17.10

**Comment by Dvbnhbq** [comment] 2018-02-14 17:12
I'd like to have all the `C-w` commands such as `C-w, HJKL` for navigating, `C-w, =` to make windows equal etc., to avoid using a mouse or trackpad.

**Comment by bpasero** [comment] 2018-07-02 10:05
Duplicate of https://github.com/VSCodeVim/Vim/issues/2696 ?

**Comment by jpoon** [comment] 2018-07-06 05:38
Indeed. Thanks @bpasero. Duplicate of #2696

**Closed by jpoon** 2018-07-06 05:38 UTC
Labels: help wanted, kind/enhancement, size/S
