### ISSUE TITLE
Failed to handle key `<C-r>`: TextEditor(vs.editor.ICodeEditor:4,$model4) has been disposed

### ISSUE THREAD

**Issue by ashish-web-developer** [VSCodeVim/Vim#7361] opened 2021-12-31 07:38 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:4,$model4) has been disposed
    at n (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)
    at Ja.$tryApplyEdits (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2322:16900)
    at u._doInvokeHandler (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1506:13116)
    at u._invokeHandler (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1506:12800)
    at u._receiveRequest (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1506:11462)
    at u._receiveOneMessage (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1506:10140)
    at vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1506:8236
    at a.fire (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at o.fire (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:19631)
    at d._receiveMessage (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24212)
    at vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:21746
    at a.fire (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at s.acceptChunk (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:16459)
    at vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:15589
    at Socket.P (vscode-file://vscode-app/c:/Users/abhya/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2984:8477)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

**Comment by J-Fields** [comment] 2022-02-03 02:49
Duplicate of #6872

**Closed by J-Fields** 2022-02-03 02:49 UTC
