### ISSUE TITLE
0.11.2 doesn't start, rolling back to 0.11.1 fixes the issue

### ISSUE THREAD

**Issue by robertwahler** [VSCodeVim/Vim#2436] opened 2018-03-09 19:06 UTC
0.11.1 auto updated to 0.11.2 and the block cursor is gone and I was stuck in insert mode. I downgraded to 0.11.1 and the issue is gone. Code 1.21.0 on macOS.

**Comment by rharriso** [comment] 2018-03-09 20:39
@jpoon @Chillee @shortheron 

Looks like there might have been a problem with the build.

```
[Extension Host] Here is the error stack:  Error: Cannot find module 'lodash'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/rharriso/.vscode/extensions/vscodevim.vim-0.11.2/out/src/taskQueue.js:11:11)
	at Object.<anonymous> (/Users/rharriso/.vscode/extensions/vscodevim.vim-0.11.2/out/src/taskQueue.js:85:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
```

<img width="1552" alt="screen shot 2018-03-09 at 3 38 13 pm" src="https://user-images.githubusercontent.com/570910/37228869-14e88704-23b0-11e8-8cfd-43eed31c1370.png">

**Comment by jpoon** [comment] 2018-03-09 21:17
Can you try this: https://github.com/VSCodeVim/Vim/issues/2287#issuecomment-357376528?

**Comment by jpoon** [comment] 2018-03-11 08:40
Likely dupe of #2287 and closing it as such.

**Closed by jpoon** 2018-03-11 08:40 UTC

**Comment by rharriso** [comment] 2018-03-12 14:16
@jpoon confirmed that worked. Would it be a good idea to add instructions about that to the readme or issue template? It seems like this is going to keep happening.
