### ISSUE TITLE
`:s` doesn't support using `&` to reference the matched string

### ISSUE THREAD

**Issue by satu** [VSCodeVim/Vim#6119] opened 2021-02-10 15:54 UTC
**Describe the bug**
The `s/texttofind/texttoreplacewith/g` command doesn't support using `&` to reference the 

**To Reproduce**

1. write `test123` on a line
2. type `:s/test/my&/g`

**Expected behavior**
Line is changed to `mytest123` -- this is the behavior in vi / vim

**Observed behavior**
Line is changed to `my&123`

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.9
- VSCode version: 1.53.1
- OS: MacOS 11.2

**Comment by J-Fields** [comment] 2021-10-15 05:32
We do support this via `\&`, but you're right - the default should be `&`. The correct behavior is really to depend on `'magic'`, but that's not yet supported.

**Comment by J-Fields** [comment] 2022-06-21 04:03
Duplicate of #7571, will be fixed in next release

**Closed by J-Fields** 2022-06-21 04:03 UTC
Labels: status/duplicate, kind/enhancement, area/commandline
