### ISSUE TITLE
Ugly vertical cursor moving with CJK characters

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [VSCodeVim/Vim#5910] opened 2020-12-20 04:33 UTC
**Describe the bug**
Ugly vertical cursor moving with CJK characters. Without vim extension, cursor moves accurately.
Also the cursor moves accurately with special characters(like below emoji).

**To Reproduce**
Use below strings:

```
안녕하세요12345
123456789012345
😀😃😄😁😆12345
123456789012345
```

**Expected behavior**
The vertical movement must be accurate.

**Screenshots**
![2020-12-20 13 26 17](https://user-images.githubusercontent.com/15520015/102705172-ca023700-42c7-11eb-9725-810f4d53f89a.gif)

**Environment (please complete the following information):**
I use this font: https://github.com/naver/d2codingfont

- Extension (VsCodeVim) version: v1.18.5
- VSCode version: 1.52.1
- OS: macOS 10.15.4 (19E287)

**Additional context**

**Comment by 5pecia1** [comment] 2020-12-25 03:00
Duplicate of #4096

**Closed** 2020-12-27 19:15 UTC
Labels: status/duplicate
