### ISSUE TITLE
getLineLength() called with out-of-bounds line 22

### ISSUE THREAD

**Issue by wayneforrest** [VSCodeVim/Vim#5512] opened 2020-10-28 03:16 UTC
**To Reproduce**
Not sure on how to reproduce this.

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 22
	at Function.getLineLength (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491507)
	at _ (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/wayneforrest/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-29 16:17
Duplicate of #5180

**Closed by J-Fields** 2020-10-29 16:17 UTC
