### ISSUE TITLE
Noremap problems

### ISSUE THREAD

**Issue by Zurek92** [VSCodeVim/Vim#4053] opened 2019-09-08 09:27 UTC
**Describe the bug**
I tried to change `hjkl` behavior to more friendly `jkl;`, in vim it's very simple in .vimrc config:
```
noremap ; l
noremap l k
noremap k j
noremap j h
```

I did the same in vscode config: settings.json:
```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [";"],
      "after": ["l"]
    },
    {
      "before": ["l"],
      "after": ["k"]
    },
    {
      "before": ["k"],
      "after": ["j"]
    },
    {
      "before": ["j"],
      "after": ["h"]
    },
  ],
    "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [";"],
      "after": ["l"]
    },
    {
      "before": ["l"],
      "after": ["k"]
    },
    {
      "before": ["k"],
      "after": ["j"]
    },
    {
      "before": ["j"],
      "after": ["h"]
    },
  ]
```
It works fine in normal mode and visual block mode but I've got a problem while selecting something (push v - select) and my noremaps don't work for about 400-500ms 
(j - expected left moved down instead)

after this short time everything works as expected but it's still very annoying.

- VSCode version: Visual Studio Code 1.38.0
- OS: Linux Mint

**Comment by J-Fields** [comment] 2019-09-08 22:15
Possible duplicate of #3812

**Comment by J-Fields** [comment] 2019-12-10 22:00
I just tried this:
```
vnoremap j h
vnoremap k j
vnoremap l k
vnoremap ; l
```
Which worked as expected

**Comment by Zurek92** [comment] 2019-12-11 11:24
But you tried it with VSCode? How this json should looks like to achieve that?

**Comment by agentlewis** [comment] 2020-07-12 05:21
@J-Fields hey mate - which file are you writing vnoremap into? neovim?

Im having trouble with vscode just locking up once it looses focus and comes mack in when I edit the mappings through the settings.json file.

**Comment by berknam** [comment] 2020-07-12 15:35
The problem in this issue is already fixed on master after PR #5000.

> 
> 
> @J-Fields hey mate - which file are you writing vnoremap into? neovim?
> 
> Im having trouble with vscode just locking up once it looses focus and comes mack in when I edit the mappings through the settings.json file.

If VSCode is really locking up it might be due to infinite recursive mappings. But that would usually happen when pressing one of the remapped key, not when loosing focus.

**Comment by J-Fields** [comment] 2020-07-12 16:44
> @J-Fields hey mate - which file are you writing vnoremap into? neovim?

https://github.com/VSCodeVim/Vim#vimrc-support

**Comment by J-Fields** [comment] 2020-07-12 16:45
New version should be out later today with #5000 included. Closing the issue

**Closed by J-Fields** 2020-07-12 16:45 UTC
Labels: area/remap
