### ISSUE TITLE
cursor not jumping up when page scrolled to the top using ctrl-d

### ISSUE THREAD

**Issue by Rhoeberg** [VSCodeVim/Vim#823] opened 2016-10-03 14:30 UTC
This is a small one, but I decided to write an issue since it is default vim behavior and it does interrupt my flow a bit.

### What did you do?
- curser around the bottom of the page
- scrolled the page all the way to the top using ctrl-u

### What did you expect to happen?
Expected that cursor would jump to the top of the page. Which seems to be default vim behavior.

### What happened instead?
Cursor not moving at all. Only page itself is moving.

### Technical details:
* VSCode Version: 1.5.3
* VsCodeVim Version: 0.2.0
* OS: MacOs

### extra
When scrolling downwards I expected the page to stop so bottom of the page would hit the last line. But instead it keeps going down until cursor is at the last line. This seems to be how vscode works though.

**Comment by xconverge** [comment] 2016-10-03 15:53
Duplicate of #810

**Closed** 2016-10-03 16:33 UTC
Labels: duplicate
