### ISSUE TITLE
Cannot read property 'getNextSearchMatchPosition' of undefined

### ISSUE THREAD

**Issue by ProseGuys** [VSCodeVim/Vim#5422] opened 2020-10-15 08:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'getNextSearchMatchPosition' of undefined
	at F.updateView (/Users/narrows/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:490400)
	at F.handleSelectionChange (/Users/narrows/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:468045)
	at Object.promise (/Users/narrows/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235549)
	at Object.runTasks (/Users/narrows/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621922)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:01
Duplicate of #5310

**Closed by J-Fields** 2020-11-12 23:01 UTC
Labels: status/duplicate
