### ISSUE TITLE
Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 15

### ISSUE THREAD

**Issue by kazuma-fujita-genova** [VSCodeVim/Vim#5615] opened 2020-11-10 01:20 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 15
	at Function.getLineLength (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at /Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88711
	at Array.map (<anonymous>)
	at ne.exec (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88618)
	at ne.execCount (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
	at F.runAction (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
	at F.handleKeyAsAnAction (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/kazuma/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-10 18:41
Duplicate of #5180, if you can reproduce please post steps on that ticket.

**Closed by J-Fields** 2020-11-10 18:41 UTC
