### ISSUE TITLE
getLineLength() called with out-of-bounds line 178

### ISSUE THREAD

**Issue by Cheb35** [VSCodeVim/Vim#5821] opened 2020-12-04 17:57 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 178
    at Function.getLineLength (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:22163)
    at l.getRight (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:10438)
    at F.updateView (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:491590)
    at _ (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:230166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:234397)
    at Object.runTasks (/Users/a35/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:27
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 18:27 UTC
Labels: status/duplicate
