### ISSUE TITLE
In insert mode, <C-r>= not working as expected 

### ISSUE THREAD

**Issue by cl806** [VSCodeVim/Vim#8170] opened 2022-12-20 16:30 UTC
**Describe the bug**
In insert mode, Ctrl-r= not working as expected

**To Reproduce**
In insert mode, type  Ctrl-r=6*10Enter

**Expected behavior**
expect 60 after Enter key 

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.72.2
- OS: Linux 

**Additional context**
In vim, in insert mode, you can enter Ctrl-r=  then enter math operation, hit enter key, the math operation result is inserted

**Comment by J-Fields** [comment] 2022-12-27 21:59
Duplicate of #4383

**Closed by J-Fields** 2022-12-27 21:59 UTC
