### ISSUE TITLE
Crtl-v + delete + paste

### ISSUE THREAD

**Issue by oricou** [VSCodeVim/Vim#5646] opened 2020-11-13 11:19 UTC
**Describe the bug**
Crtl-v + x + p (or P) does not have the correct behaviour.

**To Reproduce**

Starting with

```
1234
1234
```

If I select the block 23 on the two lines of this example and paste them before the first 1 I get

```
23
2314
14
```

when I should have

```
2314
2314
```

**Environment (please complete the following information):**

vscode 1.51.1
vim exension: v1.17.1
OS Linux x64 5.0.12

**Comment by J-Fields** [comment] 2020-11-13 17:54
Duplicate of #1796

**Closed by J-Fields** 2020-11-13 17:54 UTC
