### ISSUE TITLE
Undo does not work after save

### ISSUE THREAD

**Issue by darkermatter** [VSCodeVim/Vim#1783] opened 2017-05-30 07:27 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Environment**:

- **VSCode Version**: Insiders
- **VsCodeVim Version**: 0.8.4
- **OS**: macOS 10.12.6

**What happened**:
After saving a file with ```:w``` I cannot ```u```ndo anymore. 

**What did you expect to happen**: 
Continue undoing the horrors I inflicted on the file.

**How to reproduce it**:
Make some changes to a file, save it and try to undo those changes.

**Comment by Chillee** [comment] 2017-05-31 15:55
This issue doesn't seem to occur for me, with VSCodeVim version 0.8.4 and ArchOS.

**Comment by am1ko** [comment] 2017-06-01 20:04
Happens to me also

- VSCodeVim version 0.8.4
- VSCode Version 1.13.0-insider (1.13.0-insider)
- Mac OS Sierra 10.12.5

**Comment by erlais** [comment] 2017-06-07 12:41
VSCodeVim undo is totally unusable for me right now (default ctrl+z works just fine). Whenever a file is saved there is no undo history. It's not just when filename is changed, any save at all seems to erase undo history. I am using  auto save after 1 second delay, so I have 1 second of undo history 😄. Turning auto save off is more usable at the moment, but doesn't fix the problem.

- VSCodeVim version 0.8.4
- VSCode Version 1.13.0-insider
- Windows 10

**Comment by Chillee** [comment] 2017-06-07 20:16
@erlais @darkermatter Could you guys post your settings?

**Comment by darkermatter** [comment] 2017-06-07 20:23
```
// Place your settings in this file to overwrite the default settings
{
    "workbench.colorTheme": "Monokai-Soft",
    "workbench.iconTheme": "vscode-simpler-icons",
    "workbench.welcome.enabled": false,
    "workbench.activityBar.visible": false,
    "workbench.colorCustomizations": {
        "statusBar.background": "#B16900",
        "statusBar.noFolderBackground": "#B16900",
        "statusBar.debuggingBackground": "#B16900"
    },
    "vim.hlsearch": true,
    "vim.statusBarColorControl": true,
    "vim.statusBarColors": {
        "normal": "#000000",
        "insert": "#B00B0B",
        "replace": "#B00B0B",
        "visual": "#B16900",
        "visualline": "#B16900",
        "visualblock": "#B16900"
    },
    "editor.fontFamily": "Monaco",
    "editor.fontSize": 12.3,
    "editor.tabSize": 2,
    "editor.lineNumbers": "relative",
    "zenMode.hideStatusBar": false,
    "problems.autoReveal": true,
    "window.titleBarStyle": "custom",
    "clock.dateFormat": "    HH:MM    ",
    "gitProjectManager.baseProjectsFolders": [
        "/Projects"
    ],
    "go.testOnSave": false,
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.lintTool": "gometalinter",
    "go.lintFlags": [
        "--vendor",
        "--disable-all",
        "--enable=errcheck",
        "--enable=vet",
        "--enable=vetshadow",
        "--enable=golint",
        "--enable=ineffassign",
        "--enable=goconst",
        "--tests"
    ],
    "go.autocompleteUnimportedPackages": true,
    "git.enableSmartCommit": true,
    "todohighlight.isEnable": true,
    "todohighlight.include": "{**/*.js,**/*.jsx,**/*.ts,**/*.html,**/*.php,**/*.css,**/*.scss,**/*.go}",
    "todohighlight.exclude": "{**/node_modules/**,**/bower_components/**,**/dist/**,**/build/**,**/.vscode/**,**/_output/**,**/*.min.*,**/*.map,**/vendor/**}",
    "editor.cursorBlinking": "solid",
    "editor.cursorStyle": "block",
    "editor.minimap.enabled": false,
    "workbench.statusBar.visible": true,
    "material-icon-theme.showUpdateMessage": false,
    "vim.foldfix": true,
    "vim.enableNeovim": true,
    "vim.neovimPath": "/usr/local/bin/nvim",
    "vim.disableAnnoyingNeovimMessage": true,
    "vsicons.dontShowNewVersionMessage": true
}
```

**Comment by erlais** [comment] 2017-06-07 22:27
[My settings in Pastebin](https://pastebin.com/mu2WQFwg)

**Comment by Chillee** [comment] 2017-06-09 00:20
I was just able to replicate this issue. May have something to do with the amount of load your computer is currently under?

**Comment by darkermatter** [comment] 2017-06-09 01:08
@erlais I have an international English keyboard with the Irish keyboard layout (generally faster for typing Spanish than a Spanish keyboard¡!¡!) and Spanish regional settings. I have never had any issues with this setup.

Also, the nvim update sounds about right.

**Comment by darkermatter** [comment] 2017-06-09 01:10
@Chillee This happens under all load conditions.

**Comment by michaelHL** [comment] 2017-06-09 02:52
+1 Confirmed. :neutral_face: Can't redo my operations after saving.

- VSCodeVim version 0.8.4
- VSCode Version 1.13.0
- Windows 10 x64 1607

**Comment by dkln** [comment] 2017-06-09 07:13
Same here. But... it does work when you use `cmd+z`

**Comment by michaelHL** [comment] 2017-06-09 08:31
@dkln And <kbd>cmd</kbd><kbd>shift</kbd><kbd>z</kbd> :no_mouth:

**Comment by bjeanes** [comment] 2017-06-09 12:45
Also experiencing this. No undo available directly after save.

**Comment by Chillee** [comment] 2017-06-09 17:53
Oh shit I just realized. Fuck.

This is a change to VSCode version 1.13.0. The reason @darkermatter, @am1ko, and @erlais reported this issue early is because they're on insiders.

Now that version 1.13.0 has dropped, everybody's getting this issue (including me). It has to do with a change to VSCode on how they're handling dirty files.

**Comment by bjeanes** [comment] 2017-06-09 21:32
Fixable?

**Comment by Chillee** [comment] 2017-06-09 21:44
@bjeanes Definitely. I wrote about what I figured out here: https://github.com/VSCodeVim/Vim/issues/1814

It might be worth it for me to switch to Insiders so I can see these things before they happen...

**Comment by djmurf** [comment] 2017-06-10 21:25
Seeing issue here also.... Save file, history is gone... Please fix, I really  don't want to go back to Atom...

**Comment by Chillee** [comment] 2017-06-11 04:58
We just pushed out a new release, and this problem should be fixed in v0.8.5

**Closed by Chillee** 2017-06-11 04:58 UTC
Labels: kind/bug

**Comment by darkermatter** [comment] 2017-06-11 10:07
I've switched to 1.13 stable and it works there.

**Comment by Chillee** [comment] 2017-06-11 16:37
@darkermatter it should work anywhere if you v0. 8.5 of vscodevim installed.

**Comment by dkln** [comment] 2017-06-20 06:15
👍  ❤️

**Comment by caipre** [comment] 2017-12-22 19:59
I'm on `Version 1.19.1` with `Vim 0.10.6` and just hit this. Possibly because I'm also using the go plugin?

**Comment by savaged** [comment] 2020-02-19 09:19
Same here. I have autosave on and hitting `u` does nothing
