### ISSUE TITLE
No handler found for the command: 'extension.vim_esc'

### ISSUE THREAD

**Issue by otacon507** [VSCodeVim/Vim#306] opened 2016-06-16 18:08 UTC
I installed the plugin successfully, and accepted the prompt to restart VScode. Now there is no functionality for the pluging: typing is regular, and if I press 'esc' I am prompted with:

`No handler found for the command: 'extension.vim_esc'. An extension might be missing an activation event.`

Also, when I try to backspace now, I am similarly faced with:

`No handler found for the command: 'extension.vim_backspace'. An extension might be missing an activation event.
`
So the plugin has effectively broken VScode and must be removed until the issue is known/fixed

**Comment by jpoon** [comment] 2016-06-16 18:18
Now, this might sound crazy but....have you tried manually restarting VSCode? I've seen that VSCode doesn't seem to pick up the handlers after that first restart.

**Comment by otacon507** [comment] 2016-06-16 19:04
A restart of the entire PC doesn't fix the issue

**Comment by johnfn** [comment] 2016-06-16 19:25
What version of VSC are you running? This strikes me as a bug with VSC itself.

**Comment by otacon507** [comment] 2016-06-16 19:26
![image](https://cloud.githubusercontent.com/assets/6384324/16130362/f6680d9e-33c5-11e6-95a9-2b40eb9d3783.png)

**Comment by tylerjwatson** [comment] 2016-06-16 23:28
Same issue here.  Same version, same commit hash - my dialog mimics @otacon507's.  It's the latest packaged download off the VSCode website.  Every motion key that is pressed generates one of these warnings and doesn't act as intended.

In addition, the chromium console contains this output: 

![image](https://cloud.githubusercontent.com/assets/5001408/16136437/bbaf847c-346d-11e6-9d92-67ff88f7e11d.png)

Hopefully this may be useful to someone.

**Comment by johnfn** [comment] 2016-06-17 06:52
Ahh, that is helpful! 

That means that `vscode.window.activeTextEditor` is not available at the time. I can't imagine how that's the case, but I suppose we should poll for it before we start the extension.

**Comment by adelgado** [comment] 2016-06-17 09:27
I've also been hitting this issue for the past few days.

**Comment by johnfn** [comment] 2016-06-17 09:36
@adelgado , @tylerjwatson are you guys on Windows?

**Comment by adelgado** [comment] 2016-06-17 09:55
@johnfn No, I'm on a Mac.

**Comment by johnfn** [comment] 2016-06-17 09:59
Huh. Well, I'm stumped why it triggers for some people but not others. 

In any case, I'm pretty sure I know what caused the change. I'll commit a fix tomorrow night and hopefully push out a new version then.

**Comment by tylerjwatson** [comment] 2016-06-17 10:26
Windows here. I am yet to try it on my Linux machine.

**Comment by otacon507** [comment] 2016-06-17 14:59
Also on Windows

**Comment by johnfn** [comment] 2016-06-18 07:34
Hi guys! Could you please check out the latest version 0.0.22 and see if that fixes the problem? 

Thanks!

**Comment by dxcqcv** [comment] 2016-06-20 11:24
reinstalled, the bug does not show again. from arch linux + awesome-wm.

**Comment by jpoon** [comment] 2016-06-20 18:52
@dxcqcv yippieee! (i miss arch + awesome)

**Comment by johnfn** [comment] 2016-06-20 19:32
Great! Gonna close this. :smile:

**Closed by johnfn** 2016-06-20 19:32 UTC
Labels: v0.22

**Comment by otacon507** [comment] 2016-06-20 20:55
Fixed for me as well :+1:

**Comment by adelgado** [comment] 2016-06-21 19:02
Also working here :-)
