### ISSUE TITLE
Vimrc: Any way to remap :W to :w

### ISSUE THREAD

**Issue by mpnolan** [VSCodeVim/Vim#4689] opened 2020-03-27 01:12 UTC
I was happy to see in #463 that .vimrc support was added. But I can't seem to solve my problem with it, which is that I want to remap :W to :w so that I don't get `E492: Not an editor command: W` when I don't lift up shift fast enough.

I noted PR #3908 which adds key remapping support, however, I've tried a hodgepodge of things (from rabid and impatient searching) by now and none have seemed to work:

```
:command W w
noremap :W :w
command! W :w
```
(The first is my working solution in .vimrc)

Is there a known working way to do this?

Best to you all at a challenging time,

**Comment by J-Fields** [comment] 2020-03-27 01:16
This isn't possible at this time, though I hope to support it soon. PRs are very welcome!
Duplicate of #4454

**Closed by J-Fields** 2020-03-27 01:16 UTC
Labels: area/commandline, area/remap, kind/feature

**Comment by theqoobee** [comment] 2020-04-06 10:49
Just another question on a related subject,

Adding the following to my .vimrc file didn't do anything, is it because the feature isn't there or did I do something wrong. (There's a lot more, it's just an example)

```
nnoremap ;; :w<CR>
```

So is this feature not yet implemented?

**Comment by J-Fields** [comment] 2020-04-06 19:31
There's currently a limitation that mappings cannot overlap. `;` matches before `;;` ever has the chance to, so it's triggered and the recorded keys are reset.

**Comment by theqoobee** [comment] 2020-04-07 09:18
Oh, I'll just set it to something else, thank you!
