### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 17

### ISSUE THREAD

**Issue by davidpatr** [VSCodeVim/Vim#5326] opened 2020-10-04 09:17 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 17
    at Function.getLineLength (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
    at F.executeMovement (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:480271)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475336)
    at F.handleKeyAsAnAction (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
    at F.handleKeyEvent (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
    at Object.promise (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\prabh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:46
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:46 UTC
