### ISSUE TITLE
Typing fast kills some commands

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2060] opened 2017-10-10 12:53 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.17.0
- **VsCodeVim Version**: 0.10.1
- **OS**: macosx 10.13

**What happened**:
Trying to use `<leader><leader>s` for jumping. When I hit <leader> to fast the command is erased and I end up with `<leader>s` which does something else.

**What did you expect to happen**: 
That the ace jump like characters pop up.

**How to reproduce it**:
hit `<leader><leader>s` medium fast.

**Comment by xconverge** [comment] 2017-10-13 20:14
What do you mean s for jumping?

I am unable to reproduce this, do you think you can explain the steps in a different way? Thanks!

**Comment by bm-stschneider** [comment] 2017-10-16 06:39
Sorry, md seems to have misinterpreted the <> thing

**Comment by xconverge** [comment] 2017-10-16 14:19
What do you have ```<leader> s``` mapped to that is triggering instead of easymotion?

You can reproduce this all the time?

**Comment by bm-stschneider** [comment] 2017-10-16 15:04
`<leader>` in my case is space.

**Comment by xconverge** [comment] 2017-10-16 15:11
Yea but you said leader a triggers not leader leader s? What does leader s trigger when it isn't the easymotion search

**Comment by bm-stschneider** [comment] 2017-10-17 06:42
`<leader><leader> s <char>` | Search character
-- | --

**Comment by xconverge** [comment] 2017-10-17 15:51
Sorry, I still really do not understand.

That is what you EXPECT to be triggered. What are you triggering by accident when this bug happens

"Trying to use <leader><leader>s for jumping. **When I hit to fast the command is erased and I end up with <leader>s which does something else.**"

**Comment by bm-stschneider** [comment] 2017-10-18 06:52
okay so `<leader> == <space>` for me. if I try to use space, space, s to search for a character, similar to the well known ace jump, if I hit space, space to fast, it gets reduced to a single space. and space, s does something else than space, space, s.

**Comment by berknam** [comment] 2020-08-04 16:47
@bm-stschneider Is this still an issue? Because I can't reproduce it.

**Comment by bm-stschneider** [comment] 2020-08-04 22:54
Sorry but I do not know. I switched to the Dancer extension meanwhile. I mean, this is 3 years old :)

**Comment by berknam** [comment] 2020-08-05 10:32
I know. I've been looking for issues that I can signal as a potential fix of a PR I've done, but this one I can't reproduce it at all, that's why I asked.

@J-Fields Maybe this old issues that can no longer be reproduced should be closed. If someone else happens to have the same issue they can open a new one. There is also the issue #4283 that might be related to this, but I can't reproduce that one either.

**Comment by J-Fields** [comment] 2020-08-05 15:39
Yeah I haven't experienced this issue and it's very old, so I'll close it. If someone does have this problem, feel free to ping me on this issue or open a new one.

**Closed by J-Fields** 2020-08-05 15:39 UTC
