### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by stillzhl** [VSCodeVim/Vim#3627] opened 2019-03-27 07:24 UTC
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/hailizhang/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment] 2019-03-28 18:53
Dupe of https://github.com/VSCodeVim/Vim/issues/3362

**Closed by jpoon** 2019-03-28 18:53 UTC
