### ISSUE TITLE
Failed to handle key=<Del>. Illegal value for `line`

### ISSUE THREAD

**Issue by ajtdnta** [VSCodeVim/Vim#5394] opened 2020-10-13 01:34 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Del>. Illegal value for `line`
	at d._lineAt (c:\Users\lyczh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:545:764)
	at Object.lineAt (c:\Users\lyczh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:544:734)
	at Function.getLineAt (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22450)
	at b.delete (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:55360)
	at b.run (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:56136)
	at _.run (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:59127)
	at F.executeOperator (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:481015)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:476268)
	at async F.handleKeyAsAnAction (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\lyczh\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 21:57
Duplicate of #5305; if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 21:57 UTC
