### ISSUE TITLE
Asterisk '*' search is not case-insensitive on last match in a file

### ISSUE THREAD

**Issue by rangercej** [VSCodeVim/Vim#2673] opened 2018-05-22 08:47 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**: With vim.ignorecase = true ... if I search for a word with '/', the search is case insensitive. However pressing '*' on the last instance of a word, it is not possible to press 'n' to find the next match.

**What did you expect to happen**: / and * behaviour the same for looking for next match

**How to reproduce it (as minimally and precisely as possible)**: With these lines in a file:

    hello world
    Hello world
    hello WORLD

These actions work as expected:
- If you put the cursor on "Hello" in line 2 and press '*', then all instances of hello are found on all three lines, and pressing 'n' moves through all of them, regardless of case.
- If you put the cursor on "hello" in line 3 and press '*', then all instances of hello are found on all three lines, and pressing 'n' moves through all of them, regardless of case.
- If you put the cursor on "world" on line 2 and press '*', then all instances of world are found on all three lines, and pressing 'n' moves thorough all of them, regardless of case.
 
However this action does **not** work as expected:
- If you put the cursor on "WORLD" in line 3 and press '*', then no other instance of world is found, and pressing 'n' does not find any other instance of "world".

**Environment**:
- Extension Name: vim
- Extension Version: 0.12.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.23.1

**Comment by arussellk** [comment] 2018-06-06 06:33
@rangercej I'm working to fix this. The problem is that `smartcase` is being used by `*` and `#` even though it shouldn't be.

As a quick fix, you can try adding `"vim.smartcase": false` to you user settings.

**Comment by J-Fields** [comment] 2019-08-06 19:40
Closing in favor of #1800

**Closed by J-Fields** 2019-08-06 19:40 UTC
Labels: area/search, kind/bug
