### ISSUE TITLE
Updating version into 1.1.0, vim is not working

### ISSUE THREAD

**Issue by denniscual** [VSCodeVim/Vim#3536] opened 2019-02-28 14:39 UTC
**Describe the bug**
Updating version into 1.1.0, vim stops working. I tried to re-install the vim extension and restarting my lp, problem still occur.

**Environment**
- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.30.2
- OS: Mac

**Comment by weebs** [comment] 2019-02-28 18:57
Same issue here. Deleting the vim extension folder and reinstalling doesn't work either

Using VSCode 1.30.1 on Windows 7

**Comment by KernelDeimos** [comment] 2019-02-28 20:10
Also observed on Ubuntu 18.04. 1.0.7 is working fine

**Comment by Nogbit** [comment] 2019-02-28 21:59
Also observed openSUSE Tumbleweed, 1.0.7 is also working for me as an alternative

**Comment by JKillian** [comment] 2019-03-01 04:55
Please see https://github.com/VSCodeVim/Vim/issues/3522 - the latest version of VSCodeVim requires that you're on VSCode 1.31.0 or newer.

Please reply if you aren't able to upgrade though, in which case it makes #3525 more important to get merged.

**Comment by zNeill** [comment] 2019-03-01 08:01
Running VSCode 1.30.2 with VSCodeVim 1.1.0 on Mac OS 10.14.3, confirming same issue.

**Comment by vinceyuan** [comment] 2019-03-01 10:37
It is fixed on VSCode 1.31.

If you have issues in upgrading VSCode to 1.31 on mac, drag VSCode (and hold cmd key) out of Applications folder and then drag it back. It fixes the issue of updating.

**Comment by jpoon** [comment] 2019-03-01 22:02
Likely dupe of https://github.com/VSCodeVim/Vim/issues/3522

**Closed by jpoon** 2019-03-01 22:02 UTC
