### ISSUE TITLE
backspace not working on selected items

### ISSUE THREAD

**Issue by rajinder-yadav** [VSCodeVim/Vim#940] opened 2016-10-19 00:48 UTC
### What did you do?
from insert mode, type some text
select text, hit backspace

### What did you expect to happen?
selected text to be deleted

### What happened instead?
only a single text get deleted

### Technical details:

VsCodeVim Version: 0.3.8
VSCode Version: Code 1.6.1 (9e4e44c, 2016-10-13T15:43:46.054Z)
OS Version: Linux x64 4.4.0-43-generic

**Comment by xconverge** [comment] 2016-10-19 01:13
This is a dupe of 879

**Closed** 2016-10-19 03:17 UTC
Labels: duplicate
