### ISSUE TITLE
Holding down the l or h keys does not go right or left, it skips around

### ISSUE THREAD

**Issue by mreishus** [VSCodeVim/Vim#735] opened 2016-09-08 19:45 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I held the `l` key down.

### What did you expect to happen?

I expected the cursor to move to the right character by character.

### What happened instead?

The cursor moved right a few characters, then skipped several characters to the left, then continued moving right again, then skipped to the left again.  Here's a low FPS animated gif:  http://i.imgur.com/iip1ciZ.gifv  In it, I can't get past the words `onClick` even though I keep holding `l.`  Later in the gif, I change to holding `h`.

### Technical details:

* VSCode Version: 1.5.0
* VsCodeVim Version: 0.1.10
* OS:  Windows 7, but I've seen the same behavior on my mac.
It is inside a jsx file (with js extension).

**Comment by xconverge** [comment] 2016-09-08 19:56
Hmm we have had a few reports of this but we can't reproduce it yet...

Can you try this, it has helped a few people temporarily while we try to pin it down:

"Go into your keyboard settings and change the repeat rate to be slightly slower"

**Comment by jpoon** [comment] 2016-09-08 19:58
Might be a duplicate of this: https://github.com/VSCodeVim/Vim/issues/534.

**Comment by mreishus** [comment] 2016-09-08 22:12
Slowing the keyboard rate did help.  I had it at the fastest.   Strangely, I moved it back to the fastest and now I can't reproduce it anymore.

**Comment by dring1** [comment] 2016-09-12 23:58
Slowing the keyboard rate alleviates the issue, but really impacts vscode vim plugins.

**Comment by jpoon** [comment] 2016-09-13 00:11
Dupe bug. I'm going to close this in favor of #534.

**Closed** 2016-09-13 00:11 UTC
Labels: duplicate
