### ISSUE TITLE
Keyboard stops working with VSCode when indenting multiline [MacOS Mojave]

### ISSUE THREAD

**Issue by thauma9** [VSCodeVim/Vim#3206] opened 2018-11-13 09:43 UTC
as title, toggling the Vim extension and reloading solves the problem, so I think the problem is here.

- Extension (VsCodeVim) version: latest, 0.16.2
- VSCode version: October 2018 (version 1.29)
- OS: MacOS Mojave

Edit: it happens also on the September release, example:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/10284927/48408278-3f8a9900-e739-11e8-9679-c4b2827dbbb8.png">

**Comment by raphi011** [comment] 2018-11-22 11:37
Since today I have similiar problem ... on MacOS Mojave after typing some characters input gets stuck and I can't type anything anymore. After a few seconds it catches up and everything I have written catches up. Rinse and repeat ..

My problem does not have anything to do with indenting though .. the weird thing is this started happening out of the blue.. didn't (un)install any vs code extension or update the OS. The problem persists after rebooting.

**Comment by jpoon** [comment] 2018-12-30 11:37
Sounds like a different extension was the cause? In an effort to keep our issue list sane, I'm closing this issue.

**Closed by jpoon** 2018-12-30 11:37 UTC
