### ISSUE TITLE
Failed to handle key=<down>. Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by siwarrezgui** [VSCodeVim/Vim#6317] opened 2021-03-20 19:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<down>. Cannot read property 'isOperator' of undefined
    at filter (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:28)
    at a.operator (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:215:28)
    at I.executeMovement (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:956:77)
    at process.recordedState (internal/process/task_queues.js:97:5)
    at I.actionToRecord [as runAction] (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:700:7)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:643:43)
    at I.async [as handleKeyEvent] (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:469:11)
    at Object.promise (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\extensionBase.ts:632:27)
    at Object.runTasks (c:\Users\pc\.vscode\extensions\vscodevim.vim-1.19.0\src\taskQueue.ts:36:26)
```

</details>

**Comment by vdegenne** [comment] 2021-03-20 20:16
Stop to spam please and search before posting an issue, maybe people already reported that.

**Comment by J-Fields** [comment] 2021-03-20 20:29
Duplicate of #6309

**Closed by J-Fields** 2021-03-20 20:29 UTC
