### ISSUE TITLE
random jumping of cursor

### ISSUE THREAD

**Issue by cottrell** [VSCodeVim/Vim#3867] opened 2019-07-04 18:09 UTC
Typing "dd" and the up arrow (or any arrow) sometimes results in random jumping to some other line. Sometimes it seems like the line jumping even happens right after the 'dd' delete line command. Feels like it might even be asyncronous. 

Very hard to replicate but when it seems to start happening it happens a lot. I can dig into logs if anyone has suggestions.

**Comment by onnodb** [comment] 2019-07-05 13:08
It seems to me like this started happening recently, and it also seems to have something to do with having multiple views open on the same file.

**Comment by kianryan** [comment] 2019-07-05 16:08
Have been experiencing this for around a month - I assumed it was associated with other plugins, but have been having difficulty in isolating the problem.

Feel like I'm not going crazy alone.

**Comment by kianryan** [comment] 2019-07-05 17:58
Appears to be a duplicate of https://github.com/VSCodeVim/Vim/issues/3713

**Comment by ycavatars** [comment] 2019-07-08 02:58
I Also have this problem when I use the `gd` function except the first time. In a golang project, I use `gd` to go to the definition of a function/struct, and the file of the function will be opened in a new tab. Everything works well in the first time you open the file. However, if you close the file and use `gd` again, my cursor will jump randomly in the file.

**Comment by pot-code** [comment] 2019-07-08 07:31
I also noticed that after I typed `dd`, the vim status in status bar disappeared(which should be `--NORMAL--`).Then the cursor jumped to the end of file

**Comment by cottrell** [comment] 2019-07-16 09:57
UPDATE: "dd" or even shift-v select then "delete" leads to the issue with a jump happening after any keypress. However, a mouseclick after the delete event appears to stop the mouse jumping. 

Am hoping that will be enough of a clue for someone. My guess is "esc" is not escaping vim mode properly after the delete operation.

**Comment by wldcordeiro** [comment] 2019-07-16 18:41
This plugin is a mess. It halts so frequently and this is just a symptom of something wrong with it at the very core at this point. There's like 15 issues that all dance around the same problems.

**Comment by cottrell** [comment] 2019-07-27 12:32
https://github.com/VSCodeVim/Vim/issues/3713

**Comment by J-Fields** [comment] 2019-08-05 20:17
Closing in favor of #3713. Give that one a thumbs up if you'd like this issue to be prioritized by maintainers.

**Closed by J-Fields** 2019-08-05 20:17 UTC
