### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by gielisg** [VSCodeVim/Vim#6803] opened 2021-06-28 03:56 UTC
**To Reproduce**

1.  Make change to variable
2.  Click on n to go to next instance of the variable name
3.  Press "." to repeat substitute
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at s._applyEdit (c:\Users\gieli\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52514)
    at Object.edit (c:\Users\gieli\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:50206)
    at Object.executeTransformations (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\transformations\execute.ts:124:29)
    at I.runAction (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at I.rerunRecordedState (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\transformations\execute.ts:192:12)
    at I.actionToRecord [as runAction] (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:726:55)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\src\mode\modeHandler.ts:471:11)
    at c:\Users\gieli\.vscode\extensions\vscodevim.vim-1.21.3\extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:46
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:46 UTC
Labels: status/duplicate
