### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by tylersouthwick** [VSCodeVim/Vim#5612] opened 2020-11-09 19:37 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.17.1<details><summary>Stack trace</summary>```p</e.prototype.$executeCommand/</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:284625s/</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:282602s/<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:282707r</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:281620r<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:281357p</e.prototype.$executeCommand@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:167:284498p</e.prototype.doInvokeHandler@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:199168p</e.prototype.invokeHandler@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:198901p</e.prototype.receiveRequest@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:198193p</e.prototype.receiveOneMessage@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:197682e/this.multiplexor<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:195658t/<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:19:199544c</e.prototype[Symbol.iterator]/</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:117952c</e.prototype.invoke@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:118170u</e.prototype.fire@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:120221postMessage@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:113:870124d</e.prototype.onRequest/</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:103523s/</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:101423s/<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:101528r</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:100441r<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:100178d</e.prototype.onRequest@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:103377n/<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:108:102986$/a</</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:225058$/a</<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:226158$/a<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:1:228786l/<@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:136:49585l@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:136:49695n@https://b2b51675-755c-4fc4-ac29-588205fdb421.ws-us02.gitpod.io/bundle.js:136:48646```</details>

**Comment by J-Fields** [comment] 2020-11-12 23:31
Duplicate of #5526. What version of VS Code are you running?

**Closed by J-Fields** 2020-11-12 23:31 UTC
