### ISSUE TITLE
getLineLength() called with out-of-bounds line 19

### ISSUE THREAD

**Issue by nabeela-s** [VSCodeVim/Vim#5458] opened 2020-10-20 10:39 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 19
    at Function.getLineLength (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.isLineEnd (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14231)
    at l.getRightThroughLineBreaks (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11052)
    at Object.t.statusBarCommandText (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31336)
    at Object.updateShowCmd (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
    at F.handleKeyEvent (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/nabeela/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:58
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:58 UTC
