### ISSUE TITLE
Failed to handle key=g. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by mathaichan** [VSCodeVim/Vim#6809] opened 2021-06-29 12:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=g. Cannot read property 'previousMode' of undefined
    at I.updateView (/home/mathaichan/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:1171:50)
    at I.handleKeyAsAnAction (/home/mathaichan/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:662:16)
    at runMicrotasks (<anonymous>)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at I.text [as handleKeyEvent] (/home/mathaichan/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:471:11)
    at /home/mathaichan/.vscode/extensions/vscodevim.vim-1.21.3/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-08-30 19:34
Duplicate of #6343

**Closed by J-Fields** 2021-08-30 19:34 UTC
