### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by BorjaEst** [VSCodeVim/Vim#6930] opened 2021-07-29 12:46 UTC
**To Reproduce**
Normal usage. Details automatically collected.

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at n._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/home/borja/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/home/borja/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/borja/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/home/borja/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /home/borja/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[100, 4] | [101, 2]]"
]
actionsRunPressedKeys: [
  "<down>",
  "<left>",
  "<Esc>"
]
actionsRun: [
  "D",
  "q",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 100,
      "character": 4
    },
    "text": "lt",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 100,
        "character": 0
      },
      {
        "line": 100,
        "character": 6
      }
    ],
    "text": "result_1",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 00:05
Duplicate of #6888

**Closed by J-Fields** 2021-08-03 00:05 UTC
