### ISSUE TITLE
Unhandled rejection in promise from vscode-vim

### ISSUE THREAD

**Issue by doudou** [VSCodeVim/Vim#2201] opened 2017-12-06 19:03 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: Ubuntu 16.04.3 LTS

**What happened**:

I'm debugging my extension, and I get the following error:

~~~
   at HistoryTracker.getAllText (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/src/history/historyTracker.js:149:36)
    at HistoryTracker._initialize (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/src/history/historyTracker.js:161:78)
    at new HistoryTracker (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/src/history/historyTracker.js:139:14)
    at new ModeHandler (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/src/mode/modeHandler.js:400:40)
    at /home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/extension.js:44:42
    at Generator.next (<anonymous>)
    at __awaiter (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/extension.js:12:71)
    at Promise (<anonymous>)
    at __awaiter (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/extension.js:8:12)
    at getAndUpdateModeHandler (/home/doudou/.vscode/extensions/vscodevim.vim-0.10.5/out/extension.js:39:12)
~~~

**What did you expect to happen**: 

No unhandled rejection.

**How to reproduce it**:

- Generate a scaffold extension in a VSCode instance where vscode-vim is enabled
- start the extension target
- watch the Debug Console

**Comment by jpoon** [comment] 2017-12-12 14:08
Dupe of https://github.com/VSCodeVim/Vim/issues/2184

**Closed by jpoon** 2017-12-12 14:08 UTC
