### ISSUE TITLE
Please make InsertMode mode by default for create new file.

### ISSUE THREAD

**Issue by haacki47** [VSCodeVim/Vim#1103] opened 2016-12-01 07:06 UTC
Hello.
I got the problem when i create new file, and all time Vim include the CommandMode. It's cool, but not conveniently.
I shared this issue because in your docs nothing about this setting.

**Comment by johnfn** [comment] 2016-12-01 19:43
This is a duplicate of #1088.

It's interesting that this has gotten a bunch of attention recently!

**Closed by johnfn** 2016-12-01 19:43 UTC
