### ISSUE TITLE
Confirm-Replace does not work.

### ISSUE THREAD

**Issue by 3yakuya** [VSCodeVim/Vim#1918] opened 2017-07-11 18:39 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**Environment**:
VSCode 
VSCodeVim 
- **VSCode Version**: 1.14.0

- **VsCodeVim Version**: 0.9.0
- **OS**: macOS 10.12.5

**What happened**:
I have a file with some words like "lib" in it. I run:
:%s/lib/someReplacement/gc

It instantly replaces all "lib" with "someReplacement", rather than asking me for confirmation for everything.

**What did you expect to happen**: 
I expected it to ask me for confirmation with every occurrence of "lib" to be replaced

**How to reproduce it**:
Open any file, find a word you try to replace, run the following:

:%s/wordYouWantToReplace/someReplacement/gc

See if all words get replaced.

**Comment by Chillee** [comment] 2017-07-11 21:49
This is a duplicate of this issue https://github.com/VSCodeVim/Vim/issues/1010. I'm going to close this issue in favor of the other one due to its age and discussion.

Thanks!

**Closed by Chillee** 2017-07-11 21:49 UTC
