### ISSUE TITLE
Failed to handle key=a. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by nshibalov** [VSCodeVim/Vim#5523] opened 2020-10-28 20:25 UTC
**To Reproduce**
(Actually, I can't reproduce it myself, but those steps I made before error)

1.  Go to 'Editor'
2.  In 'Insert Mode' remove char '!'
3.  Go back to 'Visual Mode'
4. Press 'a' on keyboard (after error, 'Left Arrow' key gives error too)
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
	at h.setLastHistoryEndPosition (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:516515)
	at F.runAction (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:478718)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/nshibalov/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-06 05:59
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:59 UTC
Labels: status/duplicate
