### ISSUE TITLE
Failed to handle key=.. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by peeeechi** [VSCodeVim/Vim#5957] opened 2021-01-03 21:29 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
    at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:424)
    at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
    at a (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74323)
    at F.exec (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74368)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171810)
    at F.rerunRecordedState (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:178233)
    at v.execute (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:67137)
    at F.runAction (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171647)
    at F.handleKeyAsAnAction (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/pechi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
