### ISSUE TITLE
w command doesn't trigger Save hooks

### ISSUE THREAD

**Issue by yacinehmito** [VSCodeVim/Vim#1984] opened 2017-08-26 16:43 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: Linux

**What happened**:

I have the ESLint plugin installed that triggers a reformat on save.  It works flawlessly when I save through VSCode's menu or when using `Ctrl+s`. However if I type ':w', the reformat is not triggered (although the file is indeed saved).

**What did you expect to happen**: 

I expected the file to be reformated automatically. Note that I didn't test this with other plugins that register a Save hook (I'm quite new to VSCode). It may only be related to ESLint's plugin.

**How to reproduce it**:

- Install the ESLint plugin
- In a JS project, write a JS file that has an obviously wrong formatting (given your ESLint configuration)
- Save it with `:w`; the formatting stays the same
- Save it with `Ctrl+s` (or whatever shortcut you've set up to save a file); the formatting is fixed

**Comment by xconverge** [comment] 2017-10-05 03:44
related

https://github.com/Microsoft/vscode/issues/22040

duplicate of #1282

**Closed by xconverge** 2017-10-05 03:44 UTC

**Comment by yacinehmito** [comment] 2017-10-05 09:11
I suggest we change the title of #1282 to reflect the current understanding of the issue.

**Comment by xconverge** [comment] 2017-10-05 14:42
Will do, sorry for closing the more descriptive one!
