### ISSUE TITLE
exit from insert mode after typing anything

### ISSUE THREAD

**Issue by m3l7** [VSCodeVim/Vim#883] opened 2016-10-11 09:46 UTC
after I enter insert mode with "i", and I type any character, vscode-vim remains in insert mode, but the status bar switches to "normal mode" and the cursor changes to the normal mode.
I updated vscode to 1.6 and vscode-vim to the last version, I'm not sure which of the two is the source of the problem.

vscode-vim: 0.3.5
vscode: 1.6
OS: fedora 23, i3wm

**Comment by markrendle** [comment] 2016-10-11 10:40
I had the same problem (Windows 7), and I figured it must be an extension clash, so I spun up my Insiders instance and cleared everything out, then added them back one at a time, thinking it was probably one of the code completion plug-ins.

But no.

It is Icon plug-ins, and specifically, it's either Nomo or VSCode-Icons. Both of those caused the problem.

Bizarrely, if you set the Icon theme to one of the built-in ones, Vim goes back to working fine.

Even more bizarre still: after you've done that, if you then switch back to VSCode-Icons, it stays fine.

So, that's a workaround then :)

**Comment by markrendle** [comment] 2016-10-11 10:48
Although *HTML CSS Support* also seemed to cause it to break. I'm wondering if other extensions are throwing at startup and causing Vim to not initialize properly?

**Comment by urbanmichal** [comment] 2016-10-11 11:11
Yeap, I've got similar problems.

**Comment by 1player** [comment] 2016-10-11 12:43
@markrendle I have no Icon extension, yet I'm experiencing the same problem.

Found a way to reproduce: Open a new document with Cmd+N, defaults on Plain Text format, press "i", type something, works as intended.

Open a second document with Cmd+N, change type to HTML, press "i", type something, reverts to normal mode after the first character.

**Comment by johnfn** [comment] 2016-10-11 20:53
Thanks for the easy repro steps, @1player. Gonna look at this one soon.

**Comment by johnfn** [comment] 2016-10-12 01:54
Fixed on master. Thanks, guys!

**Closed** 2016-10-12 01:54 UTC
Labels: priority-critical
