### ISSUE TITLE
Set tabstop will set editor.tabSize to a string rather than a number

### ISSUE THREAD

**Issue by xinyangli** [VSCodeVim/Vim#6535] opened 2021-04-23 12:09 UTC
**Describe the bug**
Use :set tabstop=2 will set editor.tabSize to "2" rather than expected 2

**To Reproduce**
1. type :set tabstop=2 to set tabstop
2. open setting.json and check editor.tabSize
3. see error

**Expected behavior**
Value of editor.tabSize should be set to number rather than string

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
![image](https://user-images.githubusercontent.com/16359093/115868530-2db39100-a46f-11eb-858d-cbd90deff5b3.png)
![image](https://user-images.githubusercontent.com/16359093/115868619-4cb22300-a46f-11eb-89f6-bde9aecc7a98.png)

**Comment by J-Fields** [comment] 2021-04-23 16:14
Duplicate of #5859

**Closed by J-Fields** 2021-04-23 16:14 UTC
