### ISSUE TITLE
could not use the vim hot key in explorer , it will auto trigger the find mode in explorer

### ISSUE THREAD

**Issue by markshao** [VSCodeVim/Vim#3560] opened 2019-03-06 02:35 UTC
**Describe the bug**
could not use the vim hot key in explorer , it will auto trigger the find mode in explorer

**To Reproduce**
1. switch to the explorer 
2. try tu use j, k to move inside , but it becames search for 'jk' , there will be a small red popup  on the right top of the explorer

**Expected behavior**
disable the find , let me move using vim key like j ,k 

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.31.1
- OS: MacOS mojave 10.14.3

**Additional context**

**Comment by markshao** [comment] 2019-03-06 09:06
it doesn't happen when first launch the app , but it happens after several minutes

**Comment by zhengbli** [comment] 2019-03-07 03:03
Change the setting to simple works for me
![screenshot_20190306_220253](https://user-images.githubusercontent.com/1171301/53929413-aec72880-405b-11e9-80ca-e636f32d56d5.png)

**Comment by jpoon** [comment] 2019-03-07 04:38
Dupe of https://github.com/VSCodeVim/Vim/issues/3560

**Closed by jpoon** 2019-03-07 04:38 UTC

**Comment by Praful** [comment] 2019-03-07 14:48
@zhengbli when you said changing keyboard navigation to *simple* works for you, can you still press / and search for files? I can't do that. I can only press a letter and the next file beginning with that character will be selected. I can't type two characters, for instance. 

*If* that's the same for you, then this is not a solution but simply switching off the newly added progressive search feature!

**Comment by ferdicus** [comment] 2019-04-25 12:42
@jpoon, did you just say this issue is a dupe of itself?! 😄
