### ISSUE TITLE
command `] `[ doesn't work

### ISSUE THREAD

**Issue by HeWenJin** [VSCodeVim/Vim#5018] opened 2020-07-14 02:57 UTC
**Describe the bug**
as the title

**To Reproduce**
1.  switch to VISUAL MODE
2.  select some text
3.  and `] `[ command doesn't work

**Expected behavior**
These commands is useful after I selected some text in  VISUAL MODE, so hope to support these commands in future

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.15.0
- VSCode version: 1.47.0
- OS: win10 2004

**Additional context**
using VSCode in Remote-WSL extension, and WSL version is 2

**Comment by sql-koala** [comment] 2020-07-23 12:47
Hi,
what operation did you do that would set the marks? Changing text or a yank? (yank does not work for now). Other cases should work and the action `[ is supported in visual mode.

**Comment by HeWenJin** [comment] 2020-07-23 13:12
> Hi,
> what operation did you do that would set the marks? Changing text or a yank? (yank does not work for now). Other cases should work and the action `[ is supported in visual mode.

thx for reply,
It is after a yank, and this is the most common situation that I'm use `[ `] command

**Comment by J-Fields** [comment] 2021-07-23 23:07
Duplicate of #4734

**Closed by J-Fields** 2021-07-23 23:07 UTC
