### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by calvarado04q6cyber** [VSCodeVim/Vim#5429] opened 2020-10-16 02:32 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (/snap/code/48/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:648:52)
	at t.ExtHostTextEditor.edit (/snap/code/48/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:647:598)
	at F.executeCommand (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482834)
	at F.runAction (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475478)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/carlos/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 19:18
Duplicate of #5224. If you can reproduce, please post steps there.

**Closed by J-Fields** 2020-10-26 19:18 UTC
