### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by phamlehuy53** [VSCodeVim/Vim#5608] opened 2020-11-09 02:07 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
    at n.exec (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409709)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at n.execCount (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37395)
    at n.execCount (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:411708)
    at F.runAction (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
    at F.handleKeyAsAnAction (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/huy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:11
Duplicate of #5460

**Closed by J-Fields** 2020-11-12 23:11 UTC
