### ISSUE TITLE
Failed to handle key=f. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by xJUVIIx** [VSCodeVim/Vim#6590] opened 2021-05-05 14:29 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=f. Overlapping ranges are not allowed!
    at T._applyEdit (/Users/Juvii/Desktop/Desktop - Ethan’s MacBook Pro/Techy Stuff/Programs/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53072)
    at Object.edit (/Users/Juvii/Desktop/Desktop - Ethan’s MacBook Pro/Techy Stuff/Programs/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50744)
    at Object.executeTransformations (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/src/transformations/execute.ts:124:29)
    at j.runAction (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/src/mode/modeHandler.ts:471:11)
    at Object.promise (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/extensionBase.ts:373:73)
    at Object.runTasks (/Users/Juvii/.vscode/extensions/vscodevim.vim-1.20.1/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
