### ISSUE TITLE
Failed to handle key=j. getLineLength() called with out-of-bounds line 11

### ISSUE THREAD

**Issue by zhudepei** [VSCodeVim/Vim#5265] opened 2020-09-27 08:44 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. getLineLength() called with out-of-bounds line 11
	at Function.getLineLength (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getDownWithDesiredColumn (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11451)
	at I.execAction (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:190462)
	at I.createMovementResult (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at I.execActionWithCount (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/zhudepei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 16:17
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 16:17 UTC
Labels: kind/bug, status/duplicate
