### ISSUE TITLE
Holding down ESC causes the cursor to move left.

### ISSUE THREAD

**Issue by mreishus** [VSCodeVim/Vim#853] opened 2016-10-06 20:36 UTC
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I was in command mode, I held down ESC.  Keyboard repeat made my computer press ESC several times in a row.  For each escape press, my cursor went left one character.  I'm inside a "JavaScript  React" filetype with Spaces: 4 identation.

### What did you expect to happen?

I expected nothing to happen; or for my cursor to stay put.

### What happened instead?

Each escape press caused my cursor to move left one character.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.0
* OS: Win 7

**Comment by xconverge** [comment] 2016-10-06 21:03
Dupe of #825, should be fixed on master

**Closed** 2016-10-06 21:04 UTC
