### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by access2content** [VSCodeVim/Vim#6199] opened 2021-02-24 19:06 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.18.9<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:548679)    at https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:546656    at Object.next (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:546761)    at https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:545674    at new Promise (<anonymous>)    at r (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:545411)    at e.$executeCommand (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:160:548552)    at e.doInvokeHandler (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:19:773577)    at e.invokeHandler (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:19:773310)    at e.receiveRequest (https://amber-viper-qyxwpr2f.ws-us03.gitpod.io/bundle.js:19:772602)```</details>

**Comment by J-Fields** [comment] 2021-02-24 19:37
What version of VSCode are you running?

**Comment by J-Fields** [comment] 2021-03-24 17:52
Duplicate of #5526

**Closed by J-Fields** 2021-03-24 17:52 UTC
