### ISSUE TITLE
Wrong lines indented if selected from bottom and reindented with the "." command

### ISSUE THREAD

**Issue by BlueInt32** [VSCodeVim/Vim#2425] opened 2018-03-06 05:16 UTC
BUG REPORT

**What happened**:
In VISUAL or VISUAL LINE modes, when indenting code more than once (using the "." command) after selecting from bottom to up, the indentation is performed on wrong lines.
See the [gifv](https://i.imgur.com/cQiwPcR.gifv)

**What did you expect to happen**:
I expected the second indentation to perform on my actual selection

**How to reproduce it (as minimally and precisely as possible)**:
- Go in VISUAL LINE mode
- Select 2 or more (let's say N) lines via hitting "k" (i.e. selecting lines above the line I was on)
- Hit ">" once, the selected code is indented normally (and unselected)
- Hit "." to reproduce, the lines indented are not the ones expected, they are actually the N lines above the last line I selected

**Environment**:
- Extension Name: vim
- Extension Version: 0.11.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.20.1

**Comment by Chillee** [comment] 2018-03-07 16:44
Duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/549

**Closed** 2018-03-07 16:45 UTC
