### ISSUE TITLE
Failed to handle key=i. Cannot read property 'searchString' of undefined

### ISSUE THREAD

**Issue by KanG98** [VSCodeVim/Vim#5620] opened 2020-11-11 00:16 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=i. Cannot read property 'searchString' of undefined
	at k.exec (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:436870)
	at k.execCount (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
	at F.runAction (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
	at F.handleKeyAsAnAction (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/kylexue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 22:58
Duplicate of #5351

**Closed by J-Fields** 2020-11-12 22:58 UTC
