### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by xiaoyongaz** [VSCodeVim/Vim#5223] opened 2020-09-23 16:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:409622)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:37418)
	at async n.execCount (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:411621)
	at async F.runAction (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475314)
	at async F.handleKeyAsAnAction (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474707)
	at async F.handleKeyEvent (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471516)
	at async Object.promise (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
	at async Object.runTasks (c:\Users\xiaoyozh\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-23 18:00
What were you trying to do when this happened?

**Comment by J-Fields** [comment] 2020-09-29 05:23
Duplicate of #5239

**Closed by J-Fields** 2020-09-29 05:23 UTC
Labels: kind/bug, status/duplicate
