### ISSUE TITLE
Mark file as clean after going back to the point where the file is saved

### ISSUE THREAD

**Issue by DimmyJing** [VSCodeVim/Vim#4950] opened 2020-06-17 03:14 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I use `u` to go back to where the file originally was, the file is still marked as dirty as opposed to using ctrl-z.

**Describe the solution you'd like**
To mark the file as clean after the history is at the point where it originally was when it was last saved.

**Describe alternatives you've considered**
To mark the file as clean when there is no more history in the history tracker.

**Additional context**
This would most likely involve the `historyTracker.ts` file in `history`

**Comment by J-Fields** [comment] 2020-06-17 15:48
Duplicate of #3201

**Closed by J-Fields** 2020-06-17 15:48 UTC
Labels: upstream/vscode
