### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by MorningLit** [VSCodeVim/Vim#6865] opened 2021-07-12 10:20 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at i._applyEdit (c:\Users\ambro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\ambro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\ambro\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\ambro\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\ambro\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\ambro\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\ambro\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[114, 21] | [114, 20]]"
]
actionsRunPressedKeys: [
  ".",
  "e",
  "<left>",
  "<right>",
  "<left>",
  "<right>",
  "<left>",
  "<right>",
  ".",
  "<Esc>"
]
actionsRun: [
  "D",
  "q",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 114,
      "character": 20
    },
    "text": "be.visible",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 114,
        "character": 16
      },
      {
        "line": 114,
        "character": 30
      }
    ],
    "text": "not.be.visible",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:44
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:44 UTC
