### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by Techbittu** [VSCodeVim/Vim#6313] opened 2021-03-20 14:25 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at filter (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:28)
    at a.operator (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:215:28)
    at a.isOperatorPending (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:287:12)
    at m.currentModeIncludingPseudoModes (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/state/vimState.ts:252:31)
    at I.handleKeyEvent (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/mode/modeHandler.ts:424:39)
    at Object.promise (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/extensionBase.ts:380:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.runTasks (/home/deepak/.vscode/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-03-20 20:29
Duplicate of #6309

**Closed by J-Fields** 2021-03-20 20:29 UTC
