### ISSUE TITLE
Ctrl-W-h/l randomly switches cursors location

### ISSUE THREAD

**Issue by asvetliakov** [VSCodeVim/Vim#1051] opened 2016-11-10 12:02 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Open same file in the left and right editor groups
Repeat ```Ctrl-w l , Ctrl-w h``` few times

### What did you expect to happen?
It keeps position unchanged

### What happened instead?
Cursor starts randomly jumping between random locations in the file

On other side, Ctrl-1/Ctrl-2 works as expected

[GIF](http://g.recordit.co/BHfTzqLqDt.gif)

Also, same issue with ```zz``` after switching - it centers editor at incorrect location

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: *0.4.1*
* OS: Windows 10

**Comment by jpoon** [comment] 2016-11-14 07:10
Thanks for pointing this out. That is a hella annoying bug.

**Comment by rebornix** [comment] 2016-11-17 21:27
oh no, it comes out again. Let me grab cola and see what's happening here.

**Comment by rebornix** [comment] 2016-11-17 21:29
Unluckily I can't reproduce this on my machine with the latest one 0.4.2. @asvetliakov do you mind giving our latest version a try?

**Comment by asvetliakov** [comment] 2016-11-17 21:31
Yes, 0.4.2 fixed it. Thanks!

**Comment by rebornix** [comment] 2016-11-17 21:55
@asvetliakov thanks for your help

**Comment by xconverge** [comment] 2016-11-20 04:21
I still see it with 0.4.2

**Comment by asvetliakov** [comment] 2016-12-03 21:36
Unfortunately, it happens again with 0.4.4. The things are more worse - often after switching editors it hangs until ```Esc``` or ```Ctrl-C``` pressed.

The cursor position seems fine, but when you press ```j``` or ```k``` it jumps to other location

**Comment by rebornix** [comment] 2016-12-06 05:08
We @johnfn @xconverge sat together and tried our latest bits 0.4.9 on Insider but we could not reproduce any more. Close it right now.

If anyone can reproduce this issue, please provide valid reproduce steps and I'll stop whatever I will be doing at that moment and dig into it and get a thorough understanding of what happens in both Vim and Code side.

**Comment by asvetliakov** [comment] 2016-12-07 19:59
Can't reproduce anymore with 0.4.9, thanks!

**Comment by Chillee** [comment] 2017-05-06 20:46
This should be closed now.

**Closed** 2017-05-06 20:50 UTC
Labels: kind/bug, status/needs-more-info
