### ISSUE TITLE
:vsp should support path suggestion when I press the tab button

### ISSUE THREAD

**Issue by duteng** [VSCodeVim/Vim#1799] opened 2017-06-02 10:41 UTC
#### vsp should support path suggestion
![image](https://cloud.githubusercontent.com/assets/1821507/26719032/8e4f652c-47b5-11e7-8a39-2b62d2702037.png)

#### Here is what Vim do
![vscode](https://cloud.githubusercontent.com/assets/1821507/26722565/20d15fce-47c3-11e7-9a71-04f0825f23bd.gif)

**Comment by Chillee** [comment] 2017-06-02 14:16
This is a limitation of the VSCode API/ a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/745

I'm going to close this issue, as it's a subset of the issue linked. Thanks for the feedback though! We'll be sure to implement this feature as soon as possible.

**Closed by Chillee** 2017-06-02 14:16 UTC
