### ISSUE TITLE
Problem of <nop>

### ISSUE THREAD

**Issue by Elendeer** [VSCodeVim/Vim#5150] opened 2020-08-26 09:36 UTC
**Describe the bug**
When I map character 's' to <nop>, I want to use 's' to make up other shortcuts. However, after mapping, pressing the ’s‘ key no longer reacts, nor can I connect other keys to form a shortcut key.

**To Reproduce**

1. Write the folowing in settings.json:

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["s"],
      "after": ["<nop>"]
    },
    {
      "before": ["s", "l"],
      "after": [":", "v", "s", "p", "l", "i", "t", "\n"]
    },
]
```

2. press "sl", and nothing happen.

**Expected behavior**

Keys mapped to <nop> can also be used at the beginning of other shortcut key.

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: version 1.48
- OS: windows 10

**Comment by sql-koala** [comment] 2020-08-26 10:51
Hi,
the second mapping will be supported with the next release. You could also do it  like so:
```
        {
            "before": ["s", "l"],
            "commands": ["workbench.action.splitEditor"]
        },
```
Mapping to "nop" is not supported because afaik there is no null op in vscvim.

**Comment by J-Fields** [comment] 2020-12-09 20:48
Closing as duplicate of #3477

**Closed by J-Fields** 2020-12-09 20:48 UTC
Labels: status/duplicate
