### ISSUE TITLE
easymotion default key-mapping dose not work

### ISSUE THREAD

**Issue by CCIBB** [VSCodeVim/Vim#6823] opened 2021-07-03 16:52 UTC
**Describe the bug**
easymotion default key-mapping dose not work in version 1.21.4

**To Reproduce**

1.  space as leader key
2.  Click space-space-s for search a character in current document.
3.  Tips for this motion ''Search for 1 character(s):"  disappeared in the status bar.
4.  easymotion back to normal mode and do nothing.
5.  rollback version to 1.21.3.
6.  everything works fine.

- Extension (VsCodeVim) version: 1.21.4
- VSCode version: 1.57
- OS: macOS moJave 10.14.6

**Additional context**
user defined key-mapping  works fine but default key-mapping dose not

**Comment by liushuiyuan001** [comment] 2021-07-04 08:11
Me too
- Extension (VsCodeVim) version: 1.21.4
- VSCode version: 1.57
- OS: macOS Catalina 10.15.7

**Comment by enricofadly** [comment] 2021-07-04 11:49
i think this bug start kicked in yesterday, before that it was normal

**Comment by CCIBB** [comment] 2021-07-04 15:07
you're right,dear enricofadly! i'm quite sure that easymotion updated some days before yesterday,but bug only start kicked yesterday[2021-07-03]. @enricofadly

**Comment by suan** [comment] 2021-07-06 17:28
Encountering this as well – my leader is the comma key. Downgrading vscode-vim to 1.21.3 makes the issue go away for me.

**Comment by J-Fields** [comment] 2021-07-06 17:31
Duplicate of #6828

**Closed by J-Fields** 2021-07-06 17:31 UTC

**Comment by J-Fields** [comment] 2021-07-06 17:44
Sorry for the regression! This is fixed on 1.21.5, which is now available - please upgrade.
