### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by FelipeQuirce** [VSCodeVim/Vim#5557] opened 2020-11-02 08:37 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
	at Object.promise (/Users/quircef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:236829)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/quircef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-07 01:12
Duplicate of #5306. What were you trying to do when this happened?

**Closed by J-Fields** 2020-12-07 01:12 UTC

**Comment by berknam** [comment] 2020-12-07 16:08
@FelipeQuirce Where you trying to run the "Vim: Remap..." command from command palette when this happened?
