### ISSUE TITLE
Using single 'q' character for <ESC> binding in Insert mode removes the last typed character

### ISSUE THREAD

**Issue by alexeygrant** [VSCodeVim/Vim#1076] opened 2016-11-22 04:37 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
In vim/VsVim I bind 'q' to \<ESC\> in the insert mode. Therefore I've configured this binding:
       "vim.insertModeKeyBindingsNonRecursive": [
           {
               "before": ["q"],
               "after": ["<Esc>"]
           }
     ]
Put the exact keys you pressed.
Type anything in Insert mode, then press 'q'
### What did you expect to happen?
Pressing 'q' would exit Insert mode.
### What happened instead?
Pressing 'q' removes the last typed character and then exits Insert mode (exactly as if press ESC).
### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.3
* OS: Windows 10 x64

**Comment by xconverge** [comment] 2016-11-22 06:18
@alexeygrant Thanks for reporting this!

A temporary workaround until we fix this:

If you have any other mappings that use 2 keys, if you remove them, this one will work fine.

For example, I can reproduce this if I have jj mapped to <esc> AND q mapped to <esc>, jj then works correctly but q removes the extra char. If I have ONLY q mapped to <esc> it works correctly.

This has to do with _longestKeySequence() being checked in remapper.ts

**Comment by xconverge** [comment] 2016-11-22 06:29
I had to type "sequence" to fix this. I kept messing it all up because I would type se _q_ (exit insert) _u_ (undo my change) and it took me 3 times of that to realize that I had added this q to esc binding to debug this issue 😆

**Comment by alexeygrant** [comment] 2016-11-22 07:05
Yes, indeed I had another binding - "zz" to "q"  in the insert mode :). Thanks for the workaround, I'll survive for some time 
Any timeframes when it will be fixed?

**Comment by xconverge** [comment] 2016-11-22 15:21
I have a pull request out so it should be in the next release!

**Closed** 2016-11-22 17:49 UTC

**Comment by alexeygrant** [comment] 2017-02-25 12:05
Hmm, I didn't realise the fix was there for some time already :). It now works fine with a single character mapping to to ESC. Thanks a lot.

**Comment by xconverge** [comment] 2017-02-25 16:56
No problem!
