### ISSUE TITLE
getLineLength() called with out-of-bounds line 42

### ISSUE THREAD

**Issue by Jane-Tran** [VSCodeVim/Vim#5243] opened 2020-09-25 04:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 42
    at Function.getLineLength (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:22186)
    at l.getRight (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:10461)
    at F.updateView (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:491420)
    at _ (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:234397)
    at Object.runTasks (c:\Users\tvq_huy\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-25 20:25
Duplicate of #5180

**Closed by J-Fields** 2020-09-25 20:25 UTC
