### ISSUE TITLE
Enable `:set number` or `:se nu!`

### ISSUE THREAD

**Issue by keidarcy** [VSCodeVim/Vim#4732] opened 2020-04-12 07:59 UTC
**Is your feature request related to a problem? Please describe.**
Lack of a quick way to toggle line number like `:se nu` and `:se nonu`.

**Describe the solution you'd like**
Just like what we do in vim

**Additional context**
Toggle with `"editor.lineNumbers": "off"` and `"editor.lineNumbers": "on"` in `settings.json`.

**Comment by J-Fields** [comment] 2020-04-13 15:37
`:se number` and `:se nonumber` work, but I can see wanting the shorthand.

**Comment by xyyolab** [comment] 2020-04-14 02:12
Oh, thanks! That's helpful!
Do you want to add this description to `ROADMAP` or `README`? I can't find it anywhere. If I miss something, sorry about that.
Btw, if you work on this, add `se rnu!` for relative number, please!

**Comment by J-Fields** [comment] 2020-12-09 21:00
Duplicate of #5368, will be fixed in next release

**Closed by J-Fields** 2020-12-09 21:00 UTC
Labels: area/commandline, kind/enhancement
