### ISSUE TITLE
Failed to handle key=<Esc>. Promise.allSettled is not a function

### ISSUE THREAD

**Issue by ghosh-sudeep** [VSCodeVim/Vim#6657] opened 2021-05-24 04:13 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Promise.allSettled is not a function
    at Object.runTasks (c:\Users\sugho\.vscode\extensions\vscodevim.vim-1.20.3\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-05-26 18:19
Duplicate of #6489

**Closed by J-Fields** 2021-05-26 18:19 UTC
