### ISSUE TITLE
Failed to handle key=4. TextEditor(vs.editor.ICodeEditor:3,$model5) has been disposed

### ISSUE THREAD

**Issue by Jeanking23** [VSCodeVim/Vim#5995] opened 2021-01-15 00:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
DISPOSED: TextEditor(vs.editor.ICodeEditor:3,$model5) has been disposed
    at Object.t.disposed (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:51:9)
    at e.$tryApplyEdits (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6594:757)
    at p._doInvokeHandler (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4517:275)
    at p._invokeHandler (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4516:971)
    at p._receiveRequest (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4515:639)
    at p._receiveOneMessage (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4514:468)
    at file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4512:565
    at c.fire (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at fire (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:448:356)
    at t.PersistentProtocol._receiveMessage (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:453:525)
    at file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:450:519
    at c.fire (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at g.acceptChunk (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:445:789)
    at file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:445:141
    at Socket.t (file:///Users/admin/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:455:389)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

</details>

**Comment by J-Fields** [comment] 2021-02-19 01:49
Duplicate of #5650

**Closed by J-Fields** 2021-02-19 01:49 UTC

**Comment by Jeanking23** [comment] 2021-02-24 12:42
Please can you work me through on how to do that.  thanks you

**Comment by Jeanking23** [comment] 2021-02-24 12:55
Am clueless on to resolve the problem
