### ISSUE TITLE
getLineLength() called with out-of-bounds line 120

### ISSUE THREAD

**Issue by allan-cmsc** [VSCodeVim/Vim#5466] opened 2020-10-21 18:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 120
    at Function.getLineLength (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getUpWithDesiredColumn (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
    at l.getLeftThroughLineBreaks (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
    at Object.t.statusBarCommandText (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:31413)
    at Object.updateShowCmd (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40543)
    at F.handleKeyEvent (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:472169)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/alou/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 18:58
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 18:58 UTC
