### ISSUE TITLE
Cannot read property 'visibleRanges' of undefined

### ISSUE THREAD

**Issue by binhnguyenduc** [VSCodeVim/Vim#5298] opened 2020-09-30 02:49 UTC
**To Reproduce**

Update VSCode to 1.49.2

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'visibleRanges' of undefined
	at F.updateView (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:489831)
	at _ (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235688)
	at async Object.runTasks (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 22:00
Duplicate of #5256; if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 22:00 UTC
