### ISSUE TITLE
Illegal value for `line`

### ISSUE THREAD

**Issue by steevy72** [VSCodeVim/Vim#6237] opened 2021-03-05 20:17 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Illegal value for `line`
	at v._lineAt (/Users/steevenjeansimon/Desktop/IT/Visual Studio Code copy.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:1166)
	at Object.lineAt (/Users/steevenjeansimon/Desktop/IT/Visual Studio Code copy.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:95)
	at Function.getCharAt (/Users/steevenjeansimon/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:756624)
	at F.updateView (/Users/steevenjeansimon/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:720435)
	at M (/Users/steevenjeansimon/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:344960)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (/Users/steevenjeansimon/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:349203)
	at async Object.runTasks (/Users/steevenjeansimon/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:01
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:01 UTC
