### ISSUE TITLE
"Delete surrounding quotes" doesn't work in certain cases

### ISSUE THREAD

**Issue by jiripospisil** [VSCodeVim/Vim#3415] opened 2019-01-26 18:42 UTC
**Describe the bug**

Delete surrounding quotes (`ds"`) doesn't work in certain cases.

**To Reproduce**

Enter the following to a buffer, place your cursor on `f` and press `ds"`.

```
""foo""
```

**Expected behavior**

It should remove the inner quotes. The end result should be `"foo"`. Instead, nothing happens. Similarly, `""foo"` should become `"foo`. Interestingly it works with other surrounding characters e.g. `((foo))` correctly becomes `(foo)`. 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.3
- VSCode version: 1.30.2 
- OS: macOS

**Comment by esetnik** [comment] 2019-01-31 06:11
I traced this issue to how QuoteMatcher works. It doesn't handle nested quotes properly.

The offending line is at https://github.com/VSCodeVim/Vim/blob/master/src/actions/motion.ts#L1689
```js
    const quoteMatcher = new QuoteMatcher(this.charToMatch, text);
    const start = quoteMatcher.findOpening(position.character);
    const end = quoteMatcher.findClosing(start + 1);

    if (start === -1 || end === -1 || end === start || end < position.character) {
      return {
        start: position,
        stop: position,
        failed: true,
      };
    }
```

The problem is `quoteMatcher.findOpening(position.character)` only matches on `QuoteMatch.Opening` type quotes from the quoteMap, but the quoteMap is generated from the start of the corpus not the current cursor position so it doesn't correctly map nested quotes. Instead it'd mark the nested quotes as two start and end pairs like 1,2,,,12. So what happens is that `quoteMatcher.findOpening(position.character)` returns position 0 instead of position 1 and then `quoteMatcher.findClosing(start + 1)` returns position 1. This makes end < position.character and the replacement fails to occur.

It works with parens characters because they do not use the QuoteMatcher they use the PairMatcher. Maybe we can use PairMatcher for everything? I'm not really sure why QuoteMatcher needs to exist but I'm sure @jpoon can provide more details.

I tried to fix this in a number of ways but it is breaking other test cases. It seems the proper solution would be to implement quoteMap so that it starts at the current search position and walks incrementally in both directions finding Opening and Closing quotes relative to the cursor and not to the start of the corpus. This would also fix a number of other failing scenarios.

**Closed** 2019-01-31 07:44 UTC
