### ISSUE TITLE
vim.insertModeKeyBinding not working for  Combinatorial key (Ctrl-?)

### ISSUE THREAD

**Issue by WangRongda** [VSCodeVim/Vim#2843] opened 2018-07-16 09:23 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'user-settings'
2. config 
```
  "vim.insertModeKeyBindingsNonRecursive": [
    {
      "before": ["<C-j>"],
      "after": ["m", "m"]
    }
  ],
```
3. press <C-j> but nothing happend

**Expected behavior**
input characters:  "mm"

**Screenshots**

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.15.0
 - VSCode version:1.25.1
 - OS: 4.17.5-1-ARCH

**Additional context**
1. Last version is ok.
2. Other key(not Ctrl) is ok.

**Comment by expelledboy** [comment] 2018-07-16 09:36
Have you read through the [readme section](https://github.com/VSCodeVim/Vim#vimusectrlkeys) regarding ctrl keys?

**Comment by WangRongda** [comment] 2018-07-16 10:15
@expelledboy 
Of course! 
This is my setting: 
"vim.useCtrlKeys": true
"vim.handleKeys": {
     "<C-j>": false
}
Any Problem?

**Comment by expelledboy** [comment] 2018-07-16 15:07
I am new the project, was just in the back of my mind when I read your issue :)

**Comment by xconverge** [comment] 2018-07-16 17:15
We don't remap this ctrl+ combination <C-j> most likely. Can you use native vscode bindings to do what you want to do? Something like this 

 {
    "key": "ctrl+j",
    "command": "xxxxxxx",
    "when": "editorTextFocus && vim.active && vim.mode == 'Insert' && !inDebugRepl"
  }

**Comment by xconverge** [comment] 2018-07-16 17:15
Duplicate of #757

**Closed by xconverge** 2018-07-16 17:15 UTC

**Comment by WangRongda** [comment] 2018-07-17 01:37
@xconverge  What about I just want to remap to some keypress, which a vscode command can't do it.

**Comment by xconverge** [comment] 2018-07-17 01:54
```
{
  "key": "ctrl+j",
  "command": "type",
  "args": { "text": "mm" },
  "when": "editorTextFocus"
}
```

**Comment by WangRongda** [comment] 2018-07-17 02:10
Wow, perfect! Although it is not remap key, this is enough and satisfy my needs.Power command and I am ignorant.
