### ISSUE TITLE
Error trying to paste multi-cursor yanked content

### ISSUE THREAD

**Issue by yagudaev** [VSCodeVim/Vim#5408] opened 2020-10-14 02:26 UTC
**To Reproduce**

1. Open a file in the editor in visual mode.
2. Select text with `CMD+d` or `opt+mouse click`
3. Press `y` to yank selection
4. Press `p` to paste the selection

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async n.execCount (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:411708)
	at async F.runAction (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/mike/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:15
Duplicate of #5239

**Closed by J-Fields** 2020-11-12 23:15 UTC
