### ISSUE TITLE
Latest version breaks VSCode settings on start

### ISSUE THREAD

**Issue by Ten0** [VSCodeVim/Vim#6723] opened 2021-06-10 16:12 UTC
**Describe the bug**
With version 1.21, everytime the plugin loads, it sets the following settings into my vscode:
```json
{
	"editor.tabSize": 8,
	"editor.cursorStyle": "line",
	"editor.lineNumbers": "on",
	"editor.wordSeparators": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-",
	"editor.wordWrap": "off"
}
```

Downgrading fixes the issue.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.0
- VSCode version: 1.56.0 - Microsoft packed version
- OS: Linux

**Comment by J-Fields** [comment] 2021-06-10 16:59
Duplicate of #6717

**Closed by J-Fields** 2021-06-10 16:59 UTC
Labels: status/duplicate
