### ISSUE TITLE
getLineLength() called with out-of-bounds line 0

### ISSUE THREAD

**Issue by Tech-Helper503** [VSCodeVim/Vim#5315] opened 2020-10-01 15:54 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 0
    at Function.getLineLength (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22163)
    at l.getRight (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10438)
    at F.updateView (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:491507)
    at _ (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:234397)
    at Object.runTasks (c:\Users\AIDEN ISRAEL\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 05:47
Duplicate of #5180

**Closed by J-Fields** 2020-10-06 05:47 UTC
Labels: kind/bug, status/duplicate
