### ISSUE TITLE
Failed to handle key=<C-d>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by zorigtbaatarQ** [VSCodeVim/Vim#6176] opened 2021-02-20 08:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-d>. Illegal argument: character must be non-negative
	at Object.S [as illegalArgument] (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new d (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:80:20609)
	at new d (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:80:19977)
	at j.with (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:80:22251)
	at L.exec (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:467070)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async L.execCount (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:355705)
	at async F.runAction (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707788)
	at async F.handleKeyAsAnAction (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707179)
	at async F.handleKeyEvent (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704015)
	at async Object.promise (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:346362)
	at async Object.runTasks (c:\Users\User\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
