### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Ericgacoki** [VSCodeVim/Vim#5824] opened 2020-12-04 21:15 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (/snap/code-insiders/582/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:320)
	at t.ExtHostTextEditor.edit (/snap/code-insiders/582/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:676)
	at F.executeCommand (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:482834)
	at F.runAction (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:475478)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:471603)
	at async Object.promise (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:231560)
	at async Object.runTasks (/home/eric/.vscode-insiders/extensions/vscodevim.vim-1.17.2/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:24
Duplicate of #5224

**Closed by J-Fields** 2020-12-05 18:24 UTC
Labels: status/duplicate
