### ISSUE TITLE
In large file(more than 10M) all keys do nothing and I switch back to small file, everything work fine

### ISSUE THREAD

**Issue by xnsua** [VSCodeVim/Vim#1834] opened 2017-06-13 09:25 UTC

**Comment by simahao** [comment] 2017-06-13 09:27
+1

**Comment by Chillee** [comment] 2017-06-13 18:08
It's a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/1461

As a workaround, do the action `toggle vim` when you're working on large files. It'll disable vim, but let you work with the file normally.

**Closed by Chillee** 2017-06-13 18:08 UTC
