### ISSUE TITLE
Conserve cursor X position when moving cursor up and down

### ISSUE THREAD

**Issue by freiguy1** [VSCodeVim/Vim#4764] opened 2020-04-22 17:10 UTC
For example, I'm editing this text
```
A sort of long line^
Short
A really really really really really long line
```
Imagine the ^ is my cursor position. When I press `j` to navigate down one line, the cursor correctly goes to the `Short` line and is at the end of the text for that line. When I hit `j` again, The cursor drops _straight below_ where it currently is. This behavior is incorrect. It should conserve the initial X position in the first line, so when navigating to the bottom line it should appear somewhere in the middle (of course I could figure out where exactly if I were to count characters, but I don't think that's necessary).

Could this be some configuration I have setup incorrectly?
Thanks!

**Comment by J-Fields** [comment] 2020-04-23 01:48
I assume you have `j` mapped to `gj`?

**Comment by freiguy1** [comment] 2020-04-23 02:26
Yessir.

**Comment by J-Fields** [comment] 2020-04-23 15:09
Duplicate of #4441

**Closed by J-Fields** 2020-04-23 15:09 UTC
Labels: kind/bug
