### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by mohammad22** [VSCodeVim/Vim#5662] opened 2020-11-16 18:30 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
	at F.updateView (/Users/moemoghaddam/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:488501)
	at F.handleKeyAsAnAction (/Users/moemoghaddam/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474893)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyEvent (/Users/moemoghaddam/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/moemoghaddam/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/moemoghaddam/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 16:41
Closing as duplicate of #6343, which has a better stack trace

**Closed by J-Fields** 2021-03-24 16:41 UTC
