### ISSUE TITLE
Failed to handle key=<Esc>. getLineLength() called with out-of-bounds line 3

### ISSUE THREAD

**Issue by Stzx** [VSCodeVim/Vim#5643] opened 2020-11-13 03:33 UTC
**To Reproduce**

1.  Create a new file with the following content (Note: the blank line at the end.)
```
Contribution Guide
This document offers a set of guidelines for contributing to VSCodeVim. These are just guidelines, not rules; use your best judgment and feel free to propose changes to this document. If you need help, drop by on Slack.

Thanks for helping us in making VSCodeVim better! 

```
2.  Copy the following to the clipboard
```
Contribution Guide
```
3.  Use the `ggvG` command to select all content.
4.  Press `Shift + Insert` to insert the content or right-click to `Paste`.
5.  After the content is replaced, press `Esc`. an error will be triggered!

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. getLineLength() called with out-of-bounds line 3
	at Function.getLineLength (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22225)
	at l.getUpWithDesiredColumn (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:11622)
	at l.getLeftThroughLineBreaks (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:10872)
	at c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475270
	at Array.map (<anonymous>)
	at F.runAction (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475217)
	at F.handleKeyAsAnAction (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
	at F.handleKeyEvent (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\<user>\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

BTW, I browsed the source code. Found that after using paste or shortcut to modify the content. `VimState` is still in the old state, not updated!

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
