### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by oyd11** [VSCodeVim/Vim#6866] opened 2021-07-12 14:32 UTC
**To Reproduce**
happens sometimes when pressing "." - repeat-last-command, couldn't figure out when exactly.

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at i._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/home/kobi/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/home/kobi/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/kobi/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/home/kobi/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /home/kobi/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[97, 47] | [97, 46]]"
]
actionsRunPressedKeys: [
  "r",
  "<Esc>"
]
actionsRun: [
  "D",
  "Ve",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 97,
      "character": 47
    },
    "text": "re",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 97,
        "character": 40
      },
      {
        "line": 97,
        "character": 49
      }
    ],
    "text": "num_of_repetition_detectors101G",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:44
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:44 UTC
Labels: status/duplicate
