### ISSUE TITLE
getLineLength() called with out-of-bounds line 10

### ISSUE THREAD

**Issue by barangilani** [VSCodeVim/Vim#5236] opened 2020-09-24 11:55 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 10
	at Function.getLineLength (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:22186)
	at l.getRight (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:10461)
	at F.updateView (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:491420)
	at _ (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:234397)
	at async Object.runTasks (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by danawoodman** [comment] 2020-09-24 17:58
Dupe of #5180

**Closed** 2020-09-25 19:59 UTC
Labels: kind/bug, status/duplicate
