### ISSUE TITLE
getLineLength() called with out-of-bounds line 40

### ISSUE THREAD

**Issue by jorda0mega** [VSCodeVim/Vim#5377] opened 2020-10-11 03:37 UTC
**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 40
    at Function.getLineLength (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getRight (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
    at F.updateView (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
    at _ (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
    at Object.runTasks (/Users/jorgef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-13 19:29
Duplicate of #5180, please post repro steps there.

**Closed by J-Fields** 2020-10-13 19:29 UTC
Labels: status/duplicate
