### ISSUE TITLE
Back to start of line (0), dd and p (delete and paste), ctrl-j, :w (to save), and many other commands not working.

### ISSUE THREAD

**Issue by tineich** [VSCodeVim/Vim#3147] opened 2018-10-18 17:05 UTC
**Describe the bug**
I have found the following command mode commands not working anymore (since release v1.28 of VSCode (18 Oct 18)):
 Back to start of line (0), dd and p (delete and paste), ctrl-j (join lines), :w (to save), / (searching).

**To Reproduce**
1. Open any file in VSCode.
2. Attempt the following commands:
 Back to start of line (0), dd and p (delete and paste), ctrl-j (join lines), :w (to save), / (searching).

**Expected behavior**
 Back to start of line (0), dd and p (delete and paste), ctrl-j (join lines), :w (to save), / (searching) to work as designed/expected.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.10
- VSCode version: 1.28
- OS: Windows 10

**Additional context**
I did a uninstall and reinstall (2x) VSCodeVim version 0.16.10. However, issues still persists.

**Comment by rheiland** [comment] 2018-10-18 19:06
Same here.

- Extension (VsCodeVim) version: 0.16.10
- VSCode Version 1.28.1 (1.28.1)
- OS: OSX 10.12.6

**Comment by xconverge** [comment] 2018-10-19 01:15
Pushed a release, this should be fixed and was likely a duplicate of #3143

**Closed by xconverge** 2018-10-19 01:15 UTC
