### ISSUE TITLE
Surround: cs<x><y> broken

### ISSUE THREAD

**Issue by mitchlloyd** [VSCodeVim/Vim#1676] opened 2017-05-08 17:46 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

Bug: "change surrounding" no longer works after upgrade to 0.7.0

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: Mac OS Sierra 10.12.4

Given this text in an editor:

```
"hi"
```

Typing `cs"'` should change the surrounding double quotes to single quotes. However the command appears to not finish showing `-- SURROUND INPUT MODE --"'` in the status bar.

This also seem to fail when changing surrounding `[` or `(` characters. Interestingly it seems possible to continually enter more surrounding characters.

![screen shot 2017-05-08 at 10 44 10 am](https://cloud.githubusercontent.com/assets/15169/25817133/438482fe-33db-11e7-84b9-e000ce879953.png)

**Comment by Chillee** [comment] 2017-05-08 17:47
This is a duplicate of this: https://github.com/VSCodeVim/Vim/issues/1657

We recently broke surround a little since we did some very major refactoring. It'll be fixed in the latest release.

**Closed** 2017-05-08 19:03 UTC
