### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by KingdomB** [VSCodeVim/Vim#5391] opened 2020-10-12 16:19 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async n.execCount (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:411708)
	at async F.runAction (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/home/kingconch/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-12 23:12
Duplicate of #5460

**Closed by J-Fields** 2020-11-12 23:12 UTC
