### ISSUE TITLE
Failed to handle key=a. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Romko97** [VSCodeVim/Vim#6463] opened 2021-04-11 21:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. Overlapping ranges are not allowed!
    at T._applyEdit (/snap/code/61/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53072)
    at Object.edit (/snap/code/61/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50744)
    at Object.executeTransformations (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/src/transformations/execute.ts:122:29)
    at I.runAction (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:647:43)
    at I.text [as handleKeyEvent] (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:377:73)
    at Object.runTasks (/home/roman/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
