### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by rezasnai** [VSCodeVim/Vim#6781] opened 2021-06-22 15:04 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at s._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52517)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:50209)
    at Object.executeTransformations (/home/reza/.vscode/extensions/vscodevim.vim-1.21.3/src/transformations/execute.ts:124:29)
    at I.runAction (/home/reza/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/reza/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:652:43)
    at I.mh [as handleKeyEvent] (/home/reza/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:471:11)
    at r (/home/reza/.vscode/extensions/vscodevim.vim-1.21.3/extensionBase.ts:501:15)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
