### ISSUE TITLE
Failed to handle key=. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Taishi66** [VSCodeVim/Vim#6385] opened 2021-03-30 12:55 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.2

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. Overlapping ranges are not allowed!
    at T._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:51884)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49576)
    at Object.executeTransformations (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/src/transformations/execute.ts:122:29)
    at I.runAction (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:647:43)
    at I.text [as handleKeyEvent] (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/extensionBase.ts:377:73)
    at Object.runTasks (/home/taishi/.vscode/extensions/vscodevim.vim-1.19.2/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-03-30 15:20
What were you trying to do when this happened? Can you reproduce?

(Also, there's a new version out that I'd suggest upgrading to, though it does not fix this issue)

**Comment by J-Fields** [comment] 2021-04-21 19:45
Duplicate of #5224 (I think)

**Closed by J-Fields** 2021-04-21 19:45 UTC
Labels: status/duplicate
