### ISSUE TITLE
Failed to handle key=k. Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by linqunhe** [VSCodeVim/Vim#6948] opened 2021-08-03 03:09 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=k. Cannot read property 'name' of undefined
    at c.updateDecorations (/Users/ones-linqunhe/.vscode/extensions/vscodevim.vim-1.21.5/src/actions/plugins/easymotion/easymotion.ts:394:40)
    at j.updateView (/Users/ones-linqunhe/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:1583:32)
    at j.handleKeyAsAnAction (/Users/ones-linqunhe/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:662:16)
    at process.handledAsAction (internal/process/task_queues.js:93:5)
    at j.text [as handleKeyEvent] (/Users/ones-linqunhe/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /Users/ones-linqunhe/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2022-03-09 03:26
Duplicate of #6729

**Closed by J-Fields** 2022-03-09 03:26 UTC
Labels: status/duplicate
