### ISSUE TITLE
commands (d, y, c...) don't work with the smart selection

### ISSUE THREAD

**Issue by titouancreach** [VSCodeVim/Vim#3850] opened 2019-06-24 08:14 UTC
**Describe the bug**
Once text is selected in visual mode via smart selection, the commands applied on the text don't work. For example, `y` that should have been copied the whole selection only copy a part of the selected text

**To Reproduce**

1.  Edit a file
2.  Select some text using smart selection
3.  Press "d" for example
4.  See that not the whole selection is "cut"

**Expected behavior**
The command should be applied to the whole selection

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3995719/60002149-6498a000-9668-11e9-9bf2-dc5f012c6a4e.gif)

(I used smart select to select the function, then, I pressed "d")

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.1
- VSCode version: Version: 1.36.0-insider, Commit: 9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21
- OS: Linux x64 4.15.0-52-generic

**Additional context**

**Comment by J-Fields** [comment] 2019-07-23 22:50
Duplicate of #1806, I believe

**Comment by J-Fields** [comment] 2019-07-24 02:31
Also related: #2942

**Comment by J-Fields** [comment] 2019-09-03 19:39
Closing as dupe of #1806

**Closed by J-Fields** 2019-09-03 19:39 UTC
Labels: kind/bug, kind/enhancement
