### ISSUE TITLE
overrideCopy get unreadable code.

### ISSUE THREAD

**Issue by qws1986** [VSCodeVim/Vim#1510] opened 2017-04-14 03:29 UTC
### What did you do?
Select text and copy(cmd + c) it to other place.

### What did you expect to happen?
Pasted code is the same as copied.

### What happened instead?
Some text (chinese) is changed to unreadable code:
> Áõ∏ÂÖ≥ËµÑÊñô

After i set `overrideCopy` to `false`, it works as expect:
> 相关资料

### Technical details:

* VSCode Version:1.11.2
* VsCodeVim Version: 0.6.15
* OS: macOS Sierra

**Comment by xconverge** [comment] 2017-04-14 04:24
Duplicate of https://github.com/VSCodeVim/Vim/issues/1392

I am trying to get this one fixed right now actually!

**Closed by xconverge** 2017-04-14 04:24 UTC
