### ISSUE TITLE
[vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim

### ISSUE THREAD

**Issue by Serubin** [VSCodeVim/Vim#5342] opened 2020-10-06 20:47 UTC
**To Reproduce**

1. Do anything with vim related in vs code.
ie. `a` to enter insert mode. `v` to enter visual mode. `dd` to delete. `f` for char in line find.

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: [vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:620)
	at Object.t.checkProposedApiEnabled (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:982)
	at x.getConfiguration (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:699:923)
	at Object.getConfiguration (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:791:3)
	at h.getConfiguration (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:6027)
	at Object.updateColor (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:41572)
	at Object.setText (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:40813)
	at Object.clear (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:41272)
	at F.updateView (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:494180)
	at _ (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at async Object.promise (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235688)
	at async Object.runTasks (/Users/serubin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-06 20:50
Duplicate of #5264

**Closed by J-Fields** 2020-10-06 20:50 UTC
