### ISSUE TITLE
Unable to yank specific line range using commands? "Not an editor command"

### ISSUE THREAD

**Issue by rbutera** [VSCodeVim/Vim#5971] opened 2021-01-07 16:19 UTC
**Describe the bug**
In vim, as far as I am aware, you can use `:<start><end>y` to yank a specific range of lines.

In VSCodeVim this results in E492 "Not an editor command"

**To Reproduce**

1. Open editor, in normal mode
2. Type `:1,5y` to attempt to copy lines 1 to 5

**Expected behavior**
Lines are copied.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: MacOS

**Comment by briancodes** [comment] 2021-01-15 00:05
I'm not sure if this is a bug, as it doesn't appear to be in the [roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md) of functionality. There is a [similar](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#deleting-text) command though for delete:

:[range]d [x] | delete [range] lines [into register x]
-- | --

**Comment by J-Fields** [comment] 2021-01-19 19:52
Duplicate of #3219

**Closed by J-Fields** 2021-01-19 19:52 UTC
