### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ilovejs** [VSCodeVim/Vim#6138] opened 2021-02-14 01:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at I._applyEdit (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:36773)
    at I.edit (/snap/code/55/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:36308)
    at y.execute (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:782440)
    at F.runAction (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707900)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at F.handleKeyAsAnAction (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/home/mic/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-02-18 23:20
Duplicate of #5224. What were you trying to do when this happened? (What mode were you in? Did you have multiple cursors?)

**Closed by J-Fields** 2021-02-18 23:20 UTC
