### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by fguilleme** [VSCodeVim/Vim#5433] opened 2020-10-16 11:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:364)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:507:436)
    at new l (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
    at h.updateAndReturnMarks (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:510467)
    at h.finishCurrentStep (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:513988)
    at F.runAction (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:477890)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/francois/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-13 01:12
Duplicate of #5411. If you can reproduce, please post steps there.

**Closed by J-Fields** 2020-11-13 01:12 UTC
