### ISSUE TITLE
Navigation problems with arrow keys

### ISSUE THREAD

**Issue by igor-ribeiro** [VSCodeVim/Vim#1115] opened 2016-12-05 11:04 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Kept pressing down/up arrow (or J/K)

### What did you expect to happen?

Expected the navigation to be smooth

### What happened instead?

I was buggy

![vscode-vim](https://cloud.githubusercontent.com/assets/5148753/20882813/f32f0eee-bac9-11e6-8274-0dc738be316c.gif)

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.7
* OS: Ubuntu 16.04

**Comment by tsvetan-ganev** [comment] 2016-12-05 12:01
I experience the same thing with `0.4.7`. Usually I had this problem with the `j` and `k` keys, but it was fixed a while ago. I switched to `0.4.3` and everything is smooth - both moving with `j`, `k` and the arrow keys. With `0.4.7.` it's totally unusable.

**Comment by xconverge** [comment] 2016-12-05 15:15
This looks to be the same or similar at least to #534

**Comment by jeffperout** [comment] 2016-12-05 16:40
Same issue on Windows 10, rendering it fairly useless, however on an old Mac I have it seems to be smoother...HTH.  I'm keeping 4.4 on my main Win10 development machine !!

**Comment by tsvetan-ganev** [comment] 2016-12-05 16:53
@jeffperout 
Go to the Releases page and download your desired version's `.vsix` file.

In VS Code press `CTRL + SHIFT + P` and type `Install from VSIX`. Then locate your downloaded `.vsix` file and it will install.

**Comment by johnfn** [comment] 2016-12-05 18:40
Yeah, this is a duplicate of #354.

**Closed by johnfn** 2016-12-05 18:40 UTC
