### ISSUE TITLE
search single word

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#2620] opened 2018-05-07 02:04 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug ?

**What happened**:
Search a single word

**What did you expect to happen**:
find the word
**How to reproduce it (as minimally and precisely as possible)**:
/\<word\>
ref https://stackoverflow.com/questions/458915/searching-word-in-vim

**Environment**:
windows 10

- Extension (VsCodeVim) version: 0.11.5
- VSCode version:1.23.0
- OS version:

**Comment by jpoon** [comment] 2018-05-07 02:48
I'm fairly certain this works. In normal mode one you press / you should see the text at the bottom status bar

**Comment by tyru** [comment] 2018-05-07 03:13
> `/<word>`

You cannot use Vim regexp.
You can write `\bword\b` instead (JavaScript regexp).

FYI, the above Vim regexp is also wrong.
The correct one is `\<word\>`.

**Comment by tyru** [comment] 2018-05-07 03:19
Duplicate of #1739, #2043

**Comment by jpoon** [comment] 2018-05-07 05:58
From the description, not entirely certain you were talking about regex's @haolly. In any case, seems we have the regex case covered in a different issue so closing this as a dupe.

**Closed by jpoon** 2018-05-07 05:58 UTC
