### ISSUE TITLE
Last character missing when using find in vscode vim

### ISSUE THREAD

**Issue by w93163red** [VSCodeVim/Vim#6191] opened 2021-02-23 15:51 UTC
**Describe the bug**
The last character is hard to read when using find in vscode vim

**To Reproduce**

1. toggle find window
2. type the word you want to find
3. the last character is grayed out

**Expected behavior**
the last character should not be missing

**Screenshots**
![image](https://user-images.githubusercontent.com/7308728/108869011-cd19ec00-75c4-11eb-8b63-977e17b86f0b.png)

When changing to the default color scheme
![image](https://user-images.githubusercontent.com/7308728/108869522-49143400-75c5-11eb-90ac-7eea358dfaf2.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.18.9
- VSCode version: 1.53.2
- OS: mac os big sur 11.2.1

**Comment by J-Fields** [comment] 2021-02-23 17:25
Duplicate of #5294

**Closed by J-Fields** 2021-02-23 17:25 UTC
Labels: status/duplicate
