### ISSUE TITLE
Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 19

### ISSUE THREAD

**Issue by hsxyl** [VSCodeVim/Vim#5603] opened 2020-11-08 08:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<copy>. getLineLength() called with out-of-bounds line 19
	at Function.getLineLength (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at /Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88932
	at Array.map (<anonymous>)
	at ne.exec (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:88791)
	at ne.execCount (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
	at F.runAction (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
	at F.handleKeyAsAnAction (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/xushenbao/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:27
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:27 UTC
