### ISSUE TITLE
Failed to handle key=t. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by AshTrivedi96** [VSCodeVim/Vim#5451] opened 2020-10-19 17:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=t. Cannot read property 'stop' of undefined
    at p.get cursorStopPosition [as cursorStopPosition] (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
    at F.runAction (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475433)
    at F.handleKeyAsAnAction (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/akshaytrivedi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:48
Duplicate of #5284

**Closed by J-Fields** 2021-02-04 20:48 UTC
Labels: status/duplicate
