### ISSUE TITLE
Repeating shift operation with . (dot) is not work properly when visual block starts from bottom to top.

### ISSUE THREAD

**Issue by Kimilhee** [VSCodeVim/Vim#2814] opened 2018-07-06 09:29 UTC
Is this a BUG REPORT or FEATURE REQUEST? (choose one): Bug Report

**What happened:**
Visual block shifting (>>) with . (repeat last command) is not working properly, when you start visual block from bottom to top.

Start visual block with shift+v and kk (select 2 more lines upward)
then, >> (shift lines to right). 
Until this there's no problem.
Now, if you .(dot) to shift one more depth, it selects 3 more lines upward and shift them.

But if you select visual block from top to bottom, there is no problem.

**What did you expect to happen:**
Start visual block with shift+v and kk (select 2 more lines upward)
then, >> (shift lines to right). 
When you try to repeat shifting action with . (dot)
it should shift just what you shifted before one more time.

In original Vim, it shifts only what you'd shifted before.

**Environment:**

Extension (VsCodeVim) version: 0.14.1
VSCode version: 1.24
OS version: OS X El Capitan

**Comment by xconverge** [comment] 2018-07-06 15:12
duplicate of #549

**Closed by xconverge** 2018-07-06 15:12 UTC
