### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by xyantelope** [VSCodeVim/Vim#6184] opened 2021-02-22 01:32 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
	at v._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:1166)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:81:95)
	at x.delete (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:519744)
	at x.run (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:520516)
	at F.executeOperator (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.runAction (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
	at async F.handleKeyAsAnAction (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/xuyang/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:31
Duplicate of #6258

**Closed by J-Fields** 2021-03-24 17:31 UTC
