### ISSUE TITLE
Removing indentation considerably slower than adding indentation

### ISSUE THREAD

**Issue by simonsanchezart** [VSCodeVim/Vim#5554] opened 2020-11-02 00:36 UTC
**Describe the bug**
 Indenting a line with Visual Line and > is fast. Removing the indentation with Visual Line and < seems to take about a second to complete, no matter the amount of lines selected.

**To Reproduce**
1- Select a line in Visual mode
2- Indent the line with >
3- Select a line in Visual Mode
4- Remove indent with <

**Expected behavior**
Removing an indentation should be as fast as adding it.

**Screenshots**
![E0yI0LNyj6](https://user-images.githubusercontent.com/63672631/97819873-1519a980-1c8a-11eb-9fd3-d7ae7c906fc7.gif)
">" and "<" where pressed almost instantly after selecting the line, for reference.

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.1`

**Comment by J-Fields** [comment] 2020-11-02 01:19
Duplicate of #5188 (will be fixed in next version)

**Closed by J-Fields** 2020-11-02 01:19 UTC
