### ISSUE TITLE
Cursor behaves weird after less-than sign (<) when mapping special keys likes <Esc>

### ISSUE THREAD

**Issue by Sheepolution** [VSCodeVim/Vim#5783] opened 2020-11-29 17:41 UTC
**Describe the bug**
When mapping a key like <Esc> on inoremap, typing the less-than sign (<) results in weird behavior. The cursor will stay in front of the < for a second, after which it appears behind it.

**To Reproduce**

1.  Put the following in your .vimrc file: `inoremap <C-j> <Esc>`
2.  Save and make sure the .vimrc is used by VSCodeVim.
3.  Type `<`

**Expected behavior**
The < is typed like normal and the cursor appears after the typed character.

**Screenshots**
![ltproblem](https://user-images.githubusercontent.com/2232780/100549246-2c8c8800-3272-11eb-89f2-091ad255af92.gif)

Log output:
```
[Extension Host] Extension Startup: debug: Start
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=<ExtensionEnable>. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] Remapper: verbose: key=<ExtensionEnable>. keySlice=<ExtensionEnable>.
console.ts:137 [Extension Host] Extension Startup: debug: Finish.
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.49.1
- OS: Windows

**Comment by Sheepolution** [comment] 2020-11-29 18:10
Actually, this might have to do with the fact that I have certain control-keys settings turned on/off? I'm pretty sure none of my control-related key settings work.

**Comment by J-Fields** [comment] 2020-12-02 07:08
Duplicate of #5188

**Closed by J-Fields** 2020-12-02 07:08 UTC
