### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by A-yushgupta** [VSCodeVim/Vim#6306] opened 2021-03-19 19:46 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at filter (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:28)
    at a.operator (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:215:28)
    at a.isOperatorPending (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:287:12)
    at m.currentModeIncludingPseudoModes (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\state\vimState.ts:252:31)
    at I.handleKeyEvent (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:424:39)
    at Object.promise (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\extensionBase.ts:633:16)
    at Object.runTasks (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\taskQueue.ts:37:20)
    at Object.enqueueTask (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\src\taskQueue.ts:108:12)
    at T (c:\Users\ayush\.vscode\extensions\vscodevim.vim-1.19.0\extensionBase.ts:632:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

</details>

**Comment by J-Fields** [comment] 2021-03-20 20:29
Duplicate of #6309

**Closed by J-Fields** 2021-03-20 20:29 UTC
