### ISSUE TITLE
Failed to handle key=<down>. getLineLength() called with out-of-bounds line 136

### ISSUE THREAD

**Issue by Masumi-M** [VSCodeVim/Vim#5395] opened 2020-10-13 01:36 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<down>. getLineLength() called with out-of-bounds line 136
	at Function.getLineLength (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getDownWithDesiredColumn (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11451)
	at N.execAction (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:190462)
	at N.createMovementResult (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at N.execActionWithCount (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/masumi_morishige/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-13 19:29
Duplicate of #5180, please post repro steps there.

**Closed by J-Fields** 2020-10-13 19:29 UTC
Labels: status/duplicate
