### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by sugarraysam** [VSCodeVim/Vim#5296] opened 2020-09-30 01:36 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
	at new b (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:499:364)
	at new b (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:186)
	at new l (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:1:9260)
	at h.updateAndReturnMarks (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:510380)
	at h.finishCurrentStep (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:513901)
	at F.runAction (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:477803)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235653)
	at async Object.runTasks (/home/sugar/.vscode-oss/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

This happens when I use the `Rust` extension coding rust file

**Comment by J-Fields** [comment] 2020-10-14 01:56
Duplicate of #5226, please post repro steps there.

**Closed by J-Fields** 2020-10-14 01:56 UTC
Labels: status/duplicate
