### ISSUE TITLE
Failed to handle key=<C-a>. 

### ISSUE THREAD

**Issue by favor-ui** [VSCodeVim/Vim#5473] opened 2020-10-22 22:56 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
RangeError: Failed to handle key=<C-a>. 
    at Function.readLineAt (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:21957)
    at Function.getLineLength (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22297)
    at l.isLineEnd (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14231)
    at Function.immediateMatchingBracket (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:93851)
    at c (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:481980)
    at /home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482794
    at t.ExtHostTextEditor.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:647:588)
    at F.executeCommand (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482786)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475467)
    at F.handleKeyAsAnAction (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/home/favor/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 19:00
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 19:00 UTC
