### ISSUE TITLE
unable to delete text with mark d

### ISSUE THREAD

**Issue by nihiluis** [VSCodeVim/Vim#2211] opened 2017-12-09 19:08 UTC
* Click *thumbs-up* 👍 on this issue if you want it! Yes I want it BACK
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. Well actually no

The VSCodeVim team prioritizes issues based on reaction count. Ok

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Both

**Environment**: ????

- **VSCode Version**: 2017
- **VsCodeVim Version**: newest
- **OS**: linux

**What happened**:
when i mark text and use d, text is not deleted and mark removed.

d

**What did you expect to happen**: 
when i mark text and use d, text is deleted 100%

**How to reproduce it**:
mark text and use d like when i started using vscode and this addon (2016-2017)

**Comment by kkorus** [comment] 2017-12-16 15:29
@nihiluis Do you mark text using mouse or shift and arrow keys?

**Comment by nihiluis** [comment] 2017-12-16 18:33
mouse

**Comment by kkorus** [comment] 2017-12-16 18:35
@nihiluis  I think it is related to issue that I have created: https://github.com/VSCodeVim/Vim/issues/2224

**Comment by jpoon** [comment] 2017-12-16 22:59
Ya, dupe of that and closing it as such.

**Closed by jpoon** 2017-12-16 22:59 UTC
