### ISSUE TITLE
entering visual mode when select in insert mode

### ISSUE THREAD

**Issue by chantisnake** [VSCodeVim/Vim#1276] opened 2017-02-06 10:05 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
enter insert mode, then select some text via mouse

### What did you expect to happen?
when you set `behave xterm` in vim, it will automatically enter visual mode when you select text in insert mode.
I want a setting like `behave xterm` in vscode

### What happened instead?
The behavior is just like regular text selection in vscode. 

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: Windows 10

**Comment by J-Fields** [comment] 2020-07-14 16:16
Duplicate of #4972

**Closed by J-Fields** 2020-07-14 16:16 UTC
Labels: kind/enhancement
