### ISSUE TITLE
vim undo vs vscode undo

### ISSUE THREAD

**Issue by askeeve** [VSCodeVim/Vim#6919] opened 2021-07-27 16:22 UTC
It seems like the extension uses a different undo buffer from the standard one vscode uses. I would prefer to use the standard vscode undo buffer with the vim keybindings.  As is, I don't have a real way to call a "redo" with the vim undo.

Vim Redo is "Ctrl+R". So if I want to have access to this function, that means I need to give up all VSCode Ctrl Keybindings and surrender them entirely to the extension.  If I don't, then there's no alternative vim keybinding for Redo that I know of.

I can do ctrl+z and ctrl+r with the vscode undo/redo, but it won't redo something that I undid with a vim 'u'.  I would like to be able to use ctrl+z or 'u' to undo, and ctrl+r to redo what either of them did.

**Comment by northernocean** [comment] 2021-07-30 19:23
It is possible you can get the behavior that you want by setting the option for **Vim: Use System Clipboard** to true. I've found the behavior with undo's/redo's to be more consistent after this. See if it helps you too. 

Also I'm pretty sure you can bind Ctrl-R to vim redo (I do that). Probably I just set **Vim: Use Ctrl Keys** to true. Not really sure how much this means surrendering to the extension - that comes down to specifics. I haven't noticed any control key shortcuts that I miss.

**Comment by w-cantin** [comment] 2021-08-04 17:00
Hello @askeeve. It is possible to rebind any vscode commands using vim remapping and the "commands" attribute instead of "after". For example in my `settings.json` I use those 4 keybindings for the exact same reasons you mentioned. 

```json
   {
      "before": ["u"],
      "commands":["undo"]
    },
    {
      "before": ["U"],
      "commands": ["redo"]
    },
    {
      "before": ["leader", "u"],
      "after": ["u"]
    },
    {
      "before": ["leader", "U"],
      "after": ["<C-r>"]
    }, 
```

`u` is VSCode undo
`U` is VSCode redo
`leader u` is Vim undo
`lead U` is Vim redo

I kept vim's redo/undo commands for some special cases where VSCode's seems to struggle. For example multiple vim commands that are undone in 1 vim undo can take VScode multiple undos. It does not happen that often though. I hope that helped.

**Comment by askeeve** [comment] 2021-08-04 17:23
@w-cantin this might be a stupid question but which settings.json are you referring to here?  I understand the gist of your suggestion but some of the organization of vscode is still a bit arcane to me.

**Comment by w-cantin** [comment] 2021-08-04 18:20
I know the documentation can be confusing and it can become quite overwhelming at the beginning. I was there not that long ago so I know the feeling. I'm glad I could help you. 

By the way make sure to close this issue if the problem is fixed.

**Closed** 2021-08-04 18:21 UTC
