### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by putrasurya** [VSCodeVim/Vim#5802] opened 2020-12-01 23:29 UTC
**To Reproduce**

1. block words using v and gb
2. type y to copy
3. type escape to exit from multi cursor
4. go to desire line
5. then type p to paste
6. you will see this error

was expecting it to work the same as Ctrl+D and Ctrl+V

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:37457)
	at async n.execCount (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:411708)
	at async F.runAction (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:471603)
	at async Object.promise (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:235740)
	at async Object.runTasks (/Users/admin/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:35
Duplicate of #5239, should be fixed in the upcoming release

**Closed by J-Fields** 2020-12-05 18:35 UTC
