### ISSUE TITLE
CPU ran into 200%+ in VSCode 1.18.0

### ISSUE THREAD

**Issue by gonghao** [VSCodeVim/Vim#2124] opened 2017-11-09 04:00 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Environment**:

- **VSCode Version**: 1.18.0
- **VsCodeVim Version**: 0.10.2
- **OS**: macOS 10.13.2 Beta (17C67b)

**What happened**:

When I upgrade to VSCode 1.18.0 the CPU ran into extreme high, I found it caused by two `Code Helper.app` processes. Then I just disabled all extensions, everything is OK. It is clear that this issues is caused by extensions conflicts with VSCode, so I re-enabled each extension to figure out which one caused this situation. Finally I found it is VSCodeVim, I just re-enabled every other extensions everything is OK, but after re-enable VSCodeVim, the CPU went high.

So I don't know do you guys have the same issue?

**What did you expect to happen**: 

Normal CPU usage.

**How to reproduce it**:

- Install VSCode 1.18.0
- Install VSCodeVim and enabled it

**Comment by francescarpi** [comment] 2017-11-09 07:12
On Windows 10, the same thing happens.

**Comment by ivanvoznyakovsky** [comment] 2017-11-09 11:28
Same on High Sierra 10.13. Opening a file creates 2 CodeHelper processes with 100+%  CPU usage.

**Comment by stevestmartin** [comment] 2017-11-09 19:25
Same occurs on macOS 10.12.6

**Comment by colbell** [comment] 2017-11-10 04:58
I've got the same problem on Ubuntu 17.10.

I disabled "Easy motion", I.E added `"vim.easymotion": false,` to the user settings file, restarted VS Code and opened a Ruby source file. Once the indexing finished the CPU dropped away.

So it looks like an issue with "Easy Motion".

**Comment by stevestmartin** [comment] 2017-11-10 14:28
@colbell confirmed, if I open it with any source file active even a blank one CPU usage spikes, if i open the user settings tab and relaunch CPU is low. I can consistently reproduce this, switching to a source code tab after launch, or having source code tabs open (regardless of tab order) at launch CPU still remains low, it seems this occurs only when a source code based tab has focus on launch.

**Comment by ivanvoznyakovsky** [comment] 2017-11-10 14:41
I have my CPU going crazy whenever a file is focused or vscode is re-open with a prev file opened. once I have any file opened CPU usage spikes.

**Comment by adamwiggall** [comment] 2017-11-10 17:03
Same for me on Sierra 10.12.6, running VS code 1.18.0.

**Comment by jondot** [comment] 2017-11-10 17:06
Have the same thing. Arrived at Vim extension by elimination of extensions. Profiled the extension and got this:

![image](https://user-images.githubusercontent.com/83390/32669726-36909dec-c64a-11e7-88bd-c137b70fd145.png)

Which hints at my customising the status bar colors. Removed my config and everything is normal again!

**Comment by stevestmartin** [comment] 2017-11-10 17:15
Disabling custom status bar colors corrected the problem for me also.

**Comment by gonghao** [comment] 2017-11-10 17:20
@jondot Great work! I just disabled the customize status bar colors, everything goes well!

**Comment by colbell** [comment] 2017-11-10 22:21
Nice one @jondot disabling the colours fixed it for me too.

**Comment by ivanvoznyakovsky** [comment] 2017-11-11 11:58
confirm that `"vim.statusBarColorControl": false` fixes the issue. great catch @jondot 👍 
don't think it's a real fix but rather a workaround 😄

**Comment by chasestarr** [comment] 2017-11-11 18:31
I can reproduce consistently on `Version 1.18`. 

Just tested in `Version 1.19.0-insider 11-11-17` on `MacOS Sierra 10.12.5` and _cannot_ reproduce CPU spike. 

@MythicalFish can you still repro? I can't find a PR relevant to this issue landing in vscode from the past few days - which I find strange https://github.com/Microsoft/vscode/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%3E2017-11-07

**Comment by samumist** [comment] 2017-11-12 10:38
same for me on `macOS 10.11.6` and `vscode 1.18`.

**Comment by newro** [comment] 2017-11-14 01:45
I am experiencing a phenomenon that the CPU becomes higher after vscode 1.18 update in the Win10 environment.
The code helper process is using a high CPU, and disabling the vim plugin disables the symptom.

**Comment by sc0ttwad3** [comment] 2017-12-03 18:07
It was the vim extension causing the 100% CPU usage issue for me also. Removing any/all "neovim" related settings took care of the problem. Just changing some to a 'disabled' value or just commenting out did not work. I had to totally remove then entries.

**Comment by Chillee** [comment] 2018-03-08 20:37
Does anybody still get this issue on recent versions of VSCodeVim?

**Comment by stevebasford** [comment] 2018-03-27 10:50
I still experienced this issue in 1.21.1 and for me it was fixed by commenting out the `"vim.disableAnnoyingNeovimMessage"` setting

**Comment by jpoon** [comment] 2018-03-27 20:40
@stevebasford that setting is deprecated, it was removed awhile ago. Closing this issue as it seems resolved.

**Closed by jpoon** 2018-03-27 20:40 UTC
Labels: area/performance

**Comment by ChasKane** [comment] 2019-06-07 23:43
I was brought here by the below link (about 2/3 of the way down the page, in the emulated-plugins section), thinking I couldn't use vim-airline with VSCodeVim. It seems this no longer affecting vim-airline, yes? Might be best to remove the disclaimer at the top of the emulated-plugins section

https://marketplace.visualstudio.com/items?itemName=vscodevim.vim#-emulated-plugins

**Comment by xelaos** [comment] 2019-07-02 08:13
From my experience it depends on the machine you are using. Maybe it was worse in 2017 regardless of your machine, but it is still an issue.

**Comment by andyearnshaw** [comment] 2020-03-02 22:27
I'd recommend sticking a 👍 on https://github.com/microsoft/vscode/issues/43226 if you want to be able to enable statusbar colours without performance issues.

**Comment by nzig** [comment] 2021-02-07 09:26
Could this recent change solve this?
https://code.visualstudio.com/updates/v1_53#_status-bar-entry-background-color-api

**Comment by The-Compiler** [comment] 2021-05-20 16:48
@nzig that blog post says:

> Currently only `statusBarItem.errorBackground` is supported to avoid the Status bar looking too colorful.

so it looks to me like that'd be of limited use...

FWIW I managed to find a solution to color the status bar item based on its text, using the [Customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension:

```json
    "customizeUI.stylesheet": {
        "#vscodevim\\.vim[aria-label=\"-- INSERT --\"]": "background-color: #98971a !important;",
        "#vscodevim\\.vim[aria-label=\"-- VISUAL --\"]": "background-color: #b16286 !important;",
        "#vscodevim\\.vim[aria-label^=\":\"]": "background-color: #7c6f64 !important;",
    },
```

result:

![image](https://user-images.githubusercontent.com/625793/119018035-ef40c180-b99b-11eb-96b9-43678123d20d.png)

![image](https://user-images.githubusercontent.com/625793/119017872-bf91b980-b99b-11eb-91ab-54260abf365b.png)

![image](https://user-images.githubusercontent.com/625793/119017896-c6b8c780-b99b-11eb-8790-2408e641c393.png)

![image](https://user-images.githubusercontent.com/625793/119017991-e2bc6900-b99b-11eb-88e6-d3bee4dd6c73.png)

**Comment by edgartaor** [comment] 2022-05-29 02:25
> FWIW I managed to find a solution to color the status bar item based on its text, using the [Customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension:

For some reason this does not work for me. How do you find those values ("#vscodevim\\..."). Maybe those are different now.

**Comment by The-Compiler** [comment] 2022-05-29 11:14
> > FWIW I managed to find a solution to color the status bar item based on its text, using the [Customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension:
> 
> For some reason this does not work for me. How do you find those values ("#vscodevim\..."). Maybe those are different now.

They are indeed! It's `#vscodevim\\.vim\\.primary` now, adjusted above.

I found them by opening the developer tools (Ctrl-Shift-P, "Developer: Toggle Developer tools") and then using the picker at the top left of the "Elements" tab to inspect the element.

**Comment by robertfw** [comment] 2023-08-08 20:09
FYI, Customize UI no longer works so that option is off the table :(

I'd love to get something along these lines, as I'm often not noticing which mode I'm in, even with different cursors for insert vs normal.

**Comment by The-Compiler** [comment] 2023-08-08 20:16
> FYI, Customize UI no longer works so that option is off the table :(

I switched to [be5invis/vscode-custom-css](https://github.com/be5invis/vscode-custom-css) which still works (though since the CSS is placed in a normal file with it, use `\` instead of `\\` and `"` instead of `\"` above).

**Comment by johnnybakucz** [comment] 2024-07-16 15:22
> > FYI, Customize UI no longer works so that option is off the table :(
> 
> I switched to [be5invis/vscode-custom-css](https://github.com/be5invis/vscode-custom-css) which still works (though since the CSS is placed in a normal file with it, use `\` instead of `\\` and `"` instead of `\"` above).

I seriously love your solution, I modified it a bit to color the whole status bar to make it more visible of a change.


```
    #workbench\.parts\.statusbar:has([aria-label="-- NORMAL --"]) {
        background-color: #27981a !important;
    }

    #workbench\.parts\.statusbar:has([aria-label="-- INSERT --"]) {
        background-color: #de080f !important;
    }

    #workbench\.parts\.statusbar:has([aria-label="-- VISUAL --"]) {
        background-color: #8362b1 !important;
    }

    #workbench\.parts\.statusbar:has([aria-label="-- VISUAL LINE --"]) {
        background-color: #62b1b1 !important;
    }

**Comment by raulpenate** [comment] 2024-09-12 12:27
An easy alternative solution is to install and give permissions to [Apc Customize UI++](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension) and add the following to `settings.json`:

```json
{
  "apc.stylesheet": {
    /* Default footer style */
    ".part.statusbar.status-border-top": "background-color: rgb(143, 188, 187); color: rgb(67, 76, 94);",
    /* Apply styles based on aria-label in the footer */
    ".part.statusbar.status-border-top [aria-label='-- NORMAL --']": "background-color: #8FBCBB; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- INSERT --']": "background-color: #BF616A; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- VISUAL --']": "background-color: #B48EAD; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- VISUAL LINE --']": "background-color: #B48EAD; color: #434C5E;"
  }
}
```

**Comment by its-Danial** [comment] 2024-09-19 16:55
> An easy alternative solution is to install and give permissions to [Apc Customize UI++](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension) and add the following to `settings.json`:
> 
> ```json
> {
>   "apc.stylesheet": {
>     /* Default footer style */
>     ".part.statusbar.status-border-top": "background-color: rgb(143, 188, 187); color: rgb(67, 76, 94);",
>     /* Apply styles based on aria-label in the footer */
>     ".part.statusbar.status-border-top [aria-label='-- NORMAL --']": "background-color: #8FBCBB; color: #434C5E;",
>     ".part.statusbar.status-border-top [aria-label='-- INSERT --']": "background-color: #BF616A; color: #434C5E;",
>     ".part.statusbar.status-border-top [aria-label='-- VISUAL --']": "background-color: #B48EAD; color: #434C5E;",
>     ".part.statusbar.status-border-top [aria-label='-- VISUAL LINE --']": "background-color: #B48EAD; color: #434C5E;"
>   }
> }
> ```

Really helpful answer, because I belive if you use the "vim.statusBarColorControl" option then you cannot use "extensions.experimental.affinity" correctly because it keeps updating the settings.json.

I added a few things to your settings hope it helps, feel more complete now.
` 
  "apc.stylesheet": {
    /* Apply styles based on aria-label in the footer */
    ".part.statusbar.status-border-top [aria-label^='-- NORMAL']": "background-color: #8FBCBB; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- INSERT --']": "background-color: #BF616A; color: #e5e7eb;",
    ".part.statusbar.status-border-top [aria-label='-- VISUAL --'], .part.statusbar.status-border-top [aria-label='-- VISUAL LINE --']": "background-color: #B48EAD; color: #e5e7eb;",
    ".part.statusbar.status-border-top [aria-label='-- VISUAL BLOCK --']": "background-color: #A3BE8C; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- REPLACE --']": "background-color: #D08770; color: #434C5E;",
    ".part.statusbar.status-border-top [aria-label='-- EASYMOTION INPUT --'], .part.statusbar.status-border-top [aria-label='-- SURROUND INPUT --']": "background-color: #007ACC; color: #e5e7eb;",
    ".part.statusbar.status-border-top [aria-label^=':'], .part.statusbar.status-border-top #vscodevim\\.vim\\.showcmd": "color: #fafafa;"
  }
`

**Comment by Rabeez** [comment] 2025-03-03 16:41
I was only able to get expected output using the "Custom UI Style" extension and this snippet:
```json
    "custom-ui-style.stylesheet": {
        ".statusbar-item-label[aria-label=\"-- NORMAL --\"], .statusbar-item-label[aria-label=\"-- SURROUND INPUT --\"], .statusbar-item-label[aria-label=\"-- EASYMOTION INPUT --\"], .statusbar-item-label[aria-label='Already at oldest change'], .statusbar-item-label[aria-label=':nohlsearch']": "background-color: #89b4fa !important; color: #181825 !important",
        ".statusbar-item-label[aria-label=\"-- INSERT --\"]": "background-color: #a6e3a1 !important; color: #181825 !important",
        ".statusbar-item-label[aria-label=\"-- REPLACE --\"]": "background-color: #f38ba8 !important; color: #181825 !important",
        ".statusbar-item-label[aria-label=\"-- VISUAL --\"], .statusbar-item-label[aria-label=\"-- VISUAL BLOCK --\"], .statusbar-item-label[aria-label=\"-- VISUAL LINE --\"]": "background-color: #cba6f7 !important; color: #181825 !important",
        ".statusbar-item-label[aria-label^=':']": "background-color: #f9e2af !important; color: #181825 !important",
    },
```

**Comment by abui-dev** [comment] 2025-03-20 14:43
> I was only able to get expected output using the "Custom UI Style" extension and this snippet:
> 
>     "custom-ui-style.stylesheet": {
>         ".statusbar-item-label[aria-label=\"-- NORMAL --\"], .statusbar-item-label[aria-label=\"-- SURROUND INPUT --\"], .statusbar-item-label[aria-label=\"-- EASYMOTION INPUT --\"], .statusbar-item-label[aria-label='Already at oldest change'], .statusbar-item-label[aria-label=':nohlsearch']": "background-color: #89b4fa !important; color: #181825 !important",
>         ".statusbar-item-label[aria-label=\"-- INSERT --\"]": "background-color: #a6e3a1 !important; color: #181825 !important",
>         ".statusbar-item-label[aria-label=\"-- REPLACE --\"]": "background-color: #f38ba8 !important; color: #181825 !important",
>         ".statusbar-item-label[aria-label=\"-- VISUAL --\"], .statusbar-item-label[aria-label=\"-- VISUAL BLOCK --\"], .statusbar-item-label[aria-label=\"-- VISUAL LINE --\"]": "background-color: #cba6f7 !important; color: #181825 !important",
>         ".statusbar-item-label[aria-label^=':']": "background-color: #f9e2af !important; color: #181825 !important",
>     },

Thanks a lot!
Confirm it's working for me as well (VSCode v1.98.2 on mac) and it's the easiest solution I've seen after trying out many other extentions.
Link to the extension https://github.com/VSCodeVim/Vim/issues/2124

**Comment by Edgpaez** [comment] 2025-05-13 15:42
Adding to @Rabeez's solution [here](https://github.com/VSCodeVim/Vim/issues/2124#issuecomment-2694969828)

I added some lines to support multiple cursors:
```css
  "custom-ui-style.stylesheet": {
    ".statusbar-item-label[aria-label=\"-- NORMAL --\"], .statusbar-item-label[aria-label=\"-- SURROUND INPUT --\"], .statusbar-item-label[aria-label=\"-- EASYMOTION INPUT --\"], .statusbar-item-label[aria-label='Already at oldest change'], .statusbar-item-label[aria-label=':nohlsearch']": "background-color: #89b4fa !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- INSERT --\"]": "background-color: #a6e3a1 !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- REPLACE --\"]": "background-color: #f38ba8 !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- VISUAL --\"], .statusbar-item-label[aria-label=\"-- VISUAL BLOCK --\"], .statusbar-item-label[aria-label=\"-- VISUAL LINE --\"]": "background-color: #cba6f7 !important; color: #181825 !important",
    // multi cursor
    ".statusbar-item-label[aria-label=\"-- NORMAL --  MULTI CURSOR\"]": "background-color: #89b4fa !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- INSERT --  MULTI CURSOR\"]": "background-color: #a6e3a1 !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- REPLACE --  MULTI CURSOR\"]": "background-color: #f38ba8 !important; color: #181825 !important",
    ".statusbar-item-label[aria-label=\"-- VISUAL --  MULTI CURSOR\"]": "background-color: #cba6f7 !important; color: #181825 !important",

    ".statusbar-item-label[aria-label^=':']": "background-color: #f9e2af !important; color: #181825 !important"
  }
```

<img width="326" alt="Image" src="https://github.com/user-attachments/assets/71b9e82f-cbcf-4f5f-bd3b-f282d52f4061" />

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/1b4e2ba8-21a5-4928-93dd-8fd92e7d1786" />
