### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by maainul** [VSCodeVim/Vim#6235] opened 2021-03-05 09:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at T._applyEdit (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:51884)
	at Object.edit (/snap/code/57/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49576)
	at y.execute (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:782440)
	at F.runAction (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707900)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.handleKeyAsAnAction (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
	at async Object.runTasks (/home/onik/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment] 2021-03-21 19:59
Duplicate of #5224. If you can repro, please let me know.

**Closed by J-Fields** 2021-03-21 19:59 UTC
