### ISSUE TITLE
exclamation mark followed by movement command

### ISSUE THREAD

**Issue by jonasbradstreet** [VSCodeVim/Vim#4857] opened 2020-05-14 20:09 UTC
In the original Vim program, when I hit !} I will have selected from the current cursor position to the end of the paragraph giving me ":,<# of lines to end of paragraph>!" In VS Code "Vim" ! appears to do nothing and following it with } just moves the cursor to the end of the paragraph.

Am I doing something wrong, or is this functionality not available?

**Comment by J-Fields** [comment] 2020-05-14 20:17
Not currently available.

**Comment by jonasbradstreet** [comment] 2020-05-14 20:21
Got it. Thanks for the response.

**Comment by J-Fields** [comment] 2020-05-14 20:22
Re-opening as it's a reasonable request (and I wasn't aware of this feature until this issue)

**Comment by wesleyegberto** [comment] 2020-05-15 05:36
I noted that when in visual mode the `!}` works.

**Comment by tagniam** [comment] 2020-07-03 16:43
Seems to be a dupe of #4166?

**Closed** 2020-07-18 05:47 UTC
Labels: kind/feature
