### ISSUE TITLE
Failed to handle key=U. Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by anurag3753** [VSCodeVim/Vim#6346] opened 2021-03-25 14:12 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=U. Cannot read property 'start' of undefined
    at p.goBackHistoryStepsOnLine (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\history\historyTracker.ts:752:51)
    at Re.exec (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\actions\commands\actions.ts:1152:56)
    at Re.execCount (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\actions\base.ts:218:20)
    at I.runAction (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\mode\modeHandler.ts:719:20)
    at I.handleKeyAsAnAction (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\mode\modeHandler.ts:650:16)
    at I.handleKeyEvent (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\mode\modeHandler.ts:469:40)
    at process.text (internal/process/task_queues.js:85:5)
    at Object.promise (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\extensionBase.ts:377:73)
    at Object.runTasks (c:\Users\anuragm\.vscode\extensions\vscodevim.vim-1.19.2\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-04-04 21:07
Duplicate of #6377

**Closed by J-Fields** 2021-04-04 21:07 UTC
Labels: kind/bug
