### ISSUE TITLE
New feature request: Support for special marks

### ISSUE THREAD

**Issue by npbool** [VSCodeVim/Vim#2349] opened 2018-01-31 18:41 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What happened**:
\`], \`[, \`>, \`< don't work
**What did you expect to happen**:
As stated in http://vim.wikia.com/wiki/Using_marks,
\`[ or \`] should jump to beginning/end of previously changed or yanked text,
\`< or \`> should jump to beginning/end of last visual selection.

**How to reproduce it (as minimally and precisely as possible)**:
yank some text and press \`] or \`[. Visual select some text and deselect it, then press \`< or \`>

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.19.3
- OS version: macOS High Sierra 10.13.2

**Comment by tomdl89** [comment] 2018-10-24 11:28
I would also like to see this feature!

**Comment by J-Fields** [comment] 2021-07-26 15:36
Marking as duplicate of #4734, as I think that's the missing gap at this point.

**Closed by J-Fields** 2021-07-26 15:36 UTC
Labels: kind/enhancement
