### ISSUE TITLE
chinese input bugs

### ISSUE THREAD

**Issue by zwkno1** [VSCodeVim/Vim#1699] opened 2017-05-15 05:45 UTC
when i input multi words using chinese input sougou, the cursor  will go back to the the beginning of this words, not the end.

**Comment by Chillee** [comment] 2017-05-16 01:08
Dupe of https://github.com/VSCodeVim/Vim/issues/1027

**Comment by xconverge** [comment] 2017-05-16 02:51
Closed in favor of the other one. Please go thumbs up that issue!

**Closed by xconverge** 2017-05-16 02:51 UTC
