### ISSUE TITLE
Failed to handle key=<C-c>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by cyrilchemparathy** [VSCodeVim/Vim#5406] opened 2020-10-13 17:19 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.17.1<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:284758)    at https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:282735    at Object.next (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:282840)    at https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:281753    at new Promise (<anonymous>)    at r (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:281490)    at e.$executeCommand (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:167:284631)    at e.doInvokeHandler (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:19:199168)    at e.invokeHandler (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:19:198901)    at e.receiveRequest (https://d746e1af-ac14-467f-8557-07b4fabd5437.ws-us02.gitpod.io/bundle.js:19:198193)```</details>

**Comment by cyrilchemparathy** [comment] 2020-10-13 17:19
fails to copy...

**Comment by J-Fields** [comment] 2020-11-12 23:31
Duplicate of #5526. What version of VS Code are you running?

**Closed by J-Fields** 2020-11-12 23:31 UTC
