### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by The-spotlight** [VSCodeVim/Vim#6041] opened 2021-01-26 06:34 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

**Comment by J-Fields** [comment] 2021-03-25 15:56
Duplicate of #5985

**Closed by J-Fields** 2021-03-25 15:56 UTC
Labels: status/duplicate
