### ISSUE TITLE
Ctrl-d/u does not move cursor

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#2447] opened 2018-03-15 18:31 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**: Ctrl-d/u does not move cursor by half screen. It only scrolls screen and if the cursor would fall out of screen it puts the cursor on the edge line.

**What did you expect to happen**: Ctrl-d/u actually moves cursor.

**How to reproduce it (as minimally and precisely as possible)**: Ctrl-d/u

**Environment**:

- VS Code: 1.21.1
- Vim: 0.11.2
- OS: macOS 10.13.2

**Comment by c10b10** [comment] 2018-05-12 12:55
Having this problem as well.

**Comment by jpoon** [comment] 2018-05-13 05:39
Dupe of https://github.com/VSCodeVim/Vim/issues/1348

**Closed by jpoon** 2018-05-13 05:39 UTC
