### ISSUE TITLE
Failed to handle key=. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by lrvideckis** [VSCodeVim/Vim#6037] opened 2021-01-25 20:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.setLastHistoryEndPosition (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:207915)
	at F.runAction (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:174898)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by lrvideckis** [comment] 2021-01-28 17:30
It always happens right after pressing 'u' to undo. Although, I haven't figured out exactly how to reproduce it.

Also, it's super annoying because after this bug happens, **no** keybindings work anymore. After pressing anything, it says something like "error, history at index -1", and doesn't do that keystroke.

**Comment by lrvideckis** [comment] 2021-01-28 17:31
I've worked around this by reloading vscode when this happens.

**Comment by J-Fields** [comment] 2021-02-06 05:58
Duplicate of #5209

**Closed by J-Fields** 2021-02-06 05:58 UTC
Labels: status/duplicate
