### ISSUE TITLE
Failed to handle key=p. getLineLength() called with out-of-bounds line 42

### ISSUE THREAD

**Issue by mohammadkazemi** [VSCodeVim/Vim#5365] opened 2020-10-09 16:50 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=p. getLineLength() called with out-of-bounds line 42
	at Function.getLineLength (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at y.exec (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:412925)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.execCount (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/mohammadkazemi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-11 02:57
Duplicate of #5180

**Closed by J-Fields** 2020-10-11 02:57 UTC
Labels: status/duplicate
