### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by MichaelHaffley** [VSCodeVim/Vim#7479] opened 2022-02-11 18:30 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'substring' of undefined
    at _.display (/Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/src/cmd_line/commandLine.ts:402:89)
    at statusBarText (/Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/src/statusBar.ts:199:35)
    at Object.clear (/Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/src/statusBar.ts:105:17)
    at j.updateView (/Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/src/mode/modeHandler.ts:1579:15)
    at _ (/Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/extensionBase.ts:54:22)
    at runMicrotasks (<anonymous>)
    at process.mh (internal/process/task_queues.js:93:5)
    at /Users/phaffley/.vscode/extensions/vscodevim.vim-1.22.0/extensionBase.ts:264:15
```

</details>

**Comment by J-Fields** [comment] 2022-02-17 16:34
Duplicate of #7512

**Closed as completed by J-Fields** 2022-02-17 16:34 UTC
Labels: status/duplicate
