### ISSUE TITLE
TaskQueue: Error running task. getLineLength() called with out-of-bounds line 236.

### ISSUE THREAD

**Issue by danny-su** [VSCodeVim/Vim#5086] opened 2020-07-30 02:49 UTC
TaskQueue: Error running task. getLineLength() called with out-of-bounds line 236.

- Extension (VsCodeVim) version: v1.16.0
- VSCode version: 1.47.3
- OS: MacOS 10.15.6

**Comment by berknam** [comment] 2020-07-30 11:43
Can you give more information? What were you doing when this happened? Can you present the steps to reproduce it?

Is this the same as #5082?

**Comment by danny-su** [comment] 2020-08-05 06:32
@berknam Sorry, I can't reproduce it. I did nothing, just open vs code for a very simple project.

**Comment by berknam** [comment] 2020-08-05 10:33
Can you reproduce it with the steps from https://github.com/VSCodeVim/Vim/issues/5082#issuecomment-665502463?

**Comment by J-Fields** [comment] 2020-08-05 17:50
I've seen this a handful of times recently. Just committed 6bc75a7560507e1d632f5f2c1fd8266c49b27c6a, which should make the cause easier to identify. It'll be in the next release but you can always install from master ahead of that.

**Closed** 2020-08-12 21:59 UTC
Labels: kind/bug
