### ISSUE TITLE
Failed to handle key=q. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by jj11hh** [VSCodeVim/Vim#6949] opened 2021-08-03 03:14 UTC
**To Reproduce**

1.  Record a macro with `qq`
2.  Replay this macro with `@q`
3.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=q. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\jiangyiheng\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\jiangyiheng\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\jiangyiheng\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\jiangyiheng\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\jiangyiheng\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[37, 72] | [37, 72]]"
]
actionsRunPressedKeys: [
  "<down>",
  "@",
  "@",
  "q"
]
actionsRun: [
  "ee",
  "q",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 36,
      "character": 72
    },
    "text": "ity",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 36,
        "character": 59
      },
      {
        "line": 36,
        "character": 75
      }
    ],
    "text": "EditorGUIUtility.TrTextContent(\"\")",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-08-03 03:17
Duplicate of #6888, will be fixed in next release

**Closed by J-Fields** 2021-08-03 03:17 UTC
Labels: status/duplicate
