### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by khaliddevs** [VSCodeVim/Vim#6044] opened 2021-01-26 08:43 UTC
**To Reproduce**

1.  Open a file on VS Code
2.  Go to Insert Mode
3.  Press CRTL + A
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
	at new y (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:424)
	at new y (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
	at a (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74323)
	at F.exec (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:74368)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.exec (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:195203)
	at async x.execCount (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641)
	at async F.runAction (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/home/khalid/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 17:03
Closing as duplicate of #6339

**Closed by J-Fields** 2021-03-24 17:03 UTC
Labels: status/duplicate
