### ISSUE TITLE
Up/down motion with gj and gk does not retain cursor position

### ISSUE THREAD

**Issue by o-lim** [VSCodeVim/Vim#1675] opened 2017-05-08 17:14 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.x
- **VsCodeVim Version**: 0.7.0
- **OS**: Linux

**What happened**:
* Remap navigation keys `j` and `k` to `gj` and `gk` respectively via:
```json
{
    "vim.otherModesKeyBindingsNonRecursive": [{
         "before": ["j"],
         "after": ["g", "j"]
     }, {
         "before": ["k"],
         "after": ["g", "k"]
    }]
}
```
1. Go to the first line of a series of non-wrapped lines of text, say something like:
```C++
void foobar() {
  if (condition) {
    value = a;
  } else {
    value = b;
  }
}
```
2. Move cursor to somewhere in middle of the line, say column position 10
3. Staying in normal mode, press `j` to move down a line
4. Keep pressing `j` to keep moving down several lines
5. As soon as you hit a line that has fewer characters than where your cursor column position is, the column position gets reset to the end of the current line

**What did you expect to happen**: 
* Should behave exactly like `j` and `k` navigation for non-wrapped lines
  * When going up/down a line the cursor's column position should be restored to the column position when the up/down (`j`,`k`) navigation first occurred, unless the line is too short, in which case it should go to end of line
  * In the above example, the cursor position should stay at column 10 whenever possible

**Comment by Chillee** [comment] 2017-05-08 17:16
Haha this is also a duplicate of https://github.com/VSCodeVim/Vim/issues/1323. 

There's an open PR for this (https://github.com/VSCodeVim/Vim/pull/1561), but it has some issues. The fundamental problem is that vscode doesn't expose wrapped line information to us. It might be fixable, but it'd be quite a bit of work.

**Comment by xconverge** [comment] 2017-05-08 21:55
closing in favor of #1323

**Closed by xconverge** 2017-05-08 21:55 UTC
