### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by cclauss** [VSCodeVim/Vim#6911] opened 2021-07-25 17:29 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at n._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at j.rerunRecordedState (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:207:12)
    at j.actionToRecord [as runAction] (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /Users/cclauss/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[14, 14] | [14, 14]]"
]
actionsRunPressedKeys: [
  "<Esc>"
]
actionsRun: [
  "ee",
  "q",
  "$",
  "C",
  "C",
  "$",
  "C",
  "C",
  "C",
  "C",
  "$",
  "C",
  "$",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 14,
      "character": 14
    },
    "text": "d",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 14,
        "character": 12
      },
      {
        "line": 14,
        "character": 15
      }
    ],
    "text": "stdout",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-26 15:17
Duplicate of #6888

**Closed by J-Fields** 2021-07-26 15:17 UTC
Labels: status/duplicate
