### ISSUE TITLE
Remapping Caps Lock to Escape does not work

### ISSUE THREAD

**Issue by msasad** [VSCodeVim/Vim#2085] opened 2017-10-22 14:12 UTC
Mapping Caps Lock key as additional Escape key has no effect in VSCodeVim. One still needs to reach out the original Escape key for the purpose. I have globally mapped Caps Lock as Escape using the system settings. While all other applications respect this key mapping, it has no effect inside VSCodeVim.

System Details:
VSCode 1.17.2
vscodevim 0.10.1
OS: Linux Mint 18.1
Desktop: Cinnamon 3.2.7

* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.10.1
- **OS**: Linux Mint 18.1 Cinnamon Edition

**What happened**: 

**What did you expect to happen**: Go to normal mode

**How to reproduce it**:

**Comment by xconverge** [comment] 2017-10-22 17:37
Duplicate of #1479

**Closed** 2017-10-22 17:37 UTC
