### ISSUE TITLE
getLineLength() called with out-of-bounds line 176

### ISSUE THREAD

**Issue by skorotkiewicz** [VSCodeVim/Vim#5664] opened 2020-11-16 22:41 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 176
	at Function.getLineLength (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.promise (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/Users/modinfo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-17 21:33
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-11-17 21:33 UTC
Labels: status/duplicate
