### ISSUE TITLE
VS Code can't search with spaces

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#1094] opened 2016-11-27 23:09 UTC
_From @nikitavoloboev on November 23, 2016 17:51_

- VSCode Version: 1.7.2
- OS Version: 10.11.6

Steps to Reproduce:

1. press cmd + f and write your search query that has a space in it
2. spaces don't register 
3. for example I type in 'one word two word'
4. and I get : 
![2016-11-23 at 18 51](https://cloud.githubusercontent.com/assets/6391776/20572941/df19d512-b1ad-11e6-9dc2-24ff0401892c.png)

No spaced.

_Copied from original issue: Microsoft/vscode#15978_

**Comment by rebornix** [comment] 2016-11-27 23:09
_From @jrieken on November 23, 2016 20:35_

not for me...

<img width="479" alt="screen shot 2016-11-23 at 21 35 08" src="https://cloud.githubusercontent.com/assets/1794099/20577886/bbdb3f0c-b1c4-11e6-937b-ef109b6511cb.png">

**Comment by rebornix** [comment] 2016-11-27 23:09
_From @nikitavoloboev on November 23, 2016 20:39_

I am also using Vim Plugin : https://github.com/VSCodeVim/Vim

Perhaps that somehow plays a role.

**Comment by rebornix** [comment] 2016-11-27 23:09
_From @yoisel on November 23, 2016 21:53_

What do you mean by "OS Version: 10.11.6" ?

**Comment by rebornix** [comment] 2016-11-27 23:09
_From @nikitavoloboev on November 23, 2016 21:58_

![2016-11-23 at 22 58](https://cloud.githubusercontent.com/assets/6391776/20580022/52910cdc-b1d0-11e6-8995-f9c5bcfead8d.png)

**Comment by xconverge** [comment] 2016-11-28 00:02
@rebornix Have you reproduced this? I can't...

**Comment by johnfn** [comment] 2016-11-28 00:22
I additionally can't reproduce this.

**Comment by nikitavoloboev** [comment] 2016-11-28 00:27
Just tried it once again and for some reason it works for python files. Searching in python files allows me to have spaces in my searches however when searching in javascript files, it doesn't.

This is what I get when searching in the find bar (cmd + f) and pressing space in there : 

![2016-11-28 at 01 26](https://cloud.githubusercontent.com/assets/6391776/20653193/bb1ff998-b509-11e6-877d-67a879b7047c.png)

![2016-11-28 at 01 26](https://cloud.githubusercontent.com/assets/6391776/20653197/c34c3db6-b509-11e6-9bf1-33c9a2818dab.png)

**Comment by johnfn** [comment] 2016-11-28 00:28
I can't reproduce it on a JavaScript file either.

**Comment by johnfn** [comment] 2016-11-28 00:28
We don't have anything to do with key chord combinations. That sounds like some other sort of VSC configuration you've got going on there.

**Comment by nikitavoloboev** [comment] 2016-11-29 11:51
Does anyone know perhaps how I can solve this?

**Comment by johnfn** [comment] 2016-11-29 18:11
@nikitavoloboev I would suggest reinstalling VSCode and adding extensions 1 by 1 until you see what the problem is. I would also suggest looking into your user profile settings to see if anything in there is causing this.

**Comment by johnfn** [comment] 2016-12-01 19:46
I'm going to close this because I'm 99% sure it's unrelated to VSCodeVim. I don't even know how to make key chords. 😉

**Closed by johnfn** 2016-12-01 19:46 UTC
