### ISSUE TITLE
Holding h,j,k or l to move around results in cursor hopping back and forth

### ISSUE THREAD

**Issue by chrisolsen** [VSCodeVim/Vim#1120] opened 2016-12-05 17:39 UTC
### What did you do?

Hold h,j,k or l for a second or two to move cursor to desired location 

### What did you expect to happen?

Cursor continues to move in the direction I want it to

### What happened instead?

Cursor moving continuously jumps back and forth. ex Hold `j` to move cursor 10 lines down. Resulting movement (d:down, u:up) => ddddudududuuddudddud

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.7
* OS: Windows 10

**Comment by johnfn** [comment] 2016-12-05 18:41
Also a dupe of #534. Going to look at this soon.

**Closed by johnfn** 2016-12-05 18:41 UTC
