### ISSUE TITLE
Failed to handle key=O. Illegal value for `line`

### ISSUE THREAD

**Issue by gsbakshi** [VSCodeVim/Vim#5958] opened 2021-01-04 19:22 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=O. Illegal value for `line`
    at d._lineAt (/Volumes/SanDisk128/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
    at Object.lineAt (/Volumes/SanDisk128/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
    at Function.getCharAt (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:13177)
    at Function.tryToExecuteSurround (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:153265)
    at n.exec (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:151726)
    at n.execCount (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24652)
    at F.runAction (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171589)
    at F.handleKeyAsAnAction (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
    at F.handleKeyEvent (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/gurmeharbakshi/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-03-24 18:02
Duplicate of #6273

**Closed by J-Fields** 2021-03-24 18:02 UTC
