### ISSUE TITLE
Vim doesn't work when its version is 1.1.0

### ISSUE THREAD

**Issue by ymkim92** [VSCodeVim/Vim#3523] opened 2019-02-25 23:09 UTC
Vim doesn't work when its version is 1.1.0.
You know ESC and 'i' key doesn't work.

But when I install 1.0.8 or 1.07, it works fine.

- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.30.2
- OS: Windows 10

**Comment by jshap70** [comment] 2019-02-25 23:11
check if this is a dupe of  #3522

**Comment by caowz** [comment] 2019-02-27 02:19
I have the same problem as you. And I update the vscode to version 1.31.1. it work.

**Comment by jpoon** [comment] 2019-02-27 23:20
Please update your vscode to the latest.

**Closed by jpoon** 2019-02-27 23:20 UTC
