### ISSUE TITLE
Vertical block mode (ctrl-v) has several issues

### ISSUE THREAD

**Issue by Orionsg** [VSCodeVim/Vim#3046] opened 2018-09-13 09:31 UTC
Vertical blocks have issues. When marking a vertical block with ctrl-v:

1. Yanking the block and pasting it (p) somewhere else inserts the block of text as if it is a normal block with new line characters after each line of text in the vertical block rather than pasting the block at the column position where the cursor is, in each line that is pasted into, e.g.:

1: 111 222 333
2: aaa bbb ccc
3:
4: xxx yyy zzz
5: xxx yyy zzz

In the text above, I place the cursor at the first "3" in line one and press ctrl-v. I then then press "j" and afterwards "$" to go to end of line. Thus I now have a vertical block with two lines containing "333 and "ccc", respectively. I then press "y" to copy the content to the buffer and then move the cursor to line 4, before the first "z" and press "p" to paste in the vertical block. The two lines of text are not inserted into line 4 and 5 before the "zzz" as expected. Instead two new extra lines are inserted below line 4, containing "333" and "ccc", respectively.

2. Deleting the vertical block (d) deletes the correct text from each line, but does not copy the contents to the buffer so it can afterwards be pasted (p). Instead the buffer still contains what was in it already before the delete.

3. One cannot move the marked vertical block to the left or right with "<" or ">", respectively. The vertical block of text just sits stuck where it is.

VSCode: 1.24.1
VSCodeVim: 0.16.4
OS: Windows 7 (32 bit)

**Comment by J-Fields** [comment] 2021-04-13 21:37
Closing as duplicate of several other issues (most notably #1796), all of which will be fixed in the next release

**Closed by J-Fields** 2021-04-13 21:37 UTC
Labels: status/duplicate
