### ISSUE TITLE
Failed to handle key=). Invalid regular expression: /e)/: Unmatched ')'

### ISSUE THREAD

**Issue by zhyty** [VSCodeVim/Vim#5665] opened 2020-11-17 00:40 UTC
`<leader><leader>2se)` seems to interpret the closing parenthesis as regex. It seems like any special character (e.g. '.' or '\\') is being interpreted as regex. This seemed to have been fixed last year in #3911, but has appeared again.

**VSCodeVim version**: 1.17.1

The error I've been getting:

```
SyntaxError: Failed to handle key=). Invalid regular expression: /e)/: Unmatched ')'
```

**Comment by J-Fields** [comment] 2020-11-18 17:10
Duplicate of #5325, I believe

**Closed by J-Fields** 2020-11-18 17:10 UTC
