### ISSUE TITLE
`zt` and `zb` don't work in visual/visual line mode

### ISSUE THREAD

**Issue by BKitor** [VSCodeVim/Vim#6582] opened 2021-05-02 23:54 UTC
**Describe the bug**
zt/zb should scroll the screen to the so the cursor is at the top/bottom, but they don't work in visual mode. 
zz still works in visual mode. 

**To Reproduce**

1. Highlight something with visual mode
2. press `zt` or `zb`
3.  the screen doesn't move

**Expected behavior**
The cursor should move to the top/bottom of the screen 

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.20.2
- VSCode version: version 1.55
- OS: Ubuntu WSL

**Additional context**

**Comment by J-Fields** [comment] 2021-05-03 01:07
Duplicate of #6578

**Closed by J-Fields** 2021-05-03 01:07 UTC
