### ISSUE TITLE
Neovim wrong parameter

### ISSUE THREAD

**Issue by FreeVTS** [VSCodeVim/Vim#4145] opened 2019-10-07 13:06 UTC
Issue Type: <b>Bug</b>

I got this error since the late of september 2019. Before, this functionnality was ok :

With vim extension with neovim support enable, make this command :
:put =strftime('%c')

Give the following result :
A notification box appears on the bottom right of vscode with following text : "TaskQueue: Error running task. Failed to handle key=:. nvim_buf_set_lines: rong type for argument 1, expecting Buffer. Source: Vim (Extension)"

Windows 10 Pro 1809 17763.737

VSCode 1.38.1 (user setup)

Thanks for your support,

-- 
Serge GAGNON

Extension version: 1.11.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|19.70GB (14.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by jaredmcateer** [comment] 2019-10-09 17:04
Possibly related to/duplicate of #4126

**Comment by jpoon** [comment] 2019-10-09 19:54
Looks like it. Closing it as such.

**Closed by jpoon** 2019-10-09 19:54 UTC
