### ISSUE TITLE
easymotion key bind is not working

### ISSUE THREAD

**Issue by imSafdarAwan** [VSCodeVim/Vim#6828] opened 2021-07-05 06:30 UTC
2 days ago the easymotion keybind stoped working <leader><leader>/ is the default keybind but leader key works for only once not twice.

**Comment by tuanna-hsp** [comment] 2021-07-05 07:38
Same for me

**Comment by yanke1311** [comment] 2021-07-05 11:16
same for me too.

**Comment by tuanna-hsp** [comment] 2021-07-05 11:24
<img width="663" alt="Screen Shot 2021-07-05 at 16 43 19" src="https://user-images.githubusercontent.com/14136939/124464317-05c99d80-ddcf-11eb-9c58-0cb8a65f8de7.png">
quick workaround: install the previous release.

**Comment by RononDex** [comment] 2021-07-05 11:43
same here

**Comment by bryan-gc** [comment] 2021-07-05 20:38
It's broken for me too, I am using Ubuntu btw. Idk it has anything to do with it. I think it was working fine on Windows, I don't remember.

I "fixed" it by installing the 1.21.3 version.

**Comment by wizenith** [comment] 2021-07-06 03:21
I use WSL Ubuntu on Windows, and it probably did occurred the issue to the users like me. 
My workaround is same approach as above

**Comment by kazudeath1** [comment] 2021-07-06 05:18
same

**Comment by RononDex** [comment] 2021-07-06 09:42
@wizenith it certainly has nothing to do with WSL or Windows, I have the same problem on native windows and native linux

**Comment by wdcew** [comment] 2021-07-06 12:46
me too, I am using macOS 10.15

**Comment by k1832** [comment] 2021-07-06 13:49
It occurred to me. I'm using 'space' as a leader. But when I type 2 spaces, the navigation bar shows one <leader> and my cursor moves to the right.
After I set <leader> to default, which is '\' , it worked correctly.
I think it has nothing to do with OS.

**Comment by wizenith** [comment] 2021-07-06 16:42
> @wizenith it certainly has nothing to do with WSL or Windows, I have the same problem on native windows and native linux

I see, thanks for providing a verified info of the issue.

**Comment by J-Fields** [comment] 2021-07-06 17:06
Duplicate of #6821

**Closed by J-Fields** 2021-07-06 17:06 UTC

**Comment by J-Fields** [comment] 2021-07-06 17:45
Sorry for the regression! This is fixed on 1.21.5, which is now available - please upgrade.

**Comment by imSafdarAwan** [comment] 2021-08-05 05:42
Solved
