### ISSUE TITLE
Failed to handle key=d. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by gejianxin** [VSCodeVim/Vim#5411] opened 2020-10-14 09:07 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal argument: line must be non-negative
	at Object.t.illegalArgument (c:\Users\gejia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
	at new _ (c:\Users\gejia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:509:364)
	at new _ (c:\Users\gejia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:507:436)
	at new l (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:9299)
	at h.updateAndReturnMarks (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:510467)
	at h.finishCurrentStep (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:513988)
	at F.runAction (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:477890)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\gejia\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by fwip** [comment] 2020-12-01 21:56
Saw this while deleting imports from the very top of one file and pasting them into another. I was typing pretty fast and I'm not 100% sure my characters were correct.

**Comment by J-Fields** [comment] 2020-12-06 21:10
Duplicate of #5226

**Closed by J-Fields** 2020-12-06 21:10 UTC
Labels: status/duplicate
