### ISSUE TITLE
Failed to handle key=o. getLineLength() called with out-of-bounds line 163

### ISSUE THREAD

**Issue by dongxuanba** [VSCodeVim/Vim#5548] opened 2020-11-01 02:14 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=o. getLineLength() called with out-of-bounds line 163
    at Function.getLineLength (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getUpWithDesiredColumn (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
    at l.getLeftThroughLineBreaks (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
    at /home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475270
    at Array.map (<anonymous>)
    at F.runAction (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475217)
    at F.handleKeyAsAnAction (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at Object.promise (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/home/virtualbox/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:28
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:28 UTC
