### ISSUE TITLE
Can't map enter key

### ISSUE THREAD

**Issue by CodingJonas** [VSCodeVim/Vim#2390] opened 2018-02-18 09:25 UTC
**What happened**:
Enter key in normal mode just goes to the next line.

**What did you expect to happen**:
I want to map the enter key to save the file in normal mode

**How to reproduce it (as minimally and precisely as possible)**:
This is the part of my settings file:
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<Enter>"],
            "after": [], 
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                }
            ]
        },
        ....
```
- Extension (VsCodeVim) version:
0.10.13

**Comment by fhdhsni** [comment] 2018-03-25 15:55
Use `\n` instead of `<Enter>`

**Comment by jpoon** [comment] 2018-06-17 06:59
Dupe of https://github.com/VSCodeVim/Vim/issues/2584

**Comment by jpoon** [comment] 2018-06-19 09:14
Took another look at the code. I was mistaken. Submitted a PR to fix this.

**Closed** 2018-06-19 10:00 UTC
Labels: status/duplicate
