### ISSUE TITLE
Display vim markers

### ISSUE THREAD

**Issue by gamcoh** [VSCodeVim/Vim#4710] opened 2020-04-01 18:36 UTC
**Is your feature request related to a problem? Please describe.**
My request is not related to a problem, it's something i'd like to use.

**Describe the solution you'd like**
I want to see icons in the gutter where my vim marks are set. Like [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) but for vim markers.

**Describe alternatives you've considered**
A clear alternative is to use the Bookmarks extension but I want to use the markers of vim.

**Additional context**
I also would like to participate, so I am beginning now to develop this feature.

**Comment by J-Fields** [comment] 2020-04-01 18:42
Duplicate of #3963. Thanks for offering to tackle this; feel free to bug me if you need any guidance!

**Closed by J-Fields** 2020-04-01 18:42 UTC
Labels: kind/feature

**Comment by gamcoh** [comment] 2020-04-02 12:29
Hi, I just created my PR but the CI tells me : `TypeError: vscode.window.createTextEditorDecorationType is not a function`.
Do you have any idea why it works on my machine but not in the CI?

**Comment by gyzerok** [comment] 2020-05-15 23:54
Hello @J-Fields!

In the changelog to version 1.14.0 it mentions this issue within enhancements. However based on actual behavior, this issue and related issue it seems that nothing was implemented.

Can you help me understand it? I am a bit confused :)

**Comment by J-Fields** [comment] 2020-05-16 22:50
@gyzerok Sorry for the confusion. The changelog is generated automatically based on the issues/PRs that are closed. This was closed as a duplicate. There is a pending PR for it though, so hopefully it'll be in the next feature release.

**Comment by gyzerok** [comment] 2020-05-16 23:00
Sure, thanks for explaining!

**Comment by gamcoh** [comment] 2020-05-16 23:02
Yes, by the way @J-Fields, the changes you requested on the PR are done. everything works well, just waiting for your approval.

**Comment by J-Fields** [comment] 2020-05-16 23:32
@gamcoh Yep, I will soon. Just been focusing on some other things recently 🙂

**Comment by gamcoh** [comment] 2020-05-16 23:33
Of course, take your time!
