### ISSUE TITLE
Failed to handle key=d. getLineLength() called with out-of-bounds line 45

### ISSUE THREAD

**Issue by FlamingTree** [VSCodeVim/Vim#5571] opened 2020-11-04 01:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. getLineLength() called with out-of-bounds line 45
	at Function.getLineLength (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at F.executeOperator (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480756)
	at F.runAction (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476279)
	at F.handleKeyAsAnAction (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/sg/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-11-09 21:27
Duplicate of #5180. If you're able to reproduce, please post steps there.

**Closed by J-Fields** 2020-11-09 21:27 UTC
