### ISSUE TITLE
Need a better highlight style for light color theme

### ISSUE THREAD

**Issue by wangsongiam** [VSCodeVim/Vim#1086] opened 2016-11-23 09:01 UTC
### What did you do?
`/` for some searching
### What did you expect to happen?
get search result easily
### What happened instead?

the highlight style makes search result hard to recognize. like this 
<img width="270" alt="screen shot 2016-11-23 at 3 55 15 am" src="https://cloud.githubusercontent.com/assets/19645990/20555519/af2a440e-b130-11e6-8858-020ca42385da.png"> 
and that happens to lots of light color themes

### Technical details:

* VSCode Version:1.7.2
* VsCodeVim Version: the latest
* OS: 10.11.6

**Comment by xconverge** [comment] 2016-11-23 15:43
Duplicate of #1052

**Closed** 2016-11-23 22:43 UTC
