### ISSUE TITLE
getLineLength() called with out-of-bounds line 2499

### ISSUE THREAD

**Issue by Tizariox** [VSCodeVim/Vim#5810] opened 2020-12-03 02:46 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 2499
	at Function.getLineLength (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:22225)
	at l.getRight (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:1:10500)
	at F.updateView (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:491590)
	at _ (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:234397)
	at async Object.runTasks (/Users/alanzhong/.vscode/extensions/vscodevim.vim-1.17.2/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-12-05 18:27
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 18:27 UTC
Labels: status/duplicate
