### ISSUE TITLE
j and k are updating the goto history too much

### ISSUE THREAD

**Issue by sgronblo** [VSCodeVim/Vim#1964] opened 2017-08-11 13:21 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: Version 1.14.2 (1.14.2)
- **VsCodeVim Version**: 0.9.0
- **OS**: 10.12.6

**What happened**:

1. Use F12 to jump to a definition
2. Use `j` a few times to go down to another line
3. Repeat steps 1, 2 a few times
4. Press ctrl-dash/minus to go back through the goto history
5. VSCode jumps back one line for each `j` you have pressed

**What did you expect to happen**: 

I would expect that doing small movements like `j` and `k` to not affect the goto history. I disabled the vim plugin and verified that pressing the arrow keys does not affect the goto history.

The implications of this is that it takes more steps to jump back to places you have visited before and the goto history seems to have a rather low default size which means that you quite quickly end up not even being able to go back far enough in the history.

**How to reproduce it**:

See the steps in "What happened?"

**Comment by Chillee** [comment] 2017-08-17 01:35
This is a duplicate of  https://github.com/VSCodeVim/Vim/issues/1933.

I'm going to track this there.

**Closed** 2017-08-17 01:37 UTC
