### ISSUE TITLE
Failed to handle key=a. getLineLength() called with out-of-bounds line 9

### ISSUE THREAD

**Issue by Shunsuke135** [VSCodeVim/Vim#5529] opened 2020-10-29 15:58 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. getLineLength() called with out-of-bounds line 9
    at Function.getLineLength (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at l.getUpWithDesiredColumn (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
    at l.getLeftThroughLineBreaks (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
    at /Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475270
    at Array.map (<anonymous>)
    at F.runAction (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475217)
    at F.handleKeyAsAnAction (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at Object.promise (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/Users/isagoshunsuke/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-29 16:17
Duplicate of #5180; if you can reproduce, please post steps there.

**Closed by J-Fields** 2020-10-29 16:17 UTC
