### ISSUE TITLE
Failed to handle key=<BS>. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by congthanhnguyen1749-hub** [VSCodeVim/Vim#5881] opened 2020-12-13 17:23 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<BS>. Cannot read property 'canBeRepeatedWithDot' of undefined
    at F.runAction (/Users/nguyenthanhcong/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172434)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/Users/nguyenthanhcong/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/nguyenthanhcong/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/nguyenthanhcong/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
    at Object.runTasks (/Users/nguyenthanhcong/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:09
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:09 UTC
Labels: status/duplicate
