### ISSUE TITLE
Failed to handle key=I. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by rahim539** [VSCodeVim/Vim#5399] opened 2020-10-13 13:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=I. Cannot read property 'stop' of undefined
    at p.get cursorStopPosition [as cursorStopPosition] (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
    at F.createUndoPointForBrackets (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:494726)
    at F.runAction (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476613)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/linux/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)

```

</details>

**Comment by J-Fields** [comment] 2020-10-14 03:24
What were you trying to do when this happened? Can you reproduce?

**Comment by J-Fields** [comment] 2021-02-04 20:48
Duplicate of #5284

**Closed by J-Fields** 2021-02-04 20:48 UTC
Labels: kind/bug, status/duplicate
