### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by jevonwill** [VSCodeVim/Vim#6285] opened 2021-03-16 16:40 UTC
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.18.9<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:548679)    at https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:546656    at Object.next (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:546761)    at https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:545674    at new Promise (<anonymous>)    at r (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:545411)    at e.$executeCommand (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:160:548552)    at e.doInvokeHandler (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:19:773600)    at e.invokeHandler (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:19:773333)    at e.receiveRequest (https://blobserve.ws-us03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:master.3153/__files__/bundle.js:19:772625)```</details>

**Comment by J-Fields** [comment] 2021-03-24 17:52
Duplicate of #5526

**Closed by J-Fields** 2021-03-24 17:52 UTC
