### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 119

### ISSUE THREAD

**Issue by 90217** [VSCodeVim/Vim#5343] opened 2020-10-07 06:51 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 119
	at Function.getLineLength (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at l.getLeftThroughLineBreaks (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10872)
	at /Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475270
	at Array.map (<anonymous>)
	at F.runAction (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475217)
	at F.handleKeyAsAnAction (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/xingbin/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-14 00:55
Duplicate of #5180

**Closed by J-Fields** 2020-10-14 00:55 UTC
