### ISSUE TITLE
Failed to handle key=<up>. getLineLength() called with out-of-bounds line 15

### ISSUE THREAD

**Issue by xtedx** [VSCodeVim/Vim#5328] opened 2020-10-04 13:24 UTC
**To Reproduce**

0. escape to go to normal more
1.  Go to line 4 on the sample text file using down arrow
2. press shift v to enter visual line
2.  press down arrow 5 times
3.  press cmd+x to cut
4.  press  down
5. selection will jump to the bottom
6. press cmd+x again to cut
7. press up

crashes,
then pressing u to undo will also crash again

[bugreportsample.txt](https://github.com/VSCodeVim/Vim/files/5323270/bugreportsample.txt)

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<up>. getLineLength() called with out-of-bounds line 15
	at Function.getLineLength (/Users/x/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getUpWithDesiredColumn (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:11622)
	at V.execAction (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:191010)
	at V.createMovementResult (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158252)
	at V.execActionWithCount (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157909)
	at F.executeMovement (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/Users/teddy/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by Harvzor** [comment] 2020-10-04 20:03
I just ran into a similar issue which started with

> Failed to handle key

My fix was upgrading to the latest version of VS Code. I'm now on 1.49.3.

**Comment by xtedx** [comment] 2020-10-04 23:48
I just restarted to update to 1.49.3. tried it again, and same problem, same vim extension version. same stack trace

**Comment by J-Fields** [comment] 2020-12-05 21:53
Duplicate of #5180

**Closed by J-Fields** 2020-12-05 21:53 UTC
