### ISSUE TITLE
Failed to handle key=a. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by osgrijilio** [VSCodeVim/Vim#6778] opened 2021-06-22 02:04 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. Overlapping ranges are not allowed!
    at s._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52514)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:50206)
    at Object.executeTransformations (/Users/lfonseca/.vscode/extensions/vscodevim.vim-1.21.3/src/transformations/execute.ts:124:29)
    at I.runAction (/Users/lfonseca/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/Users/lfonseca/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (/Users/lfonseca/.vscode/extensions/vscodevim.vim-1.21.3/src/mode/modeHandler.ts:471:11)
    at /Users/lfonseca/.vscode/extensions/vscodevim.vim-1.21.3/extensionBase.ts:370:73
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
