### ISSUE TITLE
Moving cursor across folded code should not automatically unfold

### ISSUE THREAD

**Issue by sserbin** [VSCodeVim/Vim#1371] opened 2017-03-08 09:36 UTC
Originally posted in vscode - Microsoft/vscode/issues/16858
I'm not sure if @michael-yx-wu was using _this_ extension or if we had a chance to post an issue here (I did try to look it up in issues but haven't found one - apologize if I overlooked that)

-----

### What did you do?

1. Fold code block (`zc`)
2. Move down (`j`)

### What did you expect to happen?
No auto-unfolding
### What happened instead?
Auto-unfolding
### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: latest
* OS: Linux

**Comment by xconverge** [comment] 2017-03-09 03:27
dupe of #1004 can you go thumbs up that issue please? Thanks!

**Closed** 2017-03-09 07:33 UTC
Labels: duplicate
