### ISSUE TITLE
Failed to handle key=. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by mbarish-me** [VSCodeVim/Vim#6893] opened 2021-07-20 12:27 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. Overlapping ranges are not allowed!
    at n._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/Users/admin/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/Users/admin/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/admin/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/Users/admin/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /Users/admin/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[245, 64] | [245, 64]]"
]
actionsRunPressedKeys: [
  "g",
  ".",
  "w",
  "\n"
]
actionsRun: [
  "ee",
  "$",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 245,
      "character": 12
    },
    "text": "mId",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 245,
        "character": 7
      },
      {
        "line": 245,
        "character": 15
      }
    ],
    "text": "systemIds.finter",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:44
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:44 UTC
Labels: status/duplicate
