### ISSUE TITLE
Failed to handle key=l. Cannot read property 'canBeRepeatedWithDot' of undefined

### ISSUE THREAD

**Issue by hkrhasan** [VSCodeVim/Vim#6003] opened 2021-01-16 11:21 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=l. Cannot read property 'canBeRepeatedWithDot' of undefined
	at F.runAction (c:\Users\hkr\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:172434)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\hkr\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
	at async F.handleKeyEvent (c:\Users\hkr\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
	at async Object.promise (c:\Users\hkr\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
	at async Object.runTasks (c:\Users\hkr\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:08
Duplicate of #5468

**Closed by J-Fields** 2021-02-04 20:08 UTC
Labels: status/duplicate
