### ISSUE TITLE
Failed to handle key=<C-a>. Illegal value for `line`

### ISSUE THREAD

**Issue by huang-feiyu** [VSCodeVim/Vim#5432] opened 2020-10-16 06:33 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal value for `line`
	at d._lineAt (d:\DevTools\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:545:764)
	at Object.lineAt (d:\DevTools\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:544:734)
	at Function.getLineAt (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:22450)
	at _.exec (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:216058)
	at _.execCount (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37468)
	at x.exec (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:214331)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.execCount (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37457)
	at async F.runAction (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475401)
	at async F.handleKeyAsAnAction (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471603)
	at async Object.promise (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\36542\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 21:57
Duplicate of #5305; if you can reproduce, please post steps there

**Closed by J-Fields** 2020-10-26 21:57 UTC
