### ISSUE TITLE
Search/Replace BackReference not working

### ISSUE THREAD

**Issue by willemmirkovich** [VSCodeVim/Vim#6290] opened 2021-03-16 21:37 UTC
**Describe the bug**
The back reference feature that I am used to using in vim is not working in the emulation tool. Verified that the back reference worked on cmd line vim. This is on windows.

**To Reproduce**

1. Create a text file with the following contents:

x["yes"];
y["no"];

2. Try to transform ["<Something>"] to .<Something> using the following command
:%s/\["\(.*\)"\]/\.\1/gc
and notice that it doesn't work in vim vscode

**Expected behavior**
Try the exact same command in a terminal vim session and notice works just fine

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.9
- VSCode version: 1.54.3
- OS: Windows 10

**Additional context**

**Comment by nzig** [comment] 2021-04-25 08:41
This is a duplicate of https://github.com/VSCodeVim/Vim/issues/6387. The solution is to use `$1` instead of `\1`.

**Comment by J-Fields** [comment] 2021-05-04 18:22
Duplicate of #3996/#6387

**Closed by J-Fields** 2021-05-04 18:22 UTC
Labels: area/commandline, kind/enhancement
