### ISSUE TITLE
das/dis does removes more than a sentence

### ISSUE THREAD

**Issue by martinwk** [VSCodeVim/Vim#1931] opened 2017-07-17 09:55 UTC
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT ** (choose one):

**Environment**:

- **VSCode Version**: 1.14.0
- **VsCodeVim Version**:  0.9.0
- **OS**: windows7

**What happened**:

**What did you expect to happen**: 
removing of the sentence
**How to reproduce it**:
```
    if something:
        raise Exception('something')

    # add data to database
    for _ind, _row in df_meta.iterrows():
        yline = _row['YLine']
        try:
            # Cast to integers. If NaN is in the list, an exception will be
            # thrown and caught below
```
putting the cursor on cast and pressing `das` (or `dis`) removes everything from the beginning until `If NaN` that is everything from the whiteline until the end of the sentence

**Comment by brandonbloom** [comment] 2017-09-03 19:50
The code is in `class SelectSentence extends TextObjectMovement`.

Two things to fix this:

1) Use CharacterWise register mode. Similar to paragraphs that use LineWise mode: https://github.com/VSCodeVim/Vim/commit/4d1109867472f2e04740ebb41dcce2208a19619a

2) Fix up the some of the broken logic in that function with respect to trailing whitespace.

**Comment by Chillee** [comment] 2017-10-18 18:45
Vim/Nvim actually seems to have the same behavior, strangely enough.

It does seem to be a bizarre problem though.

**Comment by Chillee** [comment] 2017-10-18 18:52
`A sentence is defined as ending at a '.', '!' or '?' followed by either the
end of a line, or by a space or tab.  Any number of closing ')', ']', '"'
and ''' characters may appear after the '.', '!' or '?' before the spaces,
tabs or end of line.  A paragraph and section boundary is also a sentence
boundary.
`

**Comment by Chaoclypse** [comment] 2018-12-22 04:49
Still experiencing this issue. I did not find similar behaviour in Vim - das or dis would just delete the sentence.

**Comment by yyn19951228** [comment] 2020-03-10 02:17
Seems not a bug, but a feature of vim

**Comment by J-Fields** [comment] 2021-10-14 19:55
Yeah, looks like expected behavior to me.

**Closed by J-Fields** 2021-10-14 19:55 UTC
Labels: status/by-design
