### ISSUE TITLE
TypeError on empty file

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#3030] opened 2018-09-06 08:45 UTC
I have an empty file open and get this error on startup.

- Extension Name: vim
- Extension Version: 0.16.3
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.1-insider

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 344,
		"activateCallTime": 2,
		"activateResolvedTime": 73,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'options' of undefined"
		}
	]
}
```

**Comment by jpoon** [comment] 2018-09-07 09:53
Opting to close as duplicate of #3033 as that issue is a bit more descriptive.

**Closed by jpoon** 2018-09-07 09:53 UTC
Labels: status/duplicate
