### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by mugurlu0** [VSCodeVim/Vim#6099] opened 2021-02-04 18:03 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.8

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at I._applyEdit (c:\Users\mehme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:36773)
    at I.edit (c:\Users\mehme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:36308)
    at y.execute (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:782341)
    at F.runAction (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:707868)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at F.handleKeyAsAnAction (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:707147)
    at F.handleKeyEvent (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:703983)
    at Object.promise (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:346362)
    at Object.runTasks (c:\Users\mehme\.vscode\extensions\vscodevim.vim-1.18.8\out\extension.js:2:754478)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:03
Duplicate of #5224. Are you able to reproduce?

**Closed by J-Fields** 2021-02-04 20:03 UTC
