### ISSUE TITLE
Jump to Definition (gd) bug

### ISSUE THREAD

**Issue by PaulAndreiTaranu** [VSCodeVim/Vim#6585] opened 2021-05-03 15:55 UTC
After 'gd' to a file and moving around that file and closing the file make consecutive MOVE AFTER gd in that jumped file to jump again to the last position from the first time 'gd'. Bug in latest versions, version 1.19 works properly.

Its confusing to describe, but it is annoying enough to make me downgrade to 1.19.

**Comment by theorlangur** [comment] 2021-05-10 05:43
I can confirm that after subsequent gd's into the file and attempt to move inside (hjkl) it first jumps to some previous position in the file. And yes, downgrading to 1.19 has helped.

**Comment by J-Fields** [comment] 2021-05-14 23:48
I've noticed this as well, though I can't reliably reproduce. 63ef6283fc0762d248c4d594b457eca13eddb850 seems like the only change that could possibly be the culprit

**Comment by J-Fields** [comment] 2021-06-16 18:20
Duplicate of #6544

**Closed by J-Fields** 2021-06-16 18:20 UTC
Labels: kind/bug
