### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ninadpachpute** [VSCodeVim/Vim#6917] opened 2021-07-27 16:13 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at s._applyEdit (c:\Users\ninad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52514)
    at Object.edit (c:\Users\ninad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:50206)
    at Object.executeTransformations (c:\Users\ninad\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\ninad\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\ninad\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\ninad\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\ninad\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[86, 40] | [86, 38]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "<left>",
  "<Esc>"
]
actionsRun: [
  "D",
  "q",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 86,
      "character": 41
    },
    "text": "d",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 86,
        "character": 34
      },
      {
        "line": 86,
        "character": 42
      }
    ],
    "text": "cfg_rx_dec_mode",
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 86,
      "character": 41
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment] 2021-07-27 16:14
Duplicate of #6888

**Closed by J-Fields** 2021-07-27 16:14 UTC
Labels: status/duplicate
