### ISSUE TITLE
Copying text by selecting it from right to left drops the last letter from the copied text

### ISSUE THREAD

**Issue by Yohanna** [VSCodeVim/Vim#1441] opened 2017-03-28 07:23 UTC
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. While in Insert mode, using the mouse, make a selection **from right to left**, e.g. for the string "Hello World" start selecting from the letter `d` to `H`.
2. Copy using `Ctrl+C`
3. Paste the selection

### What did you expect to happen?

The text "Hello World" gets pasted.

### What happened instead?

The last letter, `d`, is removed, "Hello Worl" is pasted instead.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10

**Comment by xconverge** [comment] 2017-03-28 21:21
duplicate of https://github.com/VSCodeVim/Vim/issues/1355

**Closed** 2017-05-02 22:06 UTC
Labels: area/clipboard, status/duplicate
