### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by itzjustalan** [VSCodeVim/Vim#5867] opened 2020-12-11 08:50 UTC
**To Reproduce**

1.  Go to 'any file'
2.  Click on 'ctrl + A to select all text'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
    at Object.t.illegalArgument (c:\Users\alanj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:662)
    at new _ (c:\Users\alanj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:513:424)
    at new _ (c:\Users\alanj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:511:436)
    at a (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:74261)
    at F.exec (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:74306)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at x.exec (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:195203)
    at x.execCount (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:1:24579)
    at F.runAction (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:171581)
    at F.handleKeyAsAnAction (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:170974)
    at F.handleKeyEvent (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167812)
    at Object.promise (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:211972)
    at Object.runTasks (c:\Users\alanj\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2020-12-11 18:46
Duplicate of #5356. Can you please post your settings? Can you reliably reproduce this error?

**Closed by J-Fields** 2020-12-11 18:46 UTC
