### ISSUE TITLE
Failed to handle key= . getLineLength() called with out-of-bounds line 38

### ISSUE THREAD

**Issue by Manishs94** [VSCodeVim/Vim#5431] opened 2020-10-16 04:43 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key= . getLineLength() called with out-of-bounds line 38
    at Function.getLineLength (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22163)
    at l.isLineEnd (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14169)
    at l.getRightThroughLineBreaks (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10990)
    at ie.execAction (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:196350)
    at ie.createMovementResult (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:158190)
    at ie.execActionWithCount (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:157847)
    at F.executeMovement (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
    at F.runAction (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
    at F.handleKeyAsAnAction (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
    at F.handleKeyEvent (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/manishsondhi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-10-26 19:00
Duplicate of #5180, please post repro steps there

**Closed by J-Fields** 2020-10-26 19:00 UTC
