### ISSUE TITLE
Failed to handle key=v. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by sairajgemini** [VSCodeVim/Vim#6029] opened 2021-01-24 20:01 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=v. Cannot read property 'stop' of undefined
    at p.get cursorStopPosition [as cursorStopPosition] (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:196494)
    at F.runAction (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171613)
    at F.handleKeyAsAnAction (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
    at F.handleKeyEvent (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/home/saikat/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment] 2021-02-04 20:48
Duplicate of #5284

**Closed by J-Fields** 2021-02-04 20:48 UTC
Labels: status/duplicate
