### ISSUE TITLE
Insert mode `<C-r>.` inserts too many characters

### ISSUE THREAD

**Issue by YongJieYongJie** [VSCodeVim/Vim#4054] opened 2019-09-08 18:11 UTC
**Describe the bug**
In `insert` mode, pressing `<C-r>.` is supposed to insert the characters inserted during the last `insert` mode. However, the extension is inserting additional characters.

Relevant portion of  `:help i_CTRL-R` in Vim, under the special register for `.` with details on expected behavior:

```
CTRL-R {0-9a-z"%#*+:.-=}					*i_CTRL-R*
		Insert the contents of a register.  Between typing CTRL-R and
		the second character, '"' will be displayed to indicate that
		you are expected to enter the name of a register.
		The text is inserted as if you typed it, but mappings and
		abbreviations are not used.  If you have options like
		'textwidth', 'formatoptions', or 'autoindent' set, this will
		influence what will be inserted.  This is different from what
		happens with the "p" command and pasting with the mouse.
		Special registers:
			...
			'.'	the last inserted text
```

**To Reproduce**

1.  Go to any line
2.  Enter `insert` mode, insert the characters `abc`, and exit `insert` mode
3.  Go to any other line
4.  Press `i` to enter `insert` mode, press `<C-r>.`
5.  The characters `iabc` are inserted.

**Expected behavior**
The characters inserted should be `abc` (without the `i` used to enter `insert` mode).

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.10.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.37.1`

**Comment by J-Fields** [comment] 2019-09-08 18:14
Duplicate of #3773

**Closed by J-Fields** 2019-09-08 18:14 UTC
