### ISSUE TITLE
Not working at all on Ubuntu?

### ISSUE THREAD

**Issue by therealjuanmartinez** [VSCodeVim/Vim#3548] opened 2019-03-03 02:53 UTC
I'm running VSCode 1.30.2 on Ubuntu 18.10 and with Vim installed none of the commands are working nor is the cursor blocking as would be expected.  The Extensions screen does indicate the plugin is enabled.

I suspect it's a very simple problem... also I'm willing to suspect it's somehow on my end, but nothing seems awry.

**Comment by mereldawu** [comment] 2019-03-03 13:11
What version is your extension? 

I had the same issue after updating it to v 1.1.0.
I reverted back to v 1.0.8 for now, but would also like to know a better fix.

**Comment by zbennett10** [comment] 2019-03-04 04:32
Same issue here on CentOS 7. I reverted back to v 1.0.8 and everything works.

**Comment by jakedevine** [comment] 2019-03-04 18:11
I have the same issue with 1.1.0 on macOS. Reverting to 1.0.8 worked for me.

**Comment by dchansen** [comment] 2019-03-05 11:03
Same issue on Fedora 29

**Comment by jpoon** [comment] 2019-03-05 15:47
Anything interesting from the logs?

**Comment by dchansen** [comment] 2019-03-06 09:07
Yes. Not sure why I didn't think to check that. [It seems there is a problem with a regex.](https://gist.github.com/dchansen/8d14167aa9d9131c3f1672583a06dd7d)

**Comment by jpoon** [comment] 2019-03-06 16:20
Your running an old version of code.

**Comment by jpoon** [comment] 2019-03-07 04:39
Seems like it's a dupe of https://github.com/VSCodeVim/Vim/issues/3522?

**Closed by jpoon** 2019-03-07 04:39 UTC
