### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 80

### ISSUE THREAD

**Issue by Mzaien** [VSCodeVim/Vim#5270] opened 2020-09-27 21:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 80
    at Function.getLineLength (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
    at F.executeMovement (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:480271)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475336)
    at F.handleKeyAsAnAction (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
    at Object.runTasks (/Users/Mzaien/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment] 2020-09-28 16:17
Duplicate of #5180

**Closed by J-Fields** 2020-09-28 16:17 UTC
Labels: kind/bug, status/duplicate
