### ISSUE TITLE
Failed to handle key=.. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by pmjonesg** [VSCodeVim/Vim#6783] opened 2021-06-22 21:02 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=.. Overlapping ranges are not allowed!
    at T._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53072)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50744)
    at Object.executeTransformations (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/transformations/execute.ts:124:29)
    at I.runAction (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at I.rerunRecordedState (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/mode/modeHandler.ts:1097:55)
    at Object.transformer [as executeTransformations] (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/transformations/execute.ts:192:12)
    at I.actionToRecord [as runAction] (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/mode/modeHandler.ts:726:55)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/mode/modeHandler.ts:652:43)
    at I.text [as handleKeyEvent] (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/mode/modeHandler.ts:471:11)
    at Object.promise (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/extensionBase.ts:372:73)
    at Object.runTasks (/home/pjones/.vscode/extensions/vscodevim.vim-1.21.1/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment] 2021-07-23 04:48
Duplicate of #6888

**Closed by J-Fields** 2021-07-23 04:48 UTC
Labels: status/duplicate
