### ISSUE TITLE
Vim-VScode is not detecting caps which I mapped to 'esc' key while all the other native VScode stuff in VSCode is detecting the remmaped caps. OS-Linux(Manjaro) & remapped it via xmodmap.

### ISSUE THREAD

**Issue by mustafapc19** [VSCodeVim/Vim#2824] opened 2018-07-10 06:26 UTC

**Comment by xconverge** [comment] 2018-07-10 14:23
https://github.com/VSCodeVim/Vim/issues/1479#issuecomment-292452557

Workaround there

```
 "keyboard.dispatch": "keyCode"
```

duplicate of

**Closed by xconverge** 2018-07-10 14:23 UTC
