### ISSUE TITLE
Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 4

### ISSUE THREAD

**Issue by QuocVietHa08** [VSCodeVim/Vim#5217] opened 2020-09-23 10:40 UTC
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. getLineLength() called with out-of-bounds line 4
    at Function.getLineLength (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:22186)
    at F.executeMovement (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:480184)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475249)
    at F.handleKeyAsAnAction (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474707)
    at F.handleKeyEvent (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471516)
    at Object.promise (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:231560)
    at Object.runTasks (c:\Users\Admin\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment] 2020-09-23 18:04
What were you trying to do when this happened?

**Comment by J-Fields** [comment] 2020-09-25 20:25
Duplicate of #5180

**Closed by J-Fields** 2020-09-25 20:25 UTC
Labels: kind/bug
